### ISSUE TITLE
Use of Multiple Indicators To Commit To Buy, Helping To Make More Accurate Buys! 

### ISSUE THREAD

**Issue by clownfish44** [taniman/profit-trailer-enhancements#1]
Use of Multiple Indicators To Commit To Buy, Helping To Make More Accurate Buys! 

Example would be using lowbb and EMA Gain to make a buy and both values would have to be where it would buy to actually buy. If only one value is able to buy the coin can wait.

Many other bot's have this feature such as gunbot, gekko bot, etc.

**Comment by taniman** [comment]
This one is already in development. Check milestone for version 2.0

**Comment by clownfish44** [comment]
Thank you @taniman I have not checked the milestones yet I will close this issue
