### ISSUE TITLE
Allow combination of buy (or sell) strategies with use of multiple indicators

### ISSUE THREAD

**Issue by jodee8** [taniman/profit-trailer-enhancements#10]
I think it would take Profit Trailer to the next level if we were able to combine buy or sell strategies with the use of multiple indicators as conditions for the buy or sell. For example if the LOSS strategy is met e.g. coin pair is down 7% on the 24hr **AND** a secondary buy strategy, for example LOWBB conditions are met e.g. coin pair is sitting at -5% of LOWBB line... **THEN** make the buy. 

To be able to mix and match and combine strategies to formulate a kind of IFTTT (IF THIS THEN THAT) set of conditions to make the buy or the sell would really help us avoid buying bags and would ultimately help us to buy at the perfect time almost guaranteeing greater profits. 

Without this type of functionality the bot is flying blind to a coin pairs overall trend and might (with the right settings) buy at the bottom of a dip e.g. using LOWBB. But due to it being blind to the overall trend of the pair tanking downwards over the past say 4-6hrs. The result is a bag that might not recover enough to profitably exit the trade. Before the continued downward trend drags its value down, into a large 6 x DCA position, tying up valuable trading resources.

This scenario could easily be remedied if we could combine strategies/indicators.

**Comment by clownfish44** [comment]
Was already requested 

https://github.com/taniman/profit-trailer-enhancements/issues/1

**Comment by clownfish44** [comment]
Already in the 2.0 milestone https://github.com/taniman/profit-trailer/issues?q=is%3Aopen+is%3Aissue+milestone%3Av2.0
