### ISSUE TITLE
tracker, manually buy&sell and charts inside pt

### ISSUE THREAD

**Issue by hasanabuabed** [taniman/profit-trailer-enhancements#100]
![ptt-01](https://user-images.githubusercontent.com/34691718/36784074-cbf0b3e4-1c86-11e8-881f-d7e297577624.jpg)
1.extra tap to track pt

![12345-01](https://user-images.githubusercontent.com/34691718/36784670-ea94f10a-1c88-11e8-8c13-99acb85086c3.jpg)
2.option to see the chart of an open pair in the exchange 
3.option of buying and selling manually from pt UI

**Comment by hasanabuabed** [comment]
![untitled-1](https://user-images.githubusercontent.com/34691718/36784329-abbf8a40-1c87-11e8-8498-4ea04c4d30c5.jpg)

**Comment by clownfish44** [comment]
This has already been requested here https://github.com/taniman/profit-trailer-enhancements/issues/5
