### ISSUE TITLE
Profit on Telegram notication

### ISSUE THREAD

**Issue by Seeletse** [taniman/profit-trailer-enhancements#101]
Can the telegram notification show the profit made in actual FIAT as well and not in BTC and percentage.

![image](https://user-images.githubusercontent.com/36503544/36784071-c994ea48-1c86-11e8-805f-2400dfc93d63.png)

**Comment by clownfish44** [comment]
Already in the next 2.0 milestone https://github.com/taniman/profit-trailer/issues?q=is%3Aopen+is%3Aissue+milestone%3Av2.0
