### ISSUE TITLE
Stochastic RSI as a buy trigger

### ISSUE THREAD

**Issue by max00d** [taniman/profit-trailer-enhancements#102]
This a great signal to use with short time frames (ideal for bot trading).  This signal helps to identify over sold areas much faster than RSI can.

Used as a combination buy tigger it would be even more powerful, i.e.:

IF [usual buy strategy] == True and SRSI [within defined range]:
    BotCanBuy == True

This could implemented as a standard set of value (K==3, D==3, RSI Length==14, Stoch Length==14) or allow users to define their own parameters.

Where:

SRSI == (RSI - Lowest Low RSI) / Highest High RSI - Lowest Low RSI)
RSI == 100 - 100 / (1 + RS)
RS == Average Gain / Average Loss

**Comment by clownfish44** [comment]
Already in the next 2.0 milestone https://github.com/taniman/profit-trailer/issues?q=is%3Aopen+is%3Aissue+milestone%3Av2.0
