### ISSUE TITLE
Pump and dump protection

### ISSUE THREAD

**Issue by JeanGalt** [taniman/profit-trailer-enhancements#103]
Include a pump and dump protection by pair, based on the variations of their respective prices, to avoid unwanted purchases.
This protection could also work to prevent uncertainties related to the introduction of new pairs.

The interest for PT is to improve the global ROI by reducing the number of bags, and thus leave more cash available for new transactions.

**Comment by clownfish44** [comment]
No explanation of how the idea would work or example to follow along with.
