### ISSUE TITLE
Multiple time criteria for automatic SOM

### ISSUE THREAD

**Issue by JeanGalt** [taniman/profit-trailer-enhancements#104]
The current automatic SOM takes into account the variation of the BTC over 24 hours.
This 24 hour period does not take account of sudden changes in the BTC, which have a strong impact on the market price based on this value.
At least one additional time criterion, lasting less than 24 hours, would solve this problem.

**Comment by clownfish44** [comment]
already exists in ptmagic / ptfeeder which has been requested here https://github.com/taniman/profit-trailer-enhancements/issues/19
