### ISSUE TITLE
Adaptative trailing value

### ISSUE THREAD

**Issue by Franciutte** [taniman/profit-trailer-enhancements#106]
Implement an adaptative trailing value (a trailing_percentage based on trigger value). For exemple, for a sell strategy GAIN with a trigger of 1%, trailing_percentage of 20% could be interesting to avoid loosing a good trail on a small variation once the profit has reached 5% and will probably continue to grow

**Comment by clownfish44** [comment]
Already requested here https://github.com/taniman/profit-trailer-enhancements/issues/60
