### ISSUE TITLE
Report generation in excel with graph, charts.

### ISSUE THREAD

**Issue by knowngate** [taniman/profit-trailer-enhancements#108]
It is great if user can generate his excel report of all trade.
Excel should be more information with all graph, charts, it can be fill with more feature in future.

**Comment by knowngate** [comment]
*Data should be update in online doc.

**Comment by knowngate** [comment]
It's a physiological benefit if all r analys thr profit reports, sales of profit trailer grow with more people get involved in it.

**Comment by clownfish44** [comment]
Statistics, graphs and better tracking have been requested here https://github.com/taniman/profit-trailer-enhancements/issues/5
