### ISSUE TITLE
Enable community settings & presets to be shared and voted built into Profit Trailer

### ISSUE THREAD

**Issue by lunaravent** [taniman/profit-trailer-enhancements#109]
I'm sure that most of us here copied our settings from youtubers like CryptoCrow or CryptoGnome, especially when we were first starting out. I'm proposing a feature that enables individuals to share, comment and vote on each other's settings just by clicking 1 button. I know that this is a shortcut for newbies of PT, but I think it is the fast way to get started. They can then modify the settings later to their own liking, and can choose to share it or not. People can then tweak the settings together so that we all make max profits, share pump and dump coins to be excluded. Great way to grow the PT Community! 

This feature was actually implemented on Diablo 3 Bots, where people upload their settings for different characters with different builds, vote and comment on a website. That website actually links to their bot when they sign in. By clicking the settings to add to their bot on the website, they can then select the presets when they start using their bot on which settings they want to use.

To the moon!

**Comment by syl201971** [comment]
Cool proposition

**Comment by Tzarbok** [comment]
But wouldn't the copied settings become less and less profitable if everyone is using them?

**Comment by lunaravent** [comment]
I think the settings will act differently according to market conditions, so it will depend on how precise is your reaction to market changes with all the different presets, resulting in different profits

**Comment by Julianjg4186** [comment]
I think this would be very user friendly and help to protect new blood coming in to support this instead of messing up there bot

**Comment by clownfish44** [comment]
We have a community discord where you can talk strategy and share and upload settings just like you are describing.
