### ISSUE TITLE
Rich stats dashboard

### ISSUE THREAD

**Issue by ihackalot** [taniman/profit-trailer-enhancements#11]
A view including meaningful stats and tools to summarize a portfolio and slice data, much like a lite version of cointracking.info

#### Personal Analysis
- Interactive charts for trades and coins
- Calculation of key indicators
- Profit / loss, coin value & balances
- Realized and unrealized gains

#### Trades:
- List of all trades and fees
- Interactive search
- Trade annotations

**Comment by clownfish44** [comment]
Improvement already exists https://github.com/taniman/profit-trailer-enhancements/issues/5
