### ISSUE TITLE
Feature Request - Panic Sell Button in GUI

### ISSUE THREAD

**Issue by toosurreal01** [taniman/profit-trailer-enhancements#110]
Add a "panic sell" button to each row in pairs/dca log so you don't have to manually type in the pairs config to get rid of a coin.

I do this with sideways coins if I want to get out of them before they hit my sell trigger/trailing.
![untitled-1](https://user-images.githubusercontent.com/521737/36791510-15153f70-1c66-11e8-9cf3-e9e730ab6c08.jpg)

**Comment by clownfish44** [comment]
This has already been requested here https://github.com/taniman/profit-trailer-enhancements/issues/7
