### ISSUE TITLE
buy  on Bids side sell on ask side

### ISSUE THREAD

**Issue by koniu57** [taniman/profit-trailer-enhancements#111]
Bot buying pairs on Ask side only and seling on Bid side which on biger spread is kind of big loose on profit gains . it will be great if bot will be using Bids side price for buy and ask price ping for sell

**Comment by syl201971** [comment]
Interesting but would it limit the chances of getting the transaction done....

**Comment by koniu57** [comment]
I don t think so I woud say even it will incres chance of buy whitout spreed involved

**Comment by LeaderOfChampions** [comment]
The trade should happen at market value otherwise you are risking the execution of a successful trade at profit.

**Comment by koniu57** [comment]
only if spread will be biger than profit % take set up and even if that You will be geting instant buy -sell on profit Im right? let say PT buy from bids at 200 sat but ask side is at 180 sat thats 10% isntant gain in curent situation PT will be buy at 189 sat and You will be automaticly set at -10% profit which will triger DCA which hapend many time if spread is large enough isn t it? but that implementation will need as well put limit order in PT like it was on Gunbot

**Comment by clownfish44** [comment]
This would prevent trades from happening and would cause more missed trades and canceled trades of which canceled trades count toward ip bans on Binance so this would not be a good idea.
