### ISSUE TITLE
Be able able to select how much days you want to logs in sales 

### ISSUE THREAD

**Issue by syl201971** [taniman/profit-trailer-enhancements#114]

**Comment by LeaderOfChampions** [comment]
This is already a thing, read: 

https://wiki.profittrailer.io/doku.php/application.properties

trading.logHistory = 2

Set how many days of sell log history to show in the GUI. Once the set number of days passes, older history will be removed from the bot. Set this for as long as you want to hold the history, and use the Excel or Text export buttons to export your data if you want to keep it longer than that.

**Comment by clownfish44** [comment]
See post above! Thank you @LeaderOfChampions
