### ISSUE TITLE
Limit Sell Option

### ISSUE THREAD

**Issue by CryptoTurtle** [taniman/profit-trailer-enhancements#115]
It will be nice to be able to place an order with limit sell because PT sometimes misses good sell prices.  If we believe the coin will reach a certain value, we can set it to sell automatically instead of trailing profit percentage.

**Comment by sas7085** [comment]
There is no voting option. Need to vote +1.

**Comment by clownfish44** [comment]
sell buttons have been requested here https://github.com/taniman/profit-trailer-enhancements/issues/7 but to place a limit sell just go on the exchange
