### ISSUE TITLE
Dca calculator

### ISSUE THREAD

**Issue by syl201971** [taniman/profit-trailer-enhancements#117]
A web visual of the dca buying cost related to pair cost and double down configuration.  So it would be easier to make proper configuration for beginners.

**Comment by XxPhoenixXx** [comment]
Definit would be nice one day..  more of a Quality of life

**Comment by octobrium** [comment]
a dca calculator excel sheet is already floating around on youtube

**Comment by clownfish44** [comment]
There is no need for this however this already exists in ptmagic which has been requested to be merged in #19
