### ISSUE TITLE
Multiple DCA Sell Points

### ISSUE THREAD

**Issue by dtrigleth** [taniman/profit-trailer-enhancements#118]
Idea:
I think the ability to define multiple DCA sell points could be useful.

Example:
Coin has been in DCA for 1 day
    Use standard sell strategy
Coin has been in DCA for 5 days
    Use sell strategy #2, most likely a lower percentage
Coin has been in DCA for 10 days
    Use sell strategy #3 (for me I'd define this to be 0% because I'm tired of that capital being tied up)
I would even have a strategy for extra long DCA coins that would accept a small negative sell, just to get capital back.

Reasoning:
I noticed a coin of mine that was about a week into DCA had hit +0.2% profit, but then turned and went back to -6% a few minutes later. If there was a panic sell button (as I've seen mentioned already), I could have gotten rid of it instantly, but if I could have predefined DCA duration sell strategies I could feel better about not monitoring the bot so much.

**Comment by clownfish44** [comment]
Why cant you just open up the file and panic sell it using the line of code. Or go on the exchange and sell it. If anything the longer you hold a coin you want more profit to make up for lost time. This already exists as well as you can set the pending order time to place an order to sell at 0% profit.
