### ISSUE TITLE
Multiple remote login types

### ISSUE THREAD

**Issue by greywolf0210** [taniman/profit-trailer-enhancements#121]
I'm trying to start up a hedge fund type business using Profit Trailer to trade funds collected from several investors.  I'd like to be able to share one remote login password with investors that does not have access to the config files so they can keep track of the fund itself, but cannot change the settings, while still having a remote login for myself that does have access to the config files so that I can adjust the strategies remotely if needed.

**Comment by clownfish44** [comment]
Currently we do not allow commercial use / shared use without explicit permission please submit a ticket here https://support.profittrailer.com/
