### ISSUE TITLE
Add: Binance Auto Blacklist

### ISSUE THREAD

**Issue by orionmodern** [taniman/profit-trailer-enhancements#124]
"Binance Auto Blacklist
Automatically checks for new Binance listings and enables sell-only mode for pairs in ProfitTrailer. All newly listed coins will be set to sell-only mode in your PAIRS.properties file. If you are using PT-Feeder, your SomOnlyPairs in appsettings.json will be updated."

As seen on here: https://github.com/bennettca/binance-auto-blacklist

**Comment by clownfish44** [comment]
This already exists you even linked it?
