### ISSUE TITLE
Specific Coin Drop Triggers Suggestion

### ISSUE THREAD

**Issue by jaminess** [taniman/profit-trailer-enhancements#125]
Hello guys
it would be ASWSOME if it would be  possible to activate and deactivate specific coins if The Price drops or falls

For example as this setting is already working for all coins:
ALL_btc_price_drop_trigger = 4
(Goes into sell only mode BTC drops by 24% within the last 24 hours)

# What would be AWSOME:
Is it possible to deactivate/activate certain coins if i use this Command:

neo_price_drop_trigger = 4
(deactivates neo if it  drops by 4% within the last 24 hours)

neo_price_rise_trigger = 4
(activates neo if it  rises by 4% within the last 24 hours)

--------

XRP_price_drop_trigger = 4
(deactivates XRP if it  drops by 4% within the last 24 hours)

XRP_price_rise_trigger = 4
(activates XRP if it rises by 4% within the last 24 hours)

Greetings

**Comment by clownfish44** [comment]
this exists in feeder / magic which has been requested here https://github.com/taniman/profit-trailer-enhancements/issues/19
