### ISSUE TITLE
CAD and EURO

### ISSUE THREAD

**Issue by bradyn13** [taniman/profit-trailer-enhancements#127]
I live in Canada, and I'm sure a high percentage of users DO NOT live in the USA.

I would really like to be able to see my profits in CAD instead of USD.  Having the option to choose my currency would be great.  The options could be USD, CAD, and EURO.  A poll could even be taken to see which currencies are most in demand.

**Comment by djcrypto75** [comment]
![image](https://user-images.githubusercontent.com/28998183/36809383-76d323e8-1cd0-11e8-9b36-687a0bafa5a1.png)
