### ISSUE TITLE
2 Bases trading together one Bot (Read Example)

### ISSUE THREAD

**Issue by majhealth** [taniman/profit-trailer-enhancements#129]
The bot today calculates single pairs. This means if I set the config  MARKET = BTC it only trades BTC pairs on that one bot.

The bot should have the option to set  MARKET = BTC,ETH or  MARKET = ETH,BTC

Limits Pairs trading to those eligible for both Bases

MARKET = Base1,Base2

This allows for overall market growth with two coins vs just coin growth. Many people are not just doing this to build a portfolio of coins, but to build overall wealth in US Dollars. That being the case let us maximize that potential of earnings without changing to much of the Bot.

I will go through an example trade now.

Base1 PAIRs are evaluated for trades
If no Base1 pairs are good then Base2 is evaluated
Potential Trade is found between Base1ADA
Purchase price is recorded for Base1ADA, and Calculated for Base2ADA
PAIR/DCA is monitored for Base1ADA and Base2ADA value.
Base1ADA value tanks and becomes -3% profit while Base2ADA becomes +1 profit
ALL_sell_value = 1 so Base2ADA sell is triggered is normal trailing capabilities etc
1% overall trade wealth is gained.

Overall this should result in more trades and less DCA bags sitting stagnant for days waiting on a single pair to change. This is not to say the overall coin ADA in the example cant tank, but there are many cases where BTCADA may go down, but ETHADA goes up so the sell becomes better for ADA.

This is a real quick example and I know some things would need more fine tuning, but I think it explains enough of the overall idea and direction.

**Comment by clownfish44** [comment]
Already requested here https://github.com/taniman/profit-trailer-enhancements/issues/28
