### ISSUE TITLE
Add MACD as a Buying/Selling Strategy

### ISSUE THREAD

**Issue by drewfabrics** [taniman/profit-trailer-enhancements#13]
Hey ! I believe the community would love this indicator to be added it to the arsenal of buying strategies at least, MACD its use by many when charting and making buying/selling decisions. very powerful? Thank you for doing this ! 😁

**Comment by taniman** [comment]
This one is already being implemented in version 2.0
It's working for like 75%,

**Comment by drewfabrics** [comment]
Amazing, thank you so much. I will close this issue now then. 🙏
