### ISSUE TITLE
EMA calculation mode

### ISSUE THREAD

**Issue by futurestrader1987** [taniman/profit-trailer-enhancements#130]
Hello,

I would like to request a feature to be able to select by which mode the EMA calculates. Right now my guess is that its set to the close. I would like to be able to set it to calculate based on the low of the candle price, this makes entries after a pump and dump harder and entries from what I've seen in the charts are usually better.
something like this.
EMA_source = low

**Comment by clownfish44** [comment]
This would prevent a lot of good buys just use other ways to prevent pump and dumps
