### ISSUE TITLE
Total uptime readout

### ISSUE THREAD

**Issue by greywolf0210** [taniman/profit-trailer-enhancements#132]
I'd like to be able to see how long my bot has been up and running total without having to go in and do the math for all of the time it's been down for updates or errors or binance lockouts, etc

**Comment by elementalwindx** [comment]
Also make us aware when binance has locked us out. I don't know of any way to tell when binance locks me out, if ever.

**Comment by clownfish44** [comment]
A console requested here https://github.com/taniman/profit-trailer-enhancements/issues/147 is a much better idea and also just use telegram it tells you that your bot is having issues / down.
