### ISSUE TITLE
Volume Delta as criteria -> better P&D protection, future enhancement enabler

### ISSUE THREAD

**Issue by ACETyr** [taniman/profit-trailer-enhancements#134]
Recently in late Jan, early Feb we have seen huge volume increases in P&D actions which temporarily catapulted low volume coins well above the 1000BTC/24h mark. For such instances existing P&D prevention strategies bring no relief. 
I propose to add a form of Volume tracking as we do now with prices enabling several new possibilities in PT. If we can track trading volume Delta over a (preferably adjustable as 24h is too long of a time) timeperiod we can use this to more reliably make decisions if a pump is happening.
We also can confirm building momentum in pairs and could in successive features (to come) make better buy / sell / DCA decisions (for example: Shall we really DCA in a Pair with rapidly dwindeling Volume, too high negative volume delta usually means lower chance of price recovery soon).

Apart from the better P&D protection this is more of an "enabler" feature, allowing to build new functionality on it later on.

**Comment by clownfish44** [comment]
This would be a per pair feature and would be part of ptfeeder and ptmagic which is requested here #19

**Comment by ACETyr** [comment]
Actually **it is not** what is referenced here!! Neither ptfeeder NOR ptmagic take volume into account as of today and have a volume delta feature!
