### ISSUE TITLE
API for Addons

### ISSUE THREAD

**Issue by ACETyr** [taniman/profit-trailer-enhancements#135]
PT is great and the community loves it, 3rd parties are trying to work around lacking functionality via addons as PT-Feeder, PT-Magic, autopt, ...
Although the potential of such addons is great and enables additional functionality their use is limited by their means of interacting with PT only via config file changes. The approach of pulling data from PT files is clumsy at best and (when locking the file) disrupting eventually.
Why not make a standardized API for addons to interact with PT so Addons could interact better with PT and get live data about coins, dca levels, pending, sales in a safe manner (API keys).
This could even extend to the possibility of overrides. This should for safety reasons not be implemented via the GUI (HTTP GET/POST) requests.

**Comment by clownfish44** [comment]
There is no need for this as you can already do it with basic code
