### ISSUE TITLE
Feature Request: Paper Trading for Live Strategy Testing

### ISSUE THREAD

**Issue by PdubsRandom** [taniman/profit-trailer-enhancements#137]
If You could turn on test mode or a function that you could initiate coin amount and allow it to log a paper buy price, and monitor until sell. Using the exact functionality it currently has, but allow it to paper purchase a pair and hold until sell guidelines and then paper sell the pair, and log it as it was working per usual.
This would allow you to test thoroughly a strategy before going live on it. This would save on much of the troubles that we have in trying to find good settings. If you could trade in your settings for some days or a week and see how they react in the market, then you could fine tune them to make them work for you.

You could set this in the test mode or some other functionality and would be the 1 thing that i would love to see PT implement. Then i could test until my heart is content to hone my strategies and stave off bear and bull run settings that only half work.

**Comment by clownfish44** [comment]
there is no way that this would be any more accurate then the testing now as you can not implement expired orders, ping latency, and partial buy/sells into this.

**Comment by PdubsRandom** [comment]
Sorry Clown I disagree. If the system was able to run in a log file that would generate a logged buy price and wait to generate a logged sell price then that would let you test settings in market conditions without using your stake. It's all created and maintained in a log file and therefore your not putting your coins at risk to test a strategy and settings. 

It PT isn't interested in it as a viable then I figure illl get a dev team together to create yet another highly useful add on. 

I respect the creators but this would save so many people from trying to buy settings and losing while finding what works for them.
