### ISSUE TITLE
Enhancements Request - Minimize Bags! True, Progressive Trend Measurement

### ISSUE THREAD

**Issue by vovster** [taniman/profit-trailer-enhancements#138]
A way to help minimize bags and improve entry points: 
consider this real example from today: Runing PT + Feeder
settings: "MinutesToMeasureTrend": "60","TopCurrenciesToCheck": "35", Market BTC
 
AT 4pm - Top_Coin_Change (60mins) = 0.2077% 
AT 5pm - Top_Coin_Change (60mins) = 0.1826%
AT 6pm - Top_Coin_Change (60mins) = 0.1277%
AT 7pm - Top_Coin_Change (60mins) = -0.1826%

Now, this tells me that the market is dropping in general or BTC is jumping. PT, however, traded in boring through all 4 hours, and implemented no changes. At this point 7 out of 9 buys activated dca as  Top_Coin_Change progressively continues to drop. 

The idea is to make PT  aware of this progressive drop, particularly the change between the hours.  Detecting  that the overall coin drop has progressed between 4PM and 5PM, offsets can be applied. Moving on, detecting that from 5pm to 6pm the drop has progressed more, more offsets can be applied, or SOM, or even better a order wait time until PT detects a positive change in the hours that follow.  

To put it differently, if the change between 2 measurements is : 
X at 4pm <  X at 5pm = indicates bull market, 
X at 4pm > X at 5 pm  = indicates bear market (as in this example)

This simple function can provide for a real time, dynamic and progressive trend measurements; thereby enabling PT to recognize that a bear market is forming, even though Top_Coin_Change falls under boring conditions. 

{PS. The function can be further expanded to measure the progression of the trend: 
X at 4pm -  X at 5pm = Y
X at 5pm - X at 6pm = Z
IF:  Y - Z = Negative number - would mean the bear trend is accelerating, or the bull trend is slowing
IF:  Y - Z = Possitive number - would mean the bear trend is slowing, or the bull trend is accelerating.

As per this Example: 
X = 0.0251
Y=0.0549
X-Y= -0.0298 progressive change per hour, indicating progressive and accelerating downward trend. At this point would be best to apply offsets or have PT wait for a positive measurements which will indicate reversal to bull market}

I want to thank you for all your time and efforts, and thank you for considering this idea. All the Best!

**Comment by clownfish44** [comment]
This already exists in ptmagic/ptfeeder and is requested here  #19
