### ISSUE TITLE
Temporarily Blacklist a PAIR, to protect from PUMP-AND-DUMP's

### ISSUE THREAD

**Issue by NeXtAntiX** [taniman/profit-trailer-enhancements#139]
Temporarily Blacklist a PAIR, to protect from a PUMP-AND-DUMP's

If a PAIRS volume and or percentage growth spikes in a set time period, (eg, 12hours) The PAIR is added to a trade suspended list for a set time, (eg, 6 hours) This would be a simple solution to prevent the BOT from detecting a BUY of a PAIR after a PUMP.. 

On much of the back testing i have done on all the BIG BAGS i am holding :-( . I have noticed the BOT is been trigged to BUY, on many of the indicators on the backside of a PUMP. The falling percentage after a PUMP, triggers multiple buys. The BOT sees this and starts buying of the PAIR.. Best why to avoid this would be a cooling off paired for the PAIR, to holt in buying after a serge PUMP.

HEART BEAT for PAIRS
I would also like to see a HEARTBEAT condition for PAIRS, much like you have for the condition of the BOT it self.. 

If a PAIR is having a noice 1-2% rise and fall, in a 24-48 house period, this would be a good sign that the PAIR is healthy.. If these is a sudden rise (PUMP) or sudden drop (DUMP) in the price in that 24-48 hours period, then the health of the PAIR would signal unhealthy for trading.

#### Health of PAIR in 24-48 hours  #####
PAIR is Healthy (GREEN) 1% to 2% movement
PAIR is Moderate (ORANGE) 2% to 5% movement 
PAIR is volatile (RED) 5% to 50% movement

Declaimer:
The time frames (24-48 hour) and percentage’s (1%-2%) I have indicated above, are there for example only. I’m sure they would be different or could be set by the user in config settings PAIR LOG, in final release.

**Comment by tactikill** [comment]
like this but for specific pairs:

ALL_btc_price_drop_recover_trigger = 1
Valid Values: Decimal values greater or equal to 0

Turn off sell only mode if it was activated by price drop and BTC price recovers by the percentage in the setting. (Uses 24h % change in price).

ALL_btc_price_rise_trigger = 5
Valid Values: Decimal values greater or equal to 0

Turn on sell only mode if BTC price rises x% amount (Uses 24h change price). Useful to protect against large market swings if a big BTC price swing changes the market dynamics.

**Comment by Utone** [comment]
think fast. (it is  a great hint)

**Comment by clownfish44** [comment]
This is already in ptfeeder/ptmagic which has been requested #19
