### ISSUE TITLE
HEARTBEAT for PAIRS

### ISSUE THREAD

**Issue by NeXtAntiX** [taniman/profit-trailer-enhancements#140]
HEARTBEAT for PAIRS
I would also like to see a HEARTBEAT condition for PAIRS, much like you have for the condition of the BOT it self.. 

If a PAIR is having a noice 1-2% rise and fall, in a 24-48 house period, this would be a good sign that the PAIR is healthy.. If these is a sudden rise (PUMP) or sudden drop (DUMP) in the price in that 24-48 hours period, then the health of the PAIR would signal unhealthy for trading.

#### Health of PAIR in 24-48 hours  #####
PAIR is Healthy (GREEN) 1% to 2% movement
PAIR is Moderate (ORANGE) 2% to 5% movement 
PAIR is volatile (RED) 5% to 50% movement

Declaimer:
The time frames (24-48 hour) and percentage’s (1%-2%) I have indicated above, are there for example only. I’m sure they would be different or could be set by the user in config settings PAIR LOG, in final release.

**Comment by securitygeneration** [comment]
Quite possibly the one thing that I think could make a big difference to PT. At the moment PT will happily buy in at the top of a 20% rise, only for it to dump and leave you holding a -20% bag for a long time. I'd like to see the ability to set ±% values and only trade pairs that are within that threshold.

**Comment by jbraydc** [comment]
We have pump and dump protection with PT magic now but having it in PT wouldn't hurt

**Comment by clownfish44** [comment]
This already exists in pt magic / feeder and has been requested here #19
