### ISSUE TITLE
STOP the BAGS, give the BOT better VISION = Profits :-) (Stochastic, KDJ)

### ISSUE THREAD

**Issue by NeXtAntiX** [taniman/profit-trailer-enhancements#142]
In much of the back testing i have done on the buying and selling of the BOT. I have noticed, if the buy and sell strategy’s where accompanied with the aid of Stochastic eg,(KDJ) it would be a great help. This is just one strategy aid of many, YES know. Giving the BOT any better vision on the bottom and the top of a trend would be a great aid for the currant available strategies, and minimising the number of BAG’s, I’m sure..!

We all want the best profits from are BOT, but if the BOT cannot see then we are stabling in the dark holding BAG’s. Better vision, better trades.

Binance HIGHBB, LOWBB, Stochastic (KDJ)
https://www.binance.com/tradeDetail.html?symbol=OMG_BTC

Trade with the Stochastic Oscillator
https://youtu.be/DdVPFBcdkvo

AnyChart Documentation
https://docs.anychart.com/Stock_Charts/Technical_Indicators/KDJ

**Comment by clownfish44** [comment]
New indicators are in the 2.0 milestone please add to one found here https://github.com/taniman/profit-trailer/issues?q=is%3Aopen+is%3Aissue+milestone%3Av2.0
