### ISSUE TITLE
Feature request - ichimoku cloud buy/sell strategy

### ISSUE THREAD

**Issue by mgh425** [taniman/profit-trailer-enhancements#143]
adding buy/sell strategy using ichmoku cloud indicator

**Comment by jrodder** [comment]
Ichimoku for trend analysis alone would be nice.

**Comment by clownfish44** [comment]
New indicators are in the 2.0 milestone please add to one found here https://github.com/taniman/profit-trailer/issues?q=is%3Aopen+is%3Aissue+milestone%3Av2.0
