### ISSUE TITLE
Make a instant trade via telwgram, by sending coin and buying price.

### ISSUE THREAD

**Issue by knowngate** [taniman/profit-trailer-enhancements#144]
I feels sometime that it would be great if I can send my vps profit trailer bot via telegram a coin with buying price so if condition meets it can make a trade with that coin.
I m member of some community which provides me daily coin for trade, and they r high accuracy.
It would be great if this can be possible.

**Comment by RunPlz** [comment]
I'm sorry but this looks like laziness to me...

You can always log into your exchange and have a limit order placed.
Some exchanges even offer their trading app.

**Comment by knowngate** [comment]
If bot permits after scanning it will make a trade.
Yes u r right that it can done by exchange but I want statics data from bot of how much profit m gaining.
Just a minute thought.

**Comment by RunPlz** [comment]
If you have the trade done manually I understand the bot will update the purchase and will provide you with the regular statistics for a trade. 

Is this not happening?

**Comment by clownfish44** [comment]
Use the exchange or use the bot config to do this
