### ISSUE TITLE
[Feature Request Needed] Hodl specific coin, make the bot buy into the coin or DCA when its low for Long Term & Not Sale 

### ISSUE THREAD

**Issue by chillz561** [taniman/profit-trailer-enhancements#145]
This is a feature I am begging to be implemented I want the bot to Hodl a specific coin and buy into it every time the price dips  and not sell for example I want to Hodl XRP or LTC  I would like the bot to stock up on the coin by constantly buying the coin for specific amount OR percent every time the coin drops in price or basically just DCA the coin and never sell this would be great for long term holds, investment. While at the same time doing regular trades buy,dca,sell with other coins

**Comment by PdubsRandom** [comment]
If they have the individual D.C. a settings you could ddo that. Put a heading above the D.C.'s setting for HODL and set it at D.C.'s levels you'd buy.

**Comment by chillz561** [comment]
@PdubsRandom I started experimenting  with dca's to do that but it took me way to long to figure cause  i also wanted to trade and dca other coins which i wanted to dca at lower levels then the coins i want to hodl maybe setting individual DCA levels for specific  coins Would be a good feature also.

**Comment by RunPlz** [comment]
Is this a bot for holding assets or market trading?

**Comment by clownfish44** [comment]
Already requested here https://github.com/taniman/profit-trailer-enhancements/issues/40
