### ISSUE TITLE
[Feature Request] Create a page that ranks the coins you've bought and sold

### ISSUE THREAD

**Issue by elementalwindx** [taniman/profit-trailer-enhancements#146]
Create a page that ranks the coins you've personally bought and sold with your bot over an adjustable range of time (or all time) to give the user an insight on whether they should blacklist or whitelist a particular coin.

**Comment by clownfish44** [comment]
More statistics and tracking requested here https://github.com/taniman/profit-trailer-enhancements/issues/5

**Comment by elementalwindx** [comment]
These are not the same ideas man. Nothing alike.

**Comment by elementalwindx** [comment]
No revise to this? My request and the one you linked are not the same. 

I'm saying create a ranking on each coin showing the most profits made per coin. Pt tracker does not do this. I think this would be helpful to perhaps put the losers you invested in on the som list if we choose to.
