### ISSUE TITLE
[Feature request] incorporate killer entry/exit strategy - Godmode3.1 + LSMABG . example posted

### ISSUE THREAD

**Issue by D3adm3at** [taniman/profit-trailer-enhancements#148]
Would love to incorperate a strategy on tradeview. Its a great indicator used by daytraders.

Godmode3.1 (9,6,3)
LSMABG (32,0)

entry/exit points only the yellow indicator plot points. works like a charm everytime i go manual.

<img width="988" alt="screen shot 2018-03-01 at 10 39 40 am" src="https://user-images.githubusercontent.com/36961285/36853593-e41eb28e-1d3c-11e8-8b10-e10585e7ac30.png">

here are 2 good examples. script's provided on both examples

https://www.tradingview.com/chart/BTCUSD/QI5Ss5M3-Basic-Understanding-of-HOW-to-use-Godmode-Pasted-in-comments/

https://www.tradingview.com/script/oA3U7pok-GODMODE-OSCILLATOR-FRESH-BREAD-GENERATOR-FREE-TO-USE/

**Comment by clownfish44** [comment]
New indicators are in the 2.0 milestone
