### ISSUE TITLE
Trading setups

### ISSUE THREAD

**Issue by ihackalot** [taniman/profit-trailer-enhancements#15]
A view to edit, review, save and activate alternative configurations based on market conditions. This way it's possible to work on different strategies and quickly de/activate them. I do understand there are overlaps with PT Feeder and other plugins, however I do think this should be a core feature of the bot.

**Comment by iAmVaeVictus** [comment]
Should incorporate Feeder. Just sayin.

**Comment by planetofzog** [comment]
Absolutely, this should be a core part of the bot and not difficult to implement. You could allow 4 or 5 user defined rules for Pairs/DCA/SOM depending on a % change in a defined amount of minutes/hours

**Comment by clownfish44** [comment]
This already exists in feeder and has been requested to merge here https://github.com/taniman/profit-trailer-enhancements/issues/19
