### ISSUE TITLE
[Feature Enhancement Game] - Manual Sell Button

### ISSUE THREAD

**Issue by thebosstrader** [taniman/profit-trailer-enhancements#150]
My request is to add a Red Sell Button next to each Pair & DCA Pair in profit trailer.  It would be nice to be able to use the bot to manually sell.

Just my two cents.

**Comment by clownfish44** [comment]
https://github.com/taniman/profit-trailer-enhancements/issues/7

**Comment by thebosstrader** [comment]
What was the reason for closing this?  Did this exists already or did I post it in the wrong place for the game?
