### ISSUE TITLE
[Feature request] Selective DCA

### ISSUE THREAD

**Issue by dutchy1966** [taniman/profit-trailer-enhancements#151]
I would like an option to "mark/select" coin pairs for DCA. DCA can easily eat your balance and get you trapped with all your money stuck in DCA and no longer a possibilty to buy new pairs. If there is a "mark/select" option you could select one or a couple of coins to DCA. After they are cleared some other coins can be selected for DCA. That way you keep way more balance for buying. >>Clear bags a few at a time instead of all in parallel.<<

**Comment by clownfish44** [comment]
You can already do this just turn dca on for a pair when u want to dca and turn it off when you don't want to dca.
