### ISSUE TITLE
FIFO sell strategy

### ISSUE THREAD

**Issue by hemants1** [taniman/profit-trailer-enhancements#156]
Once DCA starts to accumulate at every buy trigger.. it would be nice to to have sell trigger that sells coin bought at low.

DCA
------
buy_trigger_1 = -1.5  ---> Sell this first at 10% profit
buy_trigger_2 = -3.5  ---> Sell this first at 1% profit
buy_trigger_3 = -7.5  ---> Sell this first at 1% profit
buy_trigger_4 = -9.5  ---> Sell this first at 4% profit
buy_trigger_5 = -12.5  ---> Sell this first at 2% profit
buy_trigger_6 = -17.5   ---> Sell this first at 1% profit

Hope this way, you can get rid of bag faster rather than waiting for average price...!

**Comment by clownfish44** [comment]
this would not get rid of bags faster as once you sell the bottom one your average price goes back up hence making it harder to clear upper level bags

**Comment by hemants1** [comment]
But think of a scenario where the budget is fixed and price stuck in the range of -15 and -20 for long time. That time it will help in selling and buying consistently around that range hence reduce avg price and get out faster.


Regards,
Hemant Srinivas
BT&S Applications Run Ops
1 262-290-6475 (M)
1 414-524-5536 (O)
________________________________

**Comment by RunPlz** [comment]
Interesting thought on the "LIFO" / "FIFO" strategy ...
