### ISSUE TITLE
COIN Specific DCA settings

### ISSUE THREAD

**Issue by hemants1** [taniman/profit-trailer-enhancements#157]
It would be nice to have DCA settings for individual coins. Right now I believe DCA settings are applicable for all coins not sure if DCA settings can be set for each individual coins similar to PAIRS settings.

Example:

TRX_buy_strategy = ANDERSON
TRX_buy_style = DOUBLEDOWN
TRX_buy_trigger_1 = -1.5

ADA_buy_strategy = LOWBB
ADA_buy_value = 5

**Comment by hemants1** [comment]
Similarly it would be nice to have sell strategy for individual coins in DCA settings.

**Comment by Julianjg4186** [comment]
This would be nice

**Comment by clownfish44** [comment]
Already seems to exist and more functionality to this feature is in the 2.0 milestone release.
