### ISSUE TITLE
Identify different bots 

### ISSUE THREAD

**Issue by Drakkar1964** [taniman/profit-trailer-enhancements#158]
This might not get enough support as I dont think there is many people using more than 1 bot...
Im trading with 2 to 3 bots and it get confusing sometimes which is which.

Having a away to identify each bot would be great so you dont end up changing something on the wrong bot.

Maybe be able to change background colors or name each bot and the name then shows somewhere on your user interface?

**Comment by clownfish44** [comment]
The name which is set as server.sitename = is shown as the tab title which will help u from being mixed up
