### ISSUE TITLE
Feature Request: ALL_max_cost_percentage based on Balance

### ISSUE THREAD

**Issue by hcmikejj** [taniman/profit-trailer-enhancements#159]
With this feature you will pay less for a coin if you are low in balance and make smarter buys based on the cost.
For example, if you have a total value of $10000 and you have 4 of the (max) 8 pairs with bags, if those bags take like 80% of you total value you have $2000 left. If you buy with 3% of your your total value you buy a coin for $300, this don't make sense if you have only $2000 left. Now if you buy with ALL_max_cost_percentage **based on Balance** you can trade with your full balance because now you are using 3% ($60) of the $2000 you have left! I hope this will make some sense for you guys, please leave a comment if you have other thoughts :)

**Comment by clownfish44** [comment]
This already exists please see the wiki.

**Comment by hcmikejj** [comment]
i can't find this function, as far as i can find in the wiki the ALL_max_cost_percentage is based on TCV and not on the current balance you have! This is what the wiki is showing, and this function is not suppose to be a coin specific option. Thank you

Valid Values: Decimal value greater or equal to 0.
Indicate % of total current value (TCV) of account we will use to buy.
This property only works if ALL_max_cost = 0. This is useful when your balance changes frequently and you want to keep a minimum balance.

COIN-PAIR ENABLED: This setting works with single coins. See here for more info.
