### ISSUE TITLE
Buy Trailing Based on Buy Strategy Value

### ISSUE THREAD

**Issue by renatoshira** [taniman/profit-trailer-enhancements#161]
New trailing buy based on strategy buy value, not on coin value

Why?
- Lots of times, trailing just doesn't work as expected as the coin price bumps because of individual buys/sells. When it's based on the buy strategy metric, this can avoid this behaviour on medium-low volume coins
- Sometimes, as EMASPREAD for instance, you want to buy when the spread starts to get lower, not really when it's still increasing. Sometimes the spread is still increasing but punctually the price goes up and current trailing buy is reached. So the bot buys, but the spread is still increasing.

**Comment by clownfish44** [comment]
This is already in the 2.0 milestone
