### ISSUE TITLE
Bring VOLUME variable to configs (and also allow math formulas there)

### ISSUE THREAD

**Issue by renatoshira** [taniman/profit-trailer-enhancements#163]
Lot's of the configs on PT can work well for a high volume coins but poorly for low volume and vice-versa

### Example:
Trailing buy of 0.1 can be a good number for a high volume coin, but kind of irrelevant for low volume (since the price changes much more abruptly) 

### Solution:
Be able to do something like:

Max between 0.1 and ((10000 - PAIR_VOLUME_24H) / 10000). High volume coins = less trailing
> ALL_trailing_buy = MAX(0.1, ((10000 - PAIR_VOLUME_24H) / 10000))

The same can be applied to other configs like buy value, etc.

**Ideas of variables:**
PAIR_VOLUME_24H
PAIR_VOLUME_1H
PAIR_PRICE_CHANGE_24H
PAIR_PRICE_CHANGE_1H
PAIR_AVERAGE_CANDLE_SIZE_24H
PAIR_LAST_BUY_SEC_ELAPSED
PAIR_LAST SELL_SEC_ELAPSED
BTC_VOLUME_24H
BTC_PRICE_CHANGE_24H

**Ideas of functions**
MAX
MIN
POW
ABS
basic math operators
ROUND

**This would make PT so more flexible.**
** Add on logs possible errors on configs: formulas and sintax

**Comment by nsater** [comment]
I was going to suggest something along these lines but you beat me too it (and did a better job).

For me personally, the bags that I hold have come from coins whose **volume** and **price** went up for a short period of time. They were not pump and dump per say, but something caused the price and volume to rise well over 50%, hold, then start to fall back over the coarse of a few days.

Protection from this can come from addons such at PTMagic and PTFeeder, but it would be nice to have the variables as suggested above. They would help filter out coins that have large swings in price and volume that can be risky for the bot to trade in.

**Comment by clownfish44** [comment]
One request per issue please!
