### ISSUE TITLE
Trailing Profit timer

### ISSUE THREAD

**Issue by razedavid** [taniman/profit-trailer-enhancements#165]
Trailing Profit setting are great to gain most profit, however sometimes it acts against you.
a timer will be greatly improve exiting pairs which turned sideways.

the idea is once the sell Trigger activated the trailing profit % kicks in, it may go up to 2% gain but stay there for couple mins and dropped back down to1%.
if we put a timer on the trailing profit and price stayed for a period of time trigger sell order instead trailing more profit.

Example:
Sell Trigger = 1%
trailing Profit = 0.3%
trailing profit trimer = 3 (mins)

pair triggered sell at 1%
1% -> 1.5%
1.5% -> 1.3%
1.3% -> 2%
stayed at 2% for more than 3 mins trigger sell order.

**Comment by clownfish44** [comment]
This would prevent coins from selling as the profit % changes the timer would reset.  + You would lose out on alot of coin spikes for profit
