### ISSUE TITLE
Multiple indicators

### ISSUE THREAD

**Issue by msaleh3000** [taniman/profit-trailer-enhancements#166]
It would be great to be able to define multiple indicators, Example:
EMA_1_period = 300
EMA_1_1 = 24
EMA_1_2 = 12

EMA_2_period = 900
EMA_2_1 = 25
EMA_2_2 = 17

EMA_3_period = 1400
EMA_3_1 = 20
EMA_3_2 = 9

and then I can choose which one to use when buying for a specific coin, Example:
ALL_buy_strategy = EMAGAIN
ALL_buy_indicator = EMA_2

and ofcourse the main reason for this is the coin specific setting, Example:
BTC_DASH_buy_strategy = EMAGAIN
BTC_DASH_buy_indicator = EMA_1

This is very useful for coin specific strategy as well as long term vs short term investment strategies, since not all coins behave the same in their ups and downs and short term and long term, different values for the indicators will greatly improve the performance. 

Thank you.

**Comment by clownfish44** [comment]
Already in the 2.0 milestone release to have multiple indicates
