### ISSUE TITLE
Reverse DCA strategy

### ISSUE THREAD

**Issue by aktrader87** [taniman/profit-trailer-enhancements#168]
Make it possible to use a lower buy trigger first.

ex. 

buy_trigger 1 = -10
buy_trigger 2 = -5
buy trigger 3 = -2.5
buy trigger 4 = -1.25

this would allow the pair in dca to be launched up to -0.75 with (4) levels of DCA which could have a better chance of being sold.

**Comment by RunPlz** [comment]
Why?

**Comment by aktrader87** [comment]
Basically the way DCA works now is that it buys on the way down. EX. trigger 1 = -2.5 and trigger 2 = -5 etc..

If we could use a trigger 1 = -10 and trigger 2= -5, what it does is buy more of that pair and halve the %, essentially pushing up our pair as far as our DCA levels go. I think it would be a way to get out of holding DCA bags instead of how it is setup now, and have a chance to sell quicker with more total value.

**Comment by clownfish44** [comment]
You can already do this now just set the triggers like you just did...

**Comment by aktrader87** [comment]
so you are saying setting the DCA trigger this way, the bot wont skip to trigger 2 before trigger 1?

**Comment by RunPlz** [comment]
Yes, LOL.

**Comment by aktrader87** [comment]
Ok i assumed it would hit a trigger and not go in sequence, my misunderstanding.
