### ISSUE TITLE
Seperate Balances for Different pairings

### ISSUE THREAD

**Issue by aktrader87** [taniman/profit-trailer-enhancements#169]
Not sure how this would work, but if you could allocate portions of your budget to BTC, ETH and USDT. This would widen up the possible trades and allow PT to make better choices by having a more strict buy strategy.

**Comment by aktrader87** [comment]
And to further this idea, you could have 1 bot that trades on multiple exchanges using the same concept.

**Comment by clownfish44** [comment]
Already requested here https://github.com/taniman/profit-trailer-enhancements/issues/28
