### ISSUE TITLE
Manual Sell Button

### ISSUE THREAD

**Issue by Ridonia** [taniman/profit-trailer-enhancements#17]
Sometimes DCA Bags floating around in a small positive or very small negativ ammount.
Only way to get rid of them is to panicsell. Thats ok, but for people who actually work with the bot, those command line inputs are a pain in the a** :-)
Would be Nice to have a "Sell-Button" (wich writes a panicsell comand in hotconfig) next to your pairs and dca pairs.

**Comment by clownfish44** [comment]
Issue already exists https://github.com/taniman/profit-trailer-enhancements/issues/7
