### ISSUE TITLE
Sell instantly ( Market Price )

### ISSUE THREAD

**Issue by filla17** [taniman/profit-trailer-enhancements#172]
Please Add button to Sell instantly ( Market Price )in DCA Log

**Comment by filla17** [comment]
Suggestion for PT enchancement

**Comment by chostetler15** [comment]
Can't you just log into your binance, bitrex, etc account and manually do that?

**Comment by filla17** [comment]
Yes, I can

**Comment by clownfish44** [comment]
Already requested in #7
