### ISSUE TITLE
[Feature Request] some how use TradingView buy, sell feature  make buying decisions 

### ISSUE THREAD

**Issue by chillz561** [taniman/profit-trailer-enhancements#174]
Not sure if its possible or if the the bot already does this but it would be cool if PT can somehow use the Technical Analysis feature of Tradingview to make smarter buys & sells https://www.tradingview.com/symbols/LTCBTC/technicals/ for example maybe the bot can read the indictors for buy or sell recommendation and make a descion with your settings in mind.

**Comment by Julianjg4186** [comment]
If this is possible this would be very useful

**Comment by clownfish44** [comment]
External signals have been requested here https://github.com/taniman/profit-trailer-enhancements/issues/14
