### ISSUE TITLE
Trailing Stop Loss / Stop Loss Trailer

### ISSUE THREAD

**Issue by DavidBriongos** [taniman/profit-trailer-enhancements#175]
Mi idea is to implement a Trailing Stop Loss. May be called Stop Loss Trailer.

For example, I want set profit at 3% but I don't reach it, because the price at 2.5% of profit go back down again. May be the Stop Loss Trailer can be configurated at 0.5% down trailing, in consecuence the bot can sell at 2%. I'm still winning and I don't generate bags.

Thank you!

**Comment by cobuscoetsee** [comment]
This will be great on a DCA so if I can say if a big DCA recovered with 10%, and then lose 2% for example, sell sell sell.

**Comment by octobrium** [comment]
the bot can already do what you described in the example. however, trailing stop loss at negative profit would be a nice idea, if it does not exist currently in PT

**Comment by clownfish44** [comment]
This would defeat the purpose of setting 3% sell as stuff would sell before this all the time.

**Comment by DavidBriongos** [comment]
I was suggesting something like this:

![captura](https://user-images.githubusercontent.com/37013297/37119237-11a08a56-2257-11e8-98d0-548959d782de.PNG)

This image is extracted from a functionality of another bot that exists in the market (gunbot).

Trailing Stop and Trailing Profit together.

Something like that would be great in Profit trailer!

**Comment by DavidBriongos** [comment]
I'm sorry I did not notice that it was closed.
