### ISSUE TITLE
Detailed Daily Report (24 Hour Period) to Measure the Effectiveness of PT Settings

### ISSUE THREAD

**Issue by devytan** [taniman/profit-trailer-enhancements#176]
I've been using profit trailer for a while now (less than a month I'd say). And so far my goal is simple, I want to make the most gain with the least size (percentage) of my portfolio/capital. 

It'll be great if I know:
1. how much (percentage) of my portfolio being traded over 24 hours.
2. how much (percentage) I gain over 24 hours (so far I can do it manually and calculate back from the report).

With these data I can measure how effective my settings are. 
DCA levels and size (percentage), buy and sell strategy, trailing strategy.

And maybe some sort of repository (totally unrelated with the topic but I give it a go, I guess) so I can revert back using my saved settings (although technically I can do it manual).

**Comment by clownfish44** [comment]
Most of this has been included / requested here https://github.com/taniman/profit-trailer-enhancements/issues/5
