### ISSUE TITLE
Multiple Exchanges - GUI

### ISSUE THREAD

**Issue by jorgebouche** [taniman/profit-trailer-enhancements#177]
This is a twofold idea:

1. Allow the GUI to monitor multiple instances of the bot at once. Initially picturing a drop-down menu or something similar in order to jump between active exchanges. This way, one can monitor all active instances of the bot through one interface. 

2. Allow for trading/transfer of currency between active exchanges, potentially (albeit highly unlikely) allowing for arbitrage opportunities.

**Comment by clownfish44** [comment]
Only one request per issue + no arbitrage
