### ISSUE TITLE
Minimum age variable for coin to allow trading

### ISSUE THREAD

**Issue by elitriona** [taniman/profit-trailer-enhancements#178]
Create a new variable to set a minimum age of a coin on an exchange to trade with it.
For example: minAge = 30
Would mean that a coin would have to exist on an exchange for 30 days before ProfitTrailer would trade with it.

**Comment by clownfish44** [comment]
This already exists https://github.com/bennettca/binance-auto-blacklist

**Comment by elitriona** [comment]
It only exists now as a third party integration. The ask is to have the functionality built in to PT, which it is not right now. If you are rejecting ideas that exist as third party solutions already, then why don't you close these too?:
https://github.com/taniman/profit-trailer-enhancements/issues/19
https://github.com/taniman/profit-trailer-enhancements/issues/5
