### ISSUE TITLE
Sell 50% at a time

### ISSUE THREAD

**Issue by octobrium** [taniman/profit-trailer-enhancements#179]
There should be an option to sell 50% at a time instead of just selling everything
This is basically a **reverse DCA:**

ALL_sell_percent = 50
ALL_sell_interval = 5

Coin trend: +1%, +5% (Sell 50% here), +3%, +2%, +6%, +9%, +11% (sell 50%), +7%, +17% (sell 50%)
_instead of selling everything at +5%_

Spreading profit out = maximizing profit

**Comment by clownfish44** [comment]
Coins do not typically do as your talking about and if the coin is trailing down and sells and never gets back up which actually happens very often then your holding. + The time for it to go back up you are losing $ by not trading other pairs.

**Comment by Simon2PT** [comment]
@clownfish44 If a bot buys during a good dip, I would want it to sell gradually.

**Comment by kian25** [comment]
This is actually a nice feature that can be implemented for different strategies
