### ISSUE TITLE
More indicators and ability buy based on more than 1 indicator

### ISSUE THREAD

**Issue by Vahren** [taniman/profit-trailer-enhancements#180]
Would like to see an RSI indicator/strategy, as it can be a good way to see over bought/ over sold, but would want to use this in conjunction with other indicators/strategies. Probably other indicators people would like to use also?  RSI would ideally set percentage high/low eg 70% 30% and also time frames 15 min 1 hr etc.

**Comment by Julianjg4186** [comment]
This would be amazing

**Comment by Julianjg4186** [comment]
This would be amazing

**Comment by airtime23** [comment]
Yes!

**Comment by clownfish44** [comment]
Already in 2.0 milestone
