### ISSUE TITLE
UPDATE BOUGHT PRICE AUTOMATICALLY AND AUTO CONVERSION UPON SWITCHING CURRENCY'S  

### ISSUE THREAD

**Issue by dbottrader** [taniman/profit-trailer-enhancements#181]
It would be convenient and and save a lot of time and money, i have lost money upon trying to convert upon switching from btc to eth, usdt or what have you as my dominant trading currency.

**Comment by clownfish44** [comment]
Already sorta requested here https://github.com/taniman/profit-trailer-enhancements/issues/28 which would solve this issue and be better!
