### ISSUE TITLE
(D)eeply (C)ommited (A)ssets......BUY LADDERING.......; DCA improved 2.0 

### ISSUE THREAD

**Issue by drbrauwn** [taniman/profit-trailer-enhancements#182]
**Intro**
When pairs go into DCA, and shit really hits the fan, you are in DOUBLE trouble….. and I believe improvements can be made. 

The DCA calculator (all credits to JB) does a wonderful job in showing how different DCA levels affect your (available) Balance. 

It also wonderfully pinpoints a dilemma, I think many of us are running into;
Capital that is sitting on the side, is doing nothing for you. On the other side; capital tied up does restrict you from further moving with the market and leaves you at the mercy of the market

When thinking out your strategy, you soon learn that everything is connected. If you change one parameter, it affects all the others.

**Problem analysis**
Doubling down, exponentially increases your commitment to any position you hold for a pair. It is a very aggressive strategy, which impacts all other decisions too heavily, which are; 

-	How many DCA levels you run
-	At what % your DCA buy triggers can be set
-	The initial cost of your pair
-	How many pairs you can run
-	And so on….

**Suggestion- Don’t Chew All 2.0**
We need Buy Laddering.

This way we can easily set 10 – 15 buy triggers. Each buy trigger can be set to match initial cost or any percentage you like. 

For each buy trigger you would then specify, at what minus % it should trigger (the way it already is), but you would in addition also specify how much of the coin PT buys at every trigger.

It could look like this:

buy_strategy = ANDERSON
buy_style = DOUBLEDOWN
buy_trigger_1 = -1.25 
buy_trigger_2 = -1.75
buy_trigger_3 = -2.75
buy_trigger_4 = -3.5
buy_trigger_5 = -5.5
buy_trigger_6 = -6.5

Introducing Match Initial Cost (MIC)
holdings_trigger_1 = DCA  (it does a full DCA)
holdings_trigger_2 = MIC (it does a buy at your initial cost)
holdings_trigger_3 = MIC (it does a buy at your initial cost)
holdings_trigger_4 = DCA  (it does a full DCA)
holdings_trigger_5 = MIC (it does a buy at your initial cost)
holdings_trigger_6 = MIC (it does a buy at your initial cost)

Of course there are endless variations on the above, you could work with % of your holdings as well.

**The extra benefit**
Now DCA’s can be managed way more subtle since PT is able to profit of a price drop by buying more of the coin without committing to heavily and buy again if price drops further. Since you have more buys on the way down, your chances of getting out increase.

10-15 buy triggers at different levels, also means 10-15 TRAILING opportunities which is a great improvement for Profit TRAILER!!

(DCA should be coin-specific as well for above to work to its fullest potential)

**Comment by GrummeKrumme** [comment]
Coin-specific DCA would be a great feature to have.

**Comment by clownfish44** [comment]
Partial dca's would not lower the coin price as much as just hvaing fewer dca's and larger spread between them, which is what you are supposed to use ;D.
