### ISSUE TITLE
Filter coins with less than a certain amount of days of data in the exchange

### ISSUE THREAD

**Issue by amosdeluniverso** [taniman/profit-trailer-enhancements#183]
Create an option to set this filter so if i dont want to trade new coins the bot wont buy them. I'm trying to avoid new coins which dont have enough datafor me to know if i want to trade them, also avoid exposure to the initial dumps of new coins.

**Comment by elitriona** [comment]
https://github.com/taniman/profit-trailer-enhancements/issues/178

**Comment by amosdeluniverso** [comment]
closed: Duplicated with #178
