### ISSUE TITLE
Manual Panic Sell Button

### ISSUE THREAD

**Issue by SleazyE** [taniman/profit-trailer-enhancements#184]
Panic Sell button for each pair within Pairs Log and DCA Log, then prompted for confirmation of panic sell, similar to the Stop PT Button.

**Comment by tru-fkn-blu** [comment]
+1

**Comment by Tosko4** [comment]
+1

**Comment by clownfish44** [comment]
requested here https://github.com/taniman/profit-trailer-enhancements/issues/7
