### ISSUE TITLE
Automate Pivot Reversal Strategy

### ISSUE THREAD

**Issue by HarryChronicJr** [taniman/profit-trailer-enhancements#185]
I believe with the automation of these pivots, that the potential for much higher profit percentage is obtainable. 
I have found no way to automate buys and sells on PVR with any other app or means.

I think this could be a game changer!

Thank you, if you need morw information on the strategy I can certainly provide it.

**Comment by clownfish44** [comment]
In 2.0 you can use multiple indicates which would eliminate the need for this as it will be more accurate.
