### ISSUE TITLE
Max Buy Curve based on available BTC Balance

### ISSUE THREAD

**Issue by chostetler15** [taniman/profit-trailer-enhancements#186]
Rather than having a fixed amount or a fixed percent to buy (ALL_max_buy_cost or ALL_max_cost_percentage settings), I would like to have this as a curve based on your available BTC balance.

**Example:** I just started Profit Trailer and I have 1 BTC in my account. 
ALL_max_buy_percentage: 5, 
**new setting:** 
ALL_max_buy_curve: 1.00 (setting can be adjusted from -1.00 to 1.00)

My first trade will be executed for a total amount of 0.05 BTC (5%), but now 5% of my total balance is in pairs/DCA. My second trade would be at a formula of: 

((BTC Available) x (1-(ALL_max_buy_curve x % of potential balance in (pairs+DCA))) x (All_max_buy_percentage)

Breakdown.....

0.95 BTC x (1-(1.00 x (0.05BTC / 1BTC)) x 5% = 0.045125 BTC 

This calculation will bring our buy price to a curve based on our curve setting. +1.00 will be a very conservative curve, while inversely -1.00 will be a very aggressive curve keeping our % buy high until we almost have no money available. A curve setting of 0 would be a linear translation of our investment. Any curve setting would be more safer/more conservative than the fixed rate that Profit Trailer has currently.

See this spreadsheet for the example. 
![all_max_buy_curve](https://user-images.githubusercontent.com/32551211/36951549-0b6c395e-1fba-11e8-82bf-10c05957b731.png)

Current profit trailer settings will get you deep into your DCA early if you have a couple bad buys and it doubles down a few times. But with the settings I propose you could be buying new pairs all the way down to your last satoshi. 

Please let me know if you have any questions. I can break this down further if you need a better explaination

**Comment by clownfish44** [comment]
Would need to be implemented along with this https://github.com/taniman/profit-trailer/issues/606
