### ISSUE TITLE
Better buying strategies (combined indicator)

### ISSUE THREAD

**Issue by syl201971** [taniman/profit-trailer-enhancements#187]
Using multiples indicators to help with buying coins on upward swing rather than buying coin that are on the down slope. Combinaison of fibonnaci and elliot wave or others would help in choices. The robot could then propose wich one you would like to buy.

**Comment by ajpyoung** [comment]
Elliot wave, Andrews' pitchfork, and Fibonachi combination

**Comment by airtime23** [comment]
This is the single most important feature that I would like to see, as well!  +1!

**Comment by clownfish44** [comment]
Already in the 2.0 milestone
