### ISSUE TITLE
Manual Sale Profit Logging

### ISSUE THREAD

**Issue by XanTheMadAussie** [taniman/profit-trailer-enhancements#188]
I know I’m not alone when I see a coin rising and I know it’s about to drop, so rather than letting it drop a few percent before PT triggers, or kisses the sale entirely, I do a manual sell. It would be good to work out he value and profit of this sale, then add it to the sales log! 

Pretty sinple idea and addition, but would be great for PT to keep track of these.

**Comment by XanTheMadAussie** [comment]
Misses*

**Comment by clownfish44** [comment]
Use panic sell to have it track them.
