### ISSUE TITLE
Visuals, Visuals, Visuals

### ISSUE THREAD

**Issue by drbrauwn** [taniman/profit-trailer-enhancements#189]
**Visuals Visuals Visuals**

The GUI is getting crowded, so I suggest a new window that does provides Visuals of your current and past (7 days) holdings. Just clicking on them anywhere in your pairs, DCA or sales Log in the GUI to open a new window

**To be displayed in the new window**

Live tracking (graph) of the pair that you are holding, with marks of crucial points.

Markers for;
-	Entry point buy-in (with buy strategy and buy value specified)
-	Marker for DCA buy and with level specified
-	Marker for the sell target 
-	Markers for executed sales  in past 7 (or X amount) days

If holdings that are sold can be visually  followed for another 7 (or X amount) days after it sells, it can be examined if another higher sell trigger, would have been more profitable in current market conditions.

_This is not a backtesting suggestion _

**Comment by FO320** [comment]
Great idea!

**Comment by clownfish44** [comment]
More graphs and visuals are requested here https://github.com/taniman/profit-trailer-enhancements/issues/5
