### ISSUE TITLE
Combine PTFeeder/PTMagic Per Market and Per Coin Adjusting Functionality 

### ISSUE THREAD

**Issue by jodee8** [taniman/profit-trailer-enhancements#19]
Do a deal with PTFeeder or PTMagic to incorporate everything directly into Profit Trailer and while your at it re-code it in Java so that .NET is not needed.

**Comment by juato4** [comment]
hope this win, and also  #76

**Comment by tactikill** [comment]
THIS WOULD BE AN AMAZING ADDITION. IT WOULD BRING MUCH MORE CUSTOMIZATION TO TRADING STRATEGIES. THIS WOULD ADDITION WOULD TRULY MAKE IT FEEL LIKE 2.0

**Comment by octobrium** [comment]
so basically, _make PT Trailer free_ is what you guys are saying

**Comment by juato4** [comment]
@octobrium with your criterion, the developers will stop to enhance, and will do add-ons that we pay and should be come with PT from start.

**Comment by jodee8** [comment]
@octobrium No one said make PT free... Obviously the devs require remuneration for their efforts. What we are saying is for them to work out a deal with the devs of the various add-ons either paid ones like PT Feeder or free ones like PT Magic and incorporate that functionality directly into PT. For the paid add-ons this would obviously require a financial deal perhaps in the form of a sales commission or perhaps even paid employment directly into the exisiting PT Team. For the free add-ons this might not be necessary and the devs of such add-ons might allow their work to be included purely for the recognition? What we are really hoping for here is a more streamlined approach to incorporating the functionality. Perhaps PT could design a plugins interface that add-on devs could produce either paid or free plugins that could be added to an inbuilt PT marketplace? This would provide added security for users as each plugin would be vetted by PT staff before going live in the marketplace and would add the simplicity for users to simply click a button in the GUI to add the plugins functionality. The way things currently are, to obtain the above mentioned functionality (which makes PT far more profitable) requires a rather lengthy and complicated setup process making the bot even more restricted to a certain level of technologically skilled users. To open this functionality up to the masses and thereby increase the market base of PT for both PT's developers and the devs of the various add-ons, really will require some form of simplification and a streamlined approach to incorporating the above mentioned functionality. Hence this enhancement request.

**Comment by octobrium** [comment]
there is no way they're going to integrate PT Feeder for free for current users. if anything, it will come in the form as a paid upgrade.

i'm already using PT Trailer (which i paid for). it's fantastic, and not hard to use at all. we only get 3 profit trailer enhancements, and to suggest devs should focus their attention on something that will not improve profits does not sound like a top 3 concern.

**Comment by jodee8** [comment]
@octobrium You perhaps don't understand the benefits of what we are suggesting here. Thats fine. But there are many here who do see the value in this suggestion and perhaps do understand that its implementation will be extremely profitable for both the users and the devs. Obviously we're not gonna get your vote. That's fine. Enjoy voting for the other suggestions :)

**Comment by octobrium** [comment]
that is correct - i really don't understand the benefits, which is why i posted in the first place. rather than going with the old "*you don't understand, but it's beneficial, trust me :)*" perhaps actually addressing my points and enlightening me in front of everyone here would help get you more votes. otherwise, it won't look so good to the public if you can't point out a single real benefit for integrating an already existing plugin

**Comment by jodee8** [comment]
@octobrium read my post (2 posts above this one), read the post title, also research the add-on PT Magic to get an understanding of the benefits. I don't have the time or the patience to educate you. Have a nice day :)

**Comment by juato4** [comment]
@octobrium Are you from PT team ?

**Comment by PdubsRandom** [comment]
+1

**Comment by BitRacer** [comment]
I don't think you need integration, just add similar functionality.  Seems the next logical step is multiple trading profiles(superbear, bear, normal, bull, superbull... etc), then the ability to automate switching profiles.  Sorry if that squeezed out these third party add-ons, but it does make PT even more valuable.

**Comment by juato4** [comment]
Hope this win and https://github.com/taniman/profit-trailer-enhancements/issues/264

**Comment by CryptosWORLD** [comment]
who said make ptfeeder free ? i think you understand it ll wrong, economics always can resolved some how having a win win. with these addons included in PT , 
all PT users will use them (bigger user trading database now not all PT users using the addons) and 
even more new users will come and buy PT paying per month (win win)
always is a way make the code better and faster with less bugs , put it all in same place as java
and make PT even better is a must !

**Comment by niroshana35** [comment]
PT is the main product, if a third party makes and addon it means that Main product is missing a useful feature, and if the PT community is continually requesting to implement the missing feature, then why not implement it to PT?, because not to forget that PT is the Main product not the addon.

And I agree with @CryptosWORLD "even more new users will come and buy PT paying per month" if PT is packed with more and more new features.

**Comment by taniman** [comment]
Can USE autoswitch config logic and other formula logic that makes things a bit more dynamic. That's good enough for the bot
