### ISSUE TITLE
Limit Sell as one of Profit Trailer selling options

### ISSUE THREAD

**Issue by Botislav** [taniman/profit-trailer-enhancements#190]
Can you add an option for Profit Trailer using limit sell when it hits target (gain target with trailing) instead searching for appropriate BID. User can use X percent difference to last noted price as setting. For safety not to stuck in a limit sell forever add a timer for how long limit sell must stay and PT wait at that time. If limit sell is not fully fulfilled in that time it goes back to testing where actual price is and act like it was before target was hit.
User can decide to use or not that option with settings:
ALL_limit_sell = true
ALL_limit_sell_waiting_time = 600
ALL_limit_sell_difference = -0.1

For clarity reason i will explain on a sample:
ALL_sell_strategy = GAIN
ALL_sell_value = 1
ALL_trailing_profit = 0.25
ALL_limit_sell = true
ALL_limit_sell_waiting_time = 600
ALL_limit_sell_difference = -0.1

Coin rises to 1% - Bot: “I'm watching you, but not selling yet due to my trailing profit” 
Coin rises to 1.5% - Bot: “Still watching, where's that downtrend?”
Coin drops to 1.35%, - Bot: “It's Dropping! Has it dropped .25% yet? No? I'm still watching! 
Coin rises to 6% - Bot: “I'm watching you!” 
Coin drops to 5.74% - Bot: “Gotcha! Set limit sell at price 5.64% and wait for 600 seconds
Limit sell is partially fulfilled - Bot: lets check price again
Coin price is at 2% - Bot: “I'm watching you, but not selling yet due to my trailing profit”
Coin drops to 1.75% Bot: “Gotcha! Set limit sell at price 1.65% and wait for 600 seconds
... Bot can continue until there is big enough balance for selling, amount not high enough for selling goes to dust.

**Comment by clownfish44** [comment]
Why would u want this?

Coin drops to 1.75% Bot: “Gotcha! Set limit sell at price 1.65% and wait for 600 seconds

Pt just send an order at 1.75% right now. Why would you sell for less...

**Comment by Botislav** [comment]
Because it is not selling at all and price drops below 0.

I put limit sell difference for safety so user can decide how much lower from actual price, which fits with target parameters, he/she will try to sell using limit sell.

Bot misses chance to sell because it can't find a bid to fulfil sell. By putting limit sell it can catch bids that will come in following moments, seconds, minutes. I had seen many times when target was reached and bot did not succeed to sell and price drops below 0. Than I track it and manually use limit sell and succeeded. Sometimes in few second, sometimes in minutes. I can't be behind the computer for all time, so this functionality would be really useful.

If my suggestion is not logical, please advise me how to configure a bot not to miss selling opportunity for several times. I want to set it so small trades are done as soon as possible and not waiting and seeing price going from + to - several times despite there's enough volume when coin hits the target for the first time to fulfil my sell.
