### ISSUE TITLE
Can you add an indicator of latest PING response from my VPS on the UI?

### ISSUE THREAD

**Issue by jalvarezca** [taniman/profit-trailer-enhancements#191]
I would like to know if the connection between my VPS and the Exchange service is on the expected values, according to what I'm paying for, and having a constant inidicator on the web page can help monitoring that,

Something like the response time for this https://api.binance.com/api/v1/ping
Or the response time for any API call PT periodically perform.

**Comment by clownfish44** [comment]
it is not out responsibility to tell you how your vps is doing what you paid for.

**Comment by jalvarezca** [comment]
Iknow is not your your responsibility, but i think just saying what was the last response time won't cost you too much. You are rude pal btw. That was my last contribution.
