### ISSUE TITLE
SOM trigger based on altcoin/btc trend

### ISSUE THREAD

**Issue by vecvolta** [taniman/profit-trailer-enhancements#194]
Instead of btc/usd trend

**Comment by clownfish44** [comment]
Already in ptmagic / pt feeder #19

**Comment by vecvolta** [comment]
We wouldnt need Feeder/Magic if the trigger in PT used the market in which we trade (altcoin/btc), not btc/usd.
________________________________

**Comment by vecvolta** [comment]
Why do you close it? I bought PT and vote a PT suggestion. Not Feeder
