### ISSUE TITLE
Test mode filter in Sales log

### ISSUE THREAD

**Issue by Simon2PT** [taniman/profit-trailer-enhancements#196]
After using test mode, sales are mixed up with real sales.
Would be nice to have a checkbox to filter the test mode out.
![image](https://user-images.githubusercontent.com/37113279/37094738-88a30f06-221c-11e8-894e-a5f2ac5530e0.png)

**Comment by clownfish44** [comment]
Just reset your PT data after using test mode. This will prevent all confiscation.
