### ISSUE TITLE
Daily Pair Buys Chart

### ISSUE THREAD

**Issue by chostetler15** [taniman/profit-trailer-enhancements#197]
I don't think this would be considered "backtesting," but I just want to see on a chart when a pair was purchased, (if) doubled down, and sold. 

To limit the amount of data that needs to be tracked maybe it would be limited to a 24 hour window. 

This function would help visualize how your settings are being used, since it is incredibly hard to manually put these markers on tradingview or other charting platforms. And to my knowledge there is no software API that features this. If anyone knows of one, please share in the comments.

**Comment by clownfish44** [comment]
This has been requested in #5
