### ISSUE TITLE
Whitelist Top Change Coins

### ISSUE THREAD

**Issue by tooraj-enayati** [taniman/profit-trailer-enhancements#198]
Allow "**ALL_enabled_pairs**" to take a positive number as a parameter. This number is the minimum percentage increase/change in value on the exchange. PT will then only trade the coins that have had more than the set % increase/change in the last 24 hours.

For example:

**ALL_enabled_pairs = 10** will tell PT to select the coins on the exchange that have had at least 10% increase/change in the last 24 hours.

![capture](https://user-images.githubusercontent.com/24386973/37149721-2534a4fe-2323-11e8-849a-cfd9a17fbdf2.JPG)

**Comment by clownfish44** [comment]
Pt feeder /magic can do this please request #19
