### ISSUE TITLE
Combined pairs and DCA view

### ISSUE THREAD

**Issue by david-ju** [taniman/profit-trailer-enhancements#199]
I would like to see the pais and dca view in one overview. I have a separate smaal monitor I use for monitoring PT, and I'm going mad switching between the two pages. I know I can open two browser windows, but having it in one view would be more efficient (no extra browser borders and such).

**Comment by clownfish44** [comment]
Just have everything go to the DCA log by default this will let you view everything but does not change much.

**Comment by david-ju** [comment]
How do I do that? And would this affect the way PT is trading it?
