### ISSUE TITLE
Auto Update or Update Notification For Profit Trailer Software

### ISSUE THREAD

**Issue by Uruwashii** [taniman/profit-trailer-enhancements#2]
A feature to allow the bot to notify and update when a new version is available - based on options a user selects.

**Comment by LiamAird** [comment]
Not a good idea, if the update has issues, like we say, when binance users got banned for pinging the server to much, after an update - or a bug with DCA not working correctly.

**Comment by LeaderOfChampions** [comment]
Nothing wrong with a simple pop up that notifies you when a new version is available.

**Comment by kendog819** [comment]
`Not a good idea, if the update has issues, like we say, when binance users got banned for pinging the server to much, after an update - or a bug with DCA not working correctly.`

The users shouldn't be beta testers, the new releases should be tested fully by devs before being released to the public.

**Comment by LiamAird** [comment]
Which does not always happen, as we all are aware of, for any software. 

A simple notice of a new version would be good. But auto updating is not, imo.

**Comment by iAmVaeVictus** [comment]
I left this comment in the Gui Config entry (#9) as well. It fits in either: 

What would be useful here is the ability to more easily transition the config files to new config files if there are additions or deletions in those files. Something like a line by line comparison of the settings with a copy , add, delete feature for each setting. This would be in the browser ideally. 

EXAMPLE: 

OLD FILE...................................| NEW FILE .................................| ACTIONS (clickable)...............|
ALL_trading_enabled = true......| ALL_trading_enabled = false ...| Copy from Old Settings
ALL_trading_pairs = BTC-ETH..| ALALL_trading_pairs = ALL......| Copy from Old Settings
..................................................| BTC-XXX_DCA_enabled = true | Add to Settings
some_old_setting = true ...........|..................................................| Remove from Settings


This would eliminate a lot of support issues with people making typos in their settings, leaving out settings that are needed. It would include form validation for all the settings to catch errors like ALL_trading_enabled = TRUE.

**Comment by MrKluttz** [comment]
I like the option to know when an update is available. On Linux a simple command to update is easy.   It can even be done in windows batch file as well

**Comment by Slumberland** [comment]
Definitely a seperate alert on the console please.
Yes also to auto update, but make it OPTIONAL.

**Comment by tactikill** [comment]
THIS IS NICE, BUT WE ONLY HAVE 3 FEATURES THAT ARE BEING ADDED. Let's focus our energy elsewhere. Please.

**Comment by NeXtAntiX** [comment]
I completely agree with tackikill. Updating the App is a a piece of cake, compared to the other issues pending. Spot good trades, execute..

**Comment by CousinEddie** [comment]
+1

**Comment by clownfish44** [comment]
https://github.com/taniman/profit-trailer/issues/853
