### ISSUE TITLE
Console output directly in the webgui for both pt, ptf, and blacklist/whitelist coins

### ISSUE THREAD

**Issue by elementalwindx** [taniman/profit-trailer-enhancements#20]
It would be great to have a place in the webgui to show real time input from the console of ptf and pt and show the list of currently blacklist and whitelisted coins.

This can be good so that I don't have to RDP into my server to see if it's hung. I can see directly from the webgui a timestamped action that's happened directly from the console.

**Comment by clownfish44** [comment]
This already exists, all you have to do is port forward / allow through firewall the port the bot is on to see the webgui
