### ISSUE TITLE
Time to sell

### ISSUE THREAD

**Issue by jbraydc** [taniman/profit-trailer-enhancements#201]
In the sales log I would like one more column called TTS (Time to sell) that gives you the time it took from buying the coin to selling it. So you could see what coins have the fastest trades and also how long coins have been in DCA before selling.

**Comment by tactikill** [comment]
dude, it's not hard to check your order history on your exchange. I agree this would be a small QoL enhancement, but there are much more important features to be implemented at this time.

**Comment by clownfish44** [comment]
#5 Would be part of this.
