### ISSUE TITLE
Buy/Sell signal based off CCI indicator

### ISSUE THREAD

**Issue by ColdMedina** [taniman/profit-trailer-enhancements#202]
The CCI Indicator is a little-used indicator that has proven very effective for me to use whilst trading. Often, you can simply buy when it goes low, and sell as it goes high, and make at least a few percent, if not tens of percent. Even better if you catch it right after it turns -- perfect for a trading bot. 

The CCI Indicator is a number calculated based off historical and present price. It seems to be similar to RSI but seems to be more accurate at predicting price changes when it turns. When combined with a price % trailing BUY or SELL order, it could be deadly!

Example: on BTCUSD, at 3-8 21:50 (PST) CCI (20) turns upwards from -297 and begins to climb to 139. PT could easily trail as it passes -100 (or for more gains, -150 or -200), buy when it turns, and trail as it passes +100, sell when it turns again. Especially when combined with price action (because it is not 100% every time, especially on lower time frames). 

This strategy above would result in BTCUSD buy @ ~$8390 and sell @~$8763, a 4.4% increase in 1 hour. 

http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:commodity_channel_index_cci

**Comment by clownfish44** [comment]
More included have been included in the 2.0 milestone

**Comment by kendog819** [comment]
> More included have been included in the 2.0 milestone

Not seeing this, has it been added as you specified?

**Comment by mag106** [comment]
2.4 already and there is no indicator

**Comment by rumano** [comment]
![cci](https://user-images.githubusercontent.com/17684910/110202316-87dda000-7e89-11eb-8c9f-ef96b99b3ee2.jpg)
