### ISSUE TITLE
Feature Request: Displaced EMACROSS

### ISSUE THREAD

**Issue by DomoKB** [taniman/profit-trailer-enhancements#204]
Provide a setting in indicators to allow offsetting of EMA backwards or forwards in time by x number of candles. A displaced EMA can provide earlier signals by effectively removing/reducing the 'lag'.

https://www.investopedia.com/terms/d/displacedmovingaverage.asp

21/8 EMA with no displacement
![withoutdisplacement](https://user-images.githubusercontent.com/13867804/37242097-b22d4db2-24b7-11e8-9a79-f67dcaf7bf04.png)

21/8 EMA with -8 candle displacement
![withdisplacement](https://user-images.githubusercontent.com/13867804/37242098-bb40e6de-24b7-11e8-88e7-4d82b77feb95.png)

**Comment by clownfish44** [comment]
You can't predict when the candles will cross however you can use spread.
