### ISSUE TITLE
Ability to set hotconfig when config is turned off

### ISSUE THREAD

**Issue by calebcall** [taniman/profit-trailer-enhancements#205]
I'm currently running my pt behind nginx and using nginx for the authentication so all my tools are behind a single auth.  However, I can't set anything through hotconfig when doing this.  I've tried to recreate the post on the local machine (passing all cookies, headers, etc that the UI sent) but it doesn't seem to work (even when I have auth turned on and I pass the auth cookie).  Is it currently possible to send a post to the endpoint and set hotconfig outside of the UI and if not, could this be made available with some mechanism around security (must pass certain cookie, header, etc) but could be done only from the local machine?

**Comment by clownfish44** [comment]
No this will not happen just set a password and make it secure.

**Comment by calebcall** [comment]
It's funny that you mention "make it secure" because my current install is way more secure than PT is  running it with a password and running with a password doesn't accomplish what I'm looking for.  It's ok though, I'll work around it.
