### ISSUE TITLE
Add StochRSI and MACD so PT will buy when the upswing starts

### ISSUE THREAD

**Issue by paulvhhill** [taniman/profit-trailer-enhancements#207]
I would like the buys to trade at the bottom of the dip Stoch 20 when it is over-bought or when the MACD crosses.

**Comment by clownfish44** [comment]
Already in the 2.0 release

**Comment by paulvhhill** [comment]
When you say ver 2.0 what does that mean?
I am on the version .23 and I don't see any way to implement MACD. Can someone help? I am willing to pay
