### ISSUE TITLE
Save equivalent bought price for different markets

### ISSUE THREAD

**Issue by hhaick** [taniman/profit-trailer-enhancements#208]
It would be very interesting if the bot could save the equivalent bought price of a coin for different markets.
Today, if we decide to switch markets and keep using the same coins we already have, we always have problems of losing the bought price. Then we have to calculate everything and set all manually. And if we DCA for the first time, the bot still forgets the bought price previously set and cannot calculate the new average price.
So, it would be very useful being able to switch markets without having to calculate and set all prices manually. In addition, if we get decided to switch markets, the base currency from the previous market could be converted automatically in the new currency.
**Example:** 
-I was trading on BTC market with 1BTC and I had 4 big bags of PPT, NANO, XLM and DASH.
-Then, I decided to trade on ETH market.
-The prices of my bags were automatically converted to a price in ETH (always considering Coin/USD as a reference).
-My remaining BTC balance was exchanged for ETH.
-My bags were normally DCAed  in ETH.
-My bags finally achieved the profit target and were sold in ETH with no loss due to changed market and human miscalculations.

**Comment by clownfish44** [comment]
https://github.com/taniman/profit-trailer-enhancements/issues/28 already requested
