### ISSUE TITLE
24H %, 7D%, 1M% Changes

### ISSUE THREAD

**Issue by sirloinwesk** [taniman/profit-trailer-enhancements#209]
Would love to see the ability to toggle between 24H%, 7D%, 1M% etc changes.
This would be especially helpful with strategies designed for longer changes in trends.

Such information would be great if you wanted to spend more on a coin that has a huge change in value over the last week/month as opposed to 24 hours, because it's more likely to return a decent profit, so you can raise your values accordingly.

24 hours especially in crypto can be risky with the volatility we see every few minutes, so length changes would give me confidence to up my values.

Plus having these change options opens a lot of future opportunities to  allow the bot to make decisions based on % change triggers.

Thanks!

**Comment by clownfish44** [comment]
Already requested here https://github.com/taniman/profit-trailer-enhancements/issues/5
