### ISSUE TITLE
Usage of multiple API Keys to enhance PTs reaction time

### ISSUE THREAD

**Issue by Q-Rush** [taniman/profit-trailer-enhancements#21]
Hi,

i have seen another CryptoTradingBot which i will not mention here. It uses multiple API Keys on Binance to increase the performance (reaction time in a buy/sell situation) and to decrease the possibility of an IP Ban.

You don't need multiple Binance accounts for this to work. You can create all API Keys on the same Account.

thanks in advance

**Comment by ACETyr** [comment]
Are you sure that exchanges do limit requests per API key instead of IP? Is there any statement that additional keys do really solve any problems?

**Comment by Q-Rush** [comment]
> Are you sure that exchanges do limit requests per API key instead of IP? Is there any official statement that additional keys do really solve any problems?

There is no official Statement from Binance. They would never mention something like this. But you can take a look at other CryptoBots. One of them uses this function to solve IP Bans and to increase the performance.

**Comment by Tosko4** [comment]
Anything to ensure more security towards the user is welcome!!

**Comment by elementalwindx** [comment]
This sounds awesome if this is correct.

**Comment by clownfish44** [comment]
We already use two api keys aka multiple!
