### ISSUE TITLE
Real Time Profits Column In Base Currency

### ISSUE THREAD

**Issue by sirloinwesk** [taniman/profit-trailer-enhancements#210]
![1](https://user-images.githubusercontent.com/37171971/37250454-17d42e62-2551-11e8-9702-a6678cb1f458.jpg)

Having a real time profits column on the pbl or pairs log in your base currency would be a great feature. Showing the profits/losses in BTC for example at the current value and at the buy value you've set - which adjusts based on price.

That way you can determine if it's worth the investment at all at said price, and you can make the adjustments accordingly.

**Comment by Tosko4** [comment]
I like the idea. There is already a tool written for that, but I’d rather see it built it into the roots of the tool as well.

**Comment by sirloinwesk** [comment]
Yeah I usually have another browser open where I punch in the figures (followed by having to convert it to my fiat currency) but this would be one step closer to valhalla

**Comment by clownfish44** [comment]
Already in 2.0
