### ISSUE TITLE
BB Trigger Percentage Column on PBL

### ISSUE THREAD

**Issue by sirloinwesk** [taniman/profit-trailer-enhancements#211]
![2](https://user-images.githubusercontent.com/37171971/37250511-0a6c6062-2553-11e8-96bb-a30b474c28df.jpg)

Having a BB trigger percentage column on the PBL which would allow us to see how close it is to triggering.

For instance, if you've set LOWBB to -10, and the current BB is about 3% away from executing, then the column would indicate a 97% value.

**Comment by sirloinwesk** [comment]
If it falls further below -10, then it can hit 110% etc.

**Comment by clownfish44** [comment]
Fixed
