### ISSUE TITLE
Don't Touch That Principal!

### ISSUE THREAD

**Issue by sirloinwesk** [taniman/profit-trailer-enhancements#212]
Say you have a thousand dollars.
You've made 200 dollars profit.
You decide ok, don't touch my thousand dollars. Use that 200 dollars instead.
Now the bot only uses that 200 dollars to make more money and leaves the principal alone.

ALL_profit_balance_only = true
or something like that.

**Comment by Tosko4** [comment]
Nah, what if you only made a few dollars. Than it will start trading with a few dollars only. 

Unless you can set that when the profit has reached a certain amount of dollars than only trade with that money. 

But why would you do that? You invested a thousand with the idea to start trading etc. 

You can also set what minimum amount it must not touch from your balance already. So if you see you’ve made enough to trade with, turn on that setting and it will only trade with money above your minimum balance (the thousand dollar)

**Comment by sirloinwesk** [comment]
You'd obviously have it set to false if you've only made a few dollars..

**Comment by sirloinwesk** [comment]
It's moreso for long term conservative investing with the bot follows one of the most important principles in investing- only spend the interest

**Comment by clownfish44** [comment]
Min buy buy please read about it in the wiki!
