### ISSUE TITLE
Using the USDT Market

### ISSUE THREAD

**Issue by Tosko4** [taniman/profit-trailer-enhancements#213]
Please make a feature where PT sells either yout ETH or BTC to USDT to save us from a bear market and to buy in the dip of the bear market and in return make a bigger profit?

**Comment by Tosko4** [comment]
- Author idea: Thy A on Discord

**Comment by knowngate** [comment]
Usdt in bot may b dangerous when market is at bull run. Just a thought.

**Comment by Tosko4** [comment]
Risk that the trader takes? This should be an option you can enable/disable. If one finds it dangerous, then let it remain off. 

Default setting should be set to disabled. So if one turns it on, its something one did with the concequences in mind

**Comment by clownfish44** [comment]
https://github.com/taniman/profit-trailer-enhancements/issues/28 seems like this would go under here
