### ISSUE TITLE
Feature Request - Automatically adjust buy/sell strategy and indicators based on market change.

### ISSUE THREAD

**Issue by Rooster67** [taniman/profit-trailer-enhancements#215]
It would be nice to have a feature that would change your buy/sell strategy and indicators automatically based on the market percentage rise or fall.  When the Market/Pairs rise X% use (A) - Strategy and indicators. When the Market/Pairs fall X% use (B) - Strategy and indicators. Thank you

**Comment by jbraydc** [comment]
Can do this with PTM or feeder already.

**Comment by clownfish44** [comment]
#19
