### ISSUE TITLE
Inverse DCA - Laddered/Elastic Trailing Sell Triggers

### ISSUE THREAD

**Issue by omarmoss** [taniman/profit-trailer-enhancements#216]
Would be great to be able to increase the amount by which we allow a pair's price to drop by, based on how high it has already gone, thus increasing the elasticity, the higher it rises.

Example:
ALL_trailing_sell = true

ALL_trailing_sell_value_1 = 2
ALL_trailing_profit_1 = 1

ALL_trailing_sell_value_2 = 4
ALL_trailing_profit_2 = 2.5

ALL_trailing_sell_value_3 = 6
ALL_trailing_profit_3 = 3

ALL_trailing_sell_value_4 = 10
ALL_trailing_profit_4 = 4

(Applicable to PAIRS and DCA selling per pair)

**Comment by jbraydc** [comment]
So basically what you want is a function that will allow trail to increase in proportion to the % profit the coin has made?

**Comment by omarmoss** [comment]
@jbraydc Roughly speaking, yes, though it should not necessarily be always proportional across the board.
One should be able to set one's own laddering structure.

If a pair increases in value by 2%, I might want the retracement allowance to be as much as 1% (half or 50% of the current increase), rather than the default 0.5%.

On the other hand, if a pair has increased by 5%, I might only want the retracement to be as much as 3% (60% of total increase).

In the same way as one might set variable/laddered (usually increasing -1, -3, -5, -7 etc) DCA levels; one might want to set variable (decreasing?) Trailing Profit values.

What often happens is that when a coin breaks out is that a 0.5% or 1% trailing profit gets stopped out much earlier than would be ideal when the breakout ultimately hits 10-20% increases.

The LTP (Laddered Trailing Profit) setting described would increase the potential profitability during breakouts.

**Comment by omarmoss** [comment]
In fact, rather than setting a retracement percentage allowance at each step (like DCA), a percentage of the percentage change would probably be even better.

Decreasing percentage - 
50% trail at 2%+ (=1% trail)
40% trail at 4%+
30% trail at 6%+ etc

**Comment by clownfish44** [comment]
https://github.com/taniman/profit-trailer/issues/292

**Comment by omarmoss** [comment]
What I would like to see is:

#if the pair has a gain of x% already:
DEFAULT_(DCA_)trail_percentage_1 = 1
DEFAULT_(DCA_)trail_percentage_2 = 3
DEFAULT_(DCA_)trail_percentage_3 = 5
DEFAULT_(DCA_)trail_percentage_4 = 10

with:

#set this new trail based on current pair gain %, as set above:
DEFAULT_(DCA_)trailing_profit_1 = 0.3
DEFAULT_(DCA_)trailing_profit_2 = 0.6
DEFAULT_(DCA_)trailing_profit_3 = 1
DEFAULT_(DCA_)trailing_profit_4 = 2.5

The higher the gains for a pair at any given time, the greater the trail allowance.
Make sense?

This would allow for scalping as well as swing opportunities as they happen, instead of selling-out of a trade when the pair retraces for the next leg up (at each wave).
