### ISSUE TITLE
[Feature Request] Getting ANDERSON's multiple buy trigger for other buy strat for DCA (like EMASPREAD)

### ISSUE THREAD

**Issue by Cryptoqueb** [taniman/profit-trailer-enhancements#217]
I'm using EMASPREAD has a DCA buy strat so i'm not blindly buying when my pair drops but rather buying at a low. My problem though is that the fix trigger buy is limiting my range to which I can get out of a bad bag.

I'd like to have the same option to set multiple buy triggers for other DCA buy strat like the ANDERSON's strat has. So for EMASPREAD it would consider buying only it the trigger is met for the specific DCA levels it's at. That would be so great.

thx

**Comment by tooraj-enayati** [comment]
You already have this feature! It is called Martingale. Read the wiki.

https://wiki.profittrailer.com/doku.php?id=dca.properties#dollar_cost_averaging_martingale

**Comment by Cryptoqueb** [comment]
I'm not sure you understand what i'm asking here. 

currently with EMASPREAD has a DCA strat im stuck with : 

buy_strategy = EMASPREAD
buy_trigger = -2.5

And I want this

buy_strategy = EMASPREAD
buy_style = DOUBLEDOWN
buy_trigger_1 = -2.5
buy_trigger_2 = -3
buy_trigger_3 = -4
buy_trigger_4 = -7

**Comment by tooraj-enayati** [comment]
OK, I get you.  You are asking for adjustable buy_triggers for other DCA strategies.

**Comment by Cryptoqueb** [comment]
yeap

**Comment by clownfish44** [comment]
2.0 already exists in
