### ISSUE TITLE
[Feature Request] Intelligent Pump & Dump detection

### ISSUE THREAD

**Issue by briersben** [taniman/profit-trailer-enhancements#219]
Improve the logic to detect pump & dumps, as this is one of the reasons we are ending up with (deep) bags.

Since I am rather new to PT, I am not sure how this can be achieved. What I am thinking of is looking at historical highs. If the current prive is near or higher that the highest historical price, we need to be cautious.

Also, if the price increase is too fast, this might indicate a pump.

Please let the more experienced people (experts) chime in and provide their feedback on how to make more intelligent buys and avoid higher risk buys.

**Comment by clownfish44** [comment]
Already planned in the milestones
