### ISSUE TITLE
Feature Request - DCA to Pending w/Sell Order

### ISSUE THREAD

**Issue by usslindstrom** [taniman/profit-trailer-enhancements#222]
Issue referenced within original ticket:  https://github.com/taniman/profit-trailer/issues/1399

In order to handle some of the deep bags that can show up, I'd like to request a new feature be implemented. Currently, the only way to handle bags once they have finished the DCA tree is to do one of the following:

Panic Sell
Meet a Stop-Loss criteria
Or ride the wave back until the thing gets back to positive
What I'd like to suggest implementing... Is once the DCA tree has gone all the way to the bottom, place a sell order on the coin, set at a defined percentage (like the DCA percentage) and move it to pending.

This way it would stop tracking it in the active pairs, and the bot could go and grab another set. Just a thought.

Right now, I have stop losses setup in my bot below the DCA, but it would absolutely hurt should one of those actually be invoked, and gains for the day would be lost by a single sell.

//===================================

The pending feature is not documented anywhere within the Wiki from what I could find, and the workflow does not operate as suggested.

A feature such as this would allow the bot to keep working, while not getting stuck with multiple bags just waiting to come back to the positive - and ensure a stop loss or panic sell is no longer the only options available to users of this platform.

Requesting a percentage variable be identified on when you want the negative coin to be moved over to pending and no longer actively tracked.  If it is supposed to do this, as suggested by "YoJeff", it is not working as intended.

Thank you for all the hard work on this software.

**Comment by clownfish44** [comment]
You just described the pending feature as it exists.

**Comment by usslindstrom** [comment]
Is this a joke?

The pending feature does NOT work like this.  I now have more than 5 coins that have been Dca'd to the max level.

They are still being tracked in the dca log.

They have NOT had a sell order put on them.

They are still counting against my pair limit.

Where is the documentation in the woke about "Pending"?

Where is the variable that says when to move something to "Pending" after PT puts a sell order in for ir?

Did you even read this ticket?  Your product is nice, but customer service is a joke.

**Comment by usslindstrom** [comment]
Where in the *wiki?
