### ISSUE TITLE
Feature Request: EMASPREAD as a Sell Strategy, Min/Max Values

### ISSUE THREAD

**Issue by Wolfwood1** [taniman/profit-trailer-enhancements#224]
Hi guys,

Wondering if, in addition to incorporating EMASPREAD as a sell strategy, you would also be able to add adjustable min/max trigger values?

This would act similarly to EMACROSS in my eyes but much more reactively, as we could set the following config as an example:

EMASPREAD buy
Min value: 0.01
Max value: 0.15

EMASPREAD sell
Min value: -0.01
Max value: -0.12

The buy would occur just as the EMA lines cross in an uptrend, and the sell would occur just as the downtrend begins to occur, prior to a huge retrace. This also avoids selling off into normal corrections during smaller ABCDE uptrends as a result of GAIN trailing values not ever being truly useful. The Max value is to prevent buying in to a pair too late as the current EMASPREAD only cares if something is the Min value or greater.

This scenario allows one to buy into strength confirmation, but not at the cost of waiting for the end of a large green candle as is with most EMACROSS situations due to the delay in waiting for the subsequent candle to signal that the previous candle had a confirmed crossover. 

EMACROSS would remain the solution for those individuals who are hesitant at buying into false positives, however the true gains can easily be missed with too much risk aversion.

Thanks all!

**Comment by clownfish44** [comment]
In 2.0
