### ISSUE TITLE
[REQUEST] A FAST WAY TO HOT CHANGE PT SETTINGs

### ISSUE THREAD

**Issue by keithofaptos** [taniman/profit-trailer-enhancements#225]
on pt dashboard in "config",under (or above)"hotconfig" line,
could you make a notepad? so we can have a place on the dashboard to be
able to copy/paste (hot switch) different strategies settings pre-readied. for a
lightning fast strategy change up, especially for shorting situations.
could be 10 cells ,20 lines deep or more.all on the one page,
listed above each other, in line ,as to see them well.
with a switch button, that auto switches strategy line code into pairs/dca/indicators
settings, automatically implementing settings (saving).
then we could just check configs to verify.

**Comment by clownfish44** [comment]
https://github.com/taniman/profit-trailer/issues/1044
