### ISSUE TITLE
Enable SOM after a predefined number of consecutively triggered stops

### ISSUE THREAD

**Issue by JaySatthee** [taniman/profit-trailer-enhancements#226]
It would be helpful, if we could automatically activate SOM after a number of Stop-Losses, because it usually means, that the whole market is going down.

Another idea in this context is to deactivate Stop-Loss automatically if there have been a couple of Stop-Losses in a row. It happens quite often, that the market dips in a matter of hours, but then rapidly recovers. So if Stop-Loss is activated all the time, you would sometimes lose money for no reason.

**Comment by clickstudio** [comment]
I was thinking about something similar but my idea was to enable SOM once all current trades equal a certain % loss. If you combined this with a stop loss, you could effectively limit your losses per day but still allow the current trades to recover should a market bounce occur.

**Comment by clownfish44** [comment]
Already added to a future release here https://github.com/taniman/profit-trailer/issues/480
