### ISSUE TITLE
API Key Storage

### ISSUE THREAD

**Issue by Uruwashii** [taniman/profit-trailer-enhancements#228]
API key has to be entered into the UI within a setup area and the PT writes it to a file as encrypted.  Rather than key stored in plain text file. Same process as user password which is brilliant.

Then any access to to it view, change, delete the API key is recorded in an Audit log.

**Comment by angelsomar** [comment]
The truth for security reasons would be good that the api were not in plain text

**Comment by clownfish44** [comment]
Not possible right now
