### ISSUE TITLE
Security Enhancement - Two Factor Authentication (TFA) as an option

### ISSUE THREAD

**Issue by Uruwashii** [taniman/profit-trailer-enhancements#229]
Allow users the option to add an additional layer of security by using TFA.

Options of TFA could include:

- Using Authenticator/Google Authenticator/TFA Authenticator apps
- Telegram message with code

**Comment by knowngate** [comment]
It's too dangerous in open world for the bot which entacted with sensitive data.

**Comment by clownfish44** [comment]
not possible use the second password/user option for pt
