### ISSUE TITLE
Display live number of Possibles, Pairs & DCAs in Browser Tab Title [QOL]

### ISSUE THREAD

**Issue by DigitalStartupUK** [taniman/profit-trailer-enhancements#23]
A solution like the example image below would save me the effort of switching tabs all the time to get a snapshot of what's going on in PT. Obviously, these numbers would change in real-time, much like the tradingview.com tab title.

**In this example, 2-2-6 represents: 2 Possibles - 2 Pairs - 2 DCAs**

![pt-wish](https://user-images.githubusercontent.com/24552648/36733300-18e20a6e-1bc8-11e8-9907-980555df049e.png)

**Comment by tactikill** [comment]
there are only 3 things being added this round. it's a cool idea, but this does not currently seem as important as many of the other ideas out there. i would personally be mad if this was added in place of other functionality features.
