### ISSUE TITLE
Market peak detection to prevent buys- Bill Williams Awesome Oscillator

### ISSUE THREAD

**Issue by dragonsfire1981** [taniman/profit-trailer-enhancements#234]
We need an oscillator to detect market peaks and prevent buys when a coin has already peaked and lost momentum, which will also help witn PND detection. I like using positive EMASPREAD, EMAGAIN but a disadvantage is that it will still keep rebuying once a coin has peaked, and starts reversing. 

Once a second peak has formed which is lower than the first, that should trigger a no buy order. Alternatively, the data could be derived from the MACD histogram.
[https://tradingstrategyguides.com/bill-williams-awesome-oscillator-strategy/](url)
[https://www.tradingview.com/wiki/Awesome_Oscillator_(AO)](url)

**Comment by marcomarvelous** [comment]
bro same

**Comment by clownfish44** [comment]
These links are broken and there is not enough information as how to implement.
