### ISSUE TITLE
BNB Balance auto top up

### ISSUE THREAD

**Issue by djbadders** [taniman/profit-trailer-enhancements#236]
Get the bot to maintain your BNB balance for trades so you don't have to.
A setting where you can tell the bot to automatically top up a pair when the amount drops below a fixed value with a specific number of coins would be really useful.

In addition I would love to be able to trade BNB, so having the option to allow this whilst retaining the the fees balance would be very cool.

**Comment by duckybsd** [comment]
This feature is very important, please consider it.
Something like minimal reserve option which allows the BOT to reserve amount of BNB to pay the commission fees, but also allow you take advantage of trading BNB.

**Comment by clownfish44** [comment]
https://github.com/taniman/profit-trailer/issues/496 already added to list!
