### ISSUE TITLE
ALL_btc_price_drop_trigger more control, Please.. and, Pending Log Sell, TRIGGER %

### ISSUE THREAD

**Issue by NeXtAntiX** [taniman/profit-trailer-enhancements#238]
Title: ALL_btc_price_drop_trigger more control, Please.. and, Pending Log Sell, TRIGGER %

Not to sure if this is an enhancement or and improvement on the current setup..? 

TRIGGER time for ALL_btc_price_drop_trigger (NOT 24h) but to be set via SMA_period = 300 or set by user. 
in the TRIGGERS settings for change in BTS Price, I would like the time to be governed by the settings in INDICATORS, eg, SMA_period = 300. Not hard set to 24h. If the BOT is trading 5min candles this is not going to help you if the BTC price states "Dumping" in 50min or less.. Catching the dump seems to be key in preventing Bot from picking up bad trades. 

Also would like to see more control over Pending Log Sell, TRIGGER %, as this seems to be governed via the Sell Strategy in the PAIRs.properties eg, ALL_sell_value = 0.98 translates to Sell Trigger% in Pending Log to 0.98

Thanks, :)

**Comment by clownfish44** [comment]
Added in V2!
