### ISSUE TITLE
EMACROSS SELL Strategy

### ISSUE THREAD

**Issue by hulkcrypto** [taniman/profit-trailer-enhancements#239]
Is an EMACROSS SELL strategy going to be implemented?

It would be a HUGE compliment to the EMACROSS buy strategy and should provide better results than using gain, as it would allow us to get the full profit from a bull run.

**Comment by ricardodacosta** [comment]
I agree. I have asked for this in the past but there hasn't been much interest

**Comment by hulkcrypto** [comment]
It's a common trading practice to buy on the cross up and sell on the cross down. When you use gain, you sell too early because of price fluctuations in the middle of the run.

I know it has nothing to do with 'trailing' but it should be an option, and would be especially useful for netting profits on long time scales. 

Really really keen for this feature!

**Comment by clownfish44** [comment]
In v2!
