### ISSUE TITLE
Ability to Customise Home Screen - Widgets

### ISSUE THREAD

**Issue by Uruwashii** [taniman/profit-trailer-enhancements#24]
A selection of 'widgets' you can add to the home screen so you have the information that's important to you all in one place quickly

- Current panels (profit etc.)
- Information on pairs/market from external sources
- News sources
- Action buttons (kick start a manual buy/sell/trade)
- Alerts/warnings
- Tip of the Day (?)

**Comment by clownfish44** [comment]
Information on pairs/market from external sources and News sources anr not and will not be part of PT. 

Action buttons (kick start a manual buy/sell/trade) are requested here https://github.com/taniman/profit-trailer-enhancements/issues/7

Alerts warnings are already part of PT

Tips are all over PT
