### ISSUE TITLE
Buy orders based on bid price instead of ask price

### ISSUE THREAD

**Issue by clickstudio** [taniman/profit-trailer-enhancements#240]
Once a pair's buy conditions are met (still based on trailing value) , actually place a buy limit order at the bid price (or slightly above based on variable setting) instead of the  ask price. 

Currently new trades are immediately down by the pair's spread which seems to give up a lot of potential profit sometimes.

For example, if you're trying to get a 1% gain and your market spread is 1%, the bid price actually has to move 2% to make 1% profit. If the initial purchase was at the bid price (instead of 1% higher at the ask), it only has to move up by 1% for the same result.

I guess there would need to be a function to periodically check the status of the buy order and if it was not 100% filled, adjust the order upward until the order is completely filled.

The benefit would be that the trade is at "cut even" value immediately instead of been down by the pair's spread.

**Comment by renatoshira** [comment]
You can use ALL_max_buy_spread = 0.2 until this is not implemented

**Comment by clickstudio** [comment]
@renatoshira 
Would't that just limit the potential trades ?
The buy price would still be based on the offer as I understand it.

**Comment by renatoshira** [comment]
There would be a LOT of unfilled orders. Just think rationally... There is no possible way to buy and sell the same coin without paying the spread.

If you place your buy order in the top of bids, you will only buy when spread is zero.

**Comment by clickstudio** [comment]
There is the potential for some orders to remain unfilled but I really don't understand your logic that you always need to pay the spread. If the buy order is placed at the top of the bid, all it takes is one person to sell at market and you get filled (at least partially). The spread is completely irrelevant and you have just entered the trade at the bottom of the spread instead of the top.

**Comment by renatoshira** [comment]
you can be right... I dunno exactly how this would perform. We need to test

**Comment by clickstudio** [comment]
Thanks @renatoshira . If I can assist in any way, Let me know!

**Comment by clownfish44** [comment]
Would be included with this https://github.com/taniman/profit-trailer/issues/596 as a "Sell x% above highest ask"
