### ISSUE TITLE
Feature request: Use (system) timezone of UTC offset

### ISSUE THREAD

**Issue by Ypho** [taniman/profit-trailer-enhancements#242]
A little over a week ago we went to daylight's savings time, which gave an extra hour offset compared to UTC. Since I haven't restarted my system (Raspberry Pi) for a while, all trade times are said to be an hour earlier now.

I assume that the times in UTC are sent by the Exchange API (Binance in my case), but would it be an idea to use a (system) timezone setting to calculate the trade-time instead of the UTC offset in the application.properties?

After I rebooted, the times are correct, but it looks like all sales before DST in the sales log have a 2 hour offset as well now. This is not a big issue, but it would be great if the UTC datetime can be converted to a timezone (preferably system's timezone).

**Comment by clownfish44** [comment]
Just change the offset!
