### ISSUE TITLE
Want to see profit both as % of this coin's trade, and also as % of total account value

### ISSUE THREAD

**Issue by libertyteeth** [taniman/profit-trailer-enhancements#245]
Enhancement request: in the pages for Pairs, DCA, and Pending, there's a "Profit" column. This shows the percentage gain or loss for that coin's trade.

I'd also like to see, perhaps underneath it (e.g., like it shows both Bid Price and Target Price in the same column, on the Pending Log page, just to the left of the Profit column), the "percentage gain or loss that this represents for the entire account".

Especially on the DCA and Pending pages, since when it "doubles down" a few times, that coin would be a much greater percentage of the funds in the account.

**Comment by clownfish44** [comment]
Please request this under PtTracker here https://github.com/bTayFla/PtTracker/issues as this is an enhanced feature for stats
