### ISSUE TITLE
View Buy Orders

### ISSUE THREAD

**Issue by HenryHatten** [taniman/profit-trailer-enhancements#248]
Currently it is not possible to view all the Buy orders that PT makes - we can only see the Sell orders.

These would be interesting for the user to see so they can see the DCAs in action, and to verify that the BOT is doing what they expect it to do.

**Comment by clownfish44** [comment]
Please request this under PtTracker here https://github.com/bTayFla/PtTracker/issues as this is an enhanced feature for stats
