### ISSUE TITLE
Feature request: IN THE DCA BUY SETTINGS

### ISSUE THREAD

**Issue by rasta0** [taniman/profit-trailer-enhancements#249]
please add new features for every buying trigger separately, such as the percentage of the cost value

buy_trigger_1 = -1.5
buy_trigger_1_cost_percentage = 200
buy_trigger_1_trailing = .1

buy_trigger_2 = -2.5
buy_trigger_2_cost_percentage = 240
buy_trigger_2_trailing = .4

buy_rigger_3 = -4.5
buy_trigger_3_cost_percentage = 280
buy_trigger_3_trailing = .6
.
.
.
.

**Comment by clownfish44** [comment]
https://github.com/taniman/profit-trailer-enhancements/issues/230

Duplicate
