### ISSUE TITLE
please add instant sell button for pairs

### ISSUE THREAD

**Issue by oktay50000** [taniman/profit-trailer-enhancements#250]
please add instant sell button for pairs
some times its better to sell it by hand on bot instead of goin to exchange
tnx for a great bot

**Comment by DragonBtc93** [comment]
I want that too

**Comment by derekpovah** [comment]
I think I'm a -1 on this because the bot is supposed to remove panic selling from the equation. If you absolutely need to sell, I think you should set the bot to ignore the pair and sell manually on the exchange.

**Comment by clownfish44** [comment]
https://github.com/taniman/profit-trailer/issues/360

Same concept already added!
