### ISSUE TITLE
Enhancement request. Buy and sell on Trading view alerts.

### ISSUE THREAD

**Issue by DragonBtc93** [taniman/profit-trailer-enhancements#251]
Instead of working on all these different strategies make it so we can use trading view alerts to trigger the bot. Then we can use any strategy that is on trading view.

**Comment by keithofaptos** [comment]
Put PT in SOM ,and use 
TradeView to trigger AutoView to buy , then PT strategy to sell.

**Comment by DragonBtc93** [comment]
If I'm going to use Autoview then what do I need PT for.

**Comment by keithofaptos** [comment]
Learn many ways. PT is a tool. Not a ticket.

**Comment by clownfish44** [comment]
Signal support already on the books!
https://github.com/taniman/profit-trailer/issues/320
