### ISSUE TITLE
DCA Timetable

### ISSUE THREAD

**Issue by storxusmc** [taniman/profit-trailer-enhancements#255]
I have had a lot of success with PT, but there are times that i wish i could automate the liquidation of DCA bags that are just barely missing the cutoff to sell, due to poor position in the bag. 

I would like to see the code added so you can have a series of time periods and the profit to go off of, so if you want it to liquidate something for a small profit and move on, then you can..

Example 1:
Sell_Day_1 = 1
Sall_Day_2 = 0.9
Sell_Day_3 = 0.8
Sell_Day_4 = 0.7
Sell_Day_5 = 0.6
Sell_Day_6 = 0.5
Sell_Day_7 = 0.4
Sell_Day_8 = 0.3
Sell_Day_9 = 0.2
Sell_Day_10 = 0.1

Or, 
Set it up so you can setup different profit values based on how many times its DCA'd... I make most of my profits from many quick 1-2hr trades, its when i get stuck with a position and it DCA's multiple times over 2-5 days tieing up my funds that i loose money, granted when it finally sells its a nice profit usually, but 90% of the time when i do the math based on my average day earnings, the amount of trades it blocked from happening due to tieing up so much funds, usually exceeds the end profit by a large margin...

**Comment by clownfish44** [comment]
Would need to be implemented in the same release as https://github.com/taniman/profit-trailer/issues/292 as this deals with per dca selling and this would build on that.
