### ISSUE TITLE
Timer to sell pair if held for too long.

### ISSUE THREAD

**Issue by quasio** [taniman/profit-trailer-enhancements#257]
I notice most of my successful trades happen within the 2-4hr mark, after that, it is quite likely to hit my stop loss, or if not present, cause a long term bag.

Would like to have per pair "TIME_TO_HOLD_PAIR" and just sell if the timer runs out. This will likely cause a loss but at least it should be significantly less than a stop loss (which hurts big time), and let the bot move on with another pair.

(also have a TIME_TO_HOLD_PAIR_REBUY_TIMEOUT) so you can not rebuy for x time as well.

**Comment by clownfish44** [comment]
https://github.com/taniman/profit-trailer/issues/366 already added to future release
