### ISSUE TITLE
Add 'BBW_length =' to Indicators File

### ISSUE THREAD

**Issue by JDMJas0n** [taniman/profit-trailer-enhancements#258]
Minor Enhancement - Add 'BBW_length =' to Indicators File

Explained:
I just noticed while setting up PT 2.0 that BBWidth does not have its own 'length' setting in the 'indicators file'. This can be problematic as when we use 2 Indicators for a buy strategy like LOWBB and BBWIDTH alot of people and myself want to use 2 different lengths for each of these settings. Say LOWBB Length of 20 and BBWIDTH of 14. Can we add a dedicated BBWidth_length line of code into the indicators file. 

Thank you.

Awesome work like always!

**Comment by JDMJas0n** [comment]
Please also check RSI and other strategies make sure they all can have independent lengths. :)

**Comment by Masterofcoinak** [comment]
It was implemented and with labels are even more things possible. Should be closed.
