### ISSUE TITLE
Enhance Stop loss

### ISSUE THREAD

**Issue by Helmi** [taniman/profit-trailer-enhancements#259]
Currently stop loss for DCA pairs only "fires" when either DCA is done (max buy times, max cost) or the balance is not enough to continue with stop loss.

For more possibilities with stop loss it would be helpfull if we could set _trigger and _timeout separetely for each DCA level like it's done similarly with other properties like sell_value etc. This way we could trigger Stop loss on each level, not only when DCA is done.

Example:
```
DEFAULT_Dca_Stop_Loss_Timeout_1 = 15.0
DEFAULT_Dca_Stop_Loss_Trigger_1 = -4.0
```

**Comment by clownfish44** [comment]
https://github.com/taniman/profit-trailer/issues/366 already added to a future release

**Comment by Helmi** [comment]
@clownfish44 I have a hard time tracking down what this old request is about but it sounds like something different, right? Mine is about different Stop loss trigger levels on different DCA levels. That other one is about setting different stop loss levels based on time.

**Comment by dudesahn** [comment]
Linking from other issues (like [feature] time-stops 366), I think being able to sell a pair after a predefined amount of time would be a big benefit. For me, it would be best to just be something like DEFAULT_Panic_Sell_Wait_Time, where you could set the amount of time after buying that a pair would automatically panic sell. 

Alternatively, if there was a way to sell pairs in the pending log after x amount of time, that would work as well. Pairs are already tracked based on how long they've been held to add to pending, so it doesn't seem like this should be something too difficult. I've found that with some of my strategies, selling the pair after a set time is much more effective at promoting pair turnover and minimizing loss than using a set stop-loss value or a trailing stop.

**Comment by Masterofcoinak** [comment]
Stop loss can be done DCA level specific. Should be closed.
