### ISSUE TITLE
Trade partially a coin

### ISSUE THREAD

**Issue by js8749** [taniman/profit-trailer-enhancements#260]
I would like in the future a feature that let me trade partially a coin. Example i want to trade bnbbtc in binance but i would like to always have 1.5 bnb reserve for trading fee, but i want that my bot trade freely beside that amount. Or another exaple i want to partially hold a coin that i manually buy

**Comment by clownfish44** [comment]
Already accepted to a new release here https://github.com/taniman/profit-trailer/issues/496
