### ISSUE TITLE
WMA

### ISSUE THREAD

**Issue by keithofaptos** [taniman/profit-trailer-enhancements#261]
weighted-moving-average

Most of us bot traders use MA's. And weighted backtesting is worth jumping this into 
the line up .
...plus this is a super simple coding .easy.

**Comment by alex050478** [comment]
EMA's are sort of a weighted moving average... Can you describe a scenario when WMA would outperform an EMA strategy? I can't seem to get my head around it.

**Comment by Flosen86** [comment]
Push!
