### ISSUE TITLE
[Feature Request] - Exchange sell Log importation for manual sells

### ISSUE THREAD

**Issue by BroTastix** [taniman/profit-trailer-enhancements#262]
Purpose:
Add all sells made on the exchange with profittrailer, automaticly and manualy made sells.

My point of vieuw:
-> Create a database of all trading info off the exchange.("Exchange database")
-> Compare it with the exsisting "PTFeeder database"
-> Put pairs in a database that are present in "Exchange database" and "Ptfeeder database"
-> Compare those with the active pairs/DCA and existing Sell database of Profit Trailer.
-> Update "Exchange database" (API)

Hope this sounds possible!
Or sparks an idea

**Comment by clownfish44** [comment]
We do not work with pt feeder!
