### ISSUE TITLE
Enhancement - Add Amount Difference between Current Value and Bought Cost

### ISSUE THREAD

**Issue by cybermizrach** [taniman/profit-trailer-enhancements#265]
I would like to request adding the amount Difference between Current Value and Bought Cost either in the USD column or the P% column.

**Comment by clownfish44** [comment]
There is already too much stuff on the screen and PtTracker is free now to pro/lifetime users so please use that which has this feature, but if you must you can use this https://github.com/CryptoGnome/Community-Tools/tree/master/PT-2.0-Web-GUI/Estimated-USD
