### ISSUE TITLE
Feature Request - Multiple open positions per coin

### ISSUE THREAD

**Issue by cybermizrach** [taniman/profit-trailer-enhancements#266]
Can PT allow multiple open positions per coin?  Each position's target profit must be independent to each other so that PT can sell one position while the other position's target profit is not yet achieved.

1st Buy - NEO at $10 will be sold at $10.1 per coin
2nd Buy - NEO at $9 will be sold at $9.09 per coin

The number of open positions can be defined in the PAIRs properties.

**Comment by clownfish44** [comment]
This would not work which is why we use DCA! If the coin price keeps going down then has a little uptick you would still be in bags where as if you DCA you would be out of all your positions as it averages them.
