### ISSUE TITLE
Feature Request - enhance SOM

### ISSUE THREAD

**Issue by BitRacer** [taniman/profit-trailer-enhancements#267]
I would like to see another option added to price_trigger_market

rather than running of a single coin(current options of:ETH, BTC, BNB, XMR, USDT), it would be great to have an option of "TOP_20" as well.

**Comment by clownfish44** [comment]
We already have this https://wiki.profittrailer.com/doku.php?id=pairs.properties#sell_only_mode_settings

price_trigger_market = ETH

**Comment by BitRacer** [comment]
I dont think you read my request.

I know there is a setting called "price_trigger_market"

valid values are "ETH, BTC, BNB, XMR, USDT" . I would like to see a setting called "TOP20".
