### ISSUE TITLE
Feature Request: DEFAULT_take_daily_profit_percentage = X

### ISSUE THREAD

**Issue by robheath90** [taniman/profit-trailer-enhancements#268]
In addition to DEFAULT_take_profit_percentage = X, would it be possible to include something like a DEFAULT_take_daily_profit_percentage = X, which would look at the 24h percentage rise rather than the total percentage rise?

The reason for including this is that I want to trade primarily on an EMACROSS strategy (both buy and sell). As the EMACROSS sell strategy effectively acts as my stoploss, and longer term is more useful than GAIN which could limit the benefit during bull runs on my long term HODLs, I have GAIN set as a negative value in order to effectively discount it from trading. I have a patient mindset and I wish to generally trade longer term, however I obviously would like to take advantage of outrageous pumps if I hold a coin, and EMACROSS will not accomplish that. DEFAULT_take_profit_percentage = X does, however it would require regular bot maintenance if specific pairs begin to meet the total percentage gain, but not the daily percentage gain. This thought came to me this morning when I realised I had sold DCR on Poloniex for an 11% Profit, despite the coin pumping over 100% overnight. I realise DEFAULT_max_profit = X would have taken advantage of some of this pump, but I had excluded this variable because, similar to GAIN, this would require maintenance to continuously cater this for each coin (by increasing the max_profit percentage as my coin grew according to my EMACROSS buy/sell strategy), whereas GAIN would prevent EMACROSS working as my stoploss.

**Comment by clownfish44** [comment]
We already have take profit and max profit please read the wiki!

**Comment by robheath90** [comment]
I have read it, unless I am mistaken both take_profit and max_profit are based on the total percentage gain of the coin since buying? I'm talking about a 24h percentage change?

**Comment by robheath90** [comment]
I see DEFAULT_buy_min_change_percentage and DEFAULT_buy_max_change_percentage, but no equivalent for selling?
