### ISSUE TITLE
Custom DCA settings for each pair

### ISSUE THREAD

**Issue by serial77** [taniman/profit-trailer-enhancements#27]
As the title suggests allow the bot to support custom DCA settings for each pair.

Great bot!

**Comment by clownfish44** [comment]
This has been requested here https://github.com/taniman/profit-trailer-enhancements/issues/19

**Comment by serial77** [comment]
Yeah might as well group all the feature requests together lol. What on
earth has my feature to do with a Feeder/Magic merge?
