### ISSUE TITLE
Multiple Strategies using multiple indicators

### ISSUE THREAD

**Issue by jas-on-jas** [taniman/profit-trailer-enhancements#270]
**Issue:**
Unable to have multiple strategies using multiple indicators.

**Reasons:**
I would like to have the ability to setup a strategy for purchasing a pair which has dropped and is at the low end of say LOWBB and RSI and is ripe to buy and another strategy for a pair which is moving up but within my range for LOWBB and RSI, or whatever other indicators I could decide to use. I could have multiple strategies for different situations and couple them with multiple indicators.

### **Solution**
**This would be one overall strategy emphasized by the _1 at the end**
DEFAULT_DCA_A_buy_strategy_1 = LOWBB
DEFAULT_DCA_A_buy_value_1 = 10
DEFAULT_DCA_A_buy_value_limit_1 = -10

DEFAULT_DCA_B_buy_strategy_1 = RSI
DEFAULT_DCA_B_buy_value_1 = 30
DEFAULT_DCA_B_buy_value_limit_1 = 0
_____________________________________________________________________________________
**This would be a second overall strategy emphasized by the _2 at the end**
DEFAULT_DCA_A_buy_strategy_2 = LOWBB
DEFAULT_DCA_A_buy_value_2 = 40
DEFAULT_DCA_A_buy_value_limit_2 = 10

DEFAULT_DCA_B_buy_strategy_2 = RSI
DEFAULT_DCA_B_buy_value_2 = 40
DEFAULT_DCA_B_buy_value_limit_2 = 0
_____________________________________________________________________________________
You could do the same for sell_value tied to each strategy.

Thanks

**Comment by clownfish44** [comment]
You can do this by changing the 

DEFAULT_DCA_A_buy_strategy = LOWBB
DEFAULT_DCA_A_buy_value = 10
DEFAULT_DCA_A_buy_value_limit = -10

DEFAULT_DCA_B_buy_strategy = RSI
DEFAULT_DCA_B_buy_value = 30
DEFAULT_DCA_B_buy_value_limit = 0

to

XYZ_DCA_A_buy_strategy = LOWBB
XYZ_DCA_A_buy_value = 10
XYZ_DCA_A_buy_value_limit = -10

XYZ_DCA_B_buy_strategy = RSI
XYZ_DCA_B_buy_value = 30
XYZ_DCA_B_buy_value_limit = 0

This allows you to do this per coin!

**Comment by jas-on-jas** [comment]
Hello, thanks for giving me the option to do it by coin, I'm not asking per coin though, I'm asking for multiple strategies that an be used to purchase any coin I allow for trading in my pairs, which is what my feature request is for.

With my request I could have more than 2, as maybe I want to allocate 5 indicators to narrow down to a limits few pairs that meet all the criteria so therefor my purchase costs are higher. Hopefully this makes sense, please reopen.

Thanks

**Comment by Masterofcoinak** [comment]
This can be already done by labels and Formula
https://wiki.profittrailer.com/doku.php?id=pairs.properties#default_a_buy_strategy_label
https://wiki.profittrailer.com/doku.php?id=pairs.properties#default_buy_strategy_formula
Should be closed
