### ISSUE TITLE
‼️****{ Feature Request = AUTO SELL DUST TO BNB }****‼️

### ISSUE THREAD

**Issue by juato4** [taniman/profit-trailer-enhancements#271]
Simple..

after selling a coin, if it has DUST, sell it to BNB automatically.

**Comment by clownfish44** [comment]
Go on the exchange and click the convert button they just added it! :D https://bitcoinexchangeguide.com/binance-releases-convert-dust-to-bnb-exchange-broom-sweeping-feature/
