### ISSUE TITLE
Calculate TCV correctly

### ISSUE THREAD

**Issue by echthard** [taniman/profit-trailer-enhancements#273]
This is actually a bug, not a feature request. But as stated here, I will post a request: https://github.com/taniman/profit-trailer/issues/1650

# Summary:

![image](https://user-images.githubusercontent.com/1479483/39257143-198520c6-48b1-11e8-8eb4-9e2147fedc5a.png)
I have an open buy order of 2000 BQX, so it ends up in the Pending Log. The current value is calculated over the 2000 BQX as if **I already have the 2000 BQX in my possession**. Which is worth 0.7 BTC

But in real life only 0.004 BTC from my balance is **reserved** for that 2000 BQX buy order. 

### Solution:
You should switch the current value and the target value for **buy orders** (toggle this on positive or negative `Profit in %` in Pending Log). Positive value = buy order, negative value = sell order.

Current value for sell orders is correct, for buy orders it's incorrect. Please fix this.

**Comment by clownfish44** [comment]
It clearly says you "fixed" the price to be that high / low leaving that much profit please fix your stuff so this wont happen. There is no need for us to fix it when you clearly put silly numbers for the bought price. This is not a bug nor a feature but instead a user issue.

**Comment by Masterofcoinak** [comment]
I think this was already solved.

**Comment by taniman** [comment]
Already solved
