### ISSUE TITLE
Using the same indicator across multiple candle periods for confluence.

### ISSUE THREAD

**Issue by Pennypacker85** [taniman/profit-trailer-enhancements#275]
Now that RSI/Stoch has been added into PT (fantastic!). I feel that one of the best ways I can think of to not only improve trades in general, but to protect against fast crashes (like the one just the other day) is to allow us to use the same indicators (in particular RSI/Stoch) across multiple timeframes. Many of the best trading strategies right now are using 5-15 minute candle period low RSI levels to buy. This is great, until you get the 5m RSI showing a low reading while the 1 hour is still very high. The market then continues to drop sharply after you bought based on the 5m and leaves you relying heavily on DCA to pull you out of what are now some quite heavy bags.

To avoid this most Day traders look for confluence across multiple timeframes when they are buying based on an indicator. Rarely does someone buy based on the 5m RSI alone. They might for example buy when the 5m is under 30, the 15 min is also very low, and the 1 hour is at least in the bottom half of its range.

If you were able to allow us to run say, RSI 1, RSI 2 and RSI 3 (even just two would be good but the more the better i guess), with each reading different candle periods, this could go a long way towards making smarter buys and protecting us from sudden crashes (especially because if you are buying on the 5m atm, it is often oversold long before a SOM % change trigger kicks in, leaving you making buys before the protection kicks in).

Just to add (this would be a separate feature I guess, but would go very well in tandem with this), the ultimate here would be being able to connect these RSI periods to % change over time. So just for example:
- If there has been more than 2.5% percentage drop within the last hour, PT now requires the 1 hour RSI to be below 30
- If there is a minimal % change in the last hour, then PT only requires 1 hour RSI to be below 50

Anyway, just some things I think would really help the bot make consistent buys across a wider variety of market conditions.

Cheers!

**Comment by keithofaptos** [comment]
+1

**Comment by pheonix727** [comment]
+1
i mean here to write the same request, and i found yours

**Comment by fadelchaidarf** [comment]
+1

**Comment by alex050478** [comment]
+1

**Comment by robheath90** [comment]
+1

**Comment by urnzwy** [comment]
+1

**Comment by kkhaial** [comment]
+1

**Comment by DomsterKB** [comment]
+1.  Neat to have this for BB indicator.

**Comment by markdofuturo** [comment]
+1 this should be urgents devel team! plz!

**Comment by stevenshizzleh** [comment]
YES.

**Comment by Pennypacker85** [comment]
Agreed DomsterKB. Would love this for all indicators. Just using RSI and STOCH as the most obvious examples but you could do some amazing things with BB and all the other indicators. Like being able to use a couple of BB indicators to identify an uptrend while using a short time-frame one to make your buy in into it. Would be game changing imo.

**Comment by DomsterKB** [comment]
@stevenshizzleh Great work with The North Star settings.  Your settings are the most unique I have seen using indicators from multiple time frames and I have to admit, performs better than most settings I have tried.  Nice and fast quick trades with minimal DCA 🥇 

Your settings will no doubt benefit from this enhancement many times over!

**Comment by blyzeguy** [comment]
This is a great idea, would benefit everyone greatly.

**Comment by peterpuglisi** [comment]
This sounds great, +1 from me

**Comment by MetaAtman** [comment]
+5 :)

**Comment by pyto00** [comment]
Please add this!

**Comment by angelsomar** [comment]
+1

**Comment by Squeaker1** [comment]
+1

**Comment by Masterman1980** [comment]
+1

**Comment by SanderGith** [comment]
+1

**Comment by swanfield1979** [comment]
Gief!! +1

**Comment by bvebve** [comment]
+1

**Comment by RobinopdeBeek** [comment]
I also wanted to write the same request! This would give PT a HUGE jump in capabilities. No doubt that it would half the risk on each trade.

+1

**Comment by Masterofcoinak** [comment]
Should be closed. 
https://wiki.profittrailer.com/doku.php?id=pairs.properties#sell_settings
