### ISSUE TITLE
Global Panicsell with selling Market Currency to configurable Exit Currency

### ISSUE THREAD

**Issue by NOP-Commander** [taniman/profit-trailer-enhancements#276]
Dear developers,

preamble:
I'm not sure about the impact on the market of such a feature being implemented and used by thousands of thankful users of ProfitTrailer but whales and their trading bots don't care about ethics so why should we? Anyway this is not the place for a moral debate but it's maybe worth a debate though.

request:
having the possibility to manually trigger a global panicsell, configurable per coin like XXXBTC_global_panicsell = true/false, PLUS converting a user-defined amount/percentage of your market currency (BTC,ETH etc. ) to an exit currency (probably USD,TUSD,USDT) with something like BTC_global_panicsell_exit(_percentage) = 100.
EDIT: plus BTC_global_panicsell_exit_currency = USDT

scenario 1:
you might want to globally secure profits shortly before an epic trend reversal (like BTC in 12/2017).

scenario 2:
you might want to globally avoid losses when you see the shit approaching the fan (like BTC in 02/2018).

This feature could/should address multiple instances running in parallel which could be built with features requested here:
https://github.com/taniman/profit-trailer-enhancements/issues/274
https://github.com/mehtadone/PTFeeder/issues/316

And yes, i know such a setup would be insane and a lump risk to you profit machine aswell. (; 

sincerely yours,
NOP-Commander

**Comment by fadelchaidarf** [comment]
I agree about the exit currency, when market currency is taking a dive it would be preferable to automatically sell the market currency to fiat until the storm passes

**Comment by NOP-Commander** [comment]
#302 is a nice feature i haven't thought about. Some room for improvement of panicsell spotted.

**Comment by pheonix727** [comment]
agreed

**Comment by clownfish44** [comment]
This would be added if https://github.com/taniman/profit-trailer-enhancements/issues/28 is added as this would be needed first and would make this necessary as well.

**Comment by NOP-Commander** [comment]
Hi @clownfish44,

thanks for your feedback. I fully understand and just gave thumps up on #28 meanwhile.

yours sincerely,
Nop-Commander
