### ISSUE TITLE
Keep coin amount/percentage

### ISSUE THREAD

**Issue by freecoat** [taniman/profit-trailer-enhancements#278]
Hi,
Add function:
keep a definite amount or percentage of a specific coin untouched when trading.
Reason:
Useful when running 2 instances on different bases.
Example:
Instance 1 of PT on base ETH
Instance 2 of PT on base USDT 
In instance 2 add function:
 ETH_keep_percentage = 20
Instance 1 keeps trading using the remaining 20%

**Comment by fadelchaidarf** [comment]
You can just use two different exchange accounts

**Comment by freecoat** [comment]
The idea behind keeping two instances active in one account is to use USDT
to leverage on eth when the market drops. Also if I set the loss trigger
properly the bot is going to save me loads of pain moving everything
without the hussle of doing it manually.

Il Sab 28 Apr 2018, 18:26 fadelchaidarf <notifications@github.com> ha
scritto:

**Comment by clownfish44** [comment]
@freecoat we already have this for the base currency which is what you have described https://wiki.profittrailer.com/doku.php?id=pairs.properties#keep_balance_percentage also we do not support the use of two bots on one account in any circumstance as this can lead to various issues including bans. Also this was already accepted here https://github.com/taniman/profit-trailer/issues/496 to keep bal per coin :D
