### ISSUE TITLE
Cross Market Trading/Multi Market Trading

### ISSUE THREAD

**Issue by dchedda** [taniman/profit-trailer-enhancements#28]
the ability for the bot to monitor a coins value accross the different markets on an exchange to take advantage of differences that would lead to profitable sales.

eg
etc zec - zec is cheap if bought with etc,
btc zec - zec is expensive in btc, zec that were bought using etc, are sold for a profit in btc

**Comment by dchedda** [comment]
if this could be cross exchange that would be amazing

**Comment by clownfish44** [comment]
Because market keep is volatile, for example if BTC rise more than 8% help me sell my BTC available balance and trail to sell back to USD. Trigger back when BTC drop more than certain % and buy back. If can prompt notification and ask user to click and confirm will be the best.

**Comment by clownfish44** [comment]
Could also trade multiple markets at the same time to spread your assets

**Comment by jbraydc** [comment]
You could have a big bag but be able to sell it for a profit on a different exchange. Or maybe even trade into a different pair on the same exchange.

**Comment by taniman** [comment]
This is not an arbitrage bot. I am pretty sure Arbitrage is on the No no list.
Please enlighten me how this is not border line arbitrage or I will close the issue

**Comment by aalemayehu** [comment]
As an example, if you are using Binance, you would be going from ETH market in Binance to BTC market depending on market conditions. Would this still be arbitrage if it's in the same exchange?

**Comment by juato4** [comment]
Hope this win and #264

**Comment by CryptosWORLD** [comment]
in the same exchange is no arbitrage

**Comment by taniman** [comment]
This is a type of arbitrage. which the bot is not designed to do.
