### ISSUE TITLE
Free Test BOT. I want to test zillion ideas concurrently without buying new licenses

### ISSUE THREAD

**Issue by pheonix727** [taniman/profit-trailer-enhancements#280]
the title says it all, 
i want to test multiple ideas at once to see how it works
but i'm restricted by to 2 default api-keys per license
so i would like the test bot to not require a license or api keys and it is dedicated only for test mode trading

perhaps remove the appsettings license / api keys
or the bot automatically runs in testmode if it is missing license / api keys?

advertisement benefit for the developers, 
new users who are afraid to buy a license will be more comfortable and ready to buy a license after they see their bot making stable profits

**Comment by NOP-Commander** [comment]
This sounds like a very nice marketing idea for ProfitTrailer to me. Since v2 supports paper trading the devs could enable paper trading without a paid or even without license. Paper trading should be sufficient for testing strategies or evaluating ProfitTrailer in general, shouldn't it?

Yours sincerely,
NOP-Commander

**Comment by clownfish44** [comment]
Hello @pheonix727 you can do this!

Scenario: you have 1 license with 2 bots / api's registered but want a test bot while the other two run 

Fix: 

Setup a test bot with the same api keys and license as one of your running pt bots then make sure when you start it to make the config name unique so it is not shared with your first bot and BOOM it works :D 

This should not cause any issues as testmode does not use the api keys as it used the public api, but the bot will run as it is licensed. 

We will never offer unlicensed bots free to the public.

**Comment by NOP-Commander** [comment]
Hello @clownfish44,

I'm just curious. What are your concerns about running unlicensed bots in testmode?
