### ISSUE TITLE
value - value limit direction

### ISSUE THREAD

**Issue by pheonix727** [taniman/profit-trailer-enhancements#281]
Hi i would like to specify the direction value - value limit
**how does that look like?**

**usually the bot works like this:**
EMASPRAID buy value -0.2
EMASPRAID buy value limit -0.7
the bot considers buying the pair when it goes below -0.2 and above -0.7
which mean that you may buy the pair while it is still falling

**what i want is:**
EMASPRAID buy value -0.7
EMASPRAID buy value limit -0.2
I want the bot to to consider buying the pair when it has been below -0.7 and it goes above -0.7 and it is still below -0.2

**what is that good for?**
it is like confirming a potential reversal and you buy when the pair is going up which is what you want

**same thing for sell value - value limit**

**Comment by clownfish44** [comment]
The direction is already built in depending on how you setup https://wiki.profittrailer.com/doku.php?id=pairs.properties&s[]=limit#default_a_buy_value_limit

**Comment by pheonix727** [comment]
@clownfish44 
no direction is not built in
i hope you get my point
if buy value is 1 and buy value limit is 2
i want the bot to start trailing if it enters this zone from below and not from above or the reverse
------------
but the bot trails when it is in the zone wether it came from above or below
