### ISSUE TITLE
SMA/EMA CROSS Candle Value / CROSS Candle Value Limit

### ISSUE THREAD

**Issue by pheonix727** [taniman/profit-trailer-enhancements#282]
i want cross strategies to become periods

**How Cross strategies work currently:**
EMA_CROSS_Candles = 3
will buy a pair only in the 3rd candle after the cross, not number 4, not number 2, only number 3

**what i want:**
EMA_CROSS_Candles_Value = 1
EMA_CROSS_Candles_Value_Limit = 4
i want the bot to consider buy the pair in the first 4 candles after crossing
EMA_CROSS_Candles_Value = 2
EMA_CROSS_Candles_Value_Limit = 5
i want the bot to skip the first candle after crossing and consider buying the pair from the candle #2 to #5 

**what is that good for?** 
this make cross strategies a period instead of a single point in time
having periods of time allows the bot to trail
you can't trail with a cross strategy 
it will also allow comfort in intersecting multiple strategies together

**Comment by clownfish44** [comment]
The limit is just EMA_CROSS_Candles_Value = 4 as per the wiki Define how many candles back to look and see if the EMA lines just crossed. https://wiki.profittrailer.com/doku.php?id=indicators.properties#ema_cross_candles if you use 4 it will look back in the last 4 which is the limit. Also the bot does trail with all strats including crosses. There is already "comfort in intersecting multiple strategies"

**Comment by pheonix727** [comment]
@clownfish44 
the bot indicators on trading view only shows that candle number 4 as the possible by time, that is why i assumed it is not functioning properly
