### ISSUE TITLE
GUI: separate column for each strategy 

### ISSUE THREAD

**Issue by pheonix727** [taniman/profit-trailer-enhancements#283]
when you want to arrange the pbl/pairs/dca 

***filtering by buy/sell strategy** lists all pairs with at least 1 true strategy
i want to be able to filter by each strategy individually

***filtering by buy/sell value** lists pairs by the value of the first strategy only
i want to be able to filter by each strategy individually

**Comment by clownfish44** [comment]
Not enough room on the GUI to do this however please request your sorting here https://github.com/taniman/profit-trailer-enhancements/issues/269
