### ISSUE TITLE
Introduce loglevel DEBUG2 to protect sensitive information

### ISSUE THREAD

**Issue by NOP-Commander** [taniman/profit-trailer-enhancements#285]
Dear developers,

I'd like to request the introduction of loglevel DEBUG2 or however you would like to call it if you find it worth being implemented.

Scenario:
I'm having trouble with ProfitTrailer and enable loglevel debug to collect helpful information for troubleshooting. When i post or upload (an excerpt of) the log to a public place like Discord there is a possibility that the posting/file could contain sensitive information like the license key or future data logged at loglevel debug like ip-address, dns name etc. (for the records: the same applies to unencrypted mails and other unencrypted communication channels) Sure, you could obfuscate the log before posting/uploading but people might forget because they don't realize and/or forgot. 

I yet don't know what one could do with a stolen license key but if it can be abused in any way it's worth protecting it. So basically a future loglevel debug2 will log sensitive information in addition to loglevel debug while a future loglevel debug won't log them anymore.

Since i tend to be "a bit" more paranoic as an average human i try to tweak the most out of security measures available and being able to implement them so this is the main motivation of my request. I like security in application as much as i like stability in favor of new features. Thanks for reading.

yours sincerely,
NOP-Commmander

**Comment by clownfish44** [comment]
Sorry we can not add this as all of these sensitive details must be looked at in order for the log / debug to actually be useful. In all cases you should protect your log file by not uploading it into the public discord and always send to a support member+
