### ISSUE TITLE
Multiple Strategy Logic {and, or, if, not, etc}

### ISSUE THREAD

**Issue by avizmil** [taniman/profit-trailer-enhancements#286]
I'd like to use OR between strategies with buy trailing enabled.
for example, 
I would add DEFAULT_A_buy_strategy_OR_enabled = true to each strategy that I would like to buy the moment the trigger is true.
Also, buy_trailing is a must. it should trail by the strategy it was enabled by.
I don't think nested OR/AND are needed althoug it would be nice to have :)
This would be a great enhancement .

**Comment by NOP-Commander** [comment]
Hi there,

I think there is a need for something like logically linking strategies. After watching all video tutorials for Profit Trailer I was kinda inspired and felt like I must think about a possible new config-syntax which is more readable, understandable and scales better with a growing feature-set.

So i tried to implement that logical link between strategies with my proposed new config-syntax and would be happy if you check my repo, review my approach and give honest feedback. I haven't thought about nesting, it's pretty simple and one-dimensional.

Thank you in advance!

**Comment by LiamAird** [comment]
Strategy Formula has been added in the latest version. 
You can look it up here: http://wiki.profittrailer.com/doku.php?id=pairs.properties#default_buy_strategy_formula
http://wiki.profittrailer.com/doku.php?id=pairs.properties#default_sell_strategy_formula
And the same goes for DCA settings
