### ISSUE TITLE
Average price calculation is wrong

### ISSUE THREAD

**Issue by echthard** [taniman/profit-trailer-enhancements#287]
PT in DCA says that I have +4.12% profit on my manual buy: 

![image](https://user-images.githubusercontent.com/1479483/39411668-eaa694a4-4c0e-11e8-9f11-80a76fc4fe44.png)

But I didn't buy it at 6530 sat:

![image](https://user-images.githubusercontent.com/1479483/39411637-1f78d65c-4c0e-11e8-926d-cb520a605da9.png)

**Comment by echthard** [comment]
Also for **Sales** the price is wrong:

![image](https://user-images.githubusercontent.com/1479483/39411727-462b6b82-4c10-11e8-9d5e-f95460511d2a.png)

When RPX is sold in three batches, the last batch suddenly has more profit, because of the cheaper bought cost.

**Comment by SgtBatten** [comment]
The manual buys issue is related to https://wiki.profittrailer.com/doku.php?id=faq#i_manually_bought_a_coin_and_it_already_has_a_dca_count

Using the hotconfig should allow you to fix those and this behaviour can be expected when making manual buys.

As for the other issue you already have an issue open in the correct place. this repository is for feature requests so ill close it and you can add to the other one.
