### ISSUE TITLE
Why SOM? an on hover tooltip

### ISSUE THREAD

**Issue by MetaAtman** [taniman/profit-trailer-enhancements#289]
To see in GUI why a SOM is enabled for a particular coin. Onhover tooltip.

**Comment by clownfish44** [comment]
The only reason a coin would be in SOM is because you manually set it to be as seen here https://wiki.profittrailer.com/doku.php?id=pairs.properties#default_sell_only_mode_enabled there is no trigger for a per coin SOM unless you are using feeder / magic
