### ISSUE TITLE
An iframe portal that views the market future :)

### ISSUE THREAD

**Issue by jodee8** [taniman/profit-trailer-enhancements#29]
I know none of us have a crystal ball... But If you guys could just code up a wee iframe somewhere on the dashboard that could look into the future of any selected coin pair with an adjustable timeframe e.g. 5mins ahead, 10mins ahead, 1hr ahead, 24hrs ahead, 1month ahead, 1yr ahead and report back on the exact price for that time period that would be absolutely grand! It would be the bees knees! The best thing since sliced bread! You'd make us all richer than Scrooge McDuck! I know you're not miracle workers but with your guys coding skills almost anything is possible :) lol

**Comment by jodee8** [comment]
sorry couldn't resist a little bit of silliness in this all too serious crypto world :)

**Comment by clownfish44** [comment]
This is just silly
