### ISSUE TITLE
Sales Page Summary: Bought date, sold date, pair lowest drop%, pair current profit %

### ISSUE THREAD

**Issue by pheonix727** [taniman/profit-trailer-enhancements#290]
i would like to see these values in the sales page
bought date - sold date(already there) /// to see how long i held the pair
pair lowest drop % /// to see if i should edit my trail buy
pair current profit % compared to my bought price /// to see if i should hold pairs more and edit my trail profit

**Comment by clownfish44** [comment]
Please request this under PtTracker here https://github.com/bTayFla/PtTracker/issues as this is an enhanced feature for stats
