### ISSUE TITLE
Add Reset Test Mode in the Settings panel

### ISSUE THREAD

**Issue by cybermizrach** [taniman/profit-trailer-enhancements#291]
Please add the link below in the Settings panel if the test mode is enabled. When the user click the Reset Test Mode, prompt the user to continue or not.

http://localhost:8081/settings/test/reset

**Comment by clownfish44** [comment]
You must be logged in to use this so no need to confirm as you willingly put it into the address bar.

**Comment by cybermizrach** [comment]
A Test Mode Reset button under the Settings panel would be nice so that the user won't need to visit the wiki to check the URL to reset test mode.

**Comment by clownfish44** [comment]
@cybermizrach why not just favorite the web url if you need to reset so often or put it in your pairs file with a #http://localhost:8081/settings/test/reset

**Comment by cybermizrach** [comment]
@clownfish44 Thanks! This is not a critical feature request but I encourage you to consider the user experience and customer journey.

**Comment by clownfish44** [comment]
Reset upon toggle of testmode will be implemented soon please look for an upcoming update :D Also make sure to use the strats I said above!
