### ISSUE TITLE
Wipe Testmode Data Instantly

### ISSUE THREAD

**Issue by pheonix727** [taniman/profit-trailer-enhancements#292]
in testmode
when testing a new strategy , i have to activate panic sell to move all previous pairs into sales log then delete to Data.json to have a fresh account
i want an easy way to wipe all test mode data instantly, perhaps an option inside the web GUI would help

**Comment by clownfish44** [comment]
We have a quick way to reset it here https://wiki.profittrailer.com/doku.php?id=application.properties&s[]=testmode#servertest_mode . Use the url http://localhost:8081/settings/test/reset to reset test_mode data if wanting to try another strategy for example.
