### ISSUE TITLE
API to Set Bought Price

### ISSUE THREAD

**Issue by cybermizrach** [taniman/profit-trailer-enhancements#293]
Can you add an API to set a pair's bought price? I'm planning to create a small app that requires setting a pair's bought price.

**Comment by clownfish44** [comment]
As far as I know this can be done with https://wiki.profittrailer.com/doku.php?id=swagger_api by editing the hotconfig if this can not be modified with the API please submit a bug report here https://github.com/taniman/profit-trailer/issues as this seems like it should be a core feature!
