### ISSUE TITLE
Adjustable True signal timer

### ISSUE THREAD

**Issue by DragonBtc93** [taniman/profit-trailer-enhancements#294]
I would like to be able to set the timer on true signals myself. I have had problems when a buy signal is still in the buy range I set it will time out before the next one fires.

**Comment by clownfish44** [comment]
Issue not clear as PT does not have "true signals".

**Comment by DragonBtc93** [comment]
MULTIPLE BUY INDICATORS, AND / OR BEHAVIOR
Normally, when using multiple buy/sell indicators, the bot requires them to all be true at the same time (this is called “AND” logic) before the bot will begin the buy cycle. However, with the setting DEFAULT_A_buy_on_first_signal, you can force the logic to be “OR”, where if any one of the indicators is true, the bot will begin the buy cycle immediately.

**#This “true” signal from the one indicator will remain true for a few seconds to see if there is an actual buy opportunity**. If not, the bot resets to false and continues looking for other indicators to become true.

**Comment by DragonBtc93** [comment]
Need to be able to set a time for it then just having a few seconds.
