### ISSUE TITLE
Modify buy exclusion trigger length for DEFAULT_buy_min_change_percentage and DEFAULT_buy_max_change_percentage

### ISSUE THREAD

**Issue by xinpw8** [taniman/profit-trailer-enhancements#295]
I'd like to exclude individual pairs from buys based on % price change up/down per a modifiable time frame (buy exclusion trigger length). Right now, it appears the buy exclusion trigger length for DEFAULT_buy_min_change_percentage and DEFAULT_buy_max_change_percentage is fixed at 24 hours. Please introduce a way for us to specify the length of time over which % change is calculated so pair-specific buys can be excluded for % change over any period of time.

**Comment by xinpw8** [comment]
Example: you want to avoid pump 'n' dumps, so you change your buy exclusion trigger length to 1 hour. Now, with a DEFAULT_buy_max_change_percentage = 15, you can effectively prevent buying after that massive EOS pump (and right before the massive EOS dump).

Even more compelling, in the scenario where many coins are up 15 or 20% over 24 hours and the price retrace is imminent, you don't want to buy at the top or on the way down. You change your buy exclusion trigger length to 30 minutes and, with DEFAULT_buy_min_change_percentage = -5, you don't buy anything that drops >=5% over a half hour. In the current PT version (2.0.1), prices (24 hour) will still be positive percentages for the first however long of the retrace because the buy exclusion trigger length can only be measured over 24 hours.

**Comment by Stogy** [comment]
Do IT!

**Comment by Masterofcoinak** [comment]
I think we can close this point and refer to #19

**Comment by taniman** [comment]
use CHANGEPERCENTAGE strategy
