### ISSUE TITLE
Not needing all indicators to be true to buy

### ISSUE THREAD

**Issue by Jacob11701** [taniman/profit-trailer-enhancements#296]
Suggestion:
I used another bot in the past and a good setup we all had going was to have 5 indicators setup but only 3 out of the 5 have to be true to buy. It can be any 3 instead of PT needing every indicator on to buy. I think adding the option to:

1. Say a certain indicator is required or not
2. Having the default if none are REQUIRED to select how many would be true before buys

This in my opinion would open up more buys and positions for a variety of configurations.

**Comment by ethminerjay** [comment]
+1

**Comment by MetaAtman** [comment]
Add "OR: bool value to multiple strategies could be useful

**Comment by clownfish44** [comment]
Better example of this would be https://github.com/taniman/profit-trailer-enhancements/issues/286 where you could use OR to achieve this
