### ISSUE TITLE
Config-Syntax should be case-insensitive

### ISSUE THREAD

**Issue by NOP-Commander** [taniman/profit-trailer-enhancements#297]
Dear developers,

I would like to have case-insensitive config-keys and config-values. I don't see a real reason why for example you MUST set "trading.exchange" to e.g. "BINANCE" instead of Binance, binance, BiNaNCe or bInAnCe (I lately saw that note on using uppercase for "trading.exchange" in a video-tutorial by RF Radio. Super nice tutorials, Kudos to him!). It would reduce errors in configs produced on layer 8. You could uppercase or lowercase keys/values in your code before comparing against your constants. Just a proposal to increase the user-experience on your wonderful peace of software.

yours sincerely,
NOP-Commander

**Comment by NOP-Commander** [comment]
Addition: Using config-values like "0.5" or ".5" shouldn't make a difference too.

**Comment by clownfish44** [comment]
Currently this is not even an issue as the number of people this affects is highly limited. Wait for upcoming changes as this will not affect people. :D

**Comment by NOP-Commander** [comment]
Hi @clownfish44,

thanks for your feedback. I know what you mean. It looks like i have decent skills in requesting features nobody needs. :D I'm seriously curious about what's in the pipeline because you added a big smile at the end. Looking forward to it.

yours sincerely,
NOP-Commander
