### ISSUE TITLE
Have PT accept "order" requests via API

### ISSUE THREAD

**Issue by machyy1** [taniman/profit-trailer-enhancements#299]
There are services (like Autoview.with.pink, or coinindicator.io, etc) that allow for configuring alerts when buy conditions are met.  Although these are very useful, and can send the buy command directly to the exchange, they are not "aware" like PT is.  

I would like PT to be able to receive the buy requests (via API), so PT can then use its existing logic to decide whether or not to pass the buy signal on to the exchange.

As an example, I have an alert running on Tradingview, looking for a buy signal.  The alert fires (indicating a buy condition was met), and sends the buy to PT via this new API.  PT then evaluates whether or not it should send this on to the exchange.  It would be able to evaluate things like "are we already at max pairs?  if yes, then don't send on the buy", or "are we exceeding min balance by making this buy"?  

Ideally, I look at this like an injection into the existing process of PT, just instead of having PT looking for a buy, be able to use an external service to indicate there is a potential buy.

**Comment by clownfish44** [comment]
Already accepted here https://github.com/taniman/profit-trailer/issues/320
