### ISSUE TITLE
[REQ] Order book depth setting

### ISSUE THREAD

**Issue by Mtrade** [taniman/profit-trailer-enhancements#300]
Requesting a new setting to allow for the ability to go deeper into the order book (configurable by a % limit for example) to execute a trade. This is of particular importance when trying to DCA and buy cost needed is increasing, and the coin volume and order book is thin.
Ex. When trading with higher initial cost on a low volume coin, an Anderson DCA trying to double up might not have enough quantity at the lowest ask to execute.

**Comment by clownfish44** [comment]
We already have this https://wiki.profittrailer.com/doku.php?id=pairs.properties#default_min_orderbook_volume_percentage

**Comment by Mtrade** [comment]
? I asked about this in the discord support and received from Sarlack the following:

Q: Does min_orderbook_volume_percentage setting account for order book depth beyond highest bid/lowest ask?

A: No, it only looks at the volume at the price you want in that moment - it is meant to reduce partial sells/buy
