### ISSUE TITLE
Value (1) - Value Limit (-1)

### ISSUE THREAD

**Issue by pheonix727** [taniman/profit-trailer-enhancements#301]
i want the value / value limit to be a range that contains zero in it

**Comment by clownfish44** [comment]
This can already be done depending on how you setup your limit as seen here https://wiki.profittrailer.com/doku.php?id=pairs.properties&s[]=limit#default_a_buy_value_limit

**Comment by pheonix727** [comment]
@clownfish44 no it doesn't, 
if you say it does, then i would like to report a bug
when my rang includes the zero this is how the bot reacts:
if the buy value is positive , it looks for anything more positive +1 > +10
if the buy value is negative, it looks for anything more negative -1 > -10
emaspread strategy
