### ISSUE TITLE
PANICSELL DCA only Or Pairs Only

### ISSUE THREAD

**Issue by pheonix727** [taniman/profit-trailer-enhancements#302]
self explanatory
panic sell sells everything
i want to choose what it sells
DCA or PAIRS or BOTH

**Comment by NOP-Commander** [comment]
Good point, thumbs up for this. Maybe you can comment on my request for panicsell. #276 Thanks!

**Comment by Masterofcoinak** [comment]
Panicsell is alredy seperated by Pairs and DCA
DEFAULT_panic_sell_enabled = false
DEFAULT_DCA_panic_sell_enabled = false 
Should be closed
