### ISSUE TITLE
Proposal for a new config-syntax

### ISSUE THREAD

**Issue by NOP-Commander** [taniman/profit-trailer-enhancements#303]
Dear developers,

preamble:
I love your software as it is (except the bugs (; ). This draft is not to be meant as an offense towards the developers or any kind of rating but is meant to be a proposal which - from my personal view - would make the config-file more readable and understandable, especially when the feature-set grows by time, and might additionally be an opportunity to optimize the code too. But the code-part is just a guess.

After watching all the videos for pt 2.0 on youtube (they are excellent and RF Radio has a clean and highly understandable speaker-voice. Kudos!) I thought about improvements on the config-syntax. Since I'm a linux guy I edited a lot of config-files and my proposal is based on personal experience. I transformed the config-files which came with pt 2.0 to show you what I mean. I think they are self-explaining. Additional comments are added where needed. In this proposal I took the issues #286 #296 #297 into account.

This work is done with passion and everyone is welcome to review and comment on this. Thanks!

yours sincerely,
NOP-Commander

[indicators.properties.txt](https://github.com/taniman/profit-trailer-enhancements/files/1965408/indicators.properties.txt)
[dca.properties.txt](https://github.com/taniman/profit-trailer-enhancements/files/1965409/dca.properties.txt)
[pairs.properties.txt](https://github.com/taniman/profit-trailer-enhancements/files/1965410/pairs.properties.txt)

**Comment by Jacob11701** [comment]
would love it.

**Comment by NOP-Commander** [comment]
I did some minor updates on the files and put them in a repo.
repo: https://github.com/NOP-Commander/pt-config-syntax-proposal

**Comment by NOP-Commander** [comment]
a demo implementation for #276 added to pairs.properties. check my repo for updates.

**Comment by tuxitor** [comment]
At least with nodejs it will simplify parsing a lot.

**Comment by clownfish44** [comment]
This does not make the config file any bit more understandable and certainly will not "optimize the code" as the code is already built and works fine. Just wait for the upcoming changes you will be happy very soon :D
