### ISSUE TITLE
Proportional Trailing

### ISSUE THREAD

**Issue by robheath90** [taniman/profit-trailer-enhancements#304]
Would it be possible to introduce a proportional trail for the GAIN strategy? During long pumps/price increases, the trailing sell value remains the same. Say I allow for a 20% trail from my profit, that would be 0.2% from a 1% profit, 2% trail from a 10% profit of 10% trail from a 50% profit. It would allow for long consistent rises above a moving averages to ride all the way up, but potentially be more reactive than EMACROSS as a sell strategy.

**Comment by clownfish44** [comment]
Already accepted here https://github.com/taniman/profit-trailer/issues/289
