### ISSUE TITLE
Build ability to switch exchange into PT Assistant bot

### ISSUE THREAD

**Issue by kingokeke** [taniman/profit-trailer-enhancements#305]
Hi devs. I want to request for the ability to switch exchanges to be built into the PT Assistant bot. From the way I see it, license validation happens on PT servers, so it "should" be a simple task to have the PT Assistant update the license to change the exchange information when a switch to another exchange is requested, pretty much like the bot does when changing API keys for the license. Would be appreciative if this is given due consideration. Thank you.

**Comment by clownfish44** [comment]
This may or may not be added back but this is not a Pt bot suggestion! Please look in the discord for updates on this!
