### ISSUE TITLE
[Request] DCA calculating on movement of the price and Martingale Multiplier improvements

### ISSUE THREAD

**Issue by d1rt** [taniman/profit-trailer-enhancements#307]
The current calculation logic for each level of DCA is related to the previous average price.

![dca_current](https://user-images.githubusercontent.com/2081931/39510219-a18b895c-4df1-11e8-9f72-6a7d65bad14c.png)

I believe that each level should be calculated from the previous level of purchase and not Avg. Price

![dca_request](https://user-images.githubusercontent.com/2081931/39509672-bcef171a-4def-11e8-807b-b9f66182108d.png)

Why?

You can easily calculate the drawdown for which your settings are calculated
For example, if you set
```
DEFAULT_DCA_buy_trigger = -3.5
DEFAULT_DCA_buy_percentage = 100
DEFAULT_DCA_max_buy_times = 10
```
This means that your config is calculated for a 35% (3.5*10) price drop.
Can you easily calculate this with the current logic? Me not.

However, this is a very simple example. 

What if I want to set the levels exponentially? That is, each level will be set at different distances from the previous one (+ different buy_percentage). My brain will break while I count it from every average price.

So my suggestion is add a new DCA logic with calculating from level to level.

Also I think that current the martingale multiplier is made intricate.
How it works now:

```
DEFAULT_DCA_buy_percentage = 100
LVL 0: 50
LVL 1: 50
LVL 2: 100 ((50+50)*2)
LVL 3: 400 ((50+50+100)*2)
......
```
How it should work:

DEFAULT_DCA_buy_percentage = 100
This is *Martingale Multiplier (MM)* = 1.0
So each previous level must be multiplied by MM. **Previous level** and not a sum of ALL levels.

```
LVL 0: 50
LVL 1: 50 (LVL 0 * MM)
LVL 2: 50 (LVL 1 * MM)
LVL 3: 50 (LVL 2 * MM)
```

If you want double MM then

DEFAULT_DCA_buy_percentage = 200
This is *Martingale Multiplier (MM)* = 2.0

```
LVL 0: 50
LVL 1: 100 (LVL 0 * MM)
LVL 2: 200 (LVL 1 * MM)
LVL 3: 400 (LVL 2 * MM)
```
If you want 1.5 MM then

DEFAULT_DCA_buy_percentage = 150
This is *Martingale Multiplier (MM)* = 1.5

```
LVL 0: 50
LVL 1: 75 (LVL 0 * MM)
LVL 2: 112.5 (LVL 1 * MM)
LVL 3: 168.75 (LVL 2 * MM)
```

What are the advantages of this method?

First, this is the correct calculation of the Martingale values :)
Secondly, it's easy to set up

Instead I should make something like this (current method):

```
DEFAULT_DCA_buy_trigger_1 = -1.64
DEFAULT_DCA_buy_percentage_1 = 120
DEFAULT_DCA_buy_trigger_2 = -4.72
DEFAULT_DCA_buy_percentage_2 = 65.45
DEFAULT_DCA_buy_trigger_3 = -7.08
DEFAULT_DCA_buy_percentage_3 = 47.47
DEFAULT_DCA_buy_trigger_4 = -9.45
DEFAULT_DCA_buy_percentage_4 = 38.63
DEFAULT_DCA_buy_trigger_5 = -11.81
DEFAULT_DCA_buy_percentage_5 = 33.44
DEFAULT_DCA_buy_trigger_6 = -14.0
DEFAULT_DCA_buy_percentage_6 = 30
DEFAULT_DCA_trailing_buy = 0.1
```

I'm forced to write such a complex structure, although I just wanted to multiply all the levels by 1.2 (20%)

Thanks in advance

**Comment by NOP-Commander** [comment]
Hi d1rt,

I used to emulate your request with the current logic. It's a bit try and error but it works. To my convenience I did a simple DCA Calc spreadsheet which I uploaded onto my repo (LibreOffice file format).

https://github.com/NOP-Commander/pt-utilities

Please check and let me know if this is what you meant? Thanks!

**Comment by d1rt** [comment]
Thanks for your reply, @NOP-Commander 

Unfortunately, I can't run this file on MacOS.

I use this [configurator](https://gbot-trader.herokuapp.com/configurator) for GRID building. There is martingale calculating from buy level to buy level - not avg. price.

**Comment by d1rt** [comment]
Thanks @NOP-Commander 

I guess not exactly what I meant.

LastPrice DCA strategy:

Settings
```
DEFAULT_DCA_buy_trigger = -3.5
DEFAULT_DCA_buy_percentage = 100
DEFAULT_DCA_max_buy_times = 10
```
PT just bought a coin on DCA level 5. Do you want to quickly calculate where the last price is?
```
-3.5 * 5 = coin price dropped at 17.5%
```
In your calculator, the columns **Actual Loss of Coin** and **DCA trigger** should be equal.

If you set
```
DEFAULT_DCA_buy_trigger_1 = -1.64
DEFAULT_DCA_buy_trigger_2= -4.86
DEFAULT_DCA_buy_trigger_3 = -7.02
.........
```

This should mean that at the 3 level, the price fell by **7.02%** from the level (0) of purchase

You see?

Also I think that current the martingale multiplier is made intricate.
How it works now:

```
DEFAULT_DCA_buy_percentage = 100
LVL 0: 50
LVL 1: 50
LVL 2: 100 ((50+50)*2)
LVL 3: 400 ((50+50+100)*2)
......
```
How it should work:

```
DEFAULT_DCA_buy_percentage = 100
This is *Martingale Multiplier (MM)* = 1.0
So each previous level must be multiplied by MM. **Previous level** and not a sum of ALL levels.

LVL 0: 50
LVL 1: 50 (LVL 0 * MM)
LVL 2: 50 (LVL 1 * MM)
LVL 3: 50 (LVL 2 * MM)
```

If you want double MM then
```
DEFAULT_DCA_buy_percentage = 200
This is *Martingale Multiplier (MM)* = 2.0

LVL 0: 50
LVL 1: 100 (LVL 0 * MM)
LVL 2: 200 (LVL 1 * MM)
LVL 3: 400 (LVL 2 * MM)
```
If you want 1.5 MM then
```
DEFAULT_DCA_buy_percentage = 150
This is *Martingale Multiplier (MM)* = 1.5

LVL 0: 50
LVL 1: 75 (LVL 0 * MM)
LVL 2: 112.5 (LVL 1 * MM)
LVL 3: 168.75 (LVL 2 * MM)
```

What are the advantages of this method?

First, this is the correct calculation of the Martingale values :)
Secondly, it's easy to set up

Instead I should make something like this (current method):

```
DEFAULT_DCA_buy_trigger_1 = -1.64
DEFAULT_DCA_buy_percentage_1 = 120
DEFAULT_DCA_buy_trigger_2 = -4.72
DEFAULT_DCA_buy_percentage_2 = 65.45
DEFAULT_DCA_buy_trigger_3 = -7.08
DEFAULT_DCA_buy_percentage_3 = 47.47
DEFAULT_DCA_buy_trigger_4 = -9.45
DEFAULT_DCA_buy_percentage_4 = 38.63
DEFAULT_DCA_buy_trigger_5 = -11.81
DEFAULT_DCA_buy_percentage_5 = 33.44
DEFAULT_DCA_buy_trigger_6 = -14.0
DEFAULT_DCA_buy_percentage_6 = 30
DEFAULT_DCA_trailing_buy = 0.1
```

I'm forced to write such a complex structure, although I just wanted to multiply all the levels by 1.2 (20%)

Make sense?

**Comment by NOP-Commander** [comment]
I understand what you mean and just thought about a quick & dirty workaround until this strategy will be considered for being implemented or not. My emulation also lacks on different buy percentages and can only run double down. Well, it was worth a try at least. Happy trading!

**Comment by d1rt** [comment]
@NOP-Commander thanks for you help! Have a great profit

**Comment by clownfish44** [comment]
You listed a workaround and I think that suits this finely without any additional features being built. + this has multiple requests and is highly off topic.

**Comment by NOP-Commander** [comment]
@clownfish44 

_this has multiple requests and is highly off topic._

what is **highly** off topic? the request itself?

if this issue has multiple requests, like you wrote, @d1rt can re-open them separately, can't he?
I'll have to guess now since you didn't name them.

request 1: calculation from the previous level of purchase instead of avg. price
request 2: new calculation of Martingale Multiplier

anymore?

I'm just trying to save ideas and wanted to reassure so @d1rt can re-open them correctly if he likes to.

**Comment by d1rt** [comment]
I have re-opened each issue separately
