### ISSUE TITLE
Make DEFAULT_buy_max_change_percentage relative to 24h market change

### ISSUE THREAD

**Issue by loopy83** [taniman/profit-trailer-enhancements#308]
Hi,

DEFAULT_buy_max_change_percentage = x
DEFAULT_buy_min_change_percentage = y
and
DEFAULT_DCA_buy_max_change_percentage = x
DEFAULT_DCA_buy_min_change_percentage = y

are really strong settings for a good P&D protection... BUT!

Please make these settings relative to 24h market change.

So 24h-market-change + DEFAULT_buy_max_change_percentage = SOM criteria
So 24h-market-change - DEFAULT_buy_min_change_percentage = SOM criteria

Normally I used values aroun 7-10% for several month now using an external scirpt. I never bought a P&D again during that time. Now this great feature is integrated in PT-V2, but I think it need liilte fix.

When market is 10% up and many many coins are 8-15% up, you will send many coins to SOM. So you will miss massive bull run when buying no coins.

This request is based on personal experience since Nov'17. My external script did a VERY GOOD job so I would really appreciate this little fix for this feature.

**Comment by JDMJas0n** [comment]
I Would love to see PT have
DEFAULT_buy_max_change_percentage = 'x'
DEFAULT_buy_min_change_percentage = 'y'
DEFAULT_market_change_timeframe = 'z' minutes 

Example: DEFAULT_market_change_timeframe = 10
This would look back and calculate the change % from the last 10 minutes and adjust your PBL accordingly. 

Thanks :)

**Comment by Masterofcoinak** [comment]
I think we can close this point and refer to #19

**Comment by taniman** [comment]
use CHANGEPERCENTAGE strategy
