### ISSUE TITLE
Hide Too New Coins from PBL

### ISSUE THREAD

**Issue by pheonix727** [taniman/profit-trailer-enhancements#309]
coins that are filtered by 
pair_min_listed_days = 30 days for example
still appear in PBL and in the buy strategy it says too new to buy
they are an eye sore and disturb the GUI look , i would like them hidden from PBL

**Comment by clownfish44** [comment]
All coins which are above your min volume will be listed unless you hide them. That's just how it works as it lets users know the reason for the coin being turned off.

**Comment by pheonix727** [comment]
@clownfish44 i know it works like that, i posted this because they is where you post enhancements that you want to see, and that complaints / bugs have another page
