### ISSUE TITLE
Create Trailing Sell Percentage Drop Strategy

### ISSUE THREAD

**Issue by LyndonTree** [taniman/profit-trailer-enhancements#310]
Create Trailing Sell Percentage Drop Strategy

Look at this example of trailing Profit change due to % profit gain.

DEFAULT_trailing_profit = .75 
If 3% Profit reached the DEFAULT_trailing_profit = .70   (drops 0.05 of Default)
If 5% Profit reached the DEFAULT_trailing_profit = .65 (drops 0.1 of Default)
If 8% Profit reached the DEFAULT_trailing_profit = .45 (drops 0.3 of Default)
If 10% Profit reached the DEFAULT_trailing_profit = .35 (drops 0.4 of Default)
If 15% Profit reached the DEFAULT_trailing_profit = .15 (drops 0.60 of Default) ETC
Setting to personnal prefference....

Using this feature, it would give you a better % profit when you are at a higher gain. 
So when hitting 10% profit and then it drops, you will only drop .75% to make a sell instead of the original 2.25% = saving 1.5% profit.
This would be a better strategy for those who want to make a higher percentage for short and long-term trading. 

Comments and improvements welcome.

**Comment by clownfish44** [comment]
Already requested and accepted https://github.com/taniman/profit-trailer/issues/289
