### ISSUE TITLE
Override buy settings

### ISSUE THREAD

**Issue by oiler2112** [taniman/profit-trailer-enhancements#311]
Was thinking of some additional configs for pairs, something like:

DEFAULT_Override_pairs = 2

DEFAULT_Override_A_buy_strategy = RSI
DEFAULT_Override_A_buy_value = 19
DEFAULT_Override_A_buy_value_limit = 0

DEFAULT_Override_B_buy_strategy = EMAGAIN
DEFAULT_Override_B_buy_value = -0.99

What this 'Override' setting would do is the following:

Assuming you are at your max pairs, but a coin hits DEFAULT_Override buy settings and is still within all other limits such as balance, etc, the coin will be bought. DEFAULT_Override_pairs would be the amount of pairs allowed in addition to max_trading_pairs.

Reason for this is there are many times, when you will be at your max pairs limit, but there will be a coin you can see in your possible buy log that is well below your buy settings, but does not get bought due to being at max pairs. In this situation, i will generally go to the exchange and do a manual buy, but to have it automated would be nice.

**Comment by clownfish44** [comment]
Just increase your pairs as this will always result in buying anyways I see no improvement.

**Comment by oiler2112** [comment]
Not sure how you dont see an improvement. I set my max pairs and buy settings for particular levels, but if a coin reaches these override settings when at max pairs, I would want it to override the standard buy settings.
