### ISSUE TITLE
[Request] New Martingale calculation for DCA

### ISSUE THREAD

**Issue by d1rt** [taniman/profit-trailer-enhancements#314]
I think that current the martingale multiplier is made intricate.
How it works now:

```
DEFAULT_DCA_buy_percentage = 100
LVL 0: 50
LVL 1: 50
LVL 2: 100 ((50+50)*2)
LVL 3: 400 ((50+50+100)*2)
......
```
How it should work:

DEFAULT_DCA_buy_percentage = 100
This is *Martingale Multiplier (MM)* = 1.0
So each previous level must be multiplied by MM. **Previous level** and not a sum of ALL levels.

```
LVL 0: 50
LVL 1: 50 (LVL 0 * MM)
LVL 2: 50 (LVL 1 * MM)
LVL 3: 50 (LVL 2 * MM)
```

If you want double MM then

DEFAULT_DCA_buy_percentage = 200
This is *Martingale Multiplier (MM)* = 2.0

```
LVL 0: 50
LVL 1: 100 (LVL 0 * MM)
LVL 2: 200 (LVL 1 * MM)
LVL 3: 400 (LVL 2 * MM)
```
If you want 1.5 MM then

DEFAULT_DCA_buy_percentage = 150
This is *Martingale Multiplier (MM)* = 1.5

```
LVL 0: 50
LVL 1: 75 (LVL 0 * MM)
LVL 2: 112.5 (LVL 1 * MM)
LVL 3: 168.75 (LVL 2 * MM)
```

What are the advantages of this method?

First, this is the correct calculation of the Martingale values :)
Secondly, it's easy to set up

Instead I should make something like this (current method):

```
DEFAULT_DCA_buy_trigger_1 = -1.64
DEFAULT_DCA_buy_percentage_1 = 120
DEFAULT_DCA_buy_trigger_2 = -4.72
DEFAULT_DCA_buy_percentage_2 = 65.45
DEFAULT_DCA_buy_trigger_3 = -7.08
DEFAULT_DCA_buy_percentage_3 = 47.47
DEFAULT_DCA_buy_trigger_4 = -9.45
DEFAULT_DCA_buy_percentage_4 = 38.63
DEFAULT_DCA_buy_trigger_5 = -11.81
DEFAULT_DCA_buy_percentage_5 = 33.44
DEFAULT_DCA_buy_trigger_6 = -14.0
DEFAULT_DCA_buy_percentage_6 = 30
DEFAULT_DCA_trailing_buy = 0.1
```

I'm forced to write such a complex structure, although I just wanted to multiply all the levels by 1.2 (20%)

BTW it could be a new parameter DEFAULT_DCA_buy_multiplier
Value: Decimal >= 0

Example: DEFAULT_DCA_buy_multiplier = 1.3
This means that each DCA level will be more than the previous level in 1.3 times

**Comment by pheonix727** [comment]
i think the current version is easy to understand, 100% means double the current amount, as simple as that, 
it is also concordant with the v1 anderson doubledown, so i think people will understand it easily

**Comment by NOP-Commander** [comment]
I think it's legit to request a new strategy for DCA as it is legit to request new buy or sell strategy. Adding flexibility by making the software more configurable is an addition in value, at least for me.

**Comment by d1rt** [comment]
BTW it could be a new parameter DEFAULT_DCA_buy_multiplier
Value: Decimal >= 0

Example: DEFAULT_DCA_buy_multiplier = 1.3
This means that each DCA level will be more than the previous level in 1.3 times

**Comment by taniman** [comment]
Current logic can do this. This adds extra complexity
