### ISSUE TITLE
change to test mode from inside the GUI

### ISSUE THREAD

**Issue by pheonix727** [taniman/profit-trailer-enhancements#315]
i would like to change to testmode from inside the GUI
i'm using my bot from one pc that is running all the time for mining
and using portforwarding to look into the gui from laptop
it is hard to change back and forth between testmode and real trading because i have to go visit the other pc to do it

**Comment by Masterofcoinak** [comment]
Should be closed. Part of the roadmap
![image](https://user-images.githubusercontent.com/36849981/59028631-4f480700-885c-11e9-9470-b17e911b915b.png)

**Comment by LiamAird** [comment]
Planned
