### ISSUE TITLE
Ichimoku 

### ISSUE THREAD

**Issue by padmaCoin** [taniman/profit-trailer-enhancements#316]
Ichimoku means "to see the balance of the market at a glance",
Ichimoku is a trading system, not just an indicator, it is self-sufficient.
allow to anticipate market movements and reduce our losses.
it allows to indicate dynamically:
-short or long term market trend,
-buy signal,
-sales signal,
-the strength of the rise to invest more or less,
-future price movement,

stop loss,
take profits,
panic sell,
And even a « Super panic sell » which will allow to anticipate a major correction of the market ( make a panic sell Btc followed by a purchase in usdt) ,
it works on all time units :
-long term trades,
-daily ,
-day trading ,
-scalping,
Ideal to put the bot autonomously during an absence.

**Comment by securitygeneration** [comment]
I’d love to see some form of ichimoku in PT

**Comment by hidekin** [comment]
I would love to have ichimoku too , It's my most used indicator when I trade. 
If we could have conditions like tenkan - kijun cross up or down for buy or sell point , buy over the cloud. Extra useful indicator and one of the safest to buy .

I hope you can include ichimoku

**Comment by jafoweb** [comment]
The Ichimoku indicator works on all units of time but personally I find it gives better results for long term trades, on 4h and daily charts.
Some traders use it on small time units for day trading and even on 5 or 1mn charts for scalping.
It's all about experience, so it's best to do your own testing;)
Finally, I will end with a quote from Confusus that accompanies me every day on the markets:
"The greatest glory is not to fall, but to rise at every fall."
I wish you all good trades with Profit Trailer !

**Comment by bit4boy** [comment]
Much more than an indicator, it would help to manage our purchases and not end up with bags

**Comment by Alohalex1** [comment]
Could that really make PT the smartest bot on the market ? By reading what it's capable of I would really urge to incorporate it, everyone would win .

**Comment by bit4boy** [comment]
Perfectly agree Alohalex1

**Comment by padmaCoin** [comment]
Ichimoku Beginner pdf
https://drive.google.com/file/d/1gEZr2t-u6DdfxdwlTC9Ut5_whhIhcIJU/view

**Comment by LOLOFREDI** [comment]
yes i want it please  ichi   and one indicator volume  better than obv  or also the   "volume" exceed  the 4 or 5 last days ago or more than double,   thank

**Comment by padmaCoin** [comment]
The data showed that over the past 5-years, the indicator that performed the best on its own was the Ichimoku Kinko Hyo indicator.

**Comment by taniman** [comment]
ICHIMOKU is not an indicator the bot can support as it's a visual indicator
