### ISSUE TITLE
Alert when a expected percentage of profit would achieved.

### ISSUE THREAD

**Issue by knowngate** [taniman/profit-trailer-enhancements#32]
This could great if bot user can set a percentage of profit so user will get alert on varrious channel like telegram, etc when expected percentage is achieved.

**Comment by clownfish44** [comment]
Already exists please see MoonBot https://github.com/tulihub/PT-MoonBot There is also many milestones already for making the telegram built in to PT better which will be in the next release here https://github.com/taniman/profit-trailer/issues/546
