### ISSUE TITLE
disable config line buy mouse instead of typing #

### ISSUE THREAD

**Issue by pheonix727** [taniman/profit-trailer-enhancements#321]
hi, i edit my configs alot while testing
sometimes i have to disable 10 lines by typing a # at the beginning
i would like a box  for in the gui for every line that i can click to enable or disable a line
like a check list or something

**Comment by clownfish44** [comment]
You have to check a box or push a button on the keyboard I am not sure how this helps anyone as your still doing the same amount of work.

**Comment by pheonix727** [comment]
not the same amount of work
disable one line through keyboard will take 3 steps at least (find line with mouse > home button > # )
multiply that by 10 lines? 
why you could just find the line and click mouse, 
it sounds rediculous to code this function into the bot unless you are doing extensive settings edit
