### ISSUE TITLE
Add market change time frame condition

### ISSUE THREAD

**Issue by JDMJas0n** [taniman/profit-trailer-enhancements#323]
I would love to see PT have
DEFAULT_buy_max_change_percentage = 'x'
DEFAULT_buy_min_change_percentage = 'y'
DEFAULT_market_change_timeframe = 'z' minutes

Example: DEFAULT_market_change_timeframe = 10
This would look back and calculate the change price % from the last 10 minutes and adjust your PBL accordingly.

Thanks :)

**Comment by Masterofcoinak** [comment]
We should close this and support #19
