### ISSUE TITLE
One level of security for Exchange API keys 

### ISSUE THREAD

**Issue by cobuscoetsee** [taniman/profit-trailer-enhancements#325]
With regards to security: It would be great if we can have our Exchange API keys secured so it is not the actual API key in the text file configuration, but rather something we generate and add there, that PT can interpret. This will just add one more level of security should the VPS get hacked.  If this makes sense?

**Comment by Masterofcoinak** [comment]
Should be closed. Part of the roadmap.
![image](https://user-images.githubusercontent.com/36849981/59028488-f4161480-885b-11e9-826f-2f6099591335.png)
