### ISSUE TITLE
Exclude Test Mode bots from license usage

### ISSUE THREAD

**Issue by securitygeneration** [taniman/profit-trailer-enhancements#326]
Most license holders can run 2 bots per license. At the moment that includes any bots you run in test/paper trading mode. It would be nice if we could run bots in test mode without consuming a license slot, thereby reserving the two available slots for live trading bots. Since we can't properly backtest, this would allow us to test several strategies against the live market.

**Comment by clownfish44** [comment]
https://github.com/taniman/profit-trailer-enhancements/issues/280 this issue I explained how to do this. This is also not a feature request!
