### ISSUE TITLE
buy and limit for selling over PAIRS and DCA

### ISSUE THREAD

**Issue by arthurengeletrica** [taniman/profit-trailer-enhancements#327]
Not an issue, but I suggest to have an option to have a range to sell on indicators, like for exemple, sell only with emaspread -0.01 to -1, because I would like to sell when emaspread becomes negative

**Comment by Masterofcoinak** [comment]
This is meanwhile implemented and each indicator has a value_limit (range).
Should be closed.

**Comment by Masterofcoinak** [comment]
Should be closed

**Comment by Masterofcoinak** [comment]
Since 2.3.4 Fix: buy_value_limit logic. When a buy_value and buy_value_limit is set it now works as a range.
