### ISSUE TITLE
DEFAULT_DCA_rebuy_timeout_1 ? 

### ISSUE THREAD

**Issue by pheonix727** [taniman/profit-trailer-enhancements#329]
i would like the first couple of DCA buys to have a lower timeout than the remaining DCA
say i want the first 2 to have a timeout of 5 minutes, then the remaining DCA to have a 30 minute timeout

**Comment by Masterofcoinak** [comment]
Rebuy timeouts can be DCA Level specific. Should be closed.

**Comment by Masterofcoinak** [comment]
Why not closed? Reduce the amount of enhancements to focus on the needed ones!
