### ISSUE TITLE
Trigger & Settings for Rise/Drop per Market & Coin

### ISSUE THREAD

**Issue by conando2000** [taniman/profit-trailer-enhancements#33]
Especially for non feeder users would be nice to have the possibility to define thresholds for BTC rise/drop trend and then change buy/sell strategy settings based on that, also for the trend percentage per coin maybe?

Something like this:

```
### BTC TREND OVER 5% = RISE // UNDER -5% = DROP ###
ALL_market_rise_trigger = 5
ALL_market_drop_trigger = 5

### PER COIN TREND OVER 10% = RISE // UNDER -10% = DROP ###
ALL_coin_rise_trigger = 10
ALL_coin_drop_trigger = 10

ALL_buy_value = -1.0
ALL_market_rise_buy_value = -0.5
ALL_market_drop_buy_value = -0.75
ALL_coin_drop_buy_value = -1.5

```

**Comment by clownfish44** [comment]
This has already been requested here https://github.com/taniman/profit-trailer-enhancements/issues/19
