### ISSUE TITLE
Stop Loss in DCA

### ISSUE THREAD

**Issue by ochiengj** [taniman/profit-trailer-enhancements#331]
Please give us the option to stop loss in DCA regardless of DCA level. At the moment if we have our max dca set to 7 for example, the bot has to dca 7 times before it will stop loss. By this time it may be too late in the negative and cause a huge loss that the user did not want,  also the dca bag may be too big. Makes dca stop loss difficult to use. 

Maybe something like: DEFAULT_stop_loss_use_max_dca = false

It would be great for the user to have that option to decide to stop loss dca at any level regardless of dca times. We can decide if we set a  stop loss to -4.0 it should work even though my max dca times has not reached.

Thanks guys.

**Comment by Masterofcoinak** [comment]
https://wiki.profittrailer.com/doku.php?id=dca_config#dca_stop_before_complete
Should be closed
