### ISSUE TITLE
Show Limit sell order / pending log Sale in the sales page

### ISSUE THREAD

**Issue by pheonix727** [taniman/profit-trailer-enhancements#332]
i want pairs that has been in the pending log to be shown in the sales log once sold

**Comment by Mikeeetrue** [comment]
+Telegram notification
Just sold: XVGBTC
Sell strat: PENDING LOG
Cost: 0.00131544
Rate: 0.00000504
Profit: 1.00%
Profit BTC: 0.00001303

**Comment by Masterofcoinak** [comment]
Should be canceled. Cancel pending triggers can now always be used.
