### ISSUE TITLE
Normalise MACD on a scale of 0 to 100

### ISSUE THREAD

**Issue by DomsterKB** [taniman/profit-trailer-enhancements#337]
Currently the MACD indicator is not very usable across multiple coin pairs when the price between pairs varies greatly.  For example the buy_value of XLMBTC will require precision of 8 decimal places 0.00000012.  Compare this to BCCBTC, it will require a precision of 5 decimal places 0.00012.   Due to these differences, comparing the two will not be the same when it comes to determining a good buy/sell point.

Therefore, we need to normalise the buy_value similar to the other indicators like RSI or STOCH which use a value between 0 to 100.  Or can be zero based like -1 to 0 to 1 like EMASPREAD.  To do this we can express MACD as a percentage of price:

MACD line:
100 * (MACD_fast_length - MACD_slow_length) / Close

MACD signal line:
100 * (MACD_signal (days) EMA of MACD Line) / Close

MACD histogram:
100 * (MACD Line - Signal Line) / Close

Or we can express it as a percentage of one of the Moving Averages by replacing Close with EMA.

The strength of PT is in its ability to scan the entire market using its suite of indicators with MACD being the exception.  MACD currently only seems useful for single target pairs and cannot be used broadly to find good pairs across the entire market.  Normalising the buy_values should fix this.

**Comment by angelsomar** [comment]
You can always customize the sell Value for the Pair

DEFAULT_D_buy_strategy = MACD
DEFAULT_D_buy_value = 0.0000002
DEFAULT_D_buy_value_limit = 0

BCC_D_buy_value = 0.00012
XLM_D_buy_value = 0.00000002

Well then it would cost more to graph it to determine if the bot is working well

**Comment by robheath90** [comment]
This would be excellent if implemented. As angelsomar has mentioned, in order to have appropriate signals I have had to set specific MACD prices for each coin. This is fine for a small number of coins, but when looking at MACD over the whole market it greatly reduces it's effectiveness.

**Comment by taniman** [comment]
MACDPERCENTAGE is now a normalized MACD
