### ISSUE TITLE
Max PBL Pairs Setting

### ISSUE THREAD

**Issue by Stogy** [taniman/profit-trailer-enhancements#338]
Ability to dynamically set max pairs in PBL. Say 30, 20 or 10 pairs etc.
Top 20 pairs based on top 20 volume data at any given time say every 60 minutes or some other defined time span.
max_pbl_pairs = 20 for instance.
This helps to populate the **Possible Buy Log** to a number of pairs you are comfortable with and will adjust as the market ebbs and flows based on volume ranges.
This keeps you in the game when overall market volumes drop and out of troubled pairs when overall volume rises.

**Comment by taniman** [comment]
TOPX coins has been implemented for min buy volume
