### ISSUE TITLE
Pending and Cancel Pending in %

### ISSUE THREAD

**Issue by moondust2010** [taniman/profit-trailer-enhancements#339]
Simple Request, lets move the Bag Coin in Pending and get him out if the in a good Way....

we like to have 

DEFAULT_pending_order_percent = -8
DEFAULT_cancel_pending_trigger = 1

if you dont have the Coin in Pairs again, the old DEFAULT_combined_cancel_pending_trigger = dont do any action. With the 2 new Values, you can move the coin easy to pending and back

**Comment by Masterofcoinak** [comment]
should be closed
