### ISSUE TITLE
Log min/max of traded coins especially DCA for metrics

### ISSUE THREAD

**Issue by conando2000** [taniman/profit-trailer-enhancements#34]
Especially for configuring a somehow sustainable stoploss it would be great to have some more data in the log or at least the sales log - would be great to see what the maximum and minimum values of a coin were while in DCA during "normal operations".

Would give a good indication to what value stoploss could be set to catch the "bad apples" while not triggering too often while everything works well.

**Comment by clownfish44** [comment]
A changing stop loss is already part of PTFeeder / PTMagic which their integration has been requested here https://github.com/taniman/profit-trailer-enhancements/issues/19
