### ISSUE TITLE
Allow PT to keep trailing even if it drop below the original trailing price

### ISSUE THREAD

**Issue by B0mBeur** [taniman/profit-trailer-enhancements#341]
I'm using this as sell strategies.

DEFAULT_DCA_A_sell_strategy = GAIN
DEFAULT_DCA_A_sell_value = 1

DEFAULT_DCA_B_sell_strategy = RSI
DEFAULT_DCA_B_sell_value = 68

As you know RSI rarely cross over 68. I think that you should have a way to force trailing whenever all strategies become true at the same time. Every time the price of a pair drop below the starting trailing price the trailing stop. If the RSI value moved below my RSI trigger, PT will not try to trail this pair again and there is 70% chance that the pair will drop and never sell.

Maybe we could have a new parameter for each sell strategy or something generic that force PT to trail when all the sell strategies or buy strategies become true

Something like this to apply to every strategies

DEFAULT_DCA_trailing_force = True

Or this to apply to only one stragy

DEFAULT_DCA_B_trailing_force = True

And something like this to prevent trailing from dropping too far.

DEFAULT_DCA_trailing_loss = -0.55

I hope that i'm clear... Sorry for my bad english...

**Comment by Masterofcoinak** [comment]
It should be closed.
Use https://wiki.profittrailer.com/doku.php?id=pairs.properties#default_trailing_stop_loss_trigger_arm
or https://wiki.profittrailer.com/doku.php?id=pairs.properties#default_take_profit_safety_arm
