### ISSUE TITLE
Support for TrueUSD (TUSD) market

### ISSUE THREAD

**Issue by NOP-Commander** [taniman/profit-trailer-enhancements#344]
Dear all,

Binance will list TrueUSD on 18th of May.
https://support.binance.com/hc/en-us/articles/360003892832-Binance-Will-List-TrueUSD-TUSD-on-2018-05-18

So the possibility of trading in this market is maybe some fellow customers (like me) would like to see. Maybe not in short-term, as the will be three trading pairs only in the beginning, but mid-term would be cool.

yours sincerely,
NOP-Commander

**Comment by angelsomar** [comment]
Binance the ready as a couple of work but not as a Base market

by design this pair always goes in the opposite trend to the btc

TUSDBTC

**Comment by NOP-Commander** [comment]
@clownfish44 Since Binance didn't introduce TUSD as a market on its own this issue can be closed.

**Comment by Masterofcoinak** [comment]
Other main currencies as stable coins can be used meanwhile. It can be closed.
