### ISSUE TITLE
DCA Rebuy Enhancement by Trigger / DCA_DAILY_max_buy_times

### ISSUE THREAD

**Issue by magpies88** [taniman/profit-trailer-enhancements#348]
Dear PT Team!

Could we have triggers for the rebuy timeouts just like you have done with the percentages?  This would be incredibly powerful in my opinion.

Please see example

DEFAULT_rebuy_timeout = 0

EXAMPLE 1
#THIS WILL SET A DIFFERENT TIMEOUT PER EACH DCA TRIGGER#

DEFAULT_DCA_rebuy_timeout_trigger_1 = 15 (mins) Aggressive
DEFAULT_DCA_rebuy_timeout_trigger_2 = 15 (mins) Aggressive
DEFAULT_DCA_rebuy_timeout_trigger_3 = 30 (mins) Moderate
DEFAULT_DCA_rebuy_timeout_trigger_4 = 60 (mins) Moderate
DEFAULT_DCA_rebuy_timeout_trigger_5 = 120 (mins) Conservative
DEFAULT_DCA_rebuy_timeout_trigger_6 = 180 (mins) Conservative
DEFAULT_DCA_rebuy_timeout_trigger_7 = 360 (mins) Conservative

EXAMPLE 2
#THIS WILL SET A DIFFERENT TIMEOUT PER EACH DCA TRIGGER#

DEFAULT_DCA_rebuy_timeout_trigger_1 = 15 (mins) Aggressive
DEFAULT_DCA_rebuy_timeout_trigger_2 = 15 (mins) Aggressive
DEFAULT_DCA_rebuy_timeout_trigger_3 = 30 (mins) Moderate
DEFAULT_DCA_rebuy_timeout_trigger_4 = 1440 (mins) ******Forces bot to wait a day******
DEFAULT_DCA_rebuy_timeout_trigger_5 = 15 (mins) Agressive
DEFAULT_DCA_rebuy_timeout_trigger_6 = 15 (mins) Aggresive
DEFAULT_DCA_rebuy_timeout_trigger_7 = 30 (mins) Moderate

This has alot of advantages.

- Allows the DCA to be aggressive in the early triggers and catch those quick market swings

- Later triggers get more conservative and still give you benefit of a longer timeout to protect you from any nasty market turns, and getting you a better position overall.

- Forces the bot too watch the market before executing longer after each trigger!

Thanks for your consideration!

Much appreciated!

**Comment by magpies88** [comment]
another way to get at least some functionality or benefit from this would be something like..

DEFAULT_DCA_max_buy_times = 10
DEFAULT_DCA_DAILY_max_buy_times = 3 (throttles DCA to 3 times over a 24h period)

so in this example.

DCA 3 times in a day
DCA timeout for 24hrs
DCA enabled
DCA 3 times in a day

etc etc

**Comment by Masterofcoinak** [comment]
Rebuy timeouts can be DCA Level specific. Should be closed.

**Comment by Masterofcoinak** [comment]
Why not closed? Reduce the amount of enhancements to focus on the needed ones!

**Comment by taniman** [comment]
already possible
