### ISSUE TITLE
Saving & Applying Multiple Strategies From A Panel 

### ISSUE THREAD

**Issue by knowngate** [taniman/profit-trailer-enhancements#35]
It would be good if user just select the defined strategy graphically. Algo .
Users r not so experts abt that.

**Comment by Circumvenscion** [comment]
Agreed, adding a GUI panel to select strategies would be great. Being able to save different strategies and easily switch between them (with a dial or something) would be very nice.

**Comment by rsdaltx** [comment]
Plus one on this issue. It's difficult to maintain and switch between different strategies using config files.

**Comment by iAmVaeVictus** [comment]
Agree. The bot needs to get smarter and react to the market.

**Comment by clownfish44** [comment]
@iAmVaeVictus this is shearly for saving different configs and being able to switch with a switch if your looking for something that reacts to the market see https://github.com/taniman/profit-trailer-enhancements/issues/19

**Comment by knowngate** [comment]
Thanks all.
If strategies r saved, this can be a new feature that we can assign strategies to coin so when ever bot start trade with any coin , automatically strategy assign to that coin may get active.
Just a thought.

**Comment by knowngate** [comment]
Add feature of back testing with the coin to it.
Time span, Number of trade, waiting time between Number of trade.

**Comment by knowngate** [comment]
Hey !!
Clownfish44 is the same user from Profit Trailer Tracker team. 😅

**Comment by clownfish44** [comment]
https://github.com/taniman/profit-trailer/issues/1044
