### ISSUE TITLE
Request Variable DEFAULT_DCA_Max_Cost_Percentage

### ISSUE THREAD

**Issue by hargate** [taniman/profit-trailer-enhancements#350]
Request new variable "DEFAULT_DCA_Max_Cost_Percentage".

The "DEFAULT_DCA_Max_Cost" is one of the only PT variables left that does not have a percentage component. Realistically, I would prefer to set my DEFAULT_DCA_Max_Cost at a percentage, so that it constantly adjusts as my total current value (TCV) changes.

Currently, it is one of the only PT variables that must be manually changed with increase/decrease of TCV.

Thank you for your consideration of this request.

**Comment by dhollings** [comment]
I'd like to upload this to Google Spreadsheets (I'm a Mac user) but it is rejected and I'm not sure why.  I've never had a Google spreadsheet upload rejected.  If you could figure out if this is possible, then both MAC and PC users might benefit from your gallant work!  

https://docs.google.com/spreadsheets

**Comment by hargate** [comment]
@dhollings 
I assume that it is a little too much for Google Docs. There are thousands of global variables, tens of thousands of calculated fields, and dozens of macros. Happy to discuss on Telegram, as to not be rude to the PT team. 

https://web.telegram.org/#/im?p=@crypto_tools

**Comment by Thndr** [comment]
I would like to second this feature request. When managing a bot with it's initial buys set to a percentage of the TCV it doesn't make sense to limit DCA's max cost to a static value rather than a percentage of the TCV.
Having it as a percentage option would allow more accurate management of DCA bags without constat manual intervention.

**Comment by taniman** [comment]
already implemented
