### ISSUE TITLE
PT OBV implementation is unsatisfactory

### ISSUE THREAD

**Issue by Puppytherapy** [taniman/profit-trailer-enhancements#351]
Dear PT Devs,

i have been looking into many ways how to utilize your implementation of the OBV indicators. In its core the indicator is supposed to just tell us if volume is increasing or not.

Let me quote your wiki: 

> "OBV for PT is calculated as the difference between the first volume amount captured (from OBV_length periods), and the signal candle (from OBV_signal), in percentage."

So basically i select two random candles with a "random number generator" and compare volume. Since there is almost zero correlation my comment to this implementation would be: 

> "The Current PT OBV implementation is just like getting run over by a car and a bus 10 times in a row after drinking bad beer."

Would it be possible to enhance the behavior to something useful like calculating the average volume over the OBV_length periods and compare it to the OBV_signal candle. Giving us the opportunity to actually see if OBV_signal is above of below averagu thus rising or falling.

Thank you and hope you will consider this "enhancement".
Kind Regards
Puppy

**Comment by taniman** [comment]
The OBV works the same as the OBV on TradingView The volume is an accumulation of volumes over the perido you specified
