### ISSUE TITLE
NEW TRADING STRATEGY: Add Heikin-Ashi (extremely effective TA indicator)

### ISSUE THREAD

**Issue by CryptoCapo** [taniman/profit-trailer-enhancements#352]
![image](https://user-images.githubusercontent.com/39453300/40276528-99cd20f8-5bda-11e8-8a6c-5bba7c21aeba.png)

Reposting a closed post from aycanurun because I strongly recommend Heikin-Ashi gets incorporated into Profit Trailer. The Trading View V2 strategy below is a great example and puts up very solid profit % from strategy testing in Trading View.  

Heikin-Ashi would be a great feature to add to the TA strategies, and has been historically popular with FOREX trading bots and would work just as well with crypto. 

Heikin-Ashi is a Japanese strategy (Research it!) that restructures the candles to show AVERAGE price over time periods instead of opening/closing prices. This strategy allows traders to follow trends, and can be quite effective when combined with other trending indicators like MACD. It can work well for both shorter and longer periods depending on configuration.

//@Version=2
//Heikin Ashi Strategy V2 by breizh29

strategy("Heikin Ashi Strategy V2",shorttitle="HAS V2",overlay=true,default_qty_value=1000,initial_capital=100000,currency=currency.EUR)
res = input(title="Heikin Ashi Candle Time Frame", type=resolution, defval="60")
hshift = input(1,title="Heikin Ashi Candle Time Frame Shift")
res1 = input(title="Heikin Ashi EMA Time Frame", type=resolution, defval="180")
mhshift = input(0,title="Heikin Ashi EMA Time Frame Shift")
fama = input(1,"Heikin Ashi EMA Period")
test = input(1,"Heikin Ashi EMA Shift")
sloma = input(30,"Slow EMA Period")
slomas = input(1,"Slow EMA Shift")
macdf = input(false,title="With MACD filter")
res2 = input(title="MACD Time Frame", type=resolution, defval="15")
macds = input(1,title="MACD Shift")

//Heikin Ashi Open/Close Price
ha_t = heikinashi(tickerid)
ha_open = security(ha_t, res, open[hshift])
ha_close = security(ha_t, res, close[hshift])
mha_close = security(ha_t, res1, close[mhshift])

//macd
[macdLine, signalLine, histLine] = macd(close, 12, 26, 9)
macdl = security(ha_t,res2,macdLine[macds])
macdsl= security(ha_t,res2,signalLine[macds])

//Moving Average
fma = ema(mha_close[test],fama)
sma = ema(ha_close[slomas],sloma)
plot(fma,title="MA",color=lime,linewidth=2,style=line)
plot(sma,title="SMA",color=red,linewidth=2,style=line)

//Strategy
golong = crossover(fma,sma) and (macdl > macdsl or macdf == false )
goshort = crossunder(fma,sma) and (macdl < macdsl or macdf == false )

strategy.entry("Buy",strategy.long,when = golong)
strategy.entry("Sell",strategy.short,when = goshort)

**Comment by DragonBtc93** [comment]
Oh hell yeah please bring this.

**Comment by But4ler** [comment]
@taniman No news for support this type of candle ?

**Comment by taniman** [comment]
@But4ler You know how this works. User's vote and then we see what enhancements we will implement. The enhancement game is currently going and we will pick winner at the end of the month

**Comment by taniman** [comment]
Heiking Ashi candles are now supported. But we won't build this whole strategy
