### ISSUE TITLE
Please Create separate parameters for all Strategies in Indicators config

### ISSUE THREAD

**Issue by CryptoCapo** [taniman/profit-trailer-enhancements#353]
The ability to leverage multiple strategies in PT is hindered by the fact that many of the Indicator parameters are shared by different Indicators! As an example, STOCHRSI uses the following parameters:

RSI_candle_period
RSI_length
STOCH_length

Which are also shared by RSI, and STOCH. That means I cannot configure multiple Indicator strategies with different wavelengths/sensitivities. This is just one example of many, Please create separate Indicator parameters for each indivdual Indicator!

It would also be helpful to expand the depth of some of these indicators, (SMA period vs EMA or KAMA) and K% and D% parameters.

**Comment by Masterofcoinak** [comment]
Indicators can be labeled and have now their own indicators. Can be closed
