### ISSUE TITLE
DCA cleanup script

### ISSUE THREAD

**Issue by ScottEAdams** [taniman/profit-trailer-enhancements#354]
https://gitlab.com/TradeFlu/PT-DCA-Digger

I made a little open source python script for helping to clear out DCA if required. Its nothing complicated and loosely based on @grantcause recommendations in #pt-default-settings . Feel free to add it to useful resources. Happily accepting pull requests for improvements if people want to start getting clever with trailing etc.

**Comment by angelsomar** [comment]
Interesting could you explain the logic?
