### ISSUE TITLE
Wiki Enhancement: Install Java 8 Ubuntu

### ISSUE THREAD

**Issue by pheonix727** [taniman/profit-trailer-enhancements#358]
i was having trouble while installing java 8 on ubuntu 14 , following your wiki steps it installs jdk 7
ubuntu 16 also sometimes intalls 9  or 10

so the steps in this case are : 
Installing the Oracle JDK
If you want to install the Oracle JDK, which is the official version distributed by Oracle, you will need to follow a few more steps.

First, add Oracle's PPA, then update your package repository.

sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
Then, depending on the version you want to install, execute one of the following commands:

Oracle JDK 8
This is the latest stable version of Java at time of writing, and the recommended version to install. You can do so using the following command:

sudo apt-get install oracle-java8-installer

source:
https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-get-on-ubuntu-16-04

**Comment by LiamAird** [comment]
The wiki has since been updated with information regarding java8
