### ISSUE TITLE
Manual Trading Mode

### ISSUE THREAD

**Issue by pheonix727** [taniman/profit-trailer-enhancements#359]
Sometimes i want to use the bot to trade manually
to trade manually effectively this is what i have in mind
I would like the bot to buy or trail buy at certain support and resistance levels that i will specify myself
##################################################
QLCBTC_A_Buy_Strategy = Pair_Value
QLCBTC_A_Buy_Value = 0.00002152
QLCBTC_A_Buy_Value_Limit = 0.00002001
QLCBTC_Trailing_Buy = 0.2

QLCBTC_DCA_A_Buy_Strategy = Pair_Value
QLCBTC_DCA_A_Buy_Value_1 = 0.00002001
QLCBTC_DCA_A_Buy_Value_Limit_1 = 0.00001950
QLCBTC_DCA_A_Buy_Value_2 = 0.00001950
QLCBTC_DCA_A_Buy_Value_Limit_2 = 0.00001900
QLCBTC_DCA_Trailing_Buy = 0.2

QLCBTC_A_Sell_Strategy = Pair_Value
QLCBTC_A_Sell_Value = 0.00002252
QLCBTC_A_Sell_Value_Limit = this would be ridiculous :laughing: but maybe someone has a use for it
QLCBTC_B_Sell_strategy = GAIN
QLCBTC_B_Sell_value = 1.0
QLCBTC_Trailing_Profit = 0.2

QLCBTC_DCA_A_Sell_Strategy = Pair_Value
QLCBTC_DCA_A_Sell_Value = 0.00002251
QLCBTC_DCA_A_Sell_Value_Limit = this would be ridiculous :laughing: but maybe someone has a use for it
QLCBTC_B_Sell_strategy = GAIN
QLCBTC_B_Sell_value = 1.0
QLCBTC_DCA_Trailing_Profit = 0.2

![screenshot_11](https://user-images.githubusercontent.com/38658320/40450124-fb72ded0-5eda-11e8-8de8-5e2328522c7e.png)

**Comment by Masterofcoinak** [comment]
I like this idea.

**Comment by bvebve** [comment]
Yes, would be great !!

**Comment by Masterofcoinak** [comment]
I think we can close this cause of the fixed-price strategy

**Comment by Masterofcoinak** [comment]
Should be closed. Fixedprice strategy and formula can let you do it as above explained.
