### ISSUE TITLE
Feature request customizable monitor

### ISSUE THREAD

**Issue by richardsizemore** [taniman/profit-trailer-enhancements#36]
Feature request customizable monitor

It would be useful to customize the monitor on the web GUI interface.
Maybe even add charts. 

Current chart of your progress could be useful or a chart indicating what the bot is looking for in current market conditions.  

This could be useful in making  adjustments.

**Comment by clownfish44** [comment]
Charting and graphs have already been requested here https://github.com/taniman/profit-trailer-enhancements/issues/5
