### ISSUE TITLE
buy change percentage for an the last hour

### ISSUE THREAD

**Issue by jimmyjimmyv** [taniman/profit-trailer-enhancements#360]
Could we have the buy change percentages for the last hour in addition to the last 24? or, maybe an additional line like DEFAULT_min_hour_change.. this way we could filter by volume, then by pairs that have a minimum last hour change.  Like if I only wanted to buy a pair with 600 volume and the price is +1 for the last hour..

**Comment by pheonix727** [comment]
HELL YEAH !!!

**Comment by Masterofcoinak** [comment]
Totally agree, but already requested #19. Please support there.

**Comment by taniman** [comment]
CHANGEPERCENTAGE strategy
