### ISSUE TITLE
Allow a negative MACD to guess the uptrend

### ISSUE THREAD

**Issue by js8749** [taniman/profit-trailer-enhancements#362]
Hello,

It would be posible that if i have a buying trigger of MACD and i put it in negative like -0.000000002 it start trailing from that value to positive.

**Comment by DragonBtc93** [comment]
We should have this for all indicators.

**Comment by Masterofcoinak** [comment]
Close this and support #569.

**Comment by taniman** [comment]
could possibly use strategy levels, other than that trailing logic won't change as it traisl the price
