### ISSUE TITLE
Market buy

### ISSUE THREAD

**Issue by DragonBtc93** [taniman/profit-trailer-enhancements#364]
Please give us the option to buy at market price. That way it will always fill our order and not get the order book is low. I am trading in and out of one coin with a large amount.

**Comment by Masterofcoinak** [comment]
This would be really nice. I have to set so many parameters in PT, that it is for sure buying.

**Comment by DragonBtc93** [comment]
Yeah for people that are playing with larger amounts this is really needed.

**Comment by DragonBtc93** [comment]
I'm getting so sick of not getting buys because the order book is low. Come on guys please make it so I can turn on market buy.

**Comment by Masterofcoinak** [comment]
Can be closed.
https://wiki.profittrailer.com/doku.php?id=dca.properties#default_dca_min_orderbook_price_slippage_percentage

**Comment by Masterofcoinak** [comment]
Should be closed!!!
