### ISSUE TITLE
 Pending Log sales in Sales Log and Telegram

### ISSUE THREAD

**Issue by Mikeeetrue** [taniman/profit-trailer-enhancements#365]
It will be super useful if PT allows to track sales from Pending Log (both in sales log and telegram).
There is no reason for not having this feature.

**Comment by Masterofcoinak** [comment]
This is a must in my opinion. I hate that the summary in PTN "/all" doesnt shown all items and a wrong TCV.

**Comment by Vicentewnunes** [comment]
This is why some of my friends gone to another bot, so they can leave order in the book and the bot recognize it. But hopefully this will be implemented in 2.1!!

**Comment by Masterofcoinak** [comment]
This should be closed, as it is possible now to send every coin to pairs/DCA when a trigger is reached.
https://wiki.profittrailer.com/doku.php?id=dca.properties#default_dca_combined_cancel_pending_trigger
https://wiki.profittrailer.com/doku.php?id=dca.properties#default_dca_cancel_pending_trigger
