### ISSUE TITLE
Allow indicator trailing including direction

### ISSUE THREAD

**Issue by SanderGith** [taniman/profit-trailer-enhancements#366]
Hey Elroy,

Since we have pt v2 we have a load of new indicators, which are a great improvement. Thanks for that!

At the moment I am working on using those indicators but I am missing something that would greatly help in improving the accuracy of the indicators. Especially the momentum ones.

One of the things that I am trying to achieve is to create a buy strategy using STOCH. But same goes for RSI and other indicators. For now let's stick with STOCH for the example.

When a coin loses momentum the STOCH will pretty fast move downwards to the 20 and below area. Once it's below 20 you can tell PT to buy the coin. The challenge however is, that you don't want to buy a coin while the momentum is moving down. Like we've seen past weeks it can actually take a while, STOCH stays below 20 and the price grinds down further. What I would like to do however is to be able to configure a indicator trailing before letting the indicator signal TRUE as it's buy (or sell) signal.

In the example of STOCH I would not prefer to buy a coin that has a stoch below 20 for instance. I rather buy a coin where can see that the momentum is turning. For STOCH that would be buying when it is value 20, but when it has been 10 before that. So if stoch reaches 10, pt would start 'indicator trailing' and monitor if it's going up to 20 before giving the TRUE signal to buy.

How would that be possible, For instance by having something like this in a config:

**Buy using STOCH indicator**
DEFAULT_A_BUY_STRATEGY          = STOCH 

**Start indicator trailing/looking at STOCH when it reaches 10**
DEFAULT_A_BUY_VALUE_TRIGGER = 10        

**Buy when STOCH reaches 20**
DEFAULT_A_BUY_VALUE                 = 20       

**Stop looking to buy when STOCH reaches 30** 
DEFAULT_A_BUY_VALUE_LIMIT       = 30       

**the next one is optional as you could deduct direction from trigger vs value, 
but it could make it more clear for users**
DEFAULT_A_INDICATOR_TRAILING_DIRECTION = UP  

**This would be next level and is still a rough idea in my mind. It would be:
Only buy when it goes from 10 to 20, but not if it goes to 18 and then 
goes back down to 12 (which would indicate a "weaker" momentum)**
DEFAULT_A_INDICATOR_TRAILING = 5

This is all focussed on STOCH of course, just to give an example. But personally I would love to have something similar for most of the indicators. Basically you just trail in 2 segments, first the indicators and afterwards the price. Just to give some examples: I would rather buy RSI at 30 while it moved there from 20 instead of just RSI having the value of 30 or less, as it is now.

I will attach a chart with indications of the added accuracy that would be added and unnecessary buys (false positives) that could be avoided

I really hope you like this idea :-)

Cheers,

Sander

ps if you have questions or want to discuss it further you know where to find me ;-)

![image](https://user-images.githubusercontent.com/33983565/40671478-45b3822a-636c-11e8-8773-2e44042b58a8.png)

**Comment by SanderGith** [comment]
Sorry about the markup, apparently github does something with brackets

**Comment by pheonix727** [comment]
yes , it is one of the feature we all want,
i think trailing by value is easier to code than trailing direction

**Comment by Masterofcoinak** [comment]
I think an update of yours would be good as part of them are already implemented
