### ISSUE TITLE
[Feature Request] Bags Dilution Strategy (split big bags into small bags)

### ISSUE THREAD

**Issue by But4ler** [taniman/profit-trailer-enhancements#368]
Already, thanks for your great work!

Is it possible to add a bag dilution function to PT.

Youtubeur Patrick Bier proposes a really not bad method
* [Video 1](https://www.youtube.com/watch?v=FpjgYEA970E)
* [Video 2](https://www.youtube.com/watch?v=V2Fi99p7XWg)
* [PTD: Explanation in detail](https://www.indiegogo.com/projects/ptd-profit-trailer-zero-losses-dilution-add-on-youtube-software--2/x/18825187#/)

Excel file allowing calculations as an attachment
[Bag_Dilution_Spreadsheet_V1.03.xlsx](https://github.com/taniman/profit-trailer-enhancements/files/2055164/Bag_Dilution_Spreadsheet_V1.03.xlsx)
[Bags_Spreadsheet_Cell_Description_V1.03.pdf](https://github.com/taniman/profit-trailer-enhancements/files/2055165/Bags_Spreadsheet_Cell_Description_V1.03.pdf)
[PCW_Dilution_Strategy_Steps_V1.03.pdf](https://github.com/taniman/profit-trailer-enhancements/files/2055166/PCW_Dilution_Strategy_Steps_V1.03.pdf)

I think integrating such a function into PT would allow:
* A solution when the DCA still can not resell a pair after several DCA
* Increased portfolio turnover by gradually releasing the bags
Bref
* To drastically increase the profitability of the bot by killing the bags little by little

**Comment by echthard** [comment]
I think I have an easier idea to dilute.

Just park the bag in a Pending sell order at at least break even or some profit.
Then let PT buy the coin with all the existing buy functionality. (No need for changes here, this already exists)
Then let PT sell the coin with all the existing functionality. (Again no changes needed)
When the sell is done, remember the profit and you can lower the Pending order or show in a seperate column what amount has been "recovered". When this amount exceeds the loss of that coin, then the User can sell the coin with that loss, but now it's not really a loss anymore.

**Comment by echthard** [comment]
In the UI, let the user choose a coin to dilute or auto-dilute via settings (DEFAULT_dilute_trigger = -40). 

Then the bag goes into Pending log or a seperate tab Dilutions. If it is in Pending, then it should be marked with an icon or something to show that it's in dilution. If it is in a seperate tab, then you have the possibility to show other / more data. 

All sells for that coin will be shown in the Sales log (marked with an icon). Those sells will also be shown in the Dilution tab when you click on a pending order bag. The sells will fold out and a total could be shown. So you'll see the total loss of the bag minus the total profits of the sells. Also the Pending order should be cancelled everytime after a sell and a new price should be calculated and PT should place a new Pending order. So you can see that the P% is less than before the sell.

I hope things are clear, if not let me know.

**Comment by securitygeneration** [comment]
@echthard This sounds like what the Spanish Cross strat allows you to do now?

**Comment by Masterofcoinak** [comment]
Should be closed. Part of the roadmap.
![image](https://user-images.githubusercontent.com/36849981/59029529-cbdbe500-885e-11e9-8772-4374361a3c23.png)
