### ISSUE TITLE
Separate Sell Triggers for Positive Percentage

### ISSUE THREAD

**Issue by PT-Shamba** [taniman/profit-trailer-enhancements#369]
Just a thought for possible future addition to the bot...
Some do percentage based accumulation (aka DCA) but also percentage based decumulation (selling percentages above positive)
For example you could have:
DEFAULT_DCA_sell_trigger_1 = 2 (for +2% profit)
DEFAULT_DCA_sell_trigger_2 = 4 (+4%)

DEFAULT_DCA_sell_percentage_1 = 25
DEFAULT_DCA_sell_percentage_2 = 35

In doing this somehow you could sell part of a heavy DCA bag on the way up, so you gain a percentage of profit without risking the entire thing falling back into negative status, and at the same time still being able to let the remainder of the bag continue to make gains in the hope that a future sell percentage would be obtainable, i.e.- a final sell percentage of say +10%
Doing this would also ensure that you have at least reached a break-even point of your buy amounts while still making possible higher gains.

Example:
You go throughout all of the above, and since you sold 60% of your total amount, according to the above example, you could theoretically regain 100% of your initial purchase amount while the rest can make higher gains without risking the entire amount being tied up in a further negative decline.

This also has the benefit of regaining balance that can be used by the bot for further DCA purchases.
I hope this is at least considered.

**Comment by Masterofcoinak** [comment]
#320 Maybe you like this idea too

**Comment by Thndr** [comment]
I would like to second the call for a feature that allows partial/multiple sales per a pair.
With how things are currently I can see it being a toggle to switch between DCA buying and selling in the settings, but if they can work things out maybe it can allow for both DCA buys/sells at the same time.

**Comment by Masterofcoinak** [comment]
#552 is the same, but with more up votes. We should close this one.

**Comment by ArmchairGuru** [comment]
if there is a similar one, close it.
