### ISSUE TITLE
Buy option for minimum/maximum trend trigger per coin

### ISSUE THREAD

**Issue by conando2000** [taniman/profit-trailer-enhancements#37]
Would be nice to have an option in pairs to define a max/min trend value that a coin has to have for the trend indicator to be considered for a buy.

For example don't jump into any coin with a trend less than -10% ...

**Comment by clownfish44** [comment]
This is already part of PTFeeder / PTMagic which has been requested to be added here https://github.com/taniman/profit-trailer-enhancements/issues/19
