### ISSUE TITLE
Different indicators for different coins

### ISSUE THREAD

**Issue by DragonBtc93** [taniman/profit-trailer-enhancements#370]
Don't know if there is already a way to do this but I would like to have different coins using different indicator settings. 
something like this

ONT_SMA_cross_candles = 2
ONT_SMA_candle_period = 300
ONT_SMA_fast_length = 2
ONT_SMA_slow_length = 5

**Comment by Masterofcoinak** [comment]
Should be closed
https://wiki.profittrailer.com/doku.php?id=dca.properties#default_dca_a_buy_strategy_label
