### ISSUE TITLE
Graph for a coin with strategy on it

### ISSUE THREAD

**Issue by jokaorgua** [taniman/profit-trailer-enhancements#371]
Would be great to have graph of a coin when it is pressed with strategy lines on it. Will be no need to go to TradingView and set various strategy indicators, time frames etc.

**Comment by Masterofcoinak** [comment]
This would be a great pro feature (or PRO+) or an own subscription.......
For this PT could cooperate with below Tradingview adopters:
https://github.com/smoochy/WolfsOfCrypto/wiki/About-the-TradingView-Script
https://github.com/ptstratx/ptstratx
