### ISSUE TITLE
DCA Coin Limit

### ISSUE THREAD

**Issue by carllewis1980** [taniman/profit-trailer-enhancements#373]
Can you put a limit on how many coins can go into DCA.

This will mean they will sit in pairs until a space in DCA becomes available.

This will enable you to set much tighter buy parameters and not have to worry about the bot not buying coins for a while as it will already have a coin purchased ready to bring into DCA

**Comment by Masterofcoinak** [comment]
Should be closed.
https://wiki.profittrailer.com/doku.php?id=dca.properties#dca_max_trading_pairs
