### ISSUE TITLE
DCA dullution

### ISSUE THREAD

**Issue by Jeripimo** [taniman/profit-trailer-enhancements#374]
Situation:
coin XXX -40%  buy cost $250,-
Idea:
To prevent a huge amount of your budget to spend for DCA this coin, a way to put a percentage of part only of this coin in DCA.
After DCA a number of times for this particular coin it will be eventually sold.
After this, the next part of the XXX -40% wil be put in DCA.
This going on until the complete coin is sold via DCA

**Comment by Masterofcoinak** [comment]
I like every idea to reduce the size of bags. #320 Maybe you like this too.

**Comment by Masterofcoinak** [comment]
Should be closed. Part of the roadmap.
![image](https://user-images.githubusercontent.com/36849981/59029529-cbdbe500-885e-11e9-8772-4374361a3c23.png)

**Comment by Masterofcoinak** [comment]
![image](https://user-images.githubusercontent.com/36849981/59037482-a3111b00-8871-11e9-8e97-a73ec50116a0.png)
