### ISSUE TITLE
[Request] Detection of pump & dump coin via averaging trade volume over periods

### ISSUE THREAD

**Issue by kkkoay** [taniman/profit-trailer-enhancements#376]
Currently, PT has the DEFAULT_MIN_BUY_VOLUME to filter low volume coins but this has an issue. When a coin Pump & Dump (P&D), the volume will be high and PT cannot identify the coin is in P&D stage and proceeded to buy in and trail upward towards the cliff and got stuck in huge bag when dumping.

To allow PT to detect a P&D coin, PT needs 2 sets of average buy volume over daily/hourly periods to replace the exiting DEFAULT_MIN_BUY_VOLUME. Preferably a configurable period just like the INDICATORS. One average for fast and one average for slow, so that the slow will show the average volume over a longer period of time and fast for average volume over shorter period of time. 

With these 2 fast and slow average volume numbers, genuine high volume coins will be able to maintain the a high volume number over the slow average volume and P&D coins will not. Instead P&D coins can be detected by PT via low volume number over the slow average volume when it is in P&D mode with the following scenarios:
- Fast average period: 2 - 12 hours or 1 - 2 day
- Slow average period: 720 hours or 30 days
- Genuine high volume coin: 
   1. Fast average volume: high volume number
   2. Slow average volume: high volume number
- Pump and Dump coin:
   1. Fast average volume: high volume number
   2. Slow average volume: low volume number

With these 2 average volume, PT can filters out the P&D coins or ride the wave. Currently PT is unable to distinguish a normal high volume coins vs a P&D coin and got into bagging situation. With low volume and bagging, we all know how hard to get out of the situation.

Hope this enhancement helps to move PT one step closer to be even better by able to avoid P&D coins or ride the P&D wave with additional settings to control how many entry/entries per P&D coin before got burned. This can be done by adding additional property for a coin to indicate this coin is in P&D mode.

**Comment by diablocody** [comment]
THIS PLEASE. BEEN SAYING IT FOR AGES.

**Comment by Masterofcoinak** [comment]
Totally agree, but already requested #19. Please support there.

**Comment by m4xson** [comment]
Not sure if 19 will ever be addressed after 18 months so perhaps in the meantime we can get these small features added.

**Comment by taniman** [comment]
added for 2.5.0
