### ISSUE TITLE
Allow for more flexible strategies by moving indicators to pairs&DCA files

### ISSUE THREAD

**Issue by alex050478** [taniman/profit-trailer-enhancements#377]
How about getting rid of indicators file and specifying it in the pairs files like this:

DEFAULT_A_buy_strategy = EMASPREAD
DEFAULT_A_buy_value = 0.05
DEFAULT_A_EMA_candle_period = 14400
DEFAULT_A_EMA_fast_length = 8
DEFAULT_A_EMA_slow_length = 55

DEFAULT_B_buy_strategy = EMACROSS
DEFAULT_B_buy_value = 0.05
DEFAULT_B_EMA_candle_period = 3600
DEFAULT_B_EMA_fast_length = 2
DEFAULT_B_EMA_slow_length = 6
DEFAULT_B_EMA_cross_candles = 1
etc. 

This would allow for more flexibility in crating strategies.

**Comment by Masterofcoinak** [comment]
https://wiki.profittrailer.com/doku.php?id=pairs.properties#default_a_buy_strategy_label
Should be closed
