### ISSUE TITLE
Buying start trailing in negative to positive in all indicators.

### ISSUE THREAD

**Issue by js8749** [taniman/profit-trailer-enhancements#378]
Hello, 

I suggest that we could use negative values in buying indicators.

Example using MACD in -0.00000001 its only buys at that value, it would be good that its start trailing from negative to positive in buying strategy.

The main idea is the we could use negative values in the indicator for buying and it trails from negative to positive, because if we use a negative value in an indicator and it goes up or positive the bot will not buy.

**Comment by Masterofcoinak** [comment]
Close this and support #569.

**Comment by taniman** [comment]
I am sure this is not the case anymore with all different logics
