### ISSUE TITLE
Do not buy higher than last sellprice for x days

### ISSUE THREAD

**Issue by Skeptain** [taniman/profit-trailer-enhancements#379]
Once in a while my bot sells at a specific price where the coins will stay around even for days sometimes. But I want to prevent buying in at the same price or even higher by such an option. Since the sales log is saved for 7 days with default options I think it would be reasonable to be able to prevent the bot buying higher for 7 days compared to the last sellprice saved in the sales log.

I think it should be easy to implement cause the bot just needs to compare the current price with the sales log. The days could be configured by the days of the sales log.

**Comment by taniman** [comment]
LASTSELL strategy could possibly be used for this
