### ISSUE TITLE
EMA CROSS as a selling strategy

### ISSUE THREAD

**Issue by jfrias1333** [taniman/profit-trailer-enhancements#38]
It would be nice to have the ability for the bot to sell coins when they have crossed the indicated emacross in the indicators file. This alone or in combination with Sell Strategy= Gain would prevent the bot from selling early.

**Comment by Circumvenscion** [comment]
Came here to suggest the same thing. Would love an EMACROSS sell strategy! Yes please!

**Comment by swanfield1979** [comment]
Would love this aswell!

**Comment by clownfish44** [comment]
Already been requested and added to the next milestone here https://github.com/taniman/profit-trailer/issues/370
