### ISSUE TITLE
BNB Trading

### ISSUE THREAD

**Issue by bencairns** [taniman/profit-trailer-enhancements#380]
Why not trade BNB on Binance but have a feature built into PT to hold a certain amount of BNB for fees, excluding them from trading

**Comment by Masterofcoinak** [comment]
A kind of coin specific keep balance. Nice idea

**Comment by bencairns** [comment]
wasnt thinking of it as a base trading coin. its a good performer, be nice to trade it against eth or btc when the opportunity arises without messing with a small balance for fees.

**Comment by niroshana35** [comment]
I also Vote for @bencairns idea, It'll be very useful to have BNB to trade against BTC or ETH since it gets good gains these days, while keep an small amount of BNB as a reserve for binance fees and No need to have BNB as the Base coin because BTC or ETH is performing best as the base coin.

**Comment by flybuzz** [comment]
I was about to create the same new post, I think people have been asking this over and over again for the past couple of months. Binance is world's largest exhange and BNB is gaining incredible amount of gain and popularity. I can only imagine what BNB price could be in a few years. I tried using BNB as its own market but does not work well as liquidity is thin. However under BTC/ETH/USDT market, trading BNB works very well. We are leaving lots of money on the table not be able to trade BNB as PT is not designed to trade it under those markets. Please figuer out a solution for this it will be worth it for everyone.

**Comment by flybuzz** [comment]
This might already be accepted https://github.com/taniman/profit-trailer/issues/496 but not sure when it will be implemented. It's the same feature.

**Comment by LiamAird** [comment]
This is already possible with Default_reserve_amount. Please read the wiki entry here: 
http://wiki.profittrailer.com/doku.php?id=pairs.properties#default_reserve_amount
