### ISSUE TITLE
DCA INITIAL & MOST RECENT purchase Date/Time

### ISSUE THREAD

**Issue by hoffer49** [taniman/profit-trailer-enhancements#382]
I have noticed that each time an additional bag of coins is purchased in DCA, the date/time it purchased the additional bag replaces the initial purchase date/time. Perhaps it would be more beneficial to keep the INITIAL purchase date/time and add an additional column that has the MOST RECENT purchase date/time OR you could just IGNORE the MOST RECENT purchase date/time.

**Comment by Masterofcoinak** [comment]
Should be closed
![image](https://user-images.githubusercontent.com/36849981/58371031-2c565280-7f40-11e9-9bcb-39b5d26c1c9a.png)
