### ISSUE TITLE
"LAST-IN | FIRST OUT" Technology (optional) for DCA SELLS of LAST BAG FIRST!

### ISSUE THREAD

**Issue by MAXPROPHET** [taniman/profit-trailer-enhancements#383]
**_Example:_** You have 4 bags of Tron. **Currently,** the only option I am aware of for selling DCA BAGS is **[YOU SELL ALL BAGS OF TRON]** once it reaches a GAIN of some programmed %. Say 1st Bag: 3.33% ; 2cnd Bag: 6.66% ; 3rd Bag: 9.99% ; 4th Bag: 18.98% and once the coin has gone back up at least 19.89% + GAIN - you sell for profit.

What **MY IDEA PROPOSES:** [is **_THE ABILITY TO SELL BAG #4 FOR PROFIT_**] "while still holding the other 3 Bags." So exposure in DCA is reduced further. To do this, I propose a [CONTAINER] such as Container_1 (or) of that fashion be implemented.

HERES' THE EXAMPLE CODE: MAKING POSSIBLE TO INDIVIDUALLY SELL CONTAINER(S) [DEEPER BAGS]   FIRST!             (Last in, First out-Technology) I liken this to a: "Deepening DCA RubberBand Strat."

[ DCA.PROPERTIES FILE ]

DEFAULT_DCA_max_cost = 0
DEFAULT_DCA_max_buy_times = 4
DCA_keep_balance = 0.0
DCA_keep_balance_percentage = 10
#
DEFAULT_DCA_A_buy_strategy = ANDERSON
DEFAULT_DCA_B_buy_strategy = RSI
DEFAULT_DCA_B_buy_value = 10
DEFAULT_DCA_C_buy_strategy = EMACROSS
DEFAULT_DCA_C_buy_value = -0.01
DEFAULT_DCA_C_buy_value_limit = -10
DEFAULT_DCA_trailing_buy = 0.2
#
DEFAULT_DCA_C_TRIGGER_1_CONTAINER_1 = 3.33
DEFAULT_DCA_C_TRIGGER_1_CONTAINER_1_BUY_PERCENTAGE_1 = 100
DEFAULT_DCA_C_TRIGGER_1_CONTAINER_1_sell_strategy = GAIN
DEFAULT_DCA_C_TRIGGER_1_CONTAINER_1_sell_value = 1.5
DEFAULT_DCA_C_trailing_profit_CONTAINER_1 = 0.2
#
DEFAULT_DCA_D_TRIGGER_2_CONTAINER_2_BUY_TRIGGER_2 = 6.66
DEFAULT_DCA_D_TRIGGER_2_CONTAINER_2_BUY_PERCENTAGE_2 = 50
DEFAULT_DCA_D_TRIGGER_2_CONTAINER_2_sell_strategy = GAIN
DEFAULT_DCA_D_TRIGGER_2_CONTAINER_2_sell_value = 2.5
DEFAULT_DCA_D_trailing_profit_CONTAINER_2 = 0.2
#
DEFAULT_DCA_E_TRIGGER_3_CONTAINER_3_BUY_TRIGGER_3 = 9.99
DEFAULT_DCA_E_TRIGGER_3_CONTAINER_3_BUY_PERCENTAGE_3 = 33.333
DEFAULT_DCA_E_TRIGGER_3_CONTAINER_3_sell_strategy = GAIN
DEFAULT_DCA_E_TRIGGER_3_CONTAINER_3_sell_value = 2.5
DEFAULT_DCA_E_trailing_profit_CONTAINER_3 = 0.2
#
DEFAULT_DCA_F_TRIGGER_4_CONTAINER_4_BUY_TRIGGER_3 = 18.98
DEFAULT_DCA_F_TRIGGER_4_CONTAINER_4_BUY_PERCENTAGE_3 = 25
DEFAULT_DCA_F_TRIGGER_4_CONTAINER_4_sell_strategy = GAIN
DEFAULT_DCA_F_TRIGGER_4_CONTAINER_4_sell_value = 3.33
DEFAULT_DCA_F_trailing_profit_CONTAINER_4 = 0.2
#
DCA_orderbook_profit_calculation = true
DEFAULT_DCA_max_profit = 13

With warmest regards to the profit trailer team.
MaximumProphets
Archie N. Johnson, III
Florida, USA

**Comment by Masterofcoinak** [comment]
#320 We have more or less the same idea

**Comment by MAXPROPHET** [comment]
LoL and we should both be rewarded for our efforts in explaining why it is needed 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Masterofcoinak** [comment]
maybe we can close this and focus on 1. #568

**Comment by taniman** [comment]
you can use the priority logic to decide which pairs should go first and alsomax dca pairs
