### ISSUE TITLE
Limit order slippage to ensure higher fill rates

### ISSUE THREAD

**Issue by mehtadone** [taniman/profit-trailer-enhancements#385]
In some scenarios, I would like to ensure that I receive the highest fill ratio as possible. As we place limit orders on the exchange, a better price that we send on the order will always be used to fill. 

What I suggest is a slippage factor on the buy and sell orders. 

`DEFAULT_buy_price_slippage = 0.1`

This would mean we would send a limit price to the exchange, 0.1% over the price that the buy strategies indicates we have reached and the conditions to buy are true. 

`DEFAULT_sell_price_slippage = 0.1`

This would mean we would send a limit price to the exchange, 0.1% lower than the price that the sell strategies indicate we have reached, and the the conditions to sell are true.

**Comment by Masterofcoinak** [comment]
https://wiki.profittrailer.com/doku.php?id=pairs.properties#default_min_orderbook_price_slippage_percentage
Should be closed
