### ISSUE TITLE
BBWIDTH buy strategy

### ISSUE THREAD

**Issue by mrdan89** [taniman/profit-trailer-enhancements#386]
Hi, Could we please have an option to buy when the BBWIDTH value is larger than the specified value instead of lower than the specified value? 

The idea in that is i would like to buy at LOWBB, but would like to aim to TP at the top of the BB, with at least a certain gain %. E.g. Width is 6% of price of the coin, i would risk -3% stop loss for a 6% take profit.

Thank you.

**Comment by DomsterKB** [comment]
I have added an issue which will provide this ability to change the way we compare values for all strategies including BBWIDTH.

https://github.com/taniman/profit-trailer-enhancements/issues/389
