### ISSUE TITLE
[DCA Implementation] Make the Coin-Specific Unnumbered Sell Value Outrank All Default Sell Values

### ISSUE THREAD

**Issue by goferit** [taniman/profit-trailer-enhancements#387]
Please see https://user-images.githubusercontent.com/8900109/41502780-10f1e054-7190-11e8-90ea-c4ce239bb147.png

**Comment by taniman** [comment]
this can be done by disabling the sell strategy and using a new strategy that does not have all the levels with a different letter

**Comment by taniman** [comment]
We will experiment with it in 2.5.0 beta testing see if it does not cause problems
