### ISSUE TITLE
Options for creating limit sell orders instead of stop loss and using different sell values than the ones defined in the GAIN's strategy sell_value

### ISSUE THREAD

**Issue by stefangabos** [taniman/profit-trailer-enhancements#388]
#### New option 

`DEFAULT_pending_sell_value`

When set, the bot would use this value when creating the limit sell order instead of the existing `GAIN` strategy's _sell_value_.

#### New option

`DEFAULT_pending_trigger`

This would work exactly like `DEFAULT_stop_loss_trigger` but instead of selling the coins at a loss it would instead create a  limit sell order using the aforementioned `DEFAULT_pending_sell_value` or, if option is not set, the existing `GAIN` strategy's _sell_value_.

Just as with `DEFAULT_stop_loss_trigger`, the `DEFAULT_pending_trigger` kicks in only after `DCA_max_buy_times` has been reached.

> If `DEFAULT_stop_loss_trigger` is enabled that would have priority over `DEFAULT_pending_trigger`!

**Comment by Masterofcoinak** [comment]
already solved. See
https://wiki.profittrailer.com/doku.php?id=pairs.properties#default_pending_gain_percentage
