### ISSUE TITLE
Provide two-way comparison operation for evaluating buy_value and sell_value

### ISSUE THREAD

**Issue by DomsterKB** [taniman/profit-trailer-enhancements#389]
Currently, PT is restricted to one-way comparisons for evaluating strategies.  Lets use RSI as an example.  Quoting from wiki:

"This buy/sell strategy is true when the RSI value is less than or equal to the buy_value or is greater than or equal to the sell_value."

So instead of just comparing RSI is less than or equal to buy_value, it will be beneficial to compare RSI greater than or equal to buy_value.  Vice versa for sell_value, to have RSI less than or equal to sell_value.

Adding this ability to all indicators will provide an extra dimension in determining a good buy/sell signal.  Lets use RSI again as an example.  So if we could use RSI value is greater than or equal to buy_value of 30, we could start buying a coin which was just considered oversold and on the uptrend.  And for the sell strategy, if we could use RSI value is less than or equal to sell_value of 70, we could be selling right at the peak of the uptrend before it dips.  Couple this ability with multiple indicators will make PT so much more powerful.

An example on how we can implement this in the pairs file for buy:

DEFAULT_A_buy_strategy = RSI
DEFAULT_A_buy_operator =
```
gt (greater than) or
lt (less than) or
gte (greater than equal to) or
lte (less than equal to)
```
DEFAULT_A_buy_value = 30
DEFAULT_A_buy_value_limit = 0

An example for sell:

DEFAULT_A_sell_strategy = RSI
DEFAULT_A sell_operator = same options as buy above
DEFAULT_B_sell_value = 80

The same method applies for DCA.

**Comment by vandijkict** [comment]
Is this function not implemented yet? This would be great

**Comment by Masterofcoinak** [comment]
https://wiki.profittrailer.com/doku.php?id=pairs.properties#default_a_buy_strategy_direction
I think that's what you want

**Comment by Masterofcoinak** [comment]
Should be closed.
