### ISSUE TITLE
Stop Loss after Maximum DCA Buy Times

### ISSUE THREAD

**Issue by pheonix727** [taniman/profit-trailer-enhancements#390]
hi i would like to use stop losses,
my problem is that stop losses are % based
and that forces me to use a DCA strategy that is based on % (trigger)
so if i set stop loss to = -2
i have to set dca trigger to = -1.8
but i can't set a dca strategy that uses indicators
if i set
dca_a_buy_strategy = lowbb 
dca_a_buy_value = 10
my stop loss might be triggered before i reach dca buy value
my pair my have to drop to -3% to reach this lowbb

so i would like to set stop losses after i reach max dca buy times

**Comment by stefangabos** [comment]
as the [documentation](https://wiki.profittrailer.com/doku.php?id=dca.properties#default_dca_stop_loss_trigger) states, the stop loss triggers only after the bot can't DCA anymore

**Comment by Masterofcoinak** [comment]
This isn't an issue anymore
https://wiki.profittrailer.com/doku.php?id=dca.properties#dca_stop_before_complete
