### ISSUE TITLE
Reverse DCA ~ Double up ~Leverage

### ISSUE THREAD

**Issue by pheonix727** [taniman/profit-trailer-enhancements#391]
wouldn't it be cool to double up and buy the pair again if it is in a winning streak?
like for example
my pair is now +1.5 and going up, i would like to buy the pair again , and trigger the buy pair at 1% for example, then sell the whole lot when my sell trigger is hit,
#####
that is like doubling the profits

**Comment by taleeto** [comment]
Yes, I agree.

It is also known as Pyramid buying.

**Comment by CryptosWORLD** [comment]
yes there are many request if you filter by dca or short
https://github.com/taniman/profit-trailer-enhancements/issues?utf8=%E2%9C%93&q=dca
https://github.com/taniman/profit-trailer-enhancements/issues?utf8=%E2%9C%93&q=short

its time i think dev do something about

**Comment by Masterofcoinak** [comment]
Positive DCA is already possible. Should be closed.
