### ISSUE TITLE
Automatically Buy A Stablecoin when BTC goes up

### ISSUE THREAD

**Issue by chillz561** [taniman/profit-trailer-enhancements#392]
say every time your trading pair increases a certain amount the bot will buy a certain amount of TUSD or USDT

**Comment by clintperry15** [comment]
+1

**Comment by padmaCoin** [comment]
+1

**Comment by GarrettFleischer** [comment]
+1

**Comment by Masterofcoinak** [comment]
#363 Request already existing. It should be closed.
