### ISSUE TITLE
LOWBB Sell

### ISSUE THREAD

**Issue by Luceid7** [taniman/profit-trailer-enhancements#393]
Hello, I'd like to request a feature to sell on LOWBB. Currently, there is no feature to allow for "riding the bands" (riding a trend until it falls below a specific BB threshold). I tried to emulate this using a HIGHBB sell with a sell value limit, but failed to realize that sell value limit was not a thing for HIGHBB. Could this feature be added? Would be very useful, thanks.

**Comment by Luceid7** [comment]
Consider the following screenshot:
![example](https://user-images.githubusercontent.com/36316714/42457568-c8ec818c-8365-11e8-994d-cd582168470f.PNG)
Wouldn't you want to sell this coin when it falls below that final trend line, not when it goes above it right at the start? If I try to use HIGHBB to sell, it will sell at the start of the trend as it goes over the HIGHBB line, if I sell at the end when it falls below the trend line, I will have made a lot more money :) This is called" riding the bands" where you ride a trend that is following a bollinger band line, until it falls below it. This is what LOWBB sell would accomplish.

**Comment by Masterofcoinak** [comment]
Possible meanwhile
![image](https://user-images.githubusercontent.com/36849981/58370884-527af300-7f3e-11e9-9ea3-95a0dbded651.png)
Should be closed
