### ISSUE TITLE
Cross Value Pending Buy value

### ISSUE THREAD

**Issue by pheonix727** [taniman/profit-trailer-enhancements#394]
i would like to place a pending buy value at the price level that the indictor crossed
or at the price level * multiplier factor
for example
cross happened at 0.000456
i would like to set at pending buy at 0.000456 or
at 0.000456 * 1.003 (0.3% price increase)
***************************************************
setting buying at cross candle = 1
you've already missed all the profits
![screenshot_13](https://user-images.githubusercontent.com/38658320/41946600-9dffb446-79b3-11e8-9920-46bc3f6e63c2.png)
lines
pink = sma 3 candles
red = sma 6
blue = sma 15
black = sma 30
as you can see
buying at early crosses ( sma3 , sma 6) is risky
buying at late cross (sma 15 , sma 30 ) is too late, the bot would buy after the end of the move
so i would like to set a pending buy order at the cross price , in hopes that the price is still fluctuating and that i can scalp some profits

**Comment by taniman** [comment]
Bot  does not do pending buy orders.
