### ISSUE TITLE
Automate short trading

### ISSUE THREAD

**Issue by xandorlv** [taniman/profit-trailer-enhancements#395]
It would be great if you could somehow integrate into PT the sort trading for the case when instead of having main pair profit we want to multiply altcoin.

**Comment by angelsomar** [comment]
A management system for my portfolio

**Comment by mddr123** [comment]
+1

**Comment by echthard** [comment]
I think it's more in line with PT to have "succesfull shorts (buys)" next to "succesfull longs (sells)". 

So PT just needs to remember what the amount and the bought_price (or the P%) and were, when selling. When it buys back, it should buy back exactly the same amount (costs less BTC), so you'll end up with the same amount of that alt coin, the same percentage of loss or gain (P%) and some extra BTC. 

That's just the same when we have a sell, we end up with the same conditions as before the buy, but with some extra BTC. This extra BTC is the profit and can even go in the Sales log, or the Buy log needs to have a Profit column.

**Comment by echthard** [comment]
Other option is to look at the DCAs individually. DCAs themself can be in the green (GAIN), while all buys combined for a coin can be in the red (LOSS). It's an option to just sell those that are still making profit and then only buy in lower. So if a coin price goes up, then more DCAs will turn green and become available to sell at a profit. Or if the coin price goes down, then you the new DCA will buy at a better price.

**Comment by xandorlv** [comment]
Other way is for PT to remember the total cost in base currency. Once you as a user decide to go short PT will be looking for entry in short, and once the price is good to buy PT should buy amount equal to the total cost in base currency. This way user will multiply the coins which also reduce avg.price.

Actually short could have 2 modes: 'Multiply coins' and 'Get Profit' (see proposal from @echthard).

**Comment by becikas** [comment]
+1

**Comment by clippart** [comment]
+

**Comment by aloox356** [comment]
+1

**Comment by Masterofcoinak** [comment]
I think #264 already has this in a better visual explanation

**Comment by Masterofcoinak** [comment]
Should be closed. See comment above.
