### ISSUE TITLE
[Strategy request] - MACDCROSS strategy - Buy at the crossovers

### ISSUE THREAD

**Issue by RabiiKessis** [taniman/profit-trailer-enhancements#396]
The actual MACD strategy uses the histogram data only, which makes it impossible to trigger buy orders at the crossover points.
My idea is about creating a MACDCROSS strategy and make it work like EMACROSS, where the buy zone becomes true when the MACD line crosses over the signal line. 
Then we can decide wether to buy on the exact crossover, or trail for an extra increase (the increase maybe calculated in satoshies based on the histogram data, or calculated in spread percentage, just like EMASPREAD).
Would be nice if you implement this feature, as it allows for a wide number of buying opportunities that could be narrowed down when combined with other indicators.

**Comment by fletch63** [comment]
+1, I would love to see a MACD_cross_candles option.

**Comment by iller75** [comment]
Would this be when the macd and signal line crosses the macd histogram zero line? As seen on the image, if so yes please!
![bild](https://user-images.githubusercontent.com/10998221/81510044-46cf3a80-930f-11ea-9464-75dac0e51fed.png)
