### ISSUE TITLE
[Feature request] - TradingView extention

### ISSUE THREAD

**Issue by RabiiKessis** [taniman/profit-trailer-enhancements#397]
Hello,
I suggest adding an extention/feature to allow external signals from TradingView to trigger buy/sell orers.
This would be a great alternative to all the missing strategies/indicators we want to see implemented in PT.
There are so many useful scripts out there we want to use to handle our trades.
Thank you.

**Comment by LiamAird** [comment]
This has been implemented, check out: 
https://profittrailer.com/product/pt-tradingview-integration/
