### ISSUE TITLE
[Exchange request] - Bitmex for leverage trading

### ISSUE THREAD

**Issue by RabiiKessis** [taniman/profit-trailer-enhancements#398]
Hello,

I suggest adding bitmex licence so we can automate leverage trading.
My ultimate wish is to automate my trades on Bitmex with PT, along with a feature/extention on PT to allow external signals from TradingView, 
This would be great if you make it happen.

Thank you.

**Comment by raenrfm** [comment]
Please add Bitmex, if you did this people would be buying PT in droves.

**Comment by LiamAird** [comment]
Bitmex has been added as an exchange.
