### ISSUE TITLE
New Coins on Exchanges Notification

### ISSUE THREAD

**Issue by Uruwashii** [taniman/profit-trailer-enhancements#4]
When new coins are listed on an Exchange the ability to notify us - as most coin price drops when listed we then take necessary action.  If trading on all pairs. Auto included or exclude option?

**Comment by clownfish44** [comment]
Already exists https://github.com/CryptoGnome/Community-Tools/tree/master/ProfitTrailer-Tools/Binance-Auto-Blacklist

**Comment by ACETyr** [comment]
Doesn‘t that have a milestone already?

**Comment by clownfish44** [comment]
https://github.com/taniman/profit-trailer/issues/261
