### ISSUE TITLE
Pair_HODL_Enabled = true & A HODL Section 

### ISSUE THREAD

**Issue by LeaderOfChampions** [taniman/profit-trailer-enhancements#40]
When a coin is placed into Watchmode it would be nice if it didn't count against your total pairs, have its own section to view and not count towards your ALL_min_buy_balance_percentage.

This way you can HODL coins and still monitor them while not impacting the BOT.

Would still want it to show and count in your total portfolio value on the Monitoring Tab.

**Comment by iAmVaeVictus** [comment]
Or, it would be nice to mark coins as "held" but still be able to trade around those held coins without having to create a sell order on the exchange to "trick" it.

**Comment by securitygeneration** [comment]
Related to #96?

**Comment by CousinEddie** [comment]
+1

**Comment by SAMI3711** [comment]
that option would be great!

**Comment by juato4** [comment]
Hope this win and #264
