### ISSUE TITLE
Prevent notification flood

### ISSUE THREAD

**Issue by ivzakirov** [taniman/profit-trailer-enhancements#400]
Some notification flood reducing system should be implemented. I got too many api error notifications (see attached picture). This message flood started May 2018 and still annoying me.  And I can't do anything with this. What about this scheme:
**not more than 1 (specific) message per X minutes,**
**not more than 2 (specific) messages per Y minutes,**
**not more than 3 (specific) messages per Z minutes.**
_Default values for X = 5, Y = 15, Z = 60._

![tg-nf](https://user-images.githubusercontent.com/3755954/42360551-ed258c2a-8102-11e8-8b34-4ab8ceb58dda.png)

**Comment by stefangabos** [comment]
A simple solution would be to always double the time between everything the notification but only if the previous notification was the same as the one that is about to be sent.

For example, 
- sending first notification
- after x minutes sending the notification again
- after x*2 minutes sending the notification again
- after x*4 minutes sending the notification again
- after x*8 minutes sending the notification again
...and so on

**Comment by taniman** [comment]
We send less notifications these days.
