### ISSUE TITLE
NEW IDEAS

### ISSUE THREAD

**Issue by Fit50s** [taniman/profit-trailer-enhancements#401]
I was directed by discord to post this idea here, please forward to appropriate department or send me a link as to the right department to paste idea ! Thanks !
 
Some new settings that may be beneficial!
PAIRS US$ BALANCE: TOTAL 60K INVESTMENT WITHOUT HAVING TO CHANGE BTC VALUE IN PT ! 

I have been trying out different settings on a Test bot and thought that having a US$ balance would be a benefit, logic behind this:
1)    If purchased 10BTC @ 6K = 60k, you can then allocate $20K to Pairs and allocate $40K to DCA, when the price of BTC increase, rather than have your per pair value increase the pair value will always stay the same.

Eg : 10 pairs allocating 33.3% to pairs = 3.33 BTC divide by 10 = .333 BTC per pair @ $6K  = US$1998. 
When the value of BTC increase so does the amount per pair! BUT

If you had a set US$ value the per pair cost will always stay the same at US$1998 therefore your set investment in the bot will always be $60K and no more!
The idea also why BTC should be converted into US$ rather than trading USDT, is that the value of BTC will increase over time comparing that to USDT , and the value of BTC held in the bot also appreciates!
IN SUMMARY:

If the BTC value increased to $12k you will need to keep adjusting all the BTC values to keep your investment value at $60K! If you had set US$ values then anything over $60K is profit and can be withdrawn back into fiat or increase your investment from $60K to $70K to decrease the size of any bags and then readjust back to $60K once your bags have been cleared!
PAIRS FOLDER
US$_use_balance = 20,000
The Same for DCA FOLDER
US$_use_balance = 40,000

TOTAL INVESTMENT $60K AND NO MORE !
SETTING SWITCH :

In DCA I have 20 different levels of DCA GAIN, once a coin has been DCA X amount of times the % gain value changes from 5% down to .15%. 
I have 20 settings for a bear market, 20 settings for a neutral market and 20 settings for a Bull market. Every time I need to change from bear to bull I have to # tag 20 lines (bear) and then un # 20 lines (bull). 
It would be great if you can set up a switch that each individual settings can go under so we only need to # tag 1 line rather than 20 ! 

Look forward to any feed back

**Comment by Fit50s** [comment]
I came up with the idea because every time the value of BTC goes up or down so does your investment value. If you can convert to US dollars as value but use BTC to transact then your investment will always be X amount of dollars and if BTC goes down and the BOT is trying to buy it will come up as insufficient funds. The only thing that needs to be noted is the buy value of BTC when it was bought so you can gauge your profit or lose !

**Comment by taniman** [comment]
Basically letting the bot do the work for you.  I think it's better to jsut switch to USDT market though you would not be accumulating BTC anymore
