### ISSUE TITLE
Improvements on Layout

### ISSUE THREAD

**Issue by felipeqga** [taniman/profit-trailer-enhancements#402]
Hi, 
I would like on menu bar, for example in PAIRS to appear all three stages.
1- Number of pairs Properly said (BLUE): Ja exist
2- Number of pairs where they are in TRUE (GREEN): Add
3- Number of pairs that are waiting for "Trailing" (RED): Add
See this picture:
[https://image.ibb.co/iixqrd/Screenshot_2018_07_06_21_18_44.png](url)
[https://ibb.co/jOFMxJ](url)
Second:
I would like on menu bar, for example new Menu "BUY" that 
That contain records such as:
1- Indicator values at the time of purchase.
Ex:
  RSI: BSL, BST, BSV
  EMACROS: BSL, BST, BSV
  BTC price at the time of purchase.
Thank you in advance

**Comment by LiamAird** [comment]
Will bring too much clutter to the view.
