### ISSUE TITLE
Trailing Profits w/ STOCH Modifier

### ISSUE THREAD

**Issue by RchGrav** [taniman/profit-trailer-enhancements#405]
**If STOCH is an indicator which follows the momentum of a price movement why not make STOCH a form of modifier to the trailing value.**
TRAILING = TRAILING*((VARIABLE+80-STOCH)/100) or 0 Whichever is greater
user supplied variable of 0 to 100

When price movement has additional velocity allow for additional trailing tolerance by increasing the trailing value.

**Comment by taniman** [comment]
possible with dynamic logic
