### ISSUE TITLE
Do not average pending orders

### ISSUE THREAD

**Issue by milanl71** [taniman/profit-trailer-enhancements#406]
As agreed on Discord with Elroy  - opening this enhancement request here.

I would like that the bot doesn't average prices in pending order. Would prefer that every coin which gets moved to the pending order list doesn't get averaged with already existing bag. So, each and every trade to be treated separately. 

Please see below for more details.

Copy from Discord:
_Milan - Today at 11:50
I am using the "Pending Order Wait Time" option and would love that the bot doesn't average the bags.
Should be an easy implementation as additional option, so anybody can use which one he prefers. Thanks.
So, to be very clear: One coin was moved into the pending order list and a selling order was placed at price X. Then, the bot buys that coin again and, if not sold, it moves it to the pending list, creating an averaged order with the previous bag. I would like just to have both sells orders separately because there is a higher chance to sell at least something....
PT - Elroy - Today at 12:54
@Milan I understand you. And even though this channel exists. I advice you to create your request on the profit-trailer-enhancements site
I was toying with this idea few months ago. then I dismissed it. I cannot remember why. So I will need to reinvestigate
Milan - Today at 12:57
That would be great. I was trying to do something similar manually and it is really a tedious job.
Thanks a lot_

Thanks,
Milan

**Comment by stefangabos** [comment]
I support this idea. If this is implemented I was thinking of a strategy where I would put anything I buy *immediately* in _pending orders_ and then wait for another dip for my next buy. This way I would have lots of bags and a high chance of slowly getting out of each

**Comment by milanl71** [comment]
Thanks! I was also thinking to set some short pending time in that case, maybe just a few hours.
If you move them immediately, then you pairs list will be always empty, so max_pairs would not make any sense. Could be dangerous, but max consecutive buys should still protect you.

**Comment by stefangabos** [comment]
my buy settings are pretty good. so, in 99% of times I buy when there is pretty much a good time to buy. i'm on the `USDT` market and I only buy `ETH` and `BTC`. Each buy would be for `6.25%` of my funds and thus I could buy `16` times. as soon as i buy, i would place the bought bag in pending orders for a profit of `1.5%` and wait for the next buy signal

**Comment by milanl71** [comment]
Aha... Ok, then it is something different... Good luck:)

**Comment by stefangabos** [comment]
...but i need profit trailer to *not average pending orders* :)

**Comment by milanl71** [comment]
@taniman 
Need to point out more thing!
I switched from Gunbot to Profit Trailer only because of this feature which was promised to me back in February!!
See this:
[](https://github.com/taniman/profit-trailer/issues/1139#issuecomment-366461549)
So, I will be bothering you until you implement it (keep up on your promises).  Good luck!

**Comment by taniman** [comment]
@milan71
I looked at the issue u linked. Trying to find where I promised something. Could not see any mentions of myself on that issue. other than when I closed it.

I went out of my way to try and implement this now for u. So I really hope u can show me where I promised u this feature

**Comment by taniman** [comment]
Okay seems to have been a misunderstanding.  And I did not put a reason for closing the issue either. That's on me.
But I have added this feature to 2.1.0
So closing this issue now as this feature has been implemented now.

**Comment by milanl71** [comment]
@taniman 
Sorry if this is not a correct way of communication since the issue has been closed, but let me give a try....
First, I really want to thank you for implementing this feature - works excellent!
But there is a small catch with it - when the market starts going down, the bot will go to SOM once the consecutive buys condition is met. It is very likely, just happened to me, that the Pairs tab will become empty since all the coins will be moved to pending. Unfortunately, the bot doesn't recognise sell of a pending order as a valid one to exit the SOM, therefore I need manually to fix this.
Could this be somehow solved? 

Thanks,
Milan
