### ISSUE TITLE
[feature request] Trend Watcher based on EMA.

### ISSUE THREAD

**Issue by CryptosWORLD** [taniman/profit-trailer-enhancements#408]
Trend Watcher based on EMA.. When the EMA of the current candle is above the EMA of the previous candle an uptrend is confirmed. When the EMA of the current candle is below the EMA of the previous candle a downtrend is confirmed.

so if we have an UPTREND = STRATEGY 1 
so if we have an DOWNTREND = STRATEGY 2 

so must be only one enabled and the other disabled
so if we have an UPTREND ==> STRATEGY 1 = enable then strategy 2 = disable 
and if DOWNTREND ==> strategy 1 = disable  then Strategy 2 = enable 

its will be like a upper layer above all buy and sell strategies in pairs and dca that can be enabled or disabled 
Default_Trend_Watcher = yes (if no working as PT is now)
each Strategy 1 or 2 have its own default_a, b, c, d, e **buy** & **sell** strategies !!!! 
include **dca** **buy** **sell** strategies  !!!  )

the goal is when a market is uptrend we use other config in buy and sell 
than in a down trend

Example
in ProfitTrailer_2_0_14_Default_Settings.zip there are some strategies
Strategies Available:
All Markets  - El Dorado - The Market Maker
All Markets  - El Toro - Run With The Bulls
All Markets  - Old Faithful - The Gift That Keeps On Giving
Bear Market  - FrankenStrategy - Its Alive, Its Alive!!!
Bear Market  - Double Cross - Trade The Trend
Bear Market  - Monte Carlo - Buy The Dip
Bull Market  - Jobbing The Market - Intraday Trading

so
UPTREND = BULL Market = Strategy 1, can be enabled only one of these ...
Bull Market  - Jobbing The Market - Intraday Trading
All Markets  - El Dorado - The Market Maker (with some diff config*)
All Markets  - El Toro - Run With The Bulls (with some diff config*)
All Markets  - Old Faithful - The Gift That Keeps On Giving (with some diff config*)

and
DOWNTREND = BEAR MARKET = Strategy 2 , can be enabled only one of these ...
Bear Market  - FrankenStrategy - Its Alive, Its Alive!!!
Bear Market  - Double Cross - Trade The Trend
Bear Market  - Monte Carlo - Buy The Dip
All Markets  - El Dorado - The Market Maker (with some diff config*)
All Markets  - El Toro - Run With The Bulls (with some diff config*)
All Markets  - Old Faithful - The Gift That Keeps On Giving (with some diff config*)

..  * now we know what the market is ...

so in the end if we will have
Default_Trend_Watcher = yes 
we must add 2 strategies ... like
Default_Uptrend_buy
"Bull Market  - Jobbing The Market - Intraday Trading"
Default_Downtrend_buy
"Bear Market  - Monte Carlo - Buy The Dip"

etc
Default_Uptrend_sell
(...sell strategies for uptrend market...)
Default_Downtrend_sell
(...sell strategies for downtrend market...)

and the same in DCA for buy and sell ...
Default_DCA_Uptrend_buy
(...buy dca strategies for uptrend market...)
Default_DCA_Downtrend_buy
(...buy dca strategies for downtrend market...)
Default_DCA_Uptrend_sell
(...sell dca strategies for uptrend market...)
Default_DCA_Downtrend_sell
(...sell dca strategies for downtrend market...)

if somebody have a similar idea please share ...

**Comment by Whitesnake67** [comment]
I like to bring up this thread and the need of supporting having a Trendwatcher!

Now that you can deal with multi-configs a Trendwatcher to automatically switch between them is strongly needed!

Let's say "If condition XYZ is true, then switch to config A" and "if condition ABC is true, switch to config B". 

Conditions then can be one or more indicators. Let's say "Condition ABC = true if EMA goes up 3%".

This would boost the Bot in another trading level, because no strategy meets all possible market conditions. Then we can stop using third party programs like PT Feeder or PT Magic. Those are not so "flexible" with parameters for different market conditions.....

Markus

**Comment by taniman** [comment]
auto_config is possible
