### ISSUE TITLE
[Feature Request] 30 day median volume?

### ISSUE THREAD

**Issue by diablocody** [taniman/profit-trailer-enhancements#409]
Think it would ever be possible to do something like a 30 day median volume setting? 24 hr volume doesnt really deter pump and dumps that well. If there was a 30 day median volume they would have to increase volume for over 14 days, which isnt really feasible. open to other suggestions if there are any but % dailies are a little to quick in my opinion

**Comment by Masterofcoinak** [comment]
Would be great, but actually this was already requested many times. See here #19 and support. This one should be than closed

**Comment by taniman** [comment]
Could possibly use OBV in some way
