### ISSUE TITLE
[Feature Request] Trailing Stop Loss

### ISSUE THREAD

**Issue by bvebve** [taniman/profit-trailer-enhancements#410]
A trailing stop loss would be a very good complementary selling strategy.

Imagine you expect the price to increase by 10%. What happens when the price stops at 9.9% and goes down abruptly? Yes, your profit is gone.  

What about a stop loss that moves with your gain? So if your expectations (10%) are frustrated you will not lose all what you already earned.

**Comment by bvebve** [comment]
Uhmm, sorry, it was already asked on issue 381
https://github.com/taniman/profit-trailer-enhancements/issues/381

But still unanswered  :-(

**Comment by tnauq** [comment]
profit trailer already does this. setting lower profit targets with larger trailing values should work. for example your profit target set to 0.5% but trailing value of 2%(or more). Larger trailing values will prevent you from getting stopped out too easy and the low profit target lets you exit the trade sooner

**Comment by bvebve** [comment]
You are wrong. If the price drop fast you loose your profit without sell. That's why I'm asking for a trailing StopLoss

**Comment by tnauq** [comment]
trailing profit is trailing stop loss

https://wiki.profittrailer.com/doku.php?id=a_trailing_story

**Comment by LiamAird** [comment]
Trailing Stop loss has been implemented, check the wiki for more information: 
http://wiki.profittrailer.com/doku.php?id=pairs.properties#default_trailing_stop_loss_trigger_arm
