### ISSUE TITLE
[Feature Request] Positive Stop Loss

### ISSUE THREAD

**Issue by bvebve** [taniman/profit-trailer-enhancements#411]
Please, allow positive stop loss.

That way you will not lose all what you already earned if the market goes down quickly when the price was almost your expected profit.

**Comment by m4xson** [comment]
You mean trailing stoploss and I would Like that as well :)

**Comment by LiamAird** [comment]
Trailing Stop loss has been implemented, check the wiki for more information: 
http://wiki.profittrailer.com/doku.php?id=pairs.properties#default_trailing_stop_loss_trigger_arm
