### ISSUE TITLE
[Feature Request]New options for low volume limits

### ISSUE THREAD

**Issue by tnauq** [taniman/profit-trailer-enhancements#414]
Had an idea for a new feature. Currently you can limit the trailing by traded volume using flat values (ex. 100 btc, or 1000eth). I find myself manually changing this value a lot since some days this could be 5 pairs some days and other days 40 pairs. It would be nice to have the option to trade only the top 30 coins or only coins that make up a certain percentage of the overall exchange volume

**Comment by Masterofcoinak** [comment]
Should be closed, because already existing #338

**Comment by Masterofcoinak** [comment]
Should be closed. Repeated request.
