### ISSUE TITLE
[Feature Request] Stop Loss percentages for each level of DCA

### ISSUE THREAD

**Issue by GarrettFleischer** [taniman/profit-trailer-enhancements#415]
I ultimately do not wish to risk more than 1% of my total balance on each trade.
As DCA levels accumulate the stop loss percentage must be tightened to accommodate this restriction.

I would like to specify a stop loss level for each level of DCA.

**Comment by Masterofcoinak** [comment]
Already implemented. Can be closed

**Comment by Masterofcoinak** [comment]
Should be closed. Everything in DCA can be DCA Level specific!!! CLOSE
