### ISSUE TITLE
[Feature Request] Grouped Pairs Settings

### ISSUE THREAD

**Issue by jojogilpo** [taniman/profit-trailer-enhancements#417]
Allow the ability to create groups of pairs for the purpose of creating custom settings for a group versus all pairs or a single pair.

Something like: 
GROUP1_enabled_pairs = BCC, ETH 
GROUP2_enabled_pairs = LOOM, MANA
and then 

GROUP1_A_sell_strategy = GAIN
GROUP1_A_sell_value = 3
GROUP2_A_sell_strategy = GAIN
GROUP2_A_sell_value = 0.25

**Comment by HojouFotytu** [comment]
You can easily do this with PTMagic.  ;)

![image](https://user-images.githubusercontent.com/36724681/58376935-edacb080-7fb0-11e9-9996-2b11b1904438.png)

**Comment by taniman** [comment]
added for 2.5.0
