### ISSUE TITLE
Diferente Rubuy Times in DCA

### ISSUE THREAD

**Issue by felipeqga** [taniman/profit-trailer-enhancements#418]
Hey Friend can you ADD diferente buy times?
DEFAULT_DCA_rebuy_timeout = 10
DEFAULT_DCA_rebuy_timeout_1 = 15
DEFAULT_DCA_rebuy_timeout_2 = 20
DEFAULT_DCA_rebuy_timeout_3 = 25
DEFAULT_DCA_rebuy_timeout_4 = 20
DEFAULT_DCA_rebuy_timeout_5 = 15
DEFAULT_DCA_rebuy_timeout_6 = 15
DEFAULT_DCA_rebuy_timeout_7 = 45
DEFAULT_DCA_rebuy_timeout_8 = 45

Can be done?

**Comment by Masterofcoinak** [comment]
This should be possible, cause most of the functions can be now DCA level specific.

**Comment by Masterofcoinak** [comment]
Should be closed.
