### ISSUE TITLE
Global Stoploss DCA based on "Difference" ( Current Value - Total Cost)

### ISSUE THREAD

**Issue by felipeqga** [taniman/profit-trailer-enhancements#419]
Current Value | 0.10155318($764.65)
**_Difference | (-3.27 %) -0.00342861($-25.82)_**
Total Cost | 0.10498179($790.46)

Global_stop_loss= $-25.82
And sell all pairs on DCA.

**Comment by Masterofcoinak** [comment]
If you make panic sell in DCA and Pairs, than you sold also everything.
Lost is shown on the monitor (only in the maincurrency).
![image](https://user-images.githubusercontent.com/36849981/58370670-c4057200-7f3b-11e9-8706-6d81c633186d.png)
PTTracker also shows all relevant information for such an action, which is probably.
![image](https://user-images.githubusercontent.com/36849981/58370697-0f1f8500-7f3c-11e9-95dd-b08825cefb6b.png)
Should be closed or better explained.

**Comment by taniman** [comment]
Dynamic property added in 2.5.0 that could accomplish this
