### ISSUE TITLE
Triggers enabled in less than in a 24 hour period!

### ISSUE THREAD

**Issue by Stogy** [taniman/profit-trailer-enhancements#42]
I.E.:
ALL_btc_price_drop_trigger = 4
Turn on sell only mode (SOM) if BTC price drops the percentage in the setting (Uses **24h** % change in price).

Ability to change the duration of the percent drop or rise to less than 24 hours.
24 hours is too long. Many bad things can happen in much less time than 24 hours.

**Comment by planetofzog** [comment]
Totally agree with this. 24 hours is way too long. A BTC dump can take less than an hour. This setting should be able to be user defined, I am currently having to run a seperate script that changes PT to SOM should this happen.

**Comment by clownfish44** [comment]
This is already a part of PTFeeder / PTMagic and it's integration has been requested here https://github.com/taniman/profit-trailer-enhancements/issues/19

**Comment by Stogy** [comment]
Not sure why you would close this? I do not want it in an add on I want it in ProfitTrailer. Thought that was the point of this whole excercise? If you are saying the integration is a done deal then I will shut my trap.
