### ISSUE TITLE
Custom Percent amount for Buy and Sell buttons

### ISSUE THREAD

**Issue by atka007** [taniman/profit-trailer-enhancements#420]
I love the Buy and Sell buttons
would be cool to define a custom value how much you want to buy before commiting to do it
i assume it buys the amount defined in DCA settings
what if I want to buy 200% or just 10% right now without messing my other dca settings up.
Since you guys already asking for confirmation in a floating window you could add another text field before the BUY button

**Comment by Masterofcoinak** [comment]
Maybe we can close this and keep point #563 only open

**Comment by taniman** [comment]
has been implemented
