### ISSUE TITLE
Slope of Indicators (EMASPREAD) and OR Condition in Strategies

### ISSUE THREAD

**Issue by absimaldata** [taniman/profit-trailer-enhancements#424]
Functionality of having SLOPE of indicators would be very nice to have alongside with trailing profit and buy strategies.

One can buy/sell at slope of 0.

and also can we have the OR functionality in strategies, right now its only AND, so one can make generic strategies based with the conditions totally. (By treating a strategy as one functional object).

**Comment by echthard** [comment]
I think I have a similar request:

Now we have a set of sell strats that all need to be true to be able to sell.

I would like to have two sets of sell strats and one of these two need all to be true. 

Example:
set A has RSI = 80 and HIGHBB = 10
set B has MACD = -0.000000001 AND SMASPREAD = -0.01

All strats in a set need to be true to sell, but only one set need all to be true, not both.

**Comment by echthard** [comment]
What do you mean with "slope"? Can you give an example?

**Comment by Masterofcoinak** [comment]
It should be closed as it was not explained further even requested 1 year ago!!!
