### ISSUE TITLE
Request for control the number of trading pairs depending on available balance

### ISSUE THREAD

**Issue by atka007** [taniman/profit-trailer-enhancements#426]
Request for control the number of trading pairs depending on available balance.
Generally we fall into deep bags because we attempt to trade more pairs. I have to carefully monitor my bot and adjust the number of trading pairs based on how the market is doing. The price fluctuation doesn't seem to be the best indicator for changing number of pairs but i do it based on the available balance.
Maybe if we used the: ( DEFAULT_DCA_buy_trigger_1= -1 and DEFAULT_DCA_buy_percentage_1 = 100 ) logic like this: 
DEFAULT_max_trading_pairs_1= 20 and DEFAULT_available _balance_1 = 100
DEFAULT_max_trading_pairs_1= 10 and DEFAULT_available _balance_1 = 50
DEFAULT_max_trading_pairs_1= 5 and DEFAULT_available _balance_1 = 30

**Comment by echthard** [comment]
Yes. Also would like to change other settings depending on avalaible spots left in the number of traiding pairs.

So when max = 10 and I have 9 then I have 1 spot open. And then I would like to have more conservative values for RSI and LOWBB, for example.

DEFAULT_trading_pairs_spots_open = 5 and DEFAULT_A_buy_value = 30
DEFAULT_trading_pairs_spots_open = 3 and DEFAULT_A_buy_value = 20
DEFAULT_trading_pairs_spots_open = 1 and DEFAULT_A_buy_value = 10

I have no suggestions atm of the syntax to use to match the two corresponding lines though.

**Comment by taniman** [comment]
will see if we can add support for dynamic logic for some of these
