### ISSUE TITLE
Make Buy button respect min_orderbook_volume_percentage

### ISSUE THREAD

**Issue by flybuzz** [taniman/profit-trailer-enhancements#428]
Hi I love the manual buy button feature! However it does not work as well as the regular PT buy. The problems I have encountered includes when it expires it does not try second time to re-buy, it will just expire and nothing happens. Also I was very frustrated with partial fills, I had to hit the buy button 3 times to get 80% of fill. It needs to obey some sort of min_orderbook_volume_percentage like either in Pair or DCA. Partial fills are extremely frustrating, especially when I re-buy multiple times, DCA thinks I am averaging down.

**Comment by Masterofcoinak** [comment]
I think this was already solved and I never had a partial buy
