### ISSUE TITLE
[FEATURE REQUEST] CONDITIONAL STOPLOSS

### ISSUE THREAD

**Issue by thysbotwhisper** [taniman/profit-trailer-enhancements#430]
Stoploss is now defined by one parameter: gain. It would be incredibly helpful for my particular strategy if i could define the stoploss with an indicator too.

Example: 
I buy a pair on positive smaspread. It starts at -0.5%. It goes up to 1%, but misses my sell conditions (sell: negative smacross, 0.1% gain, 0.1% trailing (grow)) . It goes back to -0.1%. Only then does SMA cross negative. I would like to sell it right there as a stoploss.

If I had a  -0.1% stoploss set though, it would have sold right away because the pair starts at -0.5%.

Now if I could refine the stoploss with a negative smaspread, it would only allow the stoploss to kick in when the sma crosses negative.

DEFAULT_DCA_stop_loss_trigger = -0.01
DEFAULT_DCA_stop_loss_A_strategy = SMAGAIN
DEFAULT_DCA_stop_loss_A_value = -0.01

This is another way of requesting a separate set of sell conditions that can be triggered independently of the "normal" sell conditions.

(Current workarounds, not really acceptable)

A. I could define sell at -100 to allow a sell on every negative smacross like this:

DEFAULT_DCA_A_sell_strategy = GAIN
DEFAULT_DCA_A_sell_value = -100
DEFAULT_DCA_B_sell_strategy = SMAspread
DEFAULT_DCA_B_sell_value = -0.01

But this would totally exclude the grow trailing sell function. I want to be able to use this. When the coin is in profit I want to use trailing sell.

B. I can use trailing when the coin is positive:
DEFAULT_DCA_A_sell_strategy = GAIN
DEFAULT_DCA_A_sell_value = 0.1
DEFAULT_DCA_B_sell_strategy = SMAspread
DEFAULT_DCA_B_sell_value = -0.01

But then it can not sell in the negative until it hits the stoploss, and the stoploss has to be lose (for example -5%) because when the pair starts it starts at -0.5% already and there are natural fluctuations. I want the stoploss to be very tight, but not right after the buy.  

So I want the stoploss to be only true when the smaspread (or another indicator) indicates the pair is actually really dropping, but then I want the stoploss to be really tight.

**Comment by taniman** [comment]
Dynamic logic can allow you to close your pairs. Or add a special sell strategy that does this.
