### ISSUE TITLE
[Feature Request] Trailing price trigger for SOM

### ISSUE THREAD

**Issue by alexdolli** [taniman/profit-trailer-enhancements#431]
Considering the crappy market and the huge "mood" swings right now, is it possible to turn the price_trigger for SOM mode into a trailing trigger? Meaning, instead of static values, let's say activate the price trigger at -6 % and disable it as soon as it recovers 2% from wherever and however low it went?
This way the bot would start trading again as soon as the market is most likely to turn around, instead of waiting for the recovery trigger. With huge percentage drops like we've seen lately, you miss out on good profit opportunities by the time it hits the static trigger.

**Comment by taniman** [comment]
use the some trigger length to better fit your SOM to your liking
