### ISSUE TITLE
[Feature Request] Add SSV column in the seles logs pages

### ISSUE THREAD

**Issue by But4ler** [taniman/profit-trailer-enhancements#432]
Hi,
Would it be possible to add the SSV column in the sell logs page?
This would make it easier to see what happens during sales and therefore improve them with existing indicators. 

For example,
- I have a 0.27 trailing.
- A gain of 0.4
- Type GROW

The pairs went up to 7.2% in the log pairs, now it's at 3.42.
Once sold, there will be only 3.42% information. 

So I can't realize the gains I'm missing and try to make improvements

**Comment by Masterofcoinak** [comment]
Already existing for PT Pro users with the advanced stats
