### ISSUE TITLE
3 columns format for GUI

### ISSUE THREAD

**Issue by nagsve** [taniman/profit-trailer-enhancements#434]
3 columns format for GUI to easy visualize all parameters on one screen without jumping different windows, something like this

..................PAIRS.....................................................................DCA.......................................................INDICATORS
#GENERAL SETTINGS#..................................	#GENERAL SETTINGS#.......................SOM_trigger_length = 288
							
#POSSIBLE BUY LOG SETTINGS#.............. #BUY FILTER SETTINGS#...................BB_std = 2
.....................................................................................................................................................BB_candle_period = 300
#BUY SETTINGS#.............................................. #BUY SETTINGS#................................so on

#SELL SETTINGS#.............................................. #SELL SETTINGS#

#SELL ONLY MODE#

#COIN SPECIFIC SETTINGS#

and please sort parameters same way shows WIKI, It's will make easy to find description of parameter.

**Comment by LiamAird** [comment]
Will make the view very messy and cluttered
