### ISSUE TITLE
[FEATURE REQUEST] MACD CROSS

### ISSUE THREAD

**Issue by thysbotwhisper** [taniman/profit-trailer-enhancements#435]
Simple macdcross strategy would be very very nice.

**Comment by m4xson** [comment]
+1 for that :)

**Comment by mikkelnl** [comment]
+1, I would love to see a MACD_cross_candles option.

**Comment by fletch63** [comment]
+1, I would love to see a MACD_cross_candles option.

**Comment by keithofaptos** [comment]
+1

**Comment by djbadders** [comment]
+1 Any chance of this?

**Comment by djbadders** [comment]
This now can be achieved in the latest PT https://wiki.profittrailer.com/en/config/crossunder
