### ISSUE TITLE
[FEATURE REQUEST] GUI SHOW CURRENT TRAILING TRIGGER PRICE

### ISSUE THREAD

**Issue by thysbotwhisper** [taniman/profit-trailer-enhancements#436]
I would like to see at what percentage the actual sell will be put in by PT after trailing is done.

Now it says "true trailing" for a sell and displays the highest price from which PT is trailing.

For example: buy value = 1 trailing is 0.1 with GROW:
It would be nice if it was trailing down from 10% it would say "true trailing: 9%" for instance. It would tell you how much trailing space there is left before PT puts the sell into the exchange.

[edit after discord discussion clarifying the idea]
I would like it to display the profit percentage where it would sell.
So it's trailing until X
Display X

**Comment by But4ler** [comment]
since we know how much PT will want to sell to, it also makes it possible to decide whether or not to sell manually.

In the meantime, I did this yesterday, if it helps [google sheets](https://drive.google.com/open?id=1M-iD7QbuNuhVM1cDgBiJF5G81TH3YEIyLdivE1wa7Ns)

**Comment by MetaAtman** [comment]
to see current trailing value in GUI would be awesome

**Comment by Masterofcoinak** [comment]
Already existing for PT Pro users with the advanced stats
