### ISSUE TITLE
BUY/SELL fees

### ISSUE THREAD

**Issue by ochiengj** [taniman/profit-trailer-enhancements#437]
Please add a way to tell PT what the trade fee is. At the moment it uses 0.25% as default I believe.

for example:  Set_trade_fee_percentage = 0.05

At the moment in BINANCE if you are set to 0.05% fees, if you are down -0.10% on a trade in PT you are actually up by +0.10% in reality, but the bot doesn't show this because it's using the wrong fees.

This will be a really big help especially in scalping (in Binance) and you can exit the trade much sooner at positive if need be, instead of falling back in the negative. It makes a big difference for scalping multiple trades per day.

**Comment by taniman** [comment]
has been added
