### ISSUE TITLE
GUI: Button to clear logs and switch from Test Mode to Live

### ISSUE THREAD

**Issue by m4xson** [taniman/profit-trailer-enhancements#438]
![pt test mode button](https://user-images.githubusercontent.com/42469965/44298669-0760ef00-a2df-11e8-9cec-ccca14b5ddf3.jpg)
You've been running a PT bot in test mode to try out a config and it's working well. You want to take that setup live directly and make real money. What you want is a nice button that will clear the test mode logs and restart the bot in live mode.

Currently it's a slightly complicated process to switch from test mode to live mode where you need root access to your bot to edit the application file and delete data files before restarting the bot. This means you have to be at a private PC to connect to your VPS and do the switch safely. This also means it's possible to get this wrong like I did and totally mess up your live PT bot. It's also impossible to do if you're on the move or have limited time.

Wouldn't it be nice to switch safely and easily from test mode to live using just your phone. What do you think?

**Comment by m4xson** [comment]
Smash the thumbs up if you want this feature!

**Comment by Masterofcoinak** [comment]
I think this no issue anymore after 2.4
![image](https://user-images.githubusercontent.com/36849981/59038600-8e358700-8873-11e9-87a0-5c0ba47e942a.png)
Should be closed.
