### ISSUE TITLE
Buy button on "dust" pairs

### ISSUE THREAD

**Issue by GarrettFleischer** [taniman/profit-trailer-enhancements#439]
**Suggestion**
Add a Buy button to pairs in the Dust log.

**Reason**
I have a few pairs that went into dust due to price loss (and my buy value percent was too low).
I would like to manually "DCA" them in the Dust log to bring them back into pairs where they can be sold or auto DCA as needed.

**Comment by LiamAird** [comment]
Added to 2.4
