### ISSUE TITLE
Option for stoploss to automatically trigger SOM

### ISSUE THREAD

**Issue by conando2000** [taniman/profit-trailer-enhancements#44]
I guess not a lot of people use stoploss anyways, which is partly due to it being so hard to control.

Have an option to go to SOM automatically after any kind of stoploss is fired and also to only fire xyz stoploss per xyz hours would be really helpful!

**Comment by clownfish44** [comment]
https://github.com/taniman/profit-trailer/issues/480 would be part of the Safety stop loss here
