### ISSUE TITLE
Feature Change: Stoploss sells and consecutive_sell_trigger

### ISSUE THREAD

**Issue by m4xson** [taniman/profit-trailer-enhancements#441]
Currently a sale triggered by stoploss can bring PT out of Sell Only Mode or prevent it going into SOM. My preference is for stoploss sales not to be counted for the SOM triggers. Stoploss sales indicate the market is not going my way and the bot should not be buying.

So I would like it if consecutive_buy_trigger and consecutive_sell_trigger did not count stoploss sells.

To go a step further a new SOM trigger based on stoploss such as consecutive_stoploss_sell_trigger = 4 would be useful added feature.. This would add another layer of protection to PT.

**Comment by juanc27** [comment]
+1. 
This will be very useful for people doing stop loss.

**Comment by juanc27** [comment]
Can you guys help with this? This can be an easy feature to implement and it will be a huge help for users doing stop loss. 

Something like this can be implemented in the pairs configuration:

# Turn on sell only mode if we got x consecutive stop_loss sells
consecutive_stop_loss_trigger = 2
# Turn off sell only mode after X minutes from the trigger
consecutive_stop_loss_trigger_timeout = 120

**Comment by taniman** [comment]
Added to 2.5.0
