### ISSUE TITLE
[FEATURE REQUEST] Use the trend of your trading market's pairs as the SOM trigger

### ISSUE THREAD

**Issue by RF-Radio** [taniman/profit-trailer-enhancements#442]
So far, all we have been able to use as the SOM trigger is the market denominating currency, whether it be BTC, ETH, or XMR.  I think using the trend of the top X amount of pairs in your market by volume would be a great indicator, and possibly more relevant than just working off of the market's base currency.  

This could be implemented by using the top 50 coins in your market as the trend, as that value is already reported on the Monitor screen.  Further development could be to add the number of coins to watch for the trend as a parameter in the Pairs config, so traders could use the top 10 or 20 coins rather than fixing it at the top 50.  

An example of such parameters could be as follows:
price_trigger_market = TREND
price_trigger_pairs = 10

In the above example, "price_trigger_pairs" should be disabled when using BTC, ETH or XMR price for the SOM trigger to avoid any conflicts.

**Comment by m4xson** [comment]
![capture](https://user-images.githubusercontent.com/42469965/44382714-0235b700-a50e-11e8-889b-d4d76ce8a1f2.JPG)
![capture2](https://user-images.githubusercontent.com/42469965/44382715-0235b700-a50e-11e8-8060-3d5fa14580ef.JPG)
Do you mean these trends that the bot already has access to?

I think this is a good idea. The more SOM triggers the better in this market! I would want a SOM trigger on Trend USD last 1H such as:

SOM_price_trigger_Trend_USD_last_1H = -0.5

**Comment by RF-Radio** [comment]
Yes, those trends would be what I’m referring to.  I was mainly interested in the BTC/ETH/XMR trend, but if USD trends can also work, even better!

**Comment by RF-Radio** [comment]
Also, it may be useful to be able to define more than 1 trigger at a time, so it could activate on any of the SOM conditions, not just one at a time, like what you posted above.

**Comment by Masterofcoinak** [comment]
Sorry i am trying to close some points and this was already more or less posted long time ago.
#19

**Comment by taniman** [comment]
I think adding indicators to filter out and prevent a buy would be a better fit. And can be added to your formula logic
