### ISSUE TITLE
Add safety net to take_profit

### ISSUE THREAD

**Issue by Helmi** [taniman/profit-trailer-enhancements#444]
Add DEFAULT_take_profit_safety to the take profit functionality. When set the bot should sell of that level of profit as soon as it had once reached the DEFAULT_take_profit_percentage.

Example:

DEFAULT_take_profit_percentage is set to 2%
DEFAULT_take_profit_timer is set to 15 mins
DEFAULT_take_profit_safety is set to 0.5%

Once it reached 2% and before the timer fired it drops back it will set at 0.5% without any other Sell strategy being true or any other time.

**Comment by Helmi** [comment]
it would probably be good to have two config values for that. 

1. DEFAULT_sell_safety_arm = 1% 
2. DEFAULT_sell_safety_fire = 0.5%

This would enable the user to only arm the safety net when profit reaches a certain level. Otherwise the safety net would trigger too early. For example if you set it to 0.5 and it reaches 0.6, comes back to 0.4 it would instantly sell. That would be stupid.

Maybe not connecting it to take profit name wise would be good as it's not really directly connected.

**Comment by taniman** [comment]
Trying to find
