### ISSUE TITLE
unrandomize DCA_max_trading_pairs buys

### ISSUE THREAD

**Issue by zapedge** [taniman/profit-trailer-enhancements#445]
Hi
i have an Idea regarding 

DCA_max_trading_pairs

> DCA_max_trading_pairs = 10
> Optional - click for more info
> 
> Valid values: Integer values greater than and equal to 0.
> 
> Set the maximum number of coins that are permitted to DCA at any given time.
> 
> Note:
> 
> If not set (including missing from the file completely) then there is no limit and all coins can be DCA'd.
> If you lower this limit below the number of coins you already have in DCA, ProfitTrailer will randomly select the ones that DCA.
> Excluded coins will stay in the DCA Log but display MAX DCA PAIRS.

DCA_max_trading_pairs is a cool feature. I can limit my DCA with it significantly.

But why does PT choose randomly?

Wouldn't it be better to have a kind of "first come, first serve" DCA?

Example:
I have 5 coins in DCA Log
I set DCA_max_trading_pairs = 4 

PT now rolls the dice and randomly sets 1 pair to not DCA
Unfortunately exactly this pair runs into a buy opportunity first while the DCA-enabled-pairs do not. PT will not buy hence the randomly selection.
It will stubborn wait for the randomly selected pairs to run into a buy opportunity.

I think this should be altered maybe by implementing a Prameter "DCA_max_trading_pairs_strategy" 
wich could for example lets say be set to  "DCA Lowest Pairs first", "DCA Highest Pairs first", "DCA positive Buy Trigger First".

If a Pair was DCA'd once it is then fixed as one of the 4 Pairs allowed to be DCA'd, i think this is how it is already.

**Comment by iller75** [comment]
This is something i really need!

**Comment by taniman** [comment]
buy_priority exists now
