### ISSUE TITLE
Sell to Stable Coin (of choice) feature

### ISSUE THREAD

**Issue by carl4315** [taniman/profit-trailer-enhancements#446]
I am looking for the ability to remove certain aspects of market risk.  These coins are all coupled together (currently). Panic selling into BTC reduces alt coin exposure but not nearly to the degree a stable coin would. 

There should be a one click button or a stop loss on BTC (%) that triggers the bot to sell all coins into a stable coin of choice (TrueUSD).  Depending on the approach, another button (business as usual) or a BTC recover % that would function in the same way as the button.

**Comment by DrToxo** [comment]
I've requested a Panic Sell to Tether so you can quickly shore up your investment.  

I really like the idea of this sort of feature.

**Comment by carl4315** [comment]
Hi DrToxo,

Glad you like this idea!  Are you a developer for PT?  I really question
Tether's legitimacy from its beginnings until now.  If other people don't,
that's cool. But, would it be possible to choose your stable coin?  I have
much more faith in projects like TrueUSD and Dai.

Best,
Bryce

**Comment by snortch** [comment]
Lots of legit stable coins now including USDC and TUSD. With the volatility of base coins like BTC and ETH, this feature would be amazing. I would love to see PT sell to the stable coin of choice whenever a price rise or drop trigger is met. Would also be really cool to get PT to sell the stable coin back for the base pair of my choice when + or - recover trigger is met.

**Comment by Masterofcoinak** [comment]
already requested #363
