### ISSUE TITLE
Candles since 0 LOWBB?

### ISSUE THREAD

**Issue by jimmyjimmyv** [taniman/profit-trailer-enhancements#447]
Is there a way we could have an indicator where we could set a line defining how many candles since 0 LOWBB (or HIGHBB) was penetrated?

DEFAULT_A_buy_strategy = LOWBB
DEFAULT_A_buy_value = 60
DEFAULT_A_buy_value_limit = 40
**_DEFAULT_candles_since_zero_LOWBB = 15_**

 I might want to buy if LOWBB is between 40 and 60, but only if 0 was penetrated within the last 15 candles. Otherwise, it would true up even if the price was coming down. I want to know that the price was down before the buy.

This combined with BBWIDTH might help identify a break to the upside after consolidation.  :)

**Comment by nealgentry** [comment]
candles since lowbb or candles since highbb would be awesome! why isn't this getting more traction??

**Comment by taniman** [comment]
using CROSSOVER/CROSSUNDER logic or _offset logic would surely get you close to this
