### ISSUE TITLE
Current difference between the current balance and the starting balance.

### ISSUE THREAD

**Issue by xyr0x** [taniman/profit-trailer-enhancements#448]
Hello,

a field that shows the current difference between current credit and starting credit would certainly be a small re-invention that would help some. The sales log are only weekly, daily and the day before yesterday and alternatively the users only have to calculate the difference manuel with a pocket calculator.

Many Thanks

**Comment by Masterofcoinak** [comment]
Are you talking about the balance or the TCV? 
The balance in my opinion doesnt make sence to keep tracking.
TCV luckily is possible now with the new STATS page.
