### ISSUE TITLE
[Feature Request] Command to keep a % of pending order in DCA (Simple dilution for bags!)

### ISSUE THREAD

**Issue by ochiengj** [taniman/profit-trailer-enhancements#449]
We just need one more command to be able to break down bags!
Commad to keep a % of a pending order in DCA, instead of sending the full amount to pending. 
ProfitTrailer already has everything else to make a bag dilution strategy possible just needs ONE more command. 
My suggestion is slightly different from others posts, and much simpler to add.
Add a command:

DEFAULT_pending_order_excluded_amount = 0.0030
or
DEFAULT_pending order excluded_percentage = 1%

1- This will send coin to pending using xxx_pending_order_price_drop_trigger already in PT.
2- This command keeps a percentage of coin in dca. For example 1% 
3- use the price of the LAST DCA BUY for the remaining small piece in dca.
4- PT can now dca this very small amount. or may even sell it without dca.
5- After SELL the pending will automatically cancel and recalculate a new pending order.
6.-Repeat

And that's it. Simple BAG DILUTION method. Just ONE more command! We are so close PT please add this!! Thanks.

**Comment by CryptosWORLD** [comment]
more info about this method here
ProfitTrailer- Bag Buster!(Part 2) -No addon? VOTE for New Command? |Get out of BAGS -Auto Dilution
https://www.youtube.com/watch?v=sEDXpyh8DQk

suggestion: yes there are many requests if you filter by dca or short
https://github.com/taniman/profit-trailer-enhancements/issues?utf8=%E2%9C%93&q=dca
https://github.com/taniman/profit-trailer-enhancements/issues?utf8=%E2%9C%93&q=short
its time i think dev do something about it

**Comment by themightycrypto** [comment]
+1 vote. we need this.

**Comment by F1power** [comment]
+2 We need this, please

**Comment by Q-Rush** [comment]
+3 We definitely need this!

**Comment by niroshana35** [comment]
DCA Dilution / DCA Bag Buster Strategy is a must have for Profit Trailer because almost all users of the PT may suffer with deep DCA Bags at a time unless they are using Stop/Loss (Loosing Money) so DCA is better because no one will ever loose their money but PT needs a Good working Strategy to Get rid of those deep DCA bags. PT is the best bot so far IMO but without this or similar Strategy PT is incomplete.

**Comment by mightysoul** [comment]
+1 up

**Comment by cryptozwerg** [comment]
+1 from me 2

**Comment by Devir71** [comment]
That would be a great feature to have.

**Comment by omeatai** [comment]
Really love this concept!

**Comment by zed1966** [comment]
I like it would be a great add

**Comment by Masterofcoinak** [comment]
Should be closed. Part of the roadmap.
![image](https://user-images.githubusercontent.com/36849981/59029529-cbdbe500-885e-11e9-8772-4374361a3c23.png)
![image](https://user-images.githubusercontent.com/36849981/59037482-a3111b00-8871-11e9-8e97-a73ec50116a0.png)

**Comment by ochiengj** [comment]
Hi PT Team! 
It would be nice if I could get some points for this suggestion? I posted it and got the votes long before it was in the roadmap! Please consider. Thanks.
