### ISSUE TITLE
Integrate the graph/tracker addon with added indicators

### ISSUE THREAD

**Issue by conando2000** [taniman/profit-trailer-enhancements#45]
Integrate the popular graph/tracker web interface addon into PT and while add it please please please add more indicators to it - for optimization/debugging purposes it would be so super helpful to directly see in the graph the current strategies low/high and trigger values and not only the current coin value.

Added sugar coating: add a fullscreen button to the graph to see in detail whats going on, would be great to be able to see the trailing for example visualized...

**Comment by clownfish44** [comment]
Please request this from the creator of the graphing tool https://github.com/CryptoGnome/Community-Tools/tree/master/ProfitTrailer-Tools/Web-GUI-Addons/Graphing-Tracker

**Comment by conando2000** [comment]
I thought this was meant as a collection of feature requests/ideas - and I specifically wrote about _integrating_ graphing or just in general a better monitoring of the bots status/operation. It's kinda sad to have to rely on external scripts being injected into the web frontend by a browser extension!

If you integrated them directly it would also have the added benefit of showing up on mobile... and browsers where you have not or cannot install a third party script injection extension ;)
