### ISSUE TITLE
Allow unattended setup

### ISSUE THREAD

**Issue by Helmi** [taniman/profit-trailer-enhancements#450]
Currently setting up a new bot is only possible through the browser, as config and password need to be set from there.

It would be good to have a chance to avoid this.

Possible solution:

If setup is not done, before directing the user to the browser setup check for a file in the pt directory. Could be something like `.init` and contain something like

```
password = urCZWU8jZRewJKuK3
config_source = local (or public)
config_public = MonteCarloV2 (public config name if config_source is set to public)
config_name = myconfname
``` 

config_source = local would of course read the config from the initialization folder.

If anything fails (missing variables, syntax wrong, etc) you could output an error and stop or continue with the browser setup.

If initialization is done successfully done this way you could delete the `.init` file and have the same security as now with no clear text password in the directory.

**Comment by taniman** [comment]
There is not enough demand
