### ISSUE TITLE
[FEATURE REQUEST]  Trailing Stop Loss 

### ISSUE THREAD

**Issue by Bla5ph3m3** [taniman/profit-trailer-enhancements#452]
There’s a feature in 3 commas called, Trailing Stop Loss.  The ability to have a stop loss trail would  help to mitigate losses, and keep the buying and selling moving along. Also will help keep the profits up when a coin pair doesn’t quite go up as high as one might have predicted. A trailing stop loss would chase the price as it goes up. And if the price never reaches the sell trigger, and begins to fall again profit trailer could still sell at a profit...  And perhaps good profit before the pair drops too low again. A feature such as this as well needed and could be a vast improvement to the stop loss the way it is now.

**Comment by Bla5ph3m3** [comment]
Sorry didn’t realize this feature was all ready requested on #381 and #410 but seriously this feature is needed badly.

**Comment by m4xson** [comment]
+1 from me. We need this. I need this.

**Comment by dechut** [comment]
trailling profit to maximum profit in up trend , and trailling stoploss to minimum loss in down trend .

i urgent need this too , thank you

**Comment by Devir71** [comment]
Trailing Stop Loss is a well needed feature to be added in PT

**Comment by LiamAird** [comment]
Trailing Stop loss has been implemented, check the wiki for more information: 
http://wiki.profittrailer.com/doku.php?id=pairs.properties#default_trailing_stop_loss_trigger_arm
