### ISSUE TITLE
Add More Exchanges

### ISSUE THREAD

**Issue by jshay21** [taniman/profit-trailer-enhancements#46]
Many of us traders are looking for automated solutions that work with USD based pairs. With the recent news concerning USDT, many of us are looking for a safe, stable base to trade from.  Also note with GDAX, Kraken and Gemini, USD funds are FDIC insured up to $250,000.  Let's get this voted up!

**Comment by clownfish44** [comment]
Very good idea in my opinion!

**Comment by iAmVaeVictus** [comment]
Wether or not you like USDT, more exchanges is a big selling point to the end user. We need the flexibility to access different coins. 

If this is implemented, what exchanges do the customers want to see added?

**Comment by jbraydc** [comment]
There is a new exchange that has no trading fees.. saw it on YouTube but cant remember it off my head.

**Comment by orangebutblue** [comment]
SO you want to trade on GDAX, which only has 4 coins?

Why not just use Gekko or some other opensource solution

**Comment by sas7085** [comment]
Yes we need support for more exchanges

**Comment by jschoenith** [comment]
@orangebutblue yep, running Gekko now

**Comment by Tosko4** [comment]
@jbraydc @orangebutblue , i think he is referring to robinhood (https://crypto.robinhood.com/)

**Comment by orangebutblue** [comment]
@Tosko4 Robinhood doesn't do crypto-trading. it't just a frontend for other exchanges

**Comment by LeaderOfChampions** [comment]
Sure, but this won't help the bot trade better, would be nice to see it perform better trades first before expanding on this front.

**Comment by elementalwindx** [comment]
Cobinhood is the exchange with no trading fees. That would be awesome.

**Comment by RoMarSky** [comment]
It would be great to give this FREE to the existing license holders or at least with a huge discount!

**Comment by clownfish44** [comment]
https://github.com/taniman/profit-trailer/issues/103 already in milestones

**Comment by Concept211** [comment]
Has the PT team even considered BitMex? Imagine if the bot could scalp in both long and short trades and it wouldn't even be necessary to use any leverage to keep it safer. Trading on the way up or down would definitely help to alleviate so many heavy bags.
