### ISSUE TITLE
[FEATURE REQUEST] Relative Volume

### ISSUE THREAD

**Issue by CryptoTropico** [taniman/profit-trailer-enhancements#460]
A relative volume strategy would be awesome:

I see it would work this way:

Suggested settings:
**First:** _Candle Period_ for this strategy: Eg. 300s (5 minutes)
**Second:** _Average Volume_ in the past X number of candles: Eg. 15 candles
**Third:** _Relative Volume_ measured in times: Eg. 1.5 times the _Average Volume_

I have used this method to scan for moving coins based on relative volume and generally Relative Volume tends to be highly correlated with strong price movement. Relative Volume would be a nice addition to PT for a scalping-style setting.

**Comment by keithofaptos** [comment]
+1. 
This is going to be primary when then things ramp up again.

**Comment by Masterofcoinak** [comment]
Would be great, but actually this was already requested many times. See here #19 and support. This one should be than closed

**Comment by taniman** [comment]
possible duplicate
