### ISSUE TITLE
[Feature Request] XXX_ignore_max_trading_pairs = true

### ISSUE THREAD

**Issue by kkkoay** [taniman/profit-trailer-enhancements#461]
Sometime when busting a certain coin with heavy bag requires buy back. But the max trading pairs may have reached and blocking the buy. It would be nice that a certain coin can be whitelisted to ignore the max trading pairs block and allow the coin to perform the buy. This will allow quickly bag busting without further delay on buy opportunities.

**Comment by Draztik99** [comment]
> Sometime when busting a certain coin with heavy bag requires buy back. But the max trading pairs may have reached and blocking the buy. It would be nice that a certain coin can be whitelisted to ignore the max trading pairs block and allow the coin to perform the buy. This will allow quickly bag busting without further delay on buy opportunities.

I was thinking of the same thing and of the same coin TUSD which always gives me a good trade

**Comment by taniman** [comment]
can be done now with new property
