### ISSUE TITLE
[ Feature Request ] Dummy Shorting 

### ISSUE THREAD

**Issue by Kirk1965** [taniman/profit-trailer-enhancements#463]
Been Testing Cryptohoppers ( Short ) Function which is not a real Shorting. But it works perfect. 
Request this feature ( Dummy Shorting ) When a coin goes negativ, the Dummy short Will auto sell the coin and track the course downwards and buy the same ammount back just cheaper and when a postive gain is reached it will sell with profit. It must buy and sell the same coin until a selected profit is reached.
This way we dont haft to DCA and it is cheaper to Dummy Short. And in the mean time the assets we get back while Dummy Short can be used for further investment. 
Functions:
 % negativ before Dummy Short. Or Strategy when to Dummy Short.
To use Profit gained by Dummy short or not.
While Dummy short a min. ammount must be reserved to buy back the coin. 
% how much profit you whant.
% how much loss you can accept.
Dummy shorting during SOM. Which will be super and effective since coin´s tend to bounce back.

PT is my favorit Bot Trader, but i do miss this function. My profit gain is larger with CP since thay have this Dummy Shorting. 
Please make this as a feature soon. 
Cheers Kirk

**Comment by Masterofcoinak** [comment]
Should be closed, because already existing here #264. Support there.
