### ISSUE TITLE
Feature request: Different DCA buy times

### ISSUE THREAD

**Issue by swanfield1979** [taniman/profit-trailer-enhancements#465]
I would like to use different strats per DCA level. So like this:

DEFAULT_DCA_A_buy_strategy_label_1 = RSI900
DEFAULT_DCA_A_buy_strategy_1 = RSI

DEFAULT_DCA_A_buy_strategy_label_2 = RSI1800
DEFAULT_DCA_A_buy_strategy_2 = RSI

DEFAULT_DCA_A_buy_strategy_label_3 = RSI3600
DEFAULT_DCA_A_buy_strategy_3 = RSI

Is this possible to add to PT?

Why I would like to see this is to get a better bottem on DCA levels when the price drops. This way I can filter more on overbought on multiple timeframes.

**Comment by Masterofcoinak** [comment]
Just tried. You can do that meanwhile. Should be closed
![image](https://user-images.githubusercontent.com/36849981/58368769-2488b500-7f24-11e9-8f32-0cc89119ffc4.png)

**Comment by Masterofcoinak** [comment]
It should be closed. Already implemented
