### ISSUE TITLE
Specific coin setting to increase volume of that coin. Sort of bag busting strategy.

### ISSUE THREAD

**Issue by Oconnode** [taniman/profit-trailer-enhancements#466]
The idea would be to have a compounding effect and increase the vol of a specific coin based on swings...
In other words,  if a 2% profit were made on a portion or all of a coin, could the next buy be increased automatically each time by that percentage? Then sold at a set gain and repeat...

So if you had a sell of lets say 25% of your ADA at a 2% gain then a buy back of the volume (inclusive of the gain) at 2% down and continually have this ticking over outside of other settings then this would be very handy. 

Almost like having another base pair. 

Also a sort of bag busting idea but with increasing traded coin as opposed to base coin.

There is such consistency in ADA for example that I have been accumulating manually but I guess this could be automated?

**Comment by omarmoss** [comment]
I like that compounding strategy. 
I was thinking of something similar, but inversly ... and perhaps easier to add into the existing code.

A variation on the existing feature:
ACME_reserve_amount = 200
and creating a:
ACME_reserve_amount_percentage = 25
with accompanying:
ACME_reserve_amount_percentage_min = 1

With the example above of 25(%):
if we had a 2% sell trigger execute, then the bot would sell for only a 1.5% base pair profit and the remaining coin/bag gets added to an ever-accumulating (dust) [reserve] pair list of free coins).
This would only execute if the profit amount being triggered is 1% or higher.

Furthermore, we could then add a second-layer sell strategy for those reserve pair coins:

ACME_reserve_sell_strategy = gain
ACME_reserve_sell_value = 100
ACME_reserve_sell_trail = 10

This would then only sell the reserve pair if its gain is 100%+ while trailing by 25%.

This second layer sell strategy would allow us to take full advantage when its market pops and effectively allow us to cover increased rebuys on that pair (using pair specific buy amounts) at the other end of its trading cycle.

**Comment by Masterofcoinak** [comment]
Should be closed. Part of the roadmap.
![image](https://user-images.githubusercontent.com/36849981/59029529-cbdbe500-885e-11e9-8772-4374361a3c23.png)
![image](https://user-images.githubusercontent.com/36849981/59037482-a3111b00-8871-11e9-8e97-a73ec50116a0.png)
