### ISSUE TITLE
[Feature Request] Value of a indicator is bigger or smaller then previous candle value

### ISSUE THREAD

**Issue by rodyla** [taniman/profit-trailer-enhancements#467]
Create a setting to check if the previous value is greater or smaller than the current value. 

For example a sell trigger for the MACD. Sell if MACD value is smaller then the previous MACD candle value. This way you can detect the downtrend in a very early stage and sell with a good profit.

Other example would be. Buy if RSI value is greater then the last value. Seeking for confirmation if the coin is really in a uptrend.

**Comment by Masterofcoinak** [comment]
Lets close here and support #569

**Comment by taniman** [comment]
_offset does this
