### ISSUE TITLE
Sort by Difference,. Market cap 'Possible Buy'

### ISSUE THREAD

**Issue by AdamCD333** [taniman/profit-trailer-enhancements#468]
** Sort the Difference:**
On DCA, far right has USD. There is a bought value and current value. Could you just post the
difference and make it sortable. This way if your DCA gets full and/or old, you can easily select which
coin to sell for the smallest loss.

Rebound:
Post the number of REBOUNDS on Pairs and DCA.

DEFAULT_min_buy_volume:
Instead of min_buy_volume, have an option for min_possible_buy_pairs.
For example on Binance DEFAULT_min_buy_volume = 100 has 64 "Possible Buy". "Possible Buy"
number fluctuates due to market activity.
Just add a setting min_possible_buy_pairs = 50 which is stable, but now min_buy_volume fluctuates.

DEFAULT_pairs_MarketCap
DEFAULT_pairs_MarketCap = 50 would also replace min_buy_volume. This would list top 50 BTC pairs
by MaarketCap on Binance. If you wanted to play it safer, set pairs_MarketCap to 30. This would
provide less volatility and less shit coins.

24hr % Change sort:
first column on "Possible Buy" tab says "Coin" in the header. You can easily sort by name, but I would
also line to sort by 24hr % Change, which is just below the name of each Coin. I want to see easily
see which coin has dropped the most in the last 24hrs so i can buy it.

**Comment by m4xson** [comment]
I like this part most of all. Should be easy to implement.

DEFAULT_pairs_MarketCap
DEFAULT_pairs_MarketCap = 50 would also replace min_buy_volume. This would list top 50 BTC pairs
by MaarketCap on Binance. If you wanted to play it safer, set pairs_MarketCap to 30. This would
provide less volatility and less shit coins.

**Comment by LiamAird** [comment]
Some of these are implemented in 2.4, some are not. 
Please do one request per issue.

**Comment by Masterofcoinak** [comment]
I think none of them are implemented

**Comment by LiamAird** [comment]
2.4 is in development.

**Comment by Masterofcoinak** [comment]
Ahh shit. I thought we are already at 2.4 and waiting for 2.5 :stuck_out_tongue:
