### ISSUE TITLE
Make the bot available after purchase to any supported exchange

### ISSUE THREAD

**Issue by iller75** [taniman/profit-trailer-enhancements#47]
Not really a feature request but still valid i believe. 

The bot should in my view not be tied to a certain exchange when you buy it, once you bought it you should be able to choose to trade on any of the supported exchanges that the bot supports. I might for example want to change exchange for some reason but at the moment i would have to buy a completely new license for that.

**Comment by clownfish44** [comment]
You can request a one time licence change using https://support.profittrailer.com/
