### ISSUE TITLE
[feature request] pair reservation

### ISSUE THREAD

**Issue by swanfield1979** [taniman/profit-trailer-enhancements#470]
For pt defender but also for other goals it would be cool if you could reserve a position for a pair or pairs in the number of pairs you are using. So in my example, ptdefender is defending 4 pairs. I would like to always have a spot for these 4 pairs when my buy strat hits. I reserve the spots by name and from the 10 pairs i trade normaly i now only use 6 for all other pairs and i reserve 4 for my defeding pairs.

In other useses you could use this to always trade a specific pair. For example i have made a specific trading setting for neo. I always want to trade neo when the buy settings i made by hand hit. I reseve neo in my pairs so that there is always a spot for neo to trade.

**Comment by Masterofcoinak** [comment]
It would be great to make a function like XXX_ignore_max_pairs = true

**Comment by Masterofcoinak** [comment]
It should be closed. Repeated request. #461

**Comment by taniman** [comment]
ignore max trading pairs is already possible
