### ISSUE TITLE
DEFAULT_min_buy_marketcap

### ISSUE THREAD

**Issue by m4xson** [taniman/profit-trailer-enhancements#471]
Often whales and wash traders will boost the volume of a low market cap coin for their own benefit. This will make Profit Trailer buy the coin near the top of a pump & dump and then we make a loss. So it would be good to select by marketcap. Probably more useful than selecting coins by the current volume.

Thumbs up if you want this!

**Comment by Masterofcoinak** [comment]
Would be great, but actually this was already requested many times. See here #19 and support. This one should be than closed

**Comment by Masterofcoinak** [comment]
I think this is also part of the road map
![image](https://user-images.githubusercontent.com/36849981/59042389-a78e0180-887a-11e9-9c41-c123f732b5e2.png)
Should be closed
