### ISSUE TITLE
DEFAULT_min_buy_average_volume

### ISSUE THREAD

**Issue by m4xson** [taniman/profit-trailer-enhancements#472]
As a way to avoid short term pumps causing the volume of a low cap coin to raise temporarily above DEFAULT_min_buy_volume. When this happens it can make PT buy the coin just before it dumps. Using average monthly volume to select would reduce this effect and save us from some pump & dump schemes.

Thumbs up if you need this!

**Comment by Masterofcoinak** [comment]
Would be great, but actually this was already requested many times. See here #19 and support. This one should be than closed

**Comment by taniman** [comment]
duplicate
