### ISSUE TITLE
PT option for delist crypto

### ISSUE THREAD

**Issue by But4ler** [taniman/profit-trailer-enhancements#475]
Via Discord, you already announce the crypto that will be "delist" by an exchange.

Could you publish this directly in the bot via a notification system?
In the event of such an announcement, additional options may be available to trigger: 
 - A panic sell?
 - a SOM?

Thank you.

**Comment by Masterofcoinak** [comment]
I think this was implemented by the new notification system in PT.

**Comment by Masterofcoinak** [comment]
All announcements will be shown now in PT
![image](https://user-images.githubusercontent.com/36849981/59042270-6f86be80-887a-11e9-821f-b4d50d5e6de6.png)
It should be closed.
