### ISSUE TITLE
GUI addition. Change in TCV last 24h and last 7 days and last 30 days,

### ISSUE THREAD

**Issue by m4xson** [taniman/profit-trailer-enhancements#476]
I would like to see how my Total Current Value has changed in the last 24h, last week and last month on the monitoring screen in PT. TCV is more important than sales. The monitoring panel that shows start balance is  not much use to me so I would like to see that replaced with changes in TCV.

**Comment by Masterofcoinak** [comment]
I think the new stats page is what you want
![image](https://user-images.githubusercontent.com/36849981/59041105-45cc9800-8878-11e9-88ff-176a19663de9.png)
Should be closed.

**Comment by m4xson** [comment]
Shame such a simple feature to assess the real performance of PT will be a pro feature.
