### ISSUE TITLE
feature request: display values in satoshi / mbtc

### ISSUE THREAD

**Issue by taniman** [taniman/profit-trailer-enhancements#478]

**Comment by Masterofcoinak** [comment]
TCV in BTC should have at least more numbers behind the 0.000.... . I think that's what you want? Should be normally the easiest thing for PT to implement.

**Comment by Masterofcoinak** [comment]
It should be closed. #565 shows general interface improvements. Support there!!

**Comment by taniman** [comment]
too big of an overhaul
