### ISSUE TITLE
feature request : multi-stage buying 

### ISSUE THREAD

**Issue by matbuf** [taniman/profit-trailer-enhancements#483]
this feature should allow multi-stage buying where you have one set of criteria met before a second set is considered.

let's say the bot should buy at RSI value: 40 but only after RSI reached value: 80.
With this setting (this is just a base) the bot could be a great wave catcher, expecially after pumps/dumps.

**Comment by Masterofcoinak** [comment]
Close this and support #569.

**Comment by taniman** [comment]
yes, this is possible with buy_strategy_level
