### ISSUE TITLE
[Feature Request] Send to pending button

### ISSUE THREAD

**Issue by tennesseedave** [taniman/profit-trailer-enhancements#484]
Add a button in Pairs and DCA GUI pages to instantly send an item to pending with a predefined profit percentage.

send_to_pending_profit_percentage = X
DCA_send_to_pending_profit_percentage = X

**Comment by Masterofcoinak** [comment]
Sad that this is still not implemented.

**Comment by Masterofcoinak** [comment]
Maybe we close this and focus on #565

**Comment by LiamAird** [comment]
Implementation planned
