### ISSUE TITLE
New Bot Strategy : Make 3 "TestMODE" buys and wait some time and BOT choose "better buy"  after some time (count down)

### ISSUE THREAD

**Issue by felipeqga** [taniman/profit-trailer-enhancements#485]
The LiveBOT :: Strategy:BEST3BUY
The robot will make three purchases in test mode and choose the best among the three and make the purchase in REAL (LiveBOT) mode.

For example :
You will place the three purchases in this way on the SIDE of the PAIR in "possible-buys-log"
                      Avr. P%
BUY1: 0.00015045 -1.26

                      Avr. P%
BUY3: 0.00015030 -1.0

                      Avr. P%
BUY3: 0.00015002 -0.26

Purchases occur after a predetermined Timeout.
So the chance that BOT has bought a pair at the wrong rate will decrease dramatically.
![screenshot 2018-11-02 22 02 25](https://user-images.githubusercontent.com/40903953/47946697-f2fbbe00-deed-11e8-9e32-02d833e54791.png)

**Comment by taniman** [comment]
Best to plan your buys accordingly and set DCA levels to accomplish this
