### ISSUE TITLE
Feature Request: Multiple Sell targets

### ISSUE THREAD

**Issue by alexdolli** [taniman/profit-trailer-enhancements#486]
Please implement multiple targets for a position.

Here is how it works:
Pair position is divided in X amount of parts (defined by user) with different sell targets (defined by user, either fixed percentage, or percentage of the last sale).
Let me explain with an example:
I buy [X] coin, total size of the position is 0.04 BTC. Instead of having one target, to sell everything at for example 3%, I define 4 targets in my strategy. 
Target 1: 3%
Target 2: 4%
Target 3: 5%
Target 4: 6%

My Target Stop is -1%.

Position gets to 3% profit, 25% of my position is sold.
Position gets to 4% profit, 25% of my position is sold.
Position gets to 5% profit, 25% of my position is sold.
Position goes back down to 4% (Target Stop - 1%), rest of my position is sold.

You can see the possibilities here. Targets could be fixed percentage amounts, or a percentage on top of the first target, or different higher values for your sell strategy (Target 1: RSI 50, Target 2: RSI 60, etc).

This could help maximize profits. It's kind of like trailing, but not.... I hope that makes sense.

**Comment by antened** [comment]
would like to see this as well

**Comment by leminhduc** [comment]
please consider this as a new coming feature. Reason: I can see a coin would move up +20% in a day, but I want to be safe and do partial sell every 5% 10% 15% 20% to lock my profit

**Comment by vovster** [comment]
Great idea, would benefit all traders. Would like to see this as well.

**Comment by ahumadaz** [comment]
PT Team,
Please add this new feature to new version.

**Comment by Masterofcoinak** [comment]
#369 support this one and close this. Repeated request.

**Comment by PTMaza** [comment]
It will be sweet to have this feature. thanks PT team

**Comment by taniman** [comment]
SOX_take_profit does this
