### ISSUE TITLE
Feature Request: Add ADX (Average Directional Index) Indicator

### ISSUE THREAD

**Issue by ricardodacosta** [taniman/profit-trailer-enhancements#487]
Profit Trailer Moto has been "We trail the trends!" for a long while yet it doesn't offer THE indicator to measure trend strength! Adding the ADX indicator to Profit Trailer can be a game changer for anyone interested in trading with trend. 

As you may know or not, the ADX indicator can tell us when a trend is in "trending" or not. 
Would you like to have a EMACROSS strategy during a trendless trend? NO
Would you like to have a MACD crossing strategy during a trendless trend? NO

There are plenty of strategies that work best when a trend IS trending. By adding an ADX indicator with a value of 25 or higher to your strategy you can ensure the bot will buy ONLY when a trend is in place avoiding a lot of sideway choppy trends.

I hope you take my suggestion!
@YogicCrypto

**Comment by CryptosWORLD** [comment]
i agree ..

**Comment by CryptosWORLD** [comment]
Average Directional Index (ADX)
The Average Directional Index (ADX) helps traders determine the strength of a trend, not its actual direction. It can be used to find out whether the market is ranging or starting a new trend. Its related to the Directional Movement Index (DMI) and, in fact, the latter has the ADX line included. The oscillator ranges between 0 and 100 with high readings indicating a strong trend and low readings indicating a weak trend. It is often combined with directional indicators. The indicator was developed by Welles Wilder, who created several core trading indicators.

**Comment by Masterofcoinak** [comment]
Repeated request #456
