### ISSUE TITLE
Feature Request: Only trade crypto trading above 200 SMA

### ISSUE THREAD

**Issue by alexanderadnanj** [taniman/profit-trailer-enhancements#488]
![image](https://user-images.githubusercontent.com/34095084/48417879-df3c2d00-e721-11e8-8736-7b7438ca6103.png)

I'll like to apply this RSI2 strategy and one of the rules is trade when the price action is above SMA200.

https://stockcharts.com/school/doku.php?id=chart_school:trading_strategies:rsi2

**Comment by thysbotwhisper** [comment]
This can be done with available indicators.

Buy strat = smagain (price above lowest of fast and slow smas. Set fast and slow both at 200, and you have price above sma200)
value = 0.01
limit = 100

SMA_cross_candles = 2
SMA_candle_period = 86400 (this is daily)
SMA_fast_length = 200
SMA_slow_length = 200

**Comment by alexanderadnanj** [comment]
try that, but is picking coins trading bellow SMA200

**Comment by Masterofcoinak** [comment]
with the formula function, you could just set everything bellow SMA200 to be (!)
![image](https://user-images.githubusercontent.com/36849981/59045309-1883e800-8880-11e9-8e8d-a4b3a5a1c5b1.png)
Should be closed, if i am correct!?
