### ISSUE TITLE
DCA Webinterface upgrade

### ISSUE THREAD

**Issue by DrCzerni** [taniman/profit-trailer-enhancements#49]
It would be nice to see advanced infos in the DCA section of the web interface.
For Example Klick on a "+" and you can see details for every DCA Level like
when the bot buys
bought price
avarage after buy

and it would be awesome if you could see the same things at the sales log.
that could help a lot to analyze the strategy.

**Comment by NeXtAntiX** [comment]
its not very clear at all when or if you will get out of the DCA, and at what level. The interface dose, like you say need an over-hall. I really want to just see what is important at a glance, seems to be so much redundant information on the DCA, screen..   Just for example:  Volume.. Not to sure why the volume is that important, when your already deep in the DCAsh#t. 

I might be more happier / comfortable if i could see when I'm 7 Levels DCA deep, I  might get out of that trade in a 2% up shift. Looking at a sea of red is not helping me.  Keep the information relevant to that screen and condition, is key.

**Comment by clownfish44** [comment]
PtTracker has this and has been requested to merge them here https://github.com/taniman/profit-trailer-enhancements/issues/5
