### ISSUE TITLE
Absolute price buy and sell orders

### ISSUE THREAD

**Issue by thysbotwhisper** [taniman/profit-trailer-enhancements#490]
Is it possible at all to allow setting pending buy and sell orders at absolute price levels instead of percentages and indicator levels?

Example:

In PT enter a couple of pending orders manually to buy btcusdt at 5020, 4920 and 4880.

**Comment by thysbotwhisper** [comment]
And stoplosses! When I look at charts, I can sometimes see levels that should trigger stoplosses when they're crossed. Would be good to be able to use absolute levels for these too..

**Comment by Masterofcoinak** [comment]
Possible meanwhile.
https://wiki.profittrailer.com/doku.php?id=buy_and_sell_strategies#fixedprice

**Comment by Masterofcoinak** [comment]
with the formula you can even make several fixedprices for sell and buy.
Should be closed.
