### ISSUE TITLE
Actually selling at gain despite trail

### ISSUE THREAD

**Issue by jadiesel** [taniman/profit-trailer-enhancements#491]
It would be nice if the bot would sell at gain, despite trailing.
As it stands now, you can start trailing, but if your trail drops below your gain, it stops and resets.

Example:
gain 2
trail 0.25

Coin goes up to 2.24. It then drops back under 2. The sale is lost, because the bot won't sell AT the gain level.  This forces us to use smaller trails, and lower gains to compensate.

**Comment by SgtBatten** [comment]
we have introduced a number of take profit and trailing stop loss settings to give you the flexibility you need for this
