### ISSUE TITLE
TCV percentage change in monitor

### ISSUE THREAD

**Issue by thysbotwhisper** [taniman/profit-trailer-enhancements#492]
I want to see if I'm making profit.

I'd love to see whether my bot is porfitable, including the alts held in pairs, dca and pending. I am more interested in seeing the average increase/decrease of my total value over the last day and week, than seeing at what average percentage the bot has sold...

**Comment by Masterofcoinak** [comment]
![image](https://user-images.githubusercontent.com/36849981/59044853-369d1880-887f-11e9-9714-b7def34fef0c.png)
Should be closed.
