### ISSUE TITLE
Please ADD  multiple STOPLOSS triggers

### ISSUE THREAD

**Issue by felipeqga** [taniman/profit-trailer-enhancements#493]
_stop_loss_trigger_1
_stop_loss_trigger_2
.........
_stop_loss_trigger_XXX
Because as the DCA increases the value increases so the Trigger have to decrease in order to reduce losses because of the high value of the DCA.

Thank you

**Comment by Masterofcoinak** [comment]
This is possible meanwhile. It should be closed.

**Comment by Masterofcoinak** [comment]
Should be closed
