### ISSUE TITLE
[FEATURE REQUEST] EMA/SMA CROSS using different Candle periods

### ISSUE THREAD

**Issue by CryptoCapo** [taniman/profit-trailer-enhancements#494]
![image](https://user-images.githubusercontent.com/39453300/48878972-7ca4fa00-edcf-11e8-98da-8064bdf8b067.png)

![image](https://user-images.githubusercontent.com/39453300/48879080-e8876280-edcf-11e8-9b4c-97d6b6422ccd.png)

On tradingview I have backtested a strategy screenshotted above - a very effective EMA/SMA Cross strategy that monitors the cross of two moving average lines on DIFFERENT Candle periods. Profit Trailer currently only allows fast_length and slow_length of MA lines on the SAME Candle period. Below is a conceptual config example to better explain: 

--Indicator.Properties--
EMA_cross_candles = 3
EMA_candle_period = 300        //I'm only using 5 min candle period on the fast length
EMA_fast_length = 3       

EMA_candle_period_2 = 900    //Now I need to look at 15 min candle period for the slow length
EMA_slow_length = 24

From my backtesting results on tradingview/PineScript, this enhancement can yield much better results from the current Profit Trailer EMA/SMA Cross.  The example below is OMG/BTC on Binance, which is an average performing coin with this backtest. This backtest was conducted from 1 SEP to 21 NOV 2018 using a 0.075% commission fee (similar to Binance fees using BNB coin for fee), and a Buy & hold over the same period would have yielded a 27% loss.

Please consider implementing this!!!

**Comment by CryptoCapo** [comment]
![image](https://user-images.githubusercontent.com/39453300/48878972-7ca4fa00-edcf-11e8-98da-8064bdf8b067.png)

**Comment by CryptoCapo** [comment]
![image](https://user-images.githubusercontent.com/39453300/48879080-e8876280-edcf-11e8-9b4c-97d6b6422ccd.png)

**Comment by grantcause** [comment]
You can do this now using Strategy Labels feature within ProfitTrailer see here: https://wiki.profittrailer.com/doku.php?id=pairs.properties#default_a_buy_strategy_label

**Comment by CryptoCapo** [comment]
> You can do this now using Strategy Labels feature within ProfitTrailer see here: https://wiki.profittrailer.com/doku.php?id=pairs.properties#default_a_buy_strategy_label

I don't believe the Strategy Labels feature will solve this issue. EMA cross in Profit Trailer only allows for a single EMA_candle_period. The code would not recognize a second candle period, so the labels don't really address this.

**Comment by taniman** [comment]
COMBIMA would accomplish this possibly

**Comment by ChicodelMar** [comment]
Hello, is there a PT setting outthere? Thanks

**Comment by ChicodelMar** [comment]
hello, can you please make a Prfoit trailer set file from this? to buy / sell futures
