### ISSUE TITLE
[Feature Request] Fully configurable price_trigger_market

### ISSUE THREAD

**Issue by Whitesnake67** [taniman/profit-trailer-enhancements#495]
price_trigger_market only works with ETH, BTC, BNB, XMR and only for a 24h time frame.
I like to have it that it works with all pairs in "Possible Buy" in a given time or
to have a similar buy/sell strategy.

For example:
"don't buy that coin if the price drops 3% in 5 Minutes" 
or 
"don't buy that coin if price rises 3% in 5 Minutes".

So it eventually needs a new indicator (for timeframe) and could be done as
a buy/sell strategy "TRUE if NOT price drops x% in new-inicator-timeframe" or so ....

Or it could be done as a upgraded SOM-strategy, but that will do SOM for all coins,
unless you have a coin-specific SOM ...

Regards,
Markus

**Comment by Masterofcoinak** [comment]
#499 That was already often suggested, but currently you can do it also with PTMagic. Look for Northstar.

**Comment by Masterofcoinak** [comment]
Should be closed refer to #19
