### ISSUE TITLE
[Feature Request] New strategy : Trend (based on EMA)

### ISSUE THREAD

**Issue by Whitesnake67** [taniman/profit-trailer-enhancements#496]
Hello,
at EON-bot (it's gone) they had a very simple but incredible powerfull "Trend" strategy, base on EMA.
It worked like this:
"We have a uptrend if the actual EMA is higher than the candle before" and
"We have a downtrend if the actual EMA is lower than the candle before"

Problem with TrailingBuy and TrailingProfit is that they could be true, even if the overall-trend is still going up or down.
EMA can easily smooth fluctuations and the bot can follow up/down the trend rather than buy/sell to early.

Look at this. EMA 3 is the white line:
![ema-trend](https://user-images.githubusercontent.com/45128772/49153044-d730df80-f314-11e8-8ae5-66806953ac50.PNG)

Trailing Profit will likely sell the coin at the red arrow, because price is dropping temporary.
EMA-Trend will follow up the EMA to the top and maximise the profit (green arrow).

Me and many other users were using this strategy long time with EON-bot and it worked great as a sell-strategy. 

It should also work as a buy strategy, but they never implemented it.

Variables could be how many candles to look back (instead of just one) and the rise % of the EMA instead of just "if it's higher".

Regards,
Markus

**Comment by Masterofcoinak** [comment]
We could close this and support #569. Bot more or less want the same.

**Comment by taniman** [comment]
This can be accmplished with current built in logic
