### ISSUE TITLE
[Feature Request] GAIN for buy

### ISSUE THREAD

**Issue by Whitesnake67** [taniman/profit-trailer-enhancements#497]
Hello,
I like to have the sell strategy GAIN also as a BUY STRATEGY.
I'm NOT talking about that LOSS strategy!
I like to buy a coin if the price rises a minimum % in a given time, to catch uptrends/pumps.

So let's say "buy if the coin rises 4% from the last x candles" and then back it up with RSI and/or MACD.

I need:
DEFAULT_A_buy_strategy = GAIN
DEFAULT_A_buy_value = x   <- defines how much the coin should rise to buy

GAIN_candle_period = x   <-  defines the candle size (in seconds)
GAIN_candles = x  <- defines how much candles back the bot should look

Thanks in advance ;-)

**Comment by hemant0111** [comment]
I am also looking this Features.  How soon can we have ?

**Comment by Masterofcoinak** [comment]
repeated request #464

**Comment by taniman** [comment]
PROFITPERCNTAGE and  CHANGEPERCENTAGE strategy is implemented
