### ISSUE TITLE
[Indicator Request]: CCI to be added for PT to use

### ISSUE THREAD

**Issue by Seeletse** [taniman/profit-trailer-enhancements#498]
The CCI Indicator is a little-used indicator that has proven very effective for me to use whilst trading. Often, you can simply buy when it goes low, and sell as it goes high, and make at least a few percent, if not tens of percent. Even better if you catch it right after it turns -- perfect for a trading bot.

The CCI Indicator is a number calculated based off historical and present price. It seems to be similar to RSI but seems to be more accurate at predicting price changes when it turns. When combined with a price % trailing BUY or SELL order, it could be deadly!

Example: on BTCUSD, at 3-8 21:50 (PST) CCI (20) turns upwards from -297 and begins to climb to 139. PT could easily trail as it passes -100 (or for more gains, -150 or -200), buy when it turns, and trail as it passes +100, sell when it turns again. Especially when combined with price action (because it is not 100% every time, especially on lower time frames).

This strategy above would result in BTCUSD buy @ $8390 and sell @$8763, a 4.4% increase in 1 hour.

http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:commodity_channel_index_cci

**Comment by mag106** [comment]
very cool indicator, I don't understand why it hasn't been added yet

**Comment by PV111** [comment]
Great indicator, hope to see in PT as soon as possible

**Comment by mirror-ru** [comment]
Indicator is very useful for trading now

**Comment by Otten-Ascom** [comment]
It would be nice

**Comment by EdjOne** [comment]
Nice, was surprised that this indicator still not implemented, hope to use it very soon))

**Comment by taniman** [comment]
Implemented for 2.5.0
