### ISSUE TITLE
[ FEATURE REQUEST ]: Automatic configuration switch when triggered

### ISSUE THREAD

**Issue by zin22** [taniman/profit-trailer-enhancements#499]
As we know the crypto market is very volatile and often we find that our current strategy configurations are not suited for a particular market and we always have to manually switch configs or tweak them to optimise gains and reduce risk even within 24-48hr periods !

Somehow if we can in-cooperate an automated configurations changer based on certain trigger points such as BTC percentage drop/rise or consecutive buys, or any other parameter which gives a good indication of market trend.  So  basically if any of these parameters get triggered then the bot will switch our config automatically.  

I use lowbb buy strategy and i use minus figures for buys and when there is a strong altcoin rally then this configuration does not do alot of buys so i would love to have an automated way to change my config according to the market. 

i think an automated config switch will be a game changer and really live up to the Automated trading experience.

**Comment by Masterofcoinak** [comment]
Use The North star PTmagic strategy to do so.

**Comment by Masterofcoinak** [comment]
Should be closed refer to #19
