### ISSUE TITLE
Suggested approach to backtesting.

### ISSUE THREAD

**Issue by l2trace** [taniman/profit-trailer-enhancements#50]
Sorry I have to because I think this is really useful. 

But if there was a way to put PT into 'capture mode' and  write the data that it receives from the exchange APIs to the filesystem as it receives it.  Then you could  run the backtrace on only  those files. 

The limitations then would be what the users  system can bear. 

Any sorry to beat dead horse I am not trying to be offensive.

**Comment by clownfish44** [comment]
Backtesting - We do not have the data nor infrastructure required to build a proper back testing logic. (Anyone can provide the data?)
