### ISSUE TITLE
Support any excange that has XRP as base pair

### ISSUE THREAD

**Issue by hemant0111** [taniman/profit-trailer-enhancements#500]
I would like to Trade where  XRP  is a base currency. Can we have support to any such exchange.
One exchange I know is - https://trade.coinfield.com

Appreciate your comments on this.

**Comment by Masterofcoinak** [comment]
Already. Binance has a XRP pair ;)
![image](https://user-images.githubusercontent.com/36849981/59044236-13be3480-887e-11e9-8b21-6ea367aaf6d9.png)
