### ISSUE TITLE
[Feature Request] Scripting ability added such as pinescript to add custom TV strategies

### ISSUE THREAD

**Issue by UplandMines** [taniman/profit-trailer-enhancements#502]
Be awesome if you could add an ability to create your own strategies based on a scripting language like pinescript or somehow incorporate or Tradingview accounts into PT that will trigger when coded alerts are met.

**Comment by KryptoView** [comment]
This is a feature set that is sorely needed, I hope its in the roadmap Q3

**Comment by Masterofcoinak** [comment]
Already implemented
https://wiki.profittrailer.com/doku.php?id=signals
