### ISSUE TITLE
Add config option to disable Fiat currency from monitor

### ISSUE THREAD

**Issue by Helmi** [taniman/profit-trailer-enhancements#504]
It takes a lot of room and is totally useless information if you don't care about your momentarily profit in USD, EUR or whatever your currency is.

It would be good to have a config option to not show any Fiat values at all.

**Comment by joechipz** [comment]
agree, 
that would be very useful

**Comment by taniman** [comment]
Screenshot?

**Comment by Helmi** [comment]
@taniman Screenshot? Of what?

**Comment by taniman** [comment]
Are you trying to remove these?
![image](https://user-images.githubusercontent.com/6751341/50929804-927c8600-1434-11e9-898c-fc2ef0a771a5.png)

**Comment by Helmi** [comment]
well just everything Fiat. It's overall these days.

- In the header line
- On the Dashboard (your screen)
and even worse
- in the Logs (Pairs, DCA, Pending, Sell)

I understand why some people may want it but I don't care about profits or losses in the current day BTC (or whatever coin) value in USD (or whatever other Fiat value). I'd prefer to focus on my quote currency and it would be great if I'd had an option to do so.

**Comment by LiamAird** [comment]
@taniman Can you add SHOW_FIAT BOOL to the account array?

**Comment by taniman** [comment]
I have added GUI_SHOW_FIAT for next release

**Comment by taniman** [comment]
added to 2.5.0
