### ISSUE TITLE
***critical issue ***----limitation of Profit Trailer - Unable to Trade High Volume - "Order Book Low"  Issue

### ISSUE THREAD

**Issue by hemant0111** [taniman/profit-trailer-enhancements#505]
I found very big limitation of Profit Trailer - Unable to Trade High Volume -

 "Order Book Low"  Issue

I am trading with 50 ETH & more , & Bot is unable to Buy coins.

I checked with support team & they explained that , bot will buy in single order  & no functionaly to place order such as - 'LIMIT ORDER'  like what we have  in exchange.

Please advise on this ASAP>

Many Thanks,
Hemant

**Comment by nocturnal86** [comment]
That could be our solution for that

https://github.com/taniman/profit-trailer-enhancements/issues/523

**Comment by Masterofcoinak** [comment]
https://wiki.profittrailer.com/doku.php?id=pairs.properties#default_min_orderbook_price_slippage_percentage
https://wiki.profittrailer.com/doku.php?id=dca.properties#default_dca_min_orderbook_price_slippage_percentage
Should be closed
