### ISSUE TITLE
Choose what DCA level

### ISSUE THREAD

**Issue by cryptopolitics** [taniman/profit-trailer-enhancements#506]
I would love to be able to manually be able to choose what DCA level a pair should use.
Thanks!

**Comment by SgtBatten** [comment]
You can set the DCA buy times and then the coin will use the next number
https://wiki.profittrailer.com/doku.php?id=hotconfig#dca_set_buy_times

**Comment by Seeletse** [comment]
If i've reached my max DCA, I guess i would have to reduce the DCA levels
for the bot to DCA further. Instead of increasing the Max DCA for all pairs?

**Comment by Masterofcoinak** [comment]
Should be closed.
https://wiki.profittrailer.com/doku.php?id=hotconfig#dca_set_buy_times
@Seeletse you could also make a coin specific Max DCA
