### ISSUE TITLE
Feature Request: Timer for buy triggers

### ISSUE THREAD

**Issue by mygreeneggsandham** [taniman/profit-trailer-enhancements#509]
A timer that would allow you set a timeframe for when a buy trigger is valid. 
Example 1: If buy trigger is met, the bot has xxx minutes to buy the coin. After that time the buy trigger is reset until the trigger conditions are met again. 
Example 2: If buy trigger is met, wait at least xxx minutes before buying. 

This would allow for some interesting strategies, while avoiding certain undesirable patterns.

**Comment by JohnSec2020** [comment]
Yes this is my request too. To set a time for buy between price changes .
Example: Set xxx seconds , the bot wait xxx seconds between price change and act to buy.
Please add this , its so important. 
Something like this already is for selling in the bot.
thanks

**Comment by taniman** [comment]
already possible with buy_within_time_period
