### ISSUE TITLE
Password for Config

### ISSUE THREAD

**Issue by WRCarlile** [taniman/profit-trailer-enhancements#51]
Add an additional password to get into config menu.

**Comment by clownfish44** [comment]
There is already a password for the config as you must log into pt to even get to the config's. If you would like it more secure please add ssl to your bot as seen here https://wiki.profittrailer.io/doku.php/setup_ssl

**Comment by WRCarlile** [comment]
But what if I want to show PT to my friend and they could mess with Config? It's kind of annoying to turn off config and then turn it on in the settings.

**Comment by WRCarlile** [comment]
@clownfish44 pretty sure this is a valid feature request and a very easy one to implement.
