### ISSUE TITLE
Feature Request: MFI

### ISSUE THREAD

**Issue by des1re10** [taniman/profit-trailer-enhancements#512]
Hi PT Team,

we definitly need senseful Volume Indicators such as MFI in order to create useful strategies.

The OBV itself is quite useless, since it doesnt consider price volatility.

I refer also to the feature request of the ADX + DI indicator to measure the strenght of a trend! Thats very important for useful trading strategies!

**Comment by CryptosWORLD** [comment]
i agree we need an  price volatility indicator.

Feature Request: Add ADX (Average Directional Index) Indicator #487
https://github.com/taniman/profit-trailer-enhancements/issues/487

[FEATURE REQUEST] Add ADX indicator #456
https://github.com/taniman/profit-trailer-enhancements/issues/456

**Comment by CryptosWORLD** [comment]
Average Directional Index: uses the ADX indicator to trade only when trends are strong enough.

**Comment by CryptosWORLD** [comment]
i say a big yes when it is a new indicator
i add also this

very good article at my opinion https://www.tradeciety.com/how-to-choose-the-best-indicators-for-your-trading/ what is the suggestion .. more indicators

**Comment by obsidain001** [comment]
Yes! Please add this!!

**Comment by taniman** [comment]
Added in 2.4.28
