### ISSUE TITLE
Add new indicator =Williams  alligator 

### ISSUE THREAD

**Issue by Pintovalle** [taniman/profit-trailer-enhancements#513]
Hi support this indicator is really good in simple to used in in trading wied it will be good for profit trailer i think this indicator if is add it to profit trailer we can kill it made lot good trades there videos in youtube how to  used in all the good staff please support consider adding this indicator I will be awesome for PT in all PT family out here thank you

**Comment by CryptosWORLD** [comment]
i say a big yes when it is a new indicator
i add also this

very good article at my opinion https://www.tradeciety.com/how-to-choose-the-best-indicators-for-your-trading/ what is the suggestion .. more indicators

**Comment by taniman** [comment]
Pretty complicated indicator. We will think of revisiting it in the future. but it's a pass for now
