### ISSUE TITLE
Enable fixed cost for DCA buys instead of percentage

### ISSUE THREAD

**Issue by Helmi** [taniman/profit-trailer-enhancements#514]
I'd like to use a fixed cost for every DCA buy instead of the percentage. 

Here's a suggestion:

```
DEFAULT_DCA_buy_percentage = 100
DEFAULT_DCA_buy_fixed = 0.1
DEFAULT_DCA_buy_fixed = initial
DEFAULT_DCA_buy_percentage = initial
```

first line is current functionality, second line would by 0.1 base coin worth of the coin, third line would by for the same cost as initial buy. Last line would by the same percentage as initially when DEFAULT_initial_cost_percentage is used - not sure if the last one is going too far.

**Comment by taniman** [comment]
DCA_buy_cost was implemented
