### ISSUE TITLE
PDHIGH setting

### ISSUE THREAD

**Issue by cryptofxasia** [taniman/profit-trailer-enhancements#519]
This suggestion is for PDHIGH setting in profit trailer. Possible please allow the time frame to be selected manually when do the settings. That means if the price goes higher within certain time frame, will open a buy order. This is more like forex price action strategy. Initiation of introducing PDHIGH by PT team indeed was a very good move as this is more towards PRICE ACTION STRATEGY. i noticed price action strategy stands a head of any other indicator strategy

**Comment by philfromqueens** [comment]
Do you mean, PDHIGH we should be able to look for a high in the previous 10 candles instead of the just the previous 1 candle?  because if that is what you mean then I definitely agree that it should be implemented.

**Comment by cryptofxasia** [comment]
Hi,thanks for your reply.

Yes  exactly. If you can create a parameters that can give a choice of
looking back at least up to 10candles and the moment the current candle
stick formation is breach the level of this 10 candle stick then the order
trigger.
You can customize it based on
1) how many candle stick to look back. Probably we can look at the highest
level reached.
2) The time frame choice because sometimes the highest level in 1H would be
not same as in 4H.

Thanks alot and please do not hesitate to contact me if you have any
questions.

Regards

**Comment by taniman** [comment]
use PDHIGH_range, this is already in the bot
