### ISSUE TITLE
Add BitMEX or/and Okex exchanges

### ISSUE THREAD

**Issue by robotlovefarm** [taniman/profit-trailer-enhancements#52]
BitMEX has almost 50% more volume than Binance and no trading fees. Okex has the same as Binance. The addition of those would make PT trading so much faster for the ones that use more than one bot. Also, we need a new exchange as Polo has very low volume

**Comment by clownfish44** [comment]
More exchanges was requested here https://github.com/taniman/profit-trailer-enhancements/issues/46

**Comment by robotlovefarm** [comment]
None of those are the ones I recommend and the reasons are completely different
