### ISSUE TITLE
Add Signal Provider to the Buy/DCA/Pending and Sales log

### ISSUE THREAD

**Issue by mehtadone** [taniman/profit-trailer-enhancements#520]
So I know if I have a big bag of DOGE, I know which provider to blame. Or if I make a lambo, I know which provider to tip

Similar to this other bot: 

![image](https://user-images.githubusercontent.com/8123496/52065198-ed098d80-256d-11e9-99e7-73f7dc479db8.png)

**Comment by taniman** [comment]
The buy/sell signal indicates which signal provider signal we received..
