### ISSUE TITLE
When BTC goes down panic sell gets ON and then change all BTC to TUSD

### ISSUE THREAD

**Issue by LeoGrandson** [taniman/profit-trailer-enhancements#521]
I would love that if BTC goes down "x" percent  or stochrsicross -0.1 then panic sell gets activated with DCA too and when everything is sold then automatically BTC gets converted to TUSD.  You guys will be like god to me if this can be real.  Or... does it already exist and I don't know yet?

**Comment by LeoGrandson** [comment]
That also includes panic sell of all DCA ( eg.  on 1D chart)

**Comment by cryptogeek0610** [comment]
You already can mate with PTF ;)

**Comment by mygreeneggsandham** [comment]
Would be a great feature without having to buy a 
$200 3rd party program do it for you. This is a great suggestion.

**Comment by Masterofcoinak** [comment]
already requested #363
