### ISSUE TITLE
DEFAULT_DCA_buy_trigger = true

### ISSUE THREAD

**Issue by victorlmt1** [taniman/profit-trailer-enhancements#522]
Hello mr. Taniman,

I`m here for a simple request: Make DEFAULT_DCA_buy_trigger possible to be ignored or always activated like with a "true" option.

Let me explain the reason I need this: I use PDHIGH as a DCA strategy, so sometimes my initial buy catches the very bottom of a PAIR and I wanted DCA to increase the ammount bought, increasing the profit, so DEFAULT_DCA_buy_trigger should be a positive value to trigger DCA.

Other times I don`t catch the very bottom, and my DCA waits until the pair starts to recover, and in this case DEFAULT_DCA_buy_trigger should be a negative value to trigger DCA.

As you can see, in both ways I need DCA to be activated, it does not matter if its a negative or positive value, all that matters is my strategy being true.

Thanks for you attention and I hope you consider adding this option.

Cya

**Comment by Masterofcoinak** [comment]
Should be closed
https://wiki.profittrailer.com/doku.php?id=dca.properties#default_dca_ignore_buy_trigger
