### ISSUE TITLE
Bypass orderbook low

### ISSUE THREAD

**Issue by nocturnal86** [taniman/profit-trailer-enhancements#523]
PT when trying to buy looks at the lowest price in the orderbook. If there are not enough coins, we get "orderbook low". 

The main idea is to have a command to tell PT to look also the next 3 orderbook asks and if  there is not + 1% difference for example from the lowest, to buy.

This way "tight" dca buys or normal won't be missed.

**Comment by Masterofcoinak** [comment]
https://wiki.profittrailer.com/doku.php?id=pairs.properties#default_min_orderbook_price_slippage_percentage
https://wiki.profittrailer.com/doku.php?id=dca.properties#default_dca_min_orderbook_price_slippage_percentage
Should be closed
