### ISSUE TITLE
Bitmex sell with "post-only" flag

### ISSUE THREAD

**Issue by mexxBf** [taniman/profit-trailer-enhancements#524]
Its quite expensive to sell with PT if it sets a limit order that gets filled instantly. Flaging the sell with "post-only" would reduce the cost dramatically, because the limit order has to appear in the orderbook first.

https://www.bitmex.com/app/orderTypeFAQ#Post-Only-Order-Example

**Comment by mkarulin** [comment]
Upvote. Please get this done.

**Comment by kunalsen83** [comment]
I once backtested it. The results - without trading fees (which is possible if even one of them is a limit order in Bitmex), the end profit was more than 2.5 times in 1 year compared to 0.15% total trading fees for a buy and a sell. Particularly in smaller time frames, it is of immense advantage to save trading fees. Please do.

**Comment by taniman** [comment]
This is not that type of bot.
