### ISSUE TITLE
GUI buttons with trailing

### ISSUE THREAD

**Issue by mexxBf** [taniman/profit-trailer-enhancements#525]
Please add trailing when buying / selling with GUI buttons. it would help getting better prices :)

**Comment by CryptosWORLD** [comment]
also when trailing is enabled (= armed) we can see it graphically in pairs-log and dca-log

**Comment by Masterofcoinak** [comment]
But this Trailing button should have 2 options, A must buy even it starts to trail in the wrong direction or Trail as pt always does and cancel if trailing fails. Could be done in the popup window

**Comment by Masterofcoinak** [comment]
maybe we can close this and use #563

**Comment by LiamAird** [comment]
Will need backend change to allow the current buy / sell buttons to enable trailing instead of direct buy/sell
@taniman is that feasible?

**Comment by taniman** [comment]
Not gonna build this. Manual buy makes the assumption that you do not need bot control. Else change a setting in config to make the 1 coin sfart trailing
