### ISSUE TITLE
Dollar Cost Selling: Sell strategy/addon

### ISSUE THREAD

**Issue by swanfield1979** [taniman/profit-trailer-enhancements#527]
Ok so you use DCA and lets say you DCA 5 times. Now the price is avareged down and when it will return now you will sell for example at a 1% profit. But in a lot of cases the bounce is better. The bounce might be 2% of even more. Example 2 is that the pice might go to 0.75% and you would not sell for 1% but the greater piece of your position is 1% profit.

So here is what I would like to see implemented. I DCA5 a position. And it returns to breakeven. I would like to sell my initial position. This way most of my position will be bought lower. Then when it goes to 0.25% i would like to sell mij DCA1 position. When it goes to 0.35% I would like to sell my DCA2 position, etc.

Ofcourse trailing would be nice to have on every position sell. 

DEFAULT_DCA_sell_position_0 = 0.25%
DEFAULT_DCA_sell_position_1 = 0.30%
DEFAULT_DCA_sell_position_2 = 0.35%

This way you can get the most out of your biggest position while selling off portions.

**Comment by robheath90** [comment]
I would like this implemented as well, but for a slightly different reason. I have a Tradingview Script which provides 6 independent buy and sell signals for a particular coin. I'd like to be able to build up my DCA bag and also sell that bag in equal parts, based on my Tradingview Signal alone and not the profit/loss of the bag. The logic could be the complete reverse of DCA as follows:

DEFAULT_DCA_max_sell_times = 6
DEFAULT_DCA_A_sell_strategy = SIGNAL

DEFAULT_DCA_sell_percentage_6 = 16.6
DEFAULT_DCA_sell_percentage_5 = 20
DEFAULT_DCA_sell_percentage_4 = 25
DEFAULT_DCA_sell_percentage_3 = 33.3
DEFAULT_DCA_sell_percentage_2 = 50
DEFAULT_DCA_sell_percentage_1 = 100

For people using an ordinary GAIN strategy this would be useful for averaging down the cost of long term or heavy DCA bags, I'm sure we can all relate to that pain over the last 18 months!!

**Comment by Masterofcoinak** [comment]
I had something similar in my mind but it got talked away.
https://github.com/taniman/profit-trailer-enhancements/issues/320

**Comment by taniman** [comment]
SOX_take_profit to take partial profits
