### ISSUE TITLE
Time based autoclose

### ISSUE THREAD

**Issue by mehtadone** [taniman/profit-trailer-enhancements#528]
It would be good to have the option to close an open position after a certain period of time. For example, if a coin hasn't sold in 3 days, then sell.

**Comment by Seeletse** [comment]
This would be nice. But how will it handle coins already being hedl if enabled?

**Comment by mehtadone** [comment]
You mean hodl coins? Those would be excluded from trading anyway wouldnt they or have a misunderstood?

**Comment by Seeletse** [comment]
I was actually referring to the bags most of us have

**Comment by ChipCrypto** [comment]
You would be able to select coin pairs not to sell. Simple.

**Comment by mehtadone** [comment]
Duplicate of https://github.com/taniman/profit-trailer-enhancements/issues/608
