### ISSUE TITLE
Add STOCH K and D

### ISSUE THREAD

**Issue by runein** [taniman/profit-trailer-enhancements#529]
Hello.

I see that STOCHRSI K and D is implemented as standalone indicators based on Tradingview.

What about STOCH K and D? I do not see those in ProfitTrailer.

I think it should be added as STOCH can be oversold for a long time and a useful tool (indicator) to have.

Rune

**Comment by SgtBatten** [comment]
hs been in for a while now.

https://wiki.profittrailer.com/doku.php?id=buy_and_sell_strategies#stoch
