### ISSUE TITLE
MIN buy Spread

### ISSUE THREAD

**Issue by crazypool2019** [taniman/profit-trailer-enhancements#530]
Hi,

PT has max buy spread, can u add min buy spread ?
for example
DEFAULT_max_buy_spread = 2.5
DEFAULT_min_buy_spread = 1.0
so the bot not buy coins where spread < 1.5 
i want set PT for coins with spread: [1.0 to 2.5]

thanks

**Comment by taniman** [comment]
Added to 2.5.0
