### ISSUE TITLE
Coin or coins acumulation

### ISSUE THREAD

**Issue by alexanderadnanj** [taniman/profit-trailer-enhancements#531]
I will like to have the following feature in order to accumulate one or more coins

using the market setting i'll like to place the coin that I want to accumulate and in enabled pairs there market where they are located
 
one coin example
market = EOS
enabled_pairs = BTC, USDT

multiple coins
market = EOS, TRON
enabled_pairs = BTC, USDT

**Comment by taniman** [comment]
this is not possible with current bot framework.
