### ISSUE TITLE
Paper Trading - PT2 test mode

### ISSUE THREAD

**Issue by CryptosWORLD** [taniman/profit-trailer-enhancements#532]
can i suggest a  way to have more free paper trading = test mode example a free licence key that works only on test mode ?
that with helps:
a) all that have PT2 can tray many more strategies in paper testing (these will help strategies be better and more profitable, that means more traders use PT2)
b) new customers that not have buy yet PT2 to try it before buy it in testing mode only 
b2) with marketing promotion can help more sells of PT2 licences come in
c) maybe a new channel for this "test mode only"  
d) more traders use test mode of PT2 and with some feedback this feature can be better in time

**Comment by CryptosWORLD** [comment]
Exclude Test Mode bots from license usage https://github.com/taniman/profit-trailer-enhancements/issues/326

**Comment by CryptosWORLD** [comment]
if in the future these free licence (for test mode only) not giving all that i wrote above you can disable it easily

**Comment by Seeletse** [comment]
this should make for a great way of testing strategies without losing out
on actual trading

**Comment by cryptogeek0610** [comment]
It does need 1 api connected to your license key. But if you'd use that api key for all your test bots, it will still work. Just change your Start_Balance for each strategy if you'd like see different balances for your test bots

**Comment by CryptosWORLD** [comment]
also a great idea is the  "free licence key that works only on test mode" works also in  Bitmex Testnet,
so all PT2 traders can use it to test their strategies there ...

**Comment by LiamAird** [comment]
Possible with: https://profittrailer.com/product/pt-paper/
