### ISSUE TITLE
Feature Idea: Error Correction

### ISSUE THREAD

**Issue by cavaliertech** [taniman/profit-trailer-enhancements#533]
From time to time, I make a mistake entering a price in HotConfig and can't fix it before the bot sells at what it logs as an incorrect profit (sometimes massively so). This can make profit-taking a headache (I use the monthly profit shown in PT Tracker to decide when and what to take). I currently use an off-bot spreadsheet to figure this out, but it would be great if there were a simple way to access the data and change the buy price for a trade so that the Sales Log can be more accurately relied upon.

**Comment by Masterofcoinak** [comment]
Support this #565 and your problem will never happen again. I would close this one.

**Comment by taniman** [comment]
delete the record and add a new record with the correction using GUI buttons
