### ISSUE TITLE
PDHIGH refinement: specify high/low or open/close

### ISSUE THREAD

**Issue by thysbotwhisper** [taniman/profit-trailer-enhancements#534]
Would be nice to be able to configure the PDHIGH setting to look at candle high&low like it currently is, or at open & close, so you just get the candle body and not the wicks.

**Comment by taniman** [comment]
PDHIGH does not currenty look at the LOW only at the HIGH.
So you want to look at the CLOSE instead of the  HIGH?

But say you have a red candle. that closed. when looking if the price is currently higher than previous candle close. That might give a false sense the direction of the trend right?

Understand what I mean?

**Comment by thysbotwhisper** [comment]
@taniman ah yeah I see the problem with price being above the close on a red candle, that it might give too many false positives to ever be usable. I think you're right. If I change my mind I'll reopen the topic.

**Comment by cryptojuggernaut** [comment]
buying when a candle opens higher then the previous close not the candle high . i don't want to buy on a candle close. the wicks on some coins are insane.
DEFAULT_A_buy_strategy = MACD
DEFAULT_A_buy_value = .000000001                                                                                                                                                                                                                                                                                                                                                     default_B_buy_strategy = pdopen
default_B_buy_value = 0.25
DEFAULT_B_buy_value_limit = .5

is this possible. i can see the difficulties buying a candle close. buying when a candle opens sounds more feasible
