### ISSUE TITLE
Feature Request: Stop loss triggers when EMA/SMA is crossed

### ISSUE THREAD

**Issue by DaveLee305** [taniman/profit-trailer-enhancements#536]
Can you add the ability for us to configure a stop loss which will trigger when the price crosses an EMA or SMA?

**Comment by thysbotwhisper** [comment]
In 2.2 and up you can use regular sell settings to sell on a strategy, but use takeprofitsafety and trailing stoploss to exit in profit

**Comment by Masterofcoinak** [comment]
Gain is not needed anymore for sell, This should be possible to do as sell strategy

**Comment by Masterofcoinak** [comment]
If you want this feature, than I would suggest that you support #561.

**Comment by taniman** [comment]
should be possible using dynamic logic
