### ISSUE TITLE
Gain sell_value_limit

### ISSUE THREAD

**Issue by thysbotwhisper** [taniman/profit-trailer-enhancements#538]
For my personal pet project I'd love to have a limit for the gain sell value.
DEFAULT_A_sell_strategy = GAIN
DEFAULT_A_sell_value = -99
_DEFAULT_A_sell_value_limit = -2_

This so the gain sell strat can't sell, unless it really needs to when the pair is down and the strategies all indicate a sell. Right now I sometimes get sells at -0.5% which is a bit of a waste, the strategies flip to a sell value, but at -0.5% I actually still want to give the pair a chance. Would be nice to be able to specify the range of allowed gain values for a sell to a range from -99 to -2 for instance.

I don't think there's anybody else but me trying to use the regular sell strategy as a backup strategy to sell at a loss when the trend goes down, but it's become a lot more attractive now with takeprofitsaftey and trailingstoploss making positive sells possible while the regular sell start functions as safety in case the pair's market goes sour.

**Comment by taniman** [comment]
yes, possible in latest versions
