### ISSUE TITLE
Feature request : Multi-level "take_profit_safety"

### ISSUE THREAD

**Issue by Whitesnake67** [taniman/profit-trailer-enhancements#539]
I like to have a multi-level "take_profit_safety". By now it's only one level.

If you have a strength indicator (like RSI) in your sell-strategy, it could be that your bought coin has a good profit, but the indicator never gets true and you will miss the deal. "take_profit_safety" is a very good tool to still have a profit but you can still miss the big profits, because your setting is to low (you can never know).

For example:
DEFAULT_take_profit_safety_arm_1 = 5
DEFAULT_take_profit_safety_fire_1 = 3

DEFAULT_take_profit_safety_arm_2 = 10
DEFAULT_take_profit_safety_fire_2 = 7

DEFAULT_take_profit_safety_arm_3 = 15
DEFAULT_take_profit_safety_fire_3 = 12

**Comment by thysbotwhisper** [comment]
That's what trailing stoploss is for, no?

**Comment by Whitesnake67** [comment]
Trailing happens only, if all sell strategies are true. But as mentioned above, this sometimes doesn't happen with strength indicators. Let's say, you only want to sell if RSI is above 80. But it stops rising on 79 and provit is 8%. Under normal circumstances you will loose the trade. But with "take_profit_safety" you can save some % as provit. But you never know how high this goes. Sometimes RSI 80 is +3%, sometimes it's 15%. With a multi level "take_profit_safety", you can set "safety nets"...

**Comment by diablocody** [comment]
I just asked the discord for this exact same thing. Would be helpful!

**Comment by Masterofcoinak** [comment]
It is trailing stoploss what your are talking. It has nothing to do with normal trailing.
![image](https://user-images.githubusercontent.com/36849981/58369071-f73e0600-7f27-11e9-9234-2e77df9ae556.png)
Should be closed

**Comment by ArmchairGuru** [comment]
With the ability to set buy or sell formulas now, you can also set your formula to be true and start to trail even if a RSI startegy is not.
