### ISSUE TITLE
Feature request: lifetime Profit

### ISSUE THREAD

**Issue by Omnicoverage** [taniman/profit-trailer-enhancements#541]
Would it be possible to have a place where I can see the total lifetime profit made by the bot?

**Comment by Seeletse** [comment]
I think PtTracker might be your best bet for having the information.

**Comment by cryptogeek0610** [comment]
Just use PTTracker

**Comment by Omnicoverage** [comment]
8( how?

**Comment by Masterofcoinak** [comment]
Should be closed, cause of PT Pro function with PT Tracker 
![image](https://user-images.githubusercontent.com/36849981/58368977-07a1b100-7f27-11e9-90bd-08f7f1309fb7.png)

**Comment by Masterofcoinak** [comment]
Should be closed

**Comment by propergol** [comment]
nope, PT Tracker is not anymore part (and has never been...) of Ptrailer.

**Comment by LiamAird** [comment]
Added to version 2.4.15
