### ISSUE TITLE
Feature Request : Specify the Sell Quantity Instead of Exiting MY Total Position

### ISSUE THREAD

**Issue by yasso115** [taniman/profit-trailer-enhancements#542]
Hello Team,

It would be great if you can implement a feature where the user can specify the sell quantity on the Pairs Tab instead of exiting all the position, as sometimes we don't want to sell the holdings.

And Selling the Qty that we want on the exchange will not be reflected on the Tracker so we can't keep track of the profits.

Thank you

**Comment by Masterofcoinak** [comment]
Maybe we can close this and support #563

**Comment by taniman** [comment]
SOX_take_profit does this
