### ISSUE TITLE
DEFAULT_max_buy_volume = #### Added?

### ISSUE THREAD

**Issue by LoneEagle** [taniman/profit-trailer-enhancements#543]
PT does have DEFAULT_min_buy_volume = ###. That feature works great. Could you please add
DEFAULT_max_buy_volume = ### This would help in keeping "penny" coins in check. Also it would help with coins that get pumped way up then dumped. If the volume is too high and the coin starts to dump PT sees the loss and starts to buy on the down with high volume. If you look at coin EVX-BTC on Binance on 3/24/19 you wold notice the Volume spiked to 30k+ BTC Pump. Then started to dump. This pattern is too risky to have a bot just start buying on the down. I was able to see what happened and manually sell at a 10% loss.

**Comment by JohnSec2020** [comment]
I request this too.

**Comment by taniman** [comment]
this will be added to 2.5.0 DEFAULT_max_buy_volume
