### ISSUE TITLE
DEFAULT_A_buy_strategy_direction and EMASPREAD/EMAGAIN

### ISSUE THREAD

**Issue by FaithlessVoid** [taniman/profit-trailer-enhancements#545]
Hi everyone,

my "idea" for an enhancement is pretty simple:

Make the optional XXX_A_buy_strategy_direction available for EMASPEAD/EMAGAIN and all the other SPREAD and GAIN strategies. Right now it is limited to RSI, STOCHRSIK, STOCHRSID, STOCHRSI, BBWIDTH and STOCH. I don't see why that is.

Example: I want to use EMASPREAD as one of my buy strategies with a short 50-period EMA, a long 100-period EMA, a buy value of -1 and strategy_direction = UP. The buy strategy should be true when the SPREAD is -1% or above, meaning -0,99% = true, 0% = true, 1% = true, 10% = true. But below -1% = false.

Why? I dont want to trade against the trend, and EMASPREAD on two long EMAs is a good way to avoid it. But I dont mind if the trend is slightly negative and want to continue trading unless the negative spread is further down than -1%. 

Right now that cannot be done because negative buy value = only true if the actual value is even further down.

**Comment by taniman** [comment]
You could use dynamic logic and so > -1 if you want
