### ISSUE TITLE
Feature Request: Second level of DCA

### ISSUE THREAD

**Issue by jSevyn** [taniman/profit-trailer-enhancements#546]
Currently we have DCA where you can have 10 max pairs enabled. PT would then populate the DCA section with 10 trading pairs. You could then use the option DCA Max Trading Pairs to limit how many of those 10 pairs would actually use DCA at the moment. So lets say we set that to 3. We know that this means that any pairs bought and placed into the DCA section would not use DCA until it was chosen to be one of the 3 that PT is allowed to use DCA on. What I would like to see is a second level of DCA. All the current features of DCA but using commands like:
DCA_Max_Trading_Pairs = 10,
DCA_Max_Buy_Times = 5,
DCA2_Max_Trading_Pairs = 3,
DCA2_Max_Buy_Times = 50,
to differentiate between the two levels. I dont mind if they use the same triggers and buy percentages since I know adding two levels of info for say 100 triggers would consume alot of space in the command lines and I am aware that is limited. But I will also admit that having that freedom to set each trigger/percentages for DCA1 and DCA2 would be nice. I have found that most pairs will sell off eventually with the use of only 5 DCA triggers. However I have also found that there are some stubborn pairs that require a bit more in order to sell off. Using the example above, it would allow all 10 pairs in the DCA section to be able to DCA 5 times and stop there. From there PT would select 3 pairs to run the second level on. I dont mind if it starts at trigger 1 again when it enters level 2 DCA or continues where it left off at trigger 5.

Current behavior of PT with DCA Enabled and using the commands:
Max_Trading_Pairs = 10,
DCA_Max_Trading_Pairs = 3,
DCA_Max_Buy_Times = 5,

PT will allow 10 pairs to go into DCA but only run 3 pairs the the DCA process. The other 7 will never use DCA. Question is why even have those 7 pairs listed in DCA then.....shouldnt they just be sent back to the PAIRS section? I have been doing this manually and its been working very well but would be nice if it was fully automated. Hopefully this is something that can be easily implemented as its pretty much using the same commands already being used for the most part aside from differentiating by DCA1 or DCA2. Shoot.....if possible why not allow more levels of DCA. I really hope this feature will be added as Im positive it will be very helpful to everyone.

**Comment by taniman** [comment]
too complicated to build and possibly not worth it as it won't be used much
