### ISSUE TITLE
Stop Loss based on VALUE loss instead of %

### ISSUE THREAD

**Issue by Aesgan** [taniman/profit-trailer-enhancements#549]
Hey

I was wondering if it would be at all possible to have a STOP LOSS defined on VALUE LOSS instead of % loss.
For example:
- I have bought OMGBTC for 1 BTC
- The coin has dropped and the value of my bag is now 0.90 BTC. Effective loss of 0.10 BTC, -10% profit
- I have bought AIONBTC for 0.5 BTC
- The coin has dropped and the value of my bag is now 0.40 BTC. Effective loss of 0.10 BTC, -20% profit

In both cases I'd like to sell the bag according to my STOP LOSS strategy, but if I just define -10% for STOP LOSS I'd sell the AION bag much earlier. So in alternative I could define to sell when a bag gets too deep for my risk analysis (ie gets negative to the point where I prefer to have the liquidity instead of the coin).

Let me know if it doesn't make sense please!

**Comment by taniman** [comment]
Use DIFF dynamic value property to accomplish this in 2.5
