### ISSUE TITLE
Consecutive_stop_loss trigger for SOM

### ISSUE THREAD

**Issue by BaliDog** [taniman/profit-trailer-enhancements#550]
I note this was requested a year ago but not implemented. Please may we have a trigger for SOM activated by consecutive stop losses, and released by one sell at a gain or take profit. During a sharp turn around a rash of SLs is accompanied by a rash of really bad buys that also SL soon after. We need to nip that in the bud after say two consecutive SL = SOM.

Consideration would have to be given to the possibility that while SOM is activated, ALL the pairs and DCA are sold as SL and hence now unable to be sold at a gain, leaving SOM enabled indefintely. There would need to be a market condition over-ride perhaps .... don't know how that would be fixed.

Many thanks!

**Comment by taniman** [comment]
#441 was implemented. The last comment
