### ISSUE TITLE
Feature request : changing dust setting value

### ISSUE THREAD

**Issue by carllewis1980** [taniman/profit-trailer-enhancements#551]
I have recently been busting bags. But found that my ETH bot is far quicker at busting them because of the you can make smaller shards without them falling into dust.
I would like to be able to change the amount in PT that a coin becomes dust.
This will cause an issue, creating a “buy value below dust” in DCA. So a further option would be to add an option that if this occurs, DCA will automatically buy the minimum amount of a coin even if it is more than the DCA setting.

**Comment by ArmchairGuru** [comment]
Dust is the point at which an amount of coin falls below the exchange trade minimum, it is a function designated by the exchange, not something that can be altered. Ensure your buy levels and percentages are above this level and there is no issue.

**Comment by Masterofcoinak** [comment]
Should be closed.

**Comment by carllewis1980** [comment]
Should this be closed? I believe changing the dust level to a custom level and having a setting that once “Buy level is below dust” it buys the minimum amount of coin is a great idea…

 

The previous response of dust level is set buy the exchange is poor. We are talking about the dust level on PT not the exchange

**Comment by Masterofcoinak** [comment]
Sorry. You are right. I was going through all enhancements to reduce the amount. Ignore duct and buy minimum function is actually not too bad of an idea.

**Comment by taniman** [comment]
If this is really needed anno 2021 we will look into it. But I have not seen enough demand

**Comment by jonestim87** [comment]
Can we get this looked at and followed up? Since binance minimum purchase is no longer $10 and is now $1 per coin, the dust setting on PT should be adjustable so if buying the minimum amount, it would still try to sell it instead of just putting into a dust category where it won't trigger to sell

**Comment by taniman** [comment]
This github is not for bugs. Also the bot has no built in dust settings. It all is read from the Binance API.

So I will disagree with your assessment.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
