### ISSUE TITLE
Feature Request: Take portion of profits at various levels

### ISSUE THREAD

**Issue by adrianbureu** [taniman/profit-trailer-enhancements#552]
Many trading system developers also use take-profit orders when placing automated trades since they can be well-defined and serve as a great risk management technique. A very useful feature for profit trailer would be to define different levels of profit to exit portions of your position. This would be incredibly useful for mid/long term trades. 

For example, lets say your bot buys ETH/BTC. Instead of exiting at a 5% gain, you can set the bot to sell 1/3 of your ETH% at 2% profit, 1/3% at 5% profit, and 1/3% at 10% profit.

**Winner Enhancement Games Q2 2019**

**Comment by JMLBUSINESS** [comment]
Perfect IDEA most trading bots do have this option to keep new positions separated from old positions just as you do with manual trading, it's way more profitable by allowing us to merge or split the positions % accordingly.

**Comment by cryptogeek0610** [comment]
I like this idea!!

**Comment by iller75** [comment]
Oh awesome, i was just gonna request this feature :D

**Comment by iller75** [comment]
@cryptogeek0610 if you like it please thumbs up the issue, that's how they see what issues most people like.

**Comment by Levante369** [comment]
Give that guy a lifetime license! :) Just was about to recommend that.

**Comment by thysbotwhisper** [comment]
I've requested this before I believe. Would be nice to be able to take partial profits.

I would suggest the following logic:

It looks at current profit percentage, and for a bunch of levels of current profit [A, B, C] the user can set a partialprofit percentage [X, Y, Z].

If price is above level [A], PT sells percentage [X] of its current holding.
If [B], sell percentage [Y].

Example 1, for very slow trend trading bots (I run a bot that could hodl until 250% if there was a continuous trend)
If the bot has 50% profit, take 25% of the position off.
If the bot has 100% profit, take 50% off.

Example 2 for scalping: 
if the bot has 1% profit in the DCA log, sell half of it and let the other half run.

**Comment by Phips02** [comment]
It's a very good idea, I've been waiting for that for a long time.

**Comment by cryptocoyns** [comment]
This is known as scaling out https://www.babypips.com/learn/forex/what-is-scaling

**Comment by PTMaza** [comment]
It will be sweat to be able to do partial Buy as well.

**Comment by LiamAird** [comment]
Is possible in 2.4 with the following features: http://wiki.profittrailer.com/doku.php?id=pairs_config#default_so_x_take_profit_target
