### ISSUE TITLE
Candle Close Trading Option

### ISSUE THREAD

**Issue by Emir-K** [taniman/profit-trailer-enhancements#553]
I like how PT can trade while the candles are forming however, I would like to have an option where you can chose to trade at the close of a candle.
For example, say you are trading with RSI and buying at 35 or lower. An option where you can chose to buy once the candle closes like "Once Per Bar Close" setting in TradingView would be useful.

**Comment by ArmchairGuru** [comment]
This exists now.
https://wiki.profittrailer.com/doku.php?id=buy_and_sell_strategies#pdclose
