### ISSUE TITLE
New indicator requests: EMA Ribbon

### ISSUE THREAD

**Issue by Emir-K** [taniman/profit-trailer-enhancements#554]
Very popular and accurate indicator EMA ribbon would be good addition if possible.

![image](https://user-images.githubusercontent.com/50059317/56855283-67417800-68f9-11e9-9302-96ca195088e6.png)
![image](https://user-images.githubusercontent.com/50059317/56855289-8213ec80-68f9-11e9-9575-59b35add6b79.png)

**Comment by CryptosWORLD** [comment]
i say a big yes when it is a new indicator
i add also this

very good article at my opinion https://www.tradeciety.com/how-to-choose-the-best-indicators-for-your-trading/  what is the suggestion  .. more indicators ..

**Comment by thysbotwhisper** [comment]
You could specify how this indicator would trigger a buy, what value would it output?

**Comment by taniman** [comment]
Sounds to me like adding multiple MALINES and checking against them would work fine here. No need for a special strategy
