### ISSUE TITLE
[FEATURE REQUEST] AUTOSELL A SPECIFIC COIN

### ISSUE THREAD

**Issue by CryptoSpank** [taniman/profit-trailer-enhancements#555]
Autosell a specific coin when it is deposited.

Example: When BTC is used as the market, BTC can come and go out of the wallet and the bot automatically adjusts its current balance and carries on.  It would be nice to have it act in this same way with specific coins that are not the market.  ..My miner deposits RVN to my exchange every day.  I would like the bot to automatically sell RVN for BTC when it appears without having to hotconfig a bought price before it does so.  This would allow my miner to inadvertently fund my trading bot autonomously in real time.

**Comment by Masterofcoinak** [comment]
RVN_panic_sell_enabled = true. Set this and normally it works.

**Comment by Masterofcoinak** [comment]
Should be closed
