### ISSUE TITLE
[FEATURE REQUEST] USE ANY COIN AS THE MARKET

### ISSUE THREAD

**Issue by CryptoSpank** [taniman/profit-trailer-enhancements#556]
Set any coin you would like as the market for the bot.  

The bot is a powerful tool.  Imagine a world where one could choose any coin as the bots market.  Not only would you sell more subscriptions, but over time as more and more users adopt the bot and apply it to their favorite coins, you would see this stimulate the entire crypto market to a decoupling from BTC.   ...Imagine opening CoinMarketCap and seeing every coin with a price chart that differs from BTC's.

**Comment by ArmchairGuru** [comment]
Using a market is a function of the exchange. Unless the exchange has a market base with quote pairs there is nothing to trade against, either manually or with a bot.
