### ISSUE TITLE
[FEATURE REQUEST] Two-Factor-Authentication for PT website

### ISSUE THREAD

**Issue by tr8es** [taniman/profit-trailer-enhancements#557]
Profittrailer Webpage login only with 2FA

**Comment by Seeletse** [comment]
This would be brilliant

**Comment by stefi01** [comment]
it is a good idea but im not sure about can only login with F2A, should be a choice but does seem pointless having the api secret on display in the app file so anyone with access to the users pc can see it but the web page password protected but anyone can see that too.

**Comment by taniman** [comment]
We will revisit this in the future
