### ISSUE TITLE
Telegram Bot buy/sell Signal - Connectivity to PT

### ISSUE THREAD

**Issue by monte-crypto** [taniman/profit-trailer-enhancements#56]
A very useful feature would be the addition of a connectivity mechanism between Telegram Bots and the PT software. This feature would enable our software to act on the "Buy" and "Sell" signals for various cryptos.

A similar feature is now available on a different crypt trading software "Cryptohopper". One of the people that I follow, "Crypto Face" has now moved on to this other software. There is no doubt that the PT community would definitely benefit from the potential trading efficiency of this feature.

**Comment by clownfish44** [comment]
External signals have already been requested here https://github.com/taniman/profit-trailer-enhancements/issues/14
