### ISSUE TITLE
Discord/Telegram Notification Feature to Include Calculated Purchased Price on DCA

### ISSUE THREAD

**Issue by GeorgeBIV** [taniman/profit-trailer-enhancements#562]
I would like to see the newly calculated price included in the telegram/discord notifications when the bot makes a new DCA purchase.

I've had a few prices go missing and rather than digging through my exchange logs and calculating my XXX_bought_price, it would be convenient if I could go back into my discord log and pull the price from there.

**Comment by Masterofcoinak** [comment]
You could use http://cointracking.info/ with API. Maybe that's an idea!?

**Comment by taniman** [comment]
Already possible
