### ISSUE TITLE
Improved manual buy/sell function (with trailing and manual amount)

### ISSUE THREAD

**Issue by Masterofcoinak** [taniman/profit-trailer-enhancements#563]
I think the picture explains itself. I know some of them have been already requested (#525,#420,#284), but this visualization makes it better to understand and to want ;).
![image](https://user-images.githubusercontent.com/36849981/58366831-ab309880-7f0a-11e9-8010-eb0214d99d47.png).
Additional 4 checkboxes would be great on the buy/sell pop up window.
1. Trailing follows the rule of PT. If the trailing value is not reached than buy or sell fails.
2. Trailing ignores possible failing. Coin price rises the trailing amount and buys it anyway. Makes probably only sense on the buy function.
3. Should be set as standard to show buy amount is as per pairs/DCA setting
4. It can be chosen instead of point 3 and buys the manual amount.

**Comment by Friwenbonda** [comment]
An upvote from me but mostly for additional Sell button functionality, especially to allow it to have a Panic Sell option (DannyA).

**Comment by taniman** [comment]
most is already possible.
