### ISSUE TITLE
Autocalculate DCA Level

### ISSUE THREAD

**Issue by Masterofcoinak** [taniman/profit-trailer-enhancements#564]
Just a small idea. The bot could automatically calculate the DCA level of each pair by its size.
It would just use the initial cost and the fixed percentage amounts of each DCA level and calculate it.
Like this, the Hotconfig function doesn't have to be used anymore and canceled pending orders have automatically the right DCA level. It also avoids huge DCA purchases by canceled pending orders (only if you don't use double down/Anderson).
DEFAULT_DCA_level_calculation = true
Additional could also be done a setting, which avoids DCA to be the stuck cause of purchase below dust value, by leveling DCA down. (only if you don't use double down/Anderson).
DEFAULT_DCA_level_down_if_below_dust_value = true

**Comment by taniman** [comment]
I don't see it
