### ISSUE TITLE
Interface improvments (Pending button, addtional sorting, price editing...)

### ISSUE THREAD

**Issue by Masterofcoinak** [taniman/profit-trailer-enhancements#565]
Hello Everyone,
I love PT and the way it improved over the time, but there is always space for more.
As I went through all open Github Enhancements, I came over several interface update proposals. I hope you don't cancel this cause of partly existing issues or more requests.
Its 1 request for an improved interface.
Below are existing issues:
E.g.: # 484 Pending button, #269 and #468  Sorting of 24H percentage, 
        #468 Price difference sorting........
Additional from my side is the function of updating the bought price. (no more Hotconfig!!)
You could also implement all features for PT Pro!!!!
I took the effort to visualize how the possible update could look like. 
![image](https://user-images.githubusercontent.com/36849981/58378911-9f0e0f00-7fce-11e9-98ff-b5039c9b0194.png)
Here also a possible pop up window for the Price and DCA level update.
![image](https://user-images.githubusercontent.com/36849981/58378951-104dc200-7fcf-11e9-8510-3ba85fe066c2.png)
Of course, all functions should be extended to PBL/PAIRS/DCA/PENDING.

Many Thanks and good luck in trading!!!

**Comment by Jthwaits** [comment]
These would definitely be welcome quality of life improvements

**Comment by taniman** [comment]
New BETA GUI has many changes
