### ISSUE TITLE
change_percentage - not only 24h

### ISSUE THREAD

**Issue by DrrMrr** [taniman/profit-trailer-enhancements#566]
add adittional indicators how specific coin is moving in different time periods. Not only for 24h

Now there is only
DEFAULT_buy_min_change_percentage
DEFAULT_buy_max_change_percentage

**Comment by tactikill** [comment]
as well as btc rise/fall riggers

**Comment by taniman** [comment]
ther is changePERCENTAGE strategy and also rise/fall triggers have custom som trigger length
