### ISSUE TITLE
UNDCA-REDCA (freeing balance and better use of swing trading)

### ISSUE THREAD

**Issue by Masterofcoinak** [taniman/profit-trailer-enhancements#568]
Hello devs,
I posted this more or less exactly 1 year ago #320, but due to lack of reason, I am trying it again.

The crypto winter was long and I am sure many had to deal with bags during this time. Sadly most of us don't have the budget to DCA out of this problem and solutions as dilution of bags would also require additional balance!!
A simple way would be to sell back DCA steps. Let's call it **UN-DCA** (or DE-DCA?!).

There are already request available for partial sells of big bags or re-sell of the last DCA step, but I would like to go 1 step further as shown in below 4 ways

1. Simple version:
Just sell the number of coins of the previous DCA level according to the current market price. 
A kind of partial panic_sell/stoploss_function for the last DCA step. 
PT could start it when the balance goes below a specific value (or 0). 
PT would compare the biggest bags or the ones below certain DCA levels and sells until the balance is again above the specific value.
Advantage:
- Balance is free
Disadvantage:
- The bag is still deep in none profit zone (in %)
- Additional sale with loss in the log

2. Improved version:
Same as before, but this time UNDCA would use its own sell strategy.
With all the nice current functions as trailing, trailing stop-loss... (with or without GAIN)
The average price should be used for the last DCA level.
Advantage:
- Balance is free
- Even possible Profit for the last trade
Disadvantage:
- The bag is back in the even deeper none profit zone (in %)

3. Advanced version:
Same as the above version, but the profit of the DCA sell will be used to improve the average price of your bag. The sell will be not shown in the sales log (or could be, but with 0% Profit). 
In case you do it more often, then this should make it possible to resolve your bag easier.
Advantage:
- Balance is free
- The average price of the existing bag is improved
Disadvantage:
- The bag is not as deep as before in the none profit zone (in %)

4. Ultimate version: 
Let the bot all the time use the UNDCA solution of version 3.
BUY>DCA>DCA>UNDCA>DCA>DCA>UNDCA>UNDCA>>PROFIT
Advantage:
Indirect more balance for additional pairs
Faster outcome into profit
Improve the value of your pair by swing trade

Getting huge and expensive bags can of course be stopped of your bot by limited DCA steps or Max DCA cost, but at some point, you have to choose between additional DCA or Stoploss.
And who wants that??

Sending it to the pending log by trigger is probably also a solution of some users, but this just lets you trade the coin again. It will also take more time until it purchased the coin again. Bag remains as it is and frees no balance.

Some users even developed smart ways by use of scripts/cronjobs to minimize their bags (thx Karl). Partial stops loss of pairs and only pairs which has risen the most would get dissolved. See option 1.

Please think about it.

**Comment by Masterofcoinak** [comment]
would be great to combine it with #264

**Comment by taniman** [comment]
I am lost at point 2. What so you mean UNDCA has own sell strategies? trailing is not a strategy so how would UNDCA make use of it? 
And Average price should be used for last level. What will this accomplish?

Step 3 and 4 build on step 2
 So maybe Ill umderstand those better ones 2 is more clear

**Comment by Masterofcoinak** [comment]
The basic idea is to make every buy (DCA step) possible to sell with a strategy (same as the standard sell). Maybe the sentence about trailing was misleading the point. More or less treat every buy as its own pair, but for DCA treat them as they are still together. 
 I tried to do it with Pending, but several commands are missing to do it as with my idea
1. General DCA trigger and buy percentage cant be done with pending
2. Max pair could slow down rebuy of the coin (if max pairs are full)
3. maybe more......
To be honest STEP 2 is not so different as STEP 4, but the idea was to start the strategy as in step 1, when the balance is below a certain value or the DCA-Level reached a point (sell partially without GAIN). Only for gaining balance in a smart way. 
STEP 3 was just basically to add the idea of calculating the profit into a still exiting pair. (not mandatory but would be really nice)
STEP 4 just uses the DCA resell strategy all the time. If PT can sell a part of the DCA bag with profit, then PT does it. If the coin falls even lower, than it buys more. Simple up and down or DCA and UNDCA.
I think I would make for every additional DCA step a higher GAIN to make it possible for the pair to trail into the next DCA bag.

I am really bad in explaining :(

**Comment by Masterofcoinak** [comment]
I have already an idea how it could look like in PT (Excel style)
![image](https://user-images.githubusercontent.com/36849981/58575907-aefb4c80-8275-11e9-9e3d-7ff2cc191121.png)

**Comment by taniman** [comment]
This system might have a place as a separate bot or addon. I don't see myself building it. It will be a lot of work
