### ISSUE TITLE
Feature Request: Trailing trend indicators

### ISSUE THREAD

**Issue by trentsteel84** [taniman/profit-trailer-enhancements#569]
I would like to be able to setup a buy strategy that trails MACD or similar trend indicators and only buys on the uptrend.
So i imagine you would need to decide how many candles to look back, keep a track of the current and recent values and if it's decreasing don't allow a buy. If it starts increasing and is below a certain value then allow a buy. You wouldn't want to buy near the top of an uptrend, so maybe a limit on the value or a maximum timer? Although i would think that other indicators would protect you there.

This could obviously be used in the opposite way for selling too.

**Comment by taniman** [comment]
This could be achieved likely with _offset logic and dynamic logic to compare
