### ISSUE TITLE
Implement Comment blocks

### ISSUE THREAD

**Issue by Brisco00** [taniman/profit-trailer-enhancements#57]
In the .properties files you are allowed to comment single lines with a '#'.  Could you implement comment blocking to comment entire sections

i.e
#/ 
Everything
here 
would 
be
commented
/#

**Comment by clownfish44** [comment]
This is already implemented

# comment 1 
# comment 2 
# comment 3 
# comment 4 
# comment 5

**Comment by Brisco00** [comment]
# Single line is implemented
# This
# was not 
# what I was 
# requesting

#/ 
I was requesting
Comment Blocks
Thank you
/#
