### ISSUE TITLE
Display Coins in Reserve in the GUI

### ISSUE THREAD

**Issue by hoffer49** [taniman/profit-trailer-enhancements#570]
Include a tab on the GUI that would display any/all coins that were held in Reserve.

**Comment by Masterofcoinak** [comment]
There we could also see again how many BNB are left.
And include them into the TCV!

**Comment by hoffer49** [comment]
Yes, but as far as the TCV goes...at first I thought that would be cool BUT you're not selling the coins in reserve OR the BNB therefore people might not want their initial cost percentage based on coins that they aren't going to sell

**Comment by Masterofcoinak** [comment]
That screams for another command. DEFAULT_reserve_amount_into_TCV = true.

**Comment by hoffer49** [comment]
LOL...I like!

**Comment by Masterofcoinak** [comment]
Maybe its better to close it this point and support #40 !? Repeated request and the others has already more supporters.

**Comment by LiamAird** [comment]
This has been added in a previous release, as a log for itself.
