### ISSUE TITLE
Indicator Request: ATR Bands

### ISSUE THREAD

**Issue by thysbotwhisper** [taniman/profit-trailer-enhancements#571]
"ATRB / Average True Range Bands" 
You calculate ATR. Say on ethusdt, last close price [LC] is 270, and ATR [from the last 14 candles] is 4. We take a multiplication factor [M] of 3. 

The low end of the ATRB is calculated  as 270 [LC]  - (4 [ATR] * 3 [M]) = 270 - 12 = 258. The high part of the range is LC + (ATR * M) = 282. 

Now for PT we want to use percentages, not absolute values, so that we can use the same tool for every pair. This is where the bands come in. If current price is in the middle of the band between low and high ATR, we call that 50%. If price is at low ATR BANDS level, we call that 0%. If it's at high ATR BANDS that's 100%. The same way lowbb works: with lowbb there is a formula that calculates a top and a bottom deviation band around the mean, and from then on with lowbb values are expressed as percentages relative within (and outside) that band.

PT ATRB indicator user inputs: candle length, and multiplication factor

**Comment by Masterofcoinak** [comment]
I think we can close this, as it was implemented with Vers. 2.3.8
