### ISSUE TITLE
Make DEFAULT_min_buy_volume an average

### ISSUE THREAD

**Issue by m4xson** [taniman/profit-trailer-enhancements#573]
When a coin is manipulated in a short term pump&dump the volume will rise above DEFAULT_min_buy_volume for a few hours and PT will be tricked into buying as the coin dumps again for a guaranteed loss. The volume should be an average for the month, saving us from some of these.

Thumbs up if you need this feature in PT!

**Comment by taniman** [comment]
This is a duplicate as I have seen a few already. So will closethis one
