### ISSUE TITLE
[Feature Request] Parabolic SAR trend confirmation indicator

### ISSUE THREAD

**Issue by kkkoay** [taniman/profit-trailer-enhancements#574]
We need a simple trend confirmation indicator and nothing is as simple as Parabolic SAR or PSAR. This paved the path for future Short trading of PT when available. This will allow better management of orders placement when in the down trend, the indicator will avoid placing long orders to minimize bagging.

**Comment by Koenvdp2** [comment]
would like to see this as well, excellent indicator for entry or stoploss in combination with ADX.

**Comment by taniman** [comment]
I have added this indicator now for 2.5.0 release. But having some problems understanding how it would be interacted with. You can elaborate on discord
