### ISSUE TITLE
Coin Selection feature - by volatility

### ISSUE THREAD

**Issue by CryptosWORLD** [taniman/profit-trailer-enhancements#575]
as we can see there are trades that give as bags, there are many reasons that may happen
on reason (of the many) is coins with no movement = volatility in period of time (example 1 d can be lees example 2 hours)

**we need a way to filter only the volatile coins to trade with**
example trade all the pair in binance that is above 3% and below 30%  (as example)

example can find coins per % change and volatility
https://www.tradingview.com/crypto-screener/

% change and volatility is not the same !!!
% change can be +3% one day and -3% on other time period
volatility is only positive % 

and yes we can have both % change and volatility filter 
example 
trade true is (trade only when)
% change = above 2% and below 10% (and) above* -2% and below -10%  (* between -2% and -10%) 
AND
volatility  = above 2.5% and below 20% **

**why below example 20% and other protection in to volatile coins = anti pump and dumps protection

**Comment by taniman** [comment]
We have ATR as a volatility indicator. Is there are other specific indicator a ticket should be created and mention the specific indicator
