### ISSUE TITLE
Feature Request - DCA and growth enhancement

### ISSUE THREAD

**Issue by jdharward** [taniman/profit-trailer-enhancements#576]
I had an idea that you might be able to implement as a feature at some future release.

Say your bot has a coin you are either holding or averaging down. It would be great if I could flag the coin to have the bot hold a percentage defined amount of the coin, say 85% and sell the 15% when sell indicators indicate to do so, and then rebuy (more) of that same coin when the buy indicators say to do so.

Under this, you could also have a bot trading only coins you want to "HODL" for long term. Simply allow the bot to trade only those coins but when it goes to "sell" the coin, it only sales a user defined percentage of the coin and then the bot attempts to buy back (more) when the price is lower.

The idea being the bot will hold a coin and trade a small portion of that coin in an attempt to build the volume of that coin held. Thus increasing future profits and/or lowering the average buy price. 

What do you think? Is something like that possible?

**Comment by taniman** [comment]
On spot you could send a bit of the coin to reserve and let the bot keep on trading. Otherwise the way the bot is designed to work it would not be that easy to build
