### ISSUE TITLE
Conditional Statements for PT variables

### ISSUE THREAD

**Issue by DrrMrr** [taniman/profit-trailer-enhancements#578]
Hi,

would it make sense to have optional conditions for variables like max_trading_pairs ?

if (my_base_balance <= (25% of total balance))
    max_trading_pairs = 8
else
    max_trading_pairs = 12

Maybe this could be useful somewhere else too.
Best regards
Damjan

**Comment by Masterofcoinak** [comment]
or make the balance as a variable to start a stop-loss sell strategy #568 to gain balance again.

**Comment by taniman** [comment]
with the use of dynamic logic it will be possible in 2.5.0
