### ISSUE TITLE
ProfitTrailer strategies as a service

### ISSUE THREAD

**Issue by DrrMrr** [taniman/profit-trailer-enhancements#579]
Hi,

I think we all appreciate your example strategies that you are publishing.

what if you could provide strategies as a service? Anyone could publish its own strategy that others could use. Of course, there are many ways the publisher could benefit from such publications.

Best regards
Damjan

**Comment by CryptosWORLD** [comment]
yes it is good to see more strategies as examples
but remember there is no strategy 100% working in all market trends
a strategy in a wrong trend may be not profitable even can create more BAGS or even loose money 

and if we all use the same strategy (let say we found one that it is now the most profitable)
we will have different results 

so the only reason i say yes is as examples to learn better to make our own strategies even better
and also better understanding of PT and how works ..

**Comment by sagarspatil** [comment]
@DrrMrr PT already provides this, please check - https://profittrailer.com/product-category/signals/
Currently, only approved providers can provide these signals.
You can also check their performance records here - https://signalstats.profittrailer.com

Does that answer your question?
