### ISSUE TITLE
Dca trade separately 

### ISSUE THREAD

**Issue by odutolaconnect** [taniman/profit-trailer-enhancements#580]
OK if is not dca, anyhow, anyname call, but explain how I will make each draw down trade separately, if market go Down 60% it mean I will have 6 trade if set at 10% interval,  if the last trade gain 2% it will take profit if set take profit at 2%, if market go back 60% it will re-enter the 6th trade again•meaning each trade take his own 2% profit seperately

**Comment by Masterofcoinak** [comment]
#568 I think it would be better if you just support my idea.

**Comment by odutolaconnect** [comment]
Your idea is not the same here, bot will just used Dca method to enter new trade, but each order trade separately with take profit set,  I. E if set 5% ,new trade will come in every 5% draw down from the first trade price

**Comment by Masterofcoinak** [comment]
If I understand you correctly, than its the same. I am not sure if my or your English is not good enough :smile:

**Comment by taniman** [comment]
Can't be build without overhauling the bot.
