### ISSUE TITLE
[Feature request] Pyramiding up

### ISSUE THREAD

**Issue by swanfield1979** [taniman/profit-trailer-enhancements#581]
Pyramiding up, scaling in or adding to winning positions. I would call it a reversed DCA.
What I would like is to increase my position in a trade when it's in a uptrend. So lets say I want to trade 100 dollar for a coin max. Now I have to make my position lower because I use DCA. So I have to calculate a lower. So taking in count that I have 3 DCA levels my first position will be 12,5 dollars.
I have a DCA in my strat for the few times a coin drops so I can still sell it. But most of the times I don't need it. So I only use 12,5% of my budget to trade with. Now if a coin goes up I want to maximize this profit. I would like to have a option to pyramid up. 

So f.e. I start with 12,5 dollar in a position. The coin rises to 3%, I look at the trend (maybe of a higher timeframe), the trend looks good. This could rise even more the comming days. I add to my postion 100% and I have 15 dollars at a 1,5% profit. Now the coin rises even further tot 8%. I want to add even more to my position because this could be a very good run for the comming days. So I buy an other 100% and I now have a position of 30 dollars. The coin rises even more etc etc. It could end with a 100 dollar position that I have for a few days that deliverd me a 22% profit on a coin that has risen x% the past few days.

Now profit taking should be like it is now. The only new option would be Enter pyramiding up from x% and pyramid levels (1,2,3,etc) and pyramid percentage levels. If it could be the same as DCA but then upwards.

**Comment by iller75** [comment]
This is already doable with positive dca to my knowledge.

**Comment by swanfield1979** [comment]
So I heard. But I want to use them both and it's not really clear to me how that would work.

**Comment by Masterofcoinak** [comment]
Yes, there are even several strategies provided by PT with positive DCA ![](https://i.imgur.com/w8Geacc.jpg)

**Comment by swanfield1979** [comment]
I have seen that but it's not two seperate strats. The strat need to go positive first of negative to trigger. So its not the same imo.

**Comment by Masterofcoinak** [comment]
You are right.

**Comment by tactikill** [comment]
> This is already doable with positive dca to my knowledge.

how? please share with the class

**Comment by taniman** [comment]
Other than you having to forget about the DCA buy times this is already possible by adding 2 different PROFITPERCENTAGE strategies and using an OR in the formula logic. 

Adding a separate field for DCA  as a counter could prove very confusing
