### ISSUE TITLE
Feature request: TV Signal valid change

### ISSUE THREAD

**Issue by matbuf** [taniman/profit-trailer-enhancements#582]
I'm usign TV signal a lot and it's great, but the only thing that give me some problem is the "valid" parameter, since it's very hard to guess how much time you will need to have the signal active if it's working with some other strategy.

My request is to add how much times it will be valide instead of the period (like "once" or "twice" or something like)

This will also avoid multiple buy/sell during the signal "valid" time

**Comment by taniman** [comment]
A starting point has been build in 2.5 for this. will need testing.
