### ISSUE TITLE
Feature request: true strategy doesn't stop or chance to split trailing for each strategy

### ISSUE THREAD

**Issue by matbuf** [taniman/profit-trailer-enhancements#583]
A limit I found in true/false trailing idea is that you can't ask bot to wait once only one strategy (let's say out of two) is true, in order to match with the second one.

let's make an example
DEFAULT_A_sell_strategy = RSI
DEFAULT_A_sell_value = 70
DEFAULT_B_sell_strategy = MACD
DEFAULT_B_sell_value = -0.000000001
DEFAULT_trailing_profit = 0.01

My target was to use RSI>70 as a trigger and wait for MACD cross down, but it will never happen, since, once B become true, A is way under 70 and turn false.
But if I was able to have RSI true from the moment it went above 70 and stay true until it will sell the coin (once MACD cross down) it will be very good.

**Comment by taniman** [comment]
use strategy_levelx to accomplish this
