### ISSUE TITLE
Ability to see how trailing affected a buy or sell

### ISSUE THREAD

**Issue by ezuhaib** [taniman/profit-trailer-enhancements#585]
I would love to see the benefit (or harm) that was caused by trailing in each buy or sale.

For our “statistification” as well as to help tune trailing settings.

**Comment by Jthwaits** [comment]
Yeah, though this could be calculated by mulling through graphs and the time of the sale, it would be nice to use this to indicate sell strategy performance.

**Comment by taniman** [comment]
We have some STATS that show  what trailing did.  Other than that I think this request is too broad
