### ISSUE TITLE
Panic sell with change in BTC price 

### ISSUE THREAD

**Issue by jango123** [taniman/profit-trailer-enhancements#586]
When price of BTC increases or decrease  instantly. trades which are in trading comes into loss specially when price of BTC increases instantly. We need to panic sell enabled on all coin or with no of coins with less loss in trade rather then all coins.
BTC price changes should be on with Number of candles with period of chart (label).

**Comment by taniman** [comment]
can use price_drop_trigger with action stoploss 
or in 2.5.0 could add a CHANGEPERCENTAGE indicator that looks at BTC price and based on this force a SELL
