### ISSUE TITLE
Telegram notification - Whenever PT forgets its buy average/prices of a coin

### ISSUE THREAD

**Issue by binarylimited** [taniman/profit-trailer-enhancements#588]
Please guys, really need this. 

The quicker I'm aware of pt forgetting buy averages the better.

this forgetting buy averages issue has been going on for ages with pt

**Comment by Masterofcoinak** [comment]
I like this idea. I like trading with BNB, but I use also BNB for Fees. So lost average prices are quite normal for me. If we can't solve the average price problem, then at least a notification would be nice.

**Comment by taniman** [comment]
already in
