### ISSUE TITLE
PT Stats Enhancements

### ISSUE THREAD

**Issue by mehtadone** [taniman/profit-trailer-enhancements#589]
The new stats page is coming on great. PTI is never going to see public release but there are some stats that I find useful and it would be good to integrate them into the GUI. The key here is that these metrics are not stats to show you "how much money you have made" but insights on how you can make your trading strategy better. 

Here are some key metrics I use and why:

- Average Trade Duration

![image](https://user-images.githubusercontent.com/8123496/59254502-38246300-8c28-11e9-9263-fbf9c52471fd.png)

This would be useful to tweak time for SL or moving into pending. 

- Average Bought Cost

![image](https://user-images.githubusercontent.com/8123496/59254562-55593180-8c28-11e9-9e37-082baceecff0.png)

This is a supplementary stat because when you DCA, your initial cost isn't really a good indicator of position sizing. Its an approximation of each position size with your DCA strategy included 

- Least Profitable pairs

![image](https://user-images.githubusercontent.com/8123496/59254688-93565580-8c28-11e9-9e9f-c366986c0d46.png)

This is useful when you have SL and you can see which coins maybe useful to blacklist. 

- Sell DCA Count

![image](https://user-images.githubusercontent.com/8123496/59254744-b08b2400-8c28-11e9-9afd-8b39cd0e851d.png)

To analyse your DCA strategy, you can see if you are adding an extra DCA level for no reason. In this example, I would probably remove the second level of DCA as it is not worth the risk. 

- Trade duration over time

![image](https://user-images.githubusercontent.com/8123496/59254913-03fd7200-8c29-11e9-86d2-880bfc8ae226.png)

This one is probably not as important, but it is good to see if you have a scalping style strategy and how any changes you have made are affecting how long you are holding a position.

**Comment by LiamAird** [comment]
Planned
