### ISSUE TITLE
Feature Request - Defined Risk Management & Dynamic Position Sizing Using ATR%

### ISSUE THREAD

**Issue by GeorgeBIV** [taniman/profit-trailer-enhancements#590]
With the new addition of the ATR%, I would like to incorporate this strategy into DEFAULT_initial_cost and DCA_max_cost as it can be utilized to calculate appropriate position sizing for risk management.

Ideally for any trade the maximum percentage of risk should not exceed R% of our trading balance.  Common wisdom puts R% as anywhere between 1-2%, but that variance can be left to a trader's discretion.  With this in mind, having the appropriate stop for a pair based on market conditions (ATR% formula), the initial_cost or DCA_max_cost could be dynamically calculated to fulfill our defined risk parameters.

EXAMPLE:
Balance = $1000 USD
Risk% (R%) = 1%
R% * Balance = $10 USD (A loss of $10 if our stop is hit)
Stop Loss (ATR% formula) = 10%
Calculated Position Size = (R% * Balance) / ATR%
$100 = (1% * $1000) / 10% ATR

In this example, our automation would place an order with the position size = $100.  If our stop gets hit at -10%, we've only lost 1% of our trading balance and successfully managed our defined risk.  

Currently this can be done by calculating and manually entering initial_cost or DCA_max_cost values and a static % stop loss, but using the ATR% for a trailing stop loss and position sizing would allow a more accurate and dynamic stop based on current market volatility and potentially offer a significant improvement to risk management.

**Comment by philfromqueens** [comment]
> I'd loveto use ATR% for Stop Loss in addition to Trailing Stop Loss also.....

trailing stop loss is a must for the atr indicator.  im surprised that was overlooked

**Comment by taniman** [comment]
@GeorgeBIV 

for this calculation are you ignoring the % or  should the calculation actually look like this?

Calculated Position Size = (R% * Balance) / ATR%
$100 = (1% * $1000) / 10% ATR

Those are percentages displayed as decimals
100 = (0.01 * 1000) / 0.1

**Comment by GeorgeBIV** [comment]
percentages as decimals, yes.

**Comment by crocal420** [comment]
> @GeorgeBIV
> 
> for this calculation are you ignoring the % or should the calculation actually look like this?
> 
> Calculated Position Size = (R% * Balance) / ATR%
> $100 = (1% * $1000) / 10% ATR
> 
> Those are percentages displayed as decimals
> 100 = (0.01 * 1000) / 0.1

Hi boss,
any news about implementing this feature?
Risk Management and Position Sizing is more important than a Strategy. Profit Trailer with this feature will be unbeatable and we need it as soon as possible.
Thank You.

**Comment by iller75** [comment]
> 
> 
> > @GeorgeBIV
> > for this calculation are you ignoring the % or should the calculation actually look like this?
> > Calculated Position Size = (R% * Balance) / ATR%
> > $100 = (1% * $1000) / 10% ATR
> > Those are percentages displayed as decimals
> > 100 = (0.01 * 1000) / 0.1
> 
> Hi boss,
> any news about implementing this feature?
> Risk Management and Position Sizing is more important than a Strategy. Profit Trailer with this feature will be unbeatable and we need it as soon as possible.
> Thank You.

Agreed on that, risk management is the most important thing when trading.

**Comment by taniman** [comment]
2.4.29 will allow for various properties to be dynamic and use any local or global indicator to calculate a dynamic value

initial_cost and DCA_max_cost are 2 of those proeprties that can be made dynamic
