### ISSUE TITLE
Integration of Donchian Channel indicator (or just a PDHIGH that tracks past X candles instead of just past 1 candle)

### ISSUE THREAD

**Issue by philfromqueens** [taniman/profit-trailer-enhancements#594]
I would love to see a Donchian Channel indicator in PT.  The Donchian Channel simply tracks the highest high and lowest low for the past x periods.  I would like to use this indicator in order to buy coins that are breaking out and trading past their previous high in the past x candles.  

In order to trade the breakout, PT would have to keep track of the donchian upper channel value for the previous candle and trigger a true when the current ask is higher than this value.  

Alternatively, an easier solution would be to allow PDHIGH to be tracked for previous x candles.  So keep track of the PDHIGH not for just the previous candle but for the high for the previous x candles.  This would act exactly the same as a donchian channel value.

**Comment by taniman** [comment]
this was already implemented
