### ISSUE TITLE
Trailing Stoploss Type Grow

### ISSUE THREAD

**Issue by randomguy1115** [taniman/profit-trailer-enhancements#595]
Hi,

it would be nice if the trailing stoploss trigger could also grow like the normal trailing.

Something like this:
DEFAULT_trailing_stop_loss_trigger_arm = 10
DEFAULT_trailing_stop_loss_trigger_percentage = -20
#DEFAULT_trailing_stop_loss_trigger_type = grow

If Profit is at 10% it would sell at 8%
if profit is at 100% it would sell at 80%

best regards

**Comment by taniman** [comment]
use dynamic logic
