### ISSUE TITLE
StochRSICross Spread as a Value not a Percentage

### ISSUE THREAD

**Issue by fletch63** [taniman/profit-trailer-enhancements#596]
Correct me if i am wrong in my understanding. The StochRsicross spread is based on the % difference between the K and D lines, which is a problem, as it varies depending on the K and D levels.  I want to buy, if the K line crosses above the D line and there is a minimum actual(not %) spread.  The percentage spread causes false buys at lower levels and causes late buys at higher levels.  Examples:  if D = 1 and K = 1.25 the spread is 25%, but the actual spread is only 0.25(this results in false buys because the spread is too small).  if  D=50 and K 62.50 the spread is still 25% but the actual spread is 12.50.  if D=80 and K 100 the spread 25% but the actual spread is 20( which can cause late buys).  Would like to have the spread as an actual value, which remains the same across the entire range and not a percentage spread which varies across the range.

**Comment by fletch63** [comment]
Hi Devs.  Is there a possibility the enhancement will be implemented?  I do not want to waste a lot of time testing my StochRSI strategy(which is promising but let down by false buys at lower levels), if it will never be implemented. Thanks

**Comment by Jthwaits** [comment]
Hi there, yeah absolutely, this needs attention. It'd be nice also to see a visualization of this in Tradingview if this isn't possible, just so we can at least see what the bot is seeing and work around it.

**Comment by mygreeneggsandham** [comment]
StochRSICross is theoretically my favorite strategy (if it worked as it should) as well. Please Devs look into this.

**Comment by Choza444** [comment]
It does not work very well, especially for closing a deal by crossing.

**Comment by taniman** [comment]
this was already change in 2.4
