### ISSUE TITLE
DCA Buy Trigger should be dynamically adjusted based on a coin's ATR value

### ISSUE THREAD

**Issue by philfromqueens** [taniman/profit-trailer-enhancements#597]
Instead of a DCA Buy Trigger that works in percentage gain/loss in profit of a coin, I would like to see the buy trigger be set to a ATR value that changes dynamically to the volatility of the specific coin.  

Instead of: 
DEFAULT_DCA_buy_trigger_1 = -1
DEFAULT_DCA_buy_trigger_2 = -2
DEFAULT_DCA_buy_trigger_3 = -3

it would be: 
DEFAULT_DCA_buy_trigger_1 = 1 ATR
DEFAULT_DCA_buy_trigger_2 = 1 ATR
DEFAULT_DCA_buy_trigger_3 = 1 ATR

ATR would be the Average true range for a specific coin.  Whenever a coin would exceed one ATR (either positive or negative) from the purchase price, then the buy trigger would be true and DCA buy strategies would go into effect (or ANDERSON would automatically buy it upon triggering).

**Comment by taniman** [comment]
Not applicable anymore as buy trigger no longer exists
