### ISSUE TITLE
Sound When A Sale Is Made

### ISSUE THREAD

**Issue by drlove69** [taniman/profit-trailer-enhancements#6]
Hey all,

It would be great if you could implement a music player into PT so we all could listen to our love songs or celebrations song at the same time as we watch PT profit away.
Just imagine some Beethoven when there is a sell :)

**Comment by clownfish44** [comment]
Very good idea to have sounds (maybe even songs or custom) on a sale to let people know

**Comment by securitygeneration** [comment]
Cha-ching? 💰

And then a buzzer for final-level DCA 💸

**Comment by LeaderOfChampions** [comment]
Shouldn’t we have their skill set focused on something less trivial? Something that would earn more profit?

**Comment by PdubsRandom** [comment]
I don't care for the music idea. I mean your on the computer play your music.
But i do like a Cha Ching when something sells.
Personal gratification from another room means i don't have to sit there and watch the red go green.
I only like it for a sell notification sound or for an error.

**Comment by securitygeneration** [comment]
@LeaderOfChampions I was kinda trolling ;) I also think there are many better places for the devs to spend their time before getting to maybe-nice-to-have-but-only-a-few-people-would-actually-use features...

If people really want this, you could just tail the log, grep for 'SOLD' and trigger a sound file to play in the meantime. On the Mac you could probably even make it speak the sale and profit amount :)

**Comment by tactikill** [comment]
"Goin' up" - IAMSU

but, seriously, there are much more dire features than this.

**Comment by angelsomar** [comment]
I think this is fixed with Telegram and Discord Notifications
