### ISSUE TITLE
Feature Request: [Percentage Based Trailing]

### ISSUE THREAD

**Issue by RichardLuo0506** [taniman/profit-trailer-enhancements#60]
Requested Params:
```
   ALL_trailing_profit_percentage
   ALL_trailing_buy_percentage

```
Trailing is a major piece of PT, but it has limited use for certain strategies. Using a percentage based trailing (especially used for DCA) would vastly improve its use cases in different strategies.

Rationale:
If I have a strategy based on a short trading window with an ALL_sell_value at 1%, I'd want a trailing buy of something like 0.1%. Problem is, if the coin dips further, 0.1% is pretty meaningless at a -10% dip. When a coin dips by 10%, I don't care about fractions of percentages, I want to get out of the coin ASAP to make room for more efficient trades, so I'd want ALL_trailing_buy to be 1-2%.
On the positive side, if a coin pumps 10%, I'm willing to wager 1-2% profits to ride the pump all the way to the top. I think this would vastly increase our profits, range of strategies, and limit our risk on a bad entry point.

Example:
ALL_trailing_buy_percentage = 10%

My coin dips by 3%, my DCA trailing buy becomes 0.3%.
My coin dips by 30%, my DCA trailing buy becomes 3%

**Comment by iAmVaeVictus** [comment]
I like this as well. Could be implemented with Feeder however without changing the current code base.

**Comment by RichardLuo0506** [comment]
Afaik Feeder measures in USD value rather than in BTC, so that's not helpful. Also Feeder will offset your trailing based on a set timeframe, not against your initial entry.

**Comment by Othon3** [comment]
My proposal would be quite the opposite:  Elastic Trailing Buy and Sell   -  or dynamic

   ALL_trailing_buy_dynamic = true/false
   ALL_trailing_profit_dynamic = false/false


profit-trailer-enhancements

Implement a way that trailing would be more dynamic, with elastic propertiers.

I explain: For the trailing buy for example, as the price moves downwards, traling becomes shorter and shorter by a degree measured in % of the pattern to estimate how far the price could rally.
If we set a buy_value of -1 and a trailing of 0.30 . Once the price reaches the -1 the bot starts trailing for 0.30 dip. As it passes the -1.3 mark, trailing would decrease buy a x% , and so forth. The ideia is to get the lowest price possible to buy. It the price goes back up, it wouldn´t have to go all the way up the 0.3 trailing, but only a % of it, measured from the lowest point in relation to the first trigger.

The same logic would apply to trailing profit. As the price moves higher than our sell_value and the bot starts traling, the trailing value would become smaller and smaller as the price moves higher above the triggered price. In the same result, this would try to get the higher price possible to sell it.

Ex...
ALL_buy_value = - 5
ALL_trailing_buy = 2
ALL_trailing_true_dynamic = true

Your coin reaches its buy trigger (-5) and PT starts trailing.
It dips by -2%, nothing changes... As the price drops to -3% (50% less than the original 2% trailing), PT would dynamic decrease the trailing buy by the same 50% (now would be ALL_trailing_buy = 1).
Coins dips to -4% (30% drop from than the last -3% drop).  , trailing drops the same 30% to 0.7%
Prices rises to -3.3% >> PT places a BUY ORDER!

(TODAY´s trailing buy would have to wait for the price to come back to -2% to place that order.

ON the sell side, its the same:

Ex...
ALL_sell_value = 10
ALL_trailing_buy = 4
ALL_trailing_true_dynamic = true

Your coin went up the 10%. Trigger is on and starts trailing...
Coin reaches 14% gain (nice!)...
Coin reaches 18%  ( 100% more than the original trailing), PT reduces trailing buy half
ALL_trailing_buy = 2
COIN rises to 20% (another rise by 100%), trailing reduces again.. now its 1%
COIN drops to 19%  ... SELL ORDER PLACED.

**Comment by clownfish44** [comment]
https://github.com/taniman/profit-trailer/issues/289 already in milestone

**Comment by AkliOnet** [comment]
https://github.com/taniman/profit-trailer/issues/227

**Comment by niroshana35** [comment]
I also Vote for this SMART Trailing Buy & Sell Strategy @RichardLuo0506 which will allow the PT Traders to capture the best possible lowest price in a major down trend or sell a pair for the best possible Profit in a major up trend other than stuck with DCA bags or sell for a low profit due to static trailing values. This will be a great addition for the PT strategies.
