### ISSUE TITLE
-Feature Request- DEFAULT_Reserve_Amount_Percentage

### ISSUE THREAD

**Issue by W1949M** [taniman/profit-trailer-enhancements#600]
The age old question, **do you hold or do you trade.**  I think we've all been there where we've felt like we are holding a coin that's going to be the next big thing, and as a result, it makes us make stupid decisions.  Well no longer, this slight modification to the existing Reserve amount code will allow us to set a reserve % for each coin individually, allowing with consistent trading to accumulate an constantly growing reserve amount so that down the line, we don't have to regret selling all of our coins earlier for mere single digit percents.  I honestly think this would help everyone to trade with peace of mind, growing capital while also building a portfolio that will be worth far more at the top, without having to guess or gamble on which coin will be the next to moon.  **HODL your coins and trade them too!**

**Comment by taniman** [comment]
no t applicable anymore as we no longer have reserve_amount logic inside a config
