### ISSUE TITLE
[Feature Request] Custom buy & sell conditions based on which buy & sell strategy is TRUE

### ISSUE THREAD

**Issue by Rh0msfer** [taniman/profit-trailer-enhancements#601]
Hi all,

Here's a suggestion for new functionality for PT. 

I would like to be able to customize some "DEFAULT" buy and sell parameters dependent on which strategy is being used by PT to buy and sell.

Fox example if we are using 2 strategies to buy:
Strategy 1 = EMASPREAD (A) AND EMAGAIN (B)
Strategy 2 = RSI (C)

DEFAULT_buy_strategy_formula = (A && B) || C

I would like to say:

IF (A AND B) is TRUE then the bot should use the following settings:
DEFAULT_trailing_buy = 0.2
DEFAULT_trailing_buy_rebound_count = 1
DEFAULT_trailing_buy_reset_with_strategies = true

IF (C) is TRUE then the bot should use the following settings:
DEFAULT_trailing_buy = 0.001
DEFAULT_trailing_buy_rebound_count = 0
DEFAULT_trailing_buy_reset_with_strategies = false

Now you might be thinking, what should the bot do if BOTH conditions are true. In that case we introduce a new weighting variable for each strategy. The bot will use the higher weighted condition if more than one strategy is true.

As an example we could write something like this (if it becomes supported) into the "Active Config" advanced display:

DEFAULT_buy_strategy_formula = (A && B) || C
IF ( A && B )                                                     // i.e. A&B = true
{
    Weight = 50
    DEFAULT_trailing_buy = 0.2
    DEFAULT_trailing_buy_rebound_count = 1
    DEFAULT_trailing_buy_reset_with_strategies = true
}    
IF ( C )                                                           // i.e. C = true
{
    Weight = 51
     DEFAULT_trailing_buy = 0.001
     DEFAULT_trailing_buy_rebound_count = 0
     DEFAULT_trailing_buy_reset_with_strategies = false
}          

I currently have quite a complicated strategy running on some of my bots and I'm limited to what I want the bot to do as I cannot specify different trailing buys and trailing profits for each strategy. My main strategies are mutually exclusive, so only one of them can be TRUE at an one time (so I wouldn't actually need a weighting in my case). My strategy is centered around EMASPREAD and looks to go long when the overall conditions of the market are bullish for a given time frame. The strategy looks at retracements based on the momentum of longer term trend, it's basically ABCD trading. I want to trail profit and buys different depending on the relative strength behind a move.

Here's my formula, for each strategy separated by ORs I want to customize buy and sell parameters as demonstrated above.

BTC_buy_strategy_formula = (H && D && C && B && O && U) || (H && I && J && !D && C && B && O && U) || (H && I && J && C && B && P) || (H && D && C && B && Q) || (H && I && !D && C && B && Q)

 STRATEGY #1 (89/200 > 2 WAIT FOR RETRACEMENT INTO THE BLACK)
 3/13 EMASPREAD -VE                DOWNTREND, BEIGE CROSS BLACK        (H)
 13/34 EMSPREAD +VE 0.25 to 10     UPTREND, BLACK + YELLOW             (D)
 34/55 EMASPREAD +VE 0.01 to 10    UPTREND, YELLOW + RED               (C)
 55/89 EMAREPAD +VE 0.1 to 10      UPTREND, RED + BLUE                 (B)
 89/200 EMASPREAD +VE 2 to 10      UPTREND, BLUE + GREY                (O)
 RSI <49                                                               (U)

 STRATEGY #2 (89/200 > 2, !H, WAIT FOR RETRACEMENT INTO THE RED)
 3/13 EMASPREAD -VE                DOWNTREND, BEIGE CROSS BLACK        (H)
 3/34 EMASPREAD -VE                DOWNTREND, BEIGE CROSS YELLOW       (I)
 3/55 EMASPREAD -VE                DOWNTREND, BEIGE CROSS RED          (J)
!13/34 EMSPREAD +VE 0.25 to 10     DOWNTREND, BLACK + YELLOW           (!D)
 34/55 EMASPREAD +VE 0.01 to 10    UPTREND, YELLOW + RED               (C)
 55/89 EMAREPAD +VE 0.1 to 10      UPTREND, RED + BLUE                 (B)
 89/200 EMASPREAD +VE 2 to 10      UPTREND, BLUE + GREY                (O)
 RSI <49                                                               (U)

 STRATEGY #3 (89/200 LESS THAN 0.5, NO 13/34, WAIT FOR RETRACEMENT INTO BLUE)
 3/13 EMASPREAD -VE                DOWNTREND, BEIGE CROSS BLACK        (H)
 3/34 EMASPREAD -VE                DOWNTREND, BEIGE CROSS YELLOW       (I)
 3/55 EMASPREAD -VE                DOWNTREND, BEIGE CROSS RED          (J)
 34/55 EMASPREAD +VE 0.01 to 10    UPTREND, YELLOW + RED               (C)
 55/89 EMAREPAD +VE 0.1 to 10      UPTREND, RED + BLUE                 (B)
 89/200 EMASPREAD +VE 0.1 to 0.499 UPTREND, BLUE + GREY                (P)

 STRATEGY #4 (89/200 GREATER THAN 0.5, LESS THAN 2, WAIT FOR RETRACEMENT INTO BLACK)
 3/13 EMASPREAD -VE                DOWNTREND, BEIGE CROSS BLACK        (H)
 13/34 EMSPREAD +VE 0.25 to 10     UPTREND, BLACK + YELLOW             (D)
 34/55 EMASPREAD +VE 0.01 to 10    UPTREND, YELLOW + RED               (C)
 55/89 EMAREPAD +VE 0.1 to 10      UPTREND, RED + BLUE                 (B)
 89/200 EMASPREAD +VE 0.5 to 1.99  UPTREND, BLUE + GREY                (Q)

 STRATEGY #5 (89/200 GREATER THAN 0.5, LESS THAN 2, WAIT FOR RETRACEMENT INTO RED)
 3/13 EMASPREAD -VE                DOWNTREND, BEIGE CROSS BLACK        (H)
 3/34 EMASPREAD -VE                DOWNTREND, BEIGE CROSS YELLOW       (I)
!13/34 EMSPREAD +VE 0.25 to 10     DOWNTREND, BLACK + YELLOW           (!D)
 34/55 EMASPREAD +VE 0.01 to 10    UPTREND, YELLOW + RED               (C)
 55/89 EMAREPAD +VE 0.1 to 10      UPTREND, RED + BLUE                 (B)
89/200 EMASPREAD +VE 0.5 to 1.99  UPTREND, BLUE + GREY                (Q)_

**Comment by taniman** [comment]
I think with more and more proeprties like trailing_buy and trailing_profit having support for dynamic logic  this is partially possible and would grow with time
