### ISSUE TITLE
[Feature Request] Retrieve PT License using email 

### ISSUE THREAD

**Issue by sagarspatil** [taniman/profit-trailer-enhancements#603]
Hello,

It would be great if there was a simple way to retrieve license information. 

Here's how it would work. 
Provide a simple form that asks for user's email, if the email has any PT license associated with it, simply send PT license to the email provided by the user.

**Comment by taniman** [comment]
The license system and the shop backend  are not linked.  So that is not really a small task.

Since this is also not bot feature but an internal matter I will close the ticket
