### ISSUE TITLE
[Minor Enhancement] Display Stoploss / Trailing Stoploss values in UI

### ISSUE THREAD

**Issue by HomeY** [taniman/profit-trailer-enhancements#604]
Hi,

It would be really nice if you could see the configured Stoploss / Trailing Stoploss values in the User Interface (Pairs & DCA tabs).
Maybe use a separate column for them? For example by combining SSV / SST into 1 column, and using the free column for SL / TSL.
Or add a line with the values to the Advanced Stats?

**Comment by taniman** [comment]
SL and TSL are displayed in advacned stats
