### ISSUE TITLE
Absolute Value Operator for Strategy Formulas

### ISSUE THREAD

**Issue by hoffer49** [taniman/profit-trailer-enhancements#606]
Perhaps an absolute value operator |x| could be added to enhance the buy/sell strategies. 
Example:
A buy order will be placed if:
A and B and C are true, where A has a Negative value 
OR if
|A| and D and E are true, where |A| is the positive value of A

So the syntax might look something like this where :
DEFAULT_buy_strategy_formula = (A && B && C) || (|A| && D && E)

I realize there are other ways perform this, but it requires extra buy/sell strategies. Adding the absolute value operation could help make creating buy/sell strategies more efficient by keeping the file size down when working with a lot of pairs.

**Comment by Masterofcoinak** [comment]
Can't you just copy the strategy A and change it to F with a negative value!?

**Comment by hoffer49** [comment]
Again, I realize there are other ways perform this, such as what you have listed above, but adding an absolute value operation could help make creating buy/sell strategies MORE efficient by keeping the file size smaller when using Feeder or PT Magic in conjunction with PT.

**Comment by taniman** [comment]
Using the dynamic logic SA< 0 and SA>0 will accomplish this. And you don't have to duplicate strategy setup either.
