### ISSUE TITLE
Feature Suggestion: Disable Alt After Price Rise % From Previous Low/Enable Alt After Price Decrease % from ATH

### ISSUE THREAD

**Issue by locohammerhead** [taniman/profit-trailer-enhancements#607]
Configurable setting which will disable all pairs which have competed their bull run.
User configurable % max price rise and drop.  When the price rises the user defined max trading %, trading is disabled for that pair until the price has decreased the % define by the user.

Example.  
LTC
Total % Rise: 1,000
Total % Decrease: 50

Bot will take the previous ATH and use that to determine if the price of the coin has dropped 50%.  If the coin hasn't dropped that much in price coin remains disabled until the req is met.
Once the coin has dropped the specified % coin is enabled for trading until the % rise req has been met.  Once that happens trading on coin is disabled and bot waits for Total % Decrease to be True.

I've been very happy with the bot and think this one feature request will help PT get into overall better positions more consistently.  Especially for people like I who trade the whole market and only use DCA.

**Comment by taniman** [comment]
You can use CHANGEPERCENTAGE stategy or PDHIGH strategy to simulate this almost pretty well.
