### ISSUE TITLE
[Feature Request] Countdown Sell Strategy

### ISSUE THREAD

**Issue by PTMaza** [taniman/profit-trailer-enhancements#608]
**[Feature Request] Countdown Strategy**

Let's say you are doing Scalping on multiple Time Frame. If you larger Time Frame is base on 20 Moving Average of 15 minutes, that mean that it is Base on the last 5 hours (20 x 15 minutes = 300 minutes).
The idea is to cut your trade regardless if it is a gain or a loss. Because after 5 Hours you can be sure that you wont catch the trend expected on your previous strategy; it is a missing trade.
With this you'll be able to get out of a losing trade before your Stop Loss. 

_DEFAULT_B_Sell_Strategy = COUNTDOWN
DEFAULT_B_Sell_Strategy_Label = Countdown 300 minutes
DEFAULT_B_Sell_Value = 300_

This is really usefull for the Short Time Traders. 
Hope it will make sens

Maza

**Comment by Mzzlaza** [comment]
You can call that how you want to call it. I am french and I do not matter (as long that we get it). : ) I am sure that « count down sell strategy » was not the right title. Cheers :)

**Comment by PTMaza** [comment]
It is the same for me 😀

**Comment by PTMaza** [comment]
@Diesel-That-Bot I think « age » is different. Age will look how old is a coin. Countdown will be a sell strategy triggered from  the date of the purchase. Hope it will make sens

**Comment by PTMaza** [comment]
But if you want to sell your pair 4h after you bought it, can you do this?

**Comment by taniman** [comment]
hodlingtime strategy will accomplish this
