### ISSUE TITLE
Open in Tradingview: Including strategy and variable settings from PT.

### ISSUE THREAD

**Issue by bkafe** [taniman/profit-trailer-enhancements#61]

**Comment by clownfish44** [comment]
You can not open settings and stuff from pt in to trading view your best option would be to open tradingview and put the info in or use this https://github.com/CryptoGnome/Community-Tools/tree/master/ProfitTrailer-Tools/Web-GUI-Addons/Advanced-Exchange to open trading view but nothing will put the strategy in for you.
