### ISSUE TITLE
Percentage Based Bag DCA with AutoCalculation

### ISSUE THREAD

**Issue by majhealth** [taniman/profit-trailer-enhancements#610]
Have DCA buy percentages auto calculate percentage based on how close to  % negative or positive you want a bag to be based on current market value of the buy. 

For example if I buy 100 dollars of "linkusdt" at 1 dollar per "linkusdt"and I go negative 2% (I'm now at 98 dollar value with 100 coins). My first DCA buy triggers at negative 2%. I receive a signal to buy the coin at 2% (the stars align).... I now buy 50% at level 1. 50 percent equals 50 coins at .98 cents per coin. I now own 150 Coins at 149 dollars total. Averaged out to .9933333333333.... per coin cost. So the coin is now 1.36% negative which is still a long way away from profit. The coin spikes up 1% before dropping again and now I'm DCAing again as this scenario continues. 

If the bot could calculate what the DCA buy level percentages should be based on what are acceptable -% values at each level this would be a much better configuration wouldn't it? 

DEFAULT_DCA_buy_percentage_1 = -.5
DEFAULT_DCA_buy_percentage_2 = -.75
DEFAULT_DCA_buy_percentage_3 = -1
DEFAULT_DCA_buy_percentage_4 = -1.25
DEFAULT_DCA_buy_percentage_5 = -2

Now I can say on Level 1 I want my bag to be -.5% after DCAing. Allowing small pumps to get me out of bags. So taking the scenario above if I had the 100 coins and hit -2% and DCA level 1 triggers a buy. The level is set to say I want to be at -.5% after the buy so profit trailer auto calculates that the percentage buy should be 310 coins at .98 cents. This gives me 410 coins total with an average value of .984874 cents. As a result I'm at -.5% on the dot. The coin pops up 1% and I'm now +.5% again and sell for a profit. The whole goal of DCAing is to average out your value to get you closer to being able to make profit or breaking even in a given order. You could say set my level 1 buy to 300% and that solves the problem for my scenario, but that percentage needs to be fluid to change based on market conditions.

**Comment by taniman** [comment]
I believe such function will make you lose sight of how much you are actually DCA'ing and thus too dangerous. You should make a consoince deciscion and tell the bot exaclty how much it needs to DCA to get to the level you want
