### ISSUE TITLE
Sell on first signal

### ISSUE THREAD

**Issue by mygreeneggsandham** [taniman/profit-trailer-enhancements#611]
Just as DEFAULT_A_buy_on_first_signal buys a coin as soon as the buy strategy becomes true, I would like a DEFAULT_A_sell_on_first_signal. 
I use strategies without trailing and without stoploss but trade based on what the indicators are showing. This works well as an automatic gain and stoploss but sometimes the values are "True" and the bot sits there thinking about it while the coin price sinks. I would love for the bot to automatically execute the strategy as soon as it becomes true.

**Comment by voltaxvoltax** [comment]
I just posted the same request!

**Comment by taniman** [comment]
This is incorrect.  The bot never thinks about selling. If all strategies are true the bot always tries to sell. And you will also see the attempts in the log file. 

If not, you may be having some different issue. And you need to go through support and check together what is wrong
