### ISSUE TITLE
Add VWMA-SMA strategy

### ISSUE THREAD

**Issue by raenrfm** [taniman/profit-trailer-enhancements#613]
I like using volume based indicators and strategies, and I feel the VWMA-SMA strategy would be dead simple to implement in PT.  Essentially the strategy works by taking the difference between the VWMA (Volume Weighted Moving Average)  and the SMA, if it's positive it indicates the market is rising and the difference indicates with how much momentum.  If negative it's dropping and the higher the negative value the more negative momentum the market is experiencing.  When I get a candle close with a positive value I take a position, when it finally turns negative (losing momentum and about to reverse) I close the position.

**Comment by taniman** [comment]
I beleive 2.5.0 will have enough to build this strategy
