### ISSUE TITLE
Feature Request:  Specific Sell Strategy linked to Specific Buy Strategy

### ISSUE THREAD

**Issue by mygreeneggsandham** [taniman/profit-trailer-enhancements#614]
I would like to see a specific sell strategy tied to a specific buy strategy. So, for instance, if you buy with A && B then the sell strategy would be X. If you buy with C && D then the sell strategy would be Y. 
This would allow for buy strategies that are good for longer term, higher profit gains to have their own sell conditions and if the market is indicating a scalping opportunity you can have a sell strategy that will sell for smaller and faster gains.

**Comment by taniman** [comment]
This should be possible in 2.5.0 seeing as we can get the buy strategies that were true from buy logs records. Though if trailing is enabled it would proof really difficult to know which strategies were true. But it's a start
