### ISSUE TITLE
Feature Request: Trailing as a strategy

### ISSUE THREAD

**Issue by mygreeneggsandham** [taniman/profit-trailer-enhancements#615]
I would like to see trailing be a buy/sell strategy.  I use several different sell strategies, some catching a rising wave where trailing is quite useful but I also have sell strategies that are on the backside of a wave, where a very small gain is still better than a stop loss. 

Having trailing only be a global On/Off is not flexible enough. I would like to see Trailing be a sell strategy. 
Imagine it like this: A = trailing  B = Gain 2%  C = Gain 0.1  D = (favorite indicator downswing)  E = (favorite indicator upswing)
(A && B && E) || (C && D)

**Comment by taniman** [comment]
In 2.4 you can define a formula for trailing to indicate which strategy combinations trail and which don't.
