### ISSUE TITLE
[Feature Request] - Bittrex Credits Use

### ISSUE THREAD

**Issue by ajpyoung** [taniman/profit-trailer-enhancements#618]
Have the ability to use Bittrex Credits on transactions, if available.

**Comment by blackup223** [comment]
I got this information from the website: 
*You can use Bittrex Credits when placing orders from the v3 API by including "UseAwards": true in the request body. Note that the order will fail if you do not have sufficient Bittrex Credits available. You can get your current Bittrex Credits balance by querying any of the balance APIs and looking for BTXCRD. *

hopefully either the PT team can make the logic for that or bittrex can turn it on by default which imo it should be anyways

**Comment by taniman** [comment]
Until Bittrex changes their API to not error out when user does not have enough credit I won't implement this
