### ISSUE TITLE
Feature Request: [Strategy Grouping]

### ISSUE THREAD

**Issue by RichardLuo0506** [taniman/profit-trailer-enhancements#62]
Problem: Not every strategy works for every coin. Not only do coins behave differently, they change their behavior in different market conditions. To account for this, I know of people who run different instances of PT and PTFeeder so they don't have to manually set the strategy for each coin on the same PT instance.

What we can do is something like this:
```
group_1_buy_strategy = EMASPREAD
group_1_buy_value = -1.5
group_1_sell_strategy = GAIN
group_1_sell_value = 1
group_1_trailing_profit = 0.215
group_1_trailing_buy = 0.215

group_1_pairs = ETHBTC, ADABTC
```

This would still follow the inheritance model existing in PT, coin-specific settings would still be highest priority and override groups settings and general settings.

`Coin > Group > General`

**Comment by clownfish44** [comment]
This is already part of PTFeeder / PTMagic which has been requested to be added here #19
