### ISSUE TITLE
[Feature Request] - Improve BitMex position/breakeven calculations including funding interest

### ISSUE THREAD

**Issue by bibotter** [taniman/profit-trailer-enhancements#621]
I love the new features in 2.4.x but personally for me the recent addition of BitMex support is the biggest breakthrough feature of PT and one that will be embraced by a bigger audience sooner or later.

I noticed that the breakeven/position calculations shown on BitMex UI and ProfitTrailer GUI are not identical. There also seem to be cases when ProfitTrailer needs to be manually told the bought cost of a position (pending orders, crashes, withdrawals etc may result in this). On other non-leverage exchanges I would expect manual intervention to be required, but BitMex works differently and it always knowns the breakeven level, above which it is possible to take profits. 

What makes this more complicated to calculate is that the leveraged positions require funding which means interest has to be paid/received automatically every 8 hours, as explained here:
https://www.bitmex.com/app/perpetualContractsGuide#funding

So to be able to accurately calculate the breakeven, PT should either:
- calculate the paid/received interest rates that occur every 8 hours and other events manually
 OR
- let the exchange inform us about the breakeven level

If PT ignores the interest rates, I believe there is a risk that some positions are sold and logged as profit, while in reality they could have been still a bit below break even (=losses).

BitMex also has futures markets where there are no paid interest, but BTCUSD/XBT and ETHUSD/XBT are the main markets with huge volumes and interest from funding plays a big role.

I don't know how hard it would be for PT to start using the position/break even/average information directly from the BitMex API, but I would imagine that using it would avoid a lot of headache and bug reports from PT users.

**My feature request would be for PT to create a BitMex-specific exemption about position calculations: listen to the exchange about the breakeven level AND refresh it periodically to make sure that the effect of funding interest is automatically taken into account.**

**Comment by julpi** [comment]
I would definitely appreciate such improvements to be implement in PT!

**Comment by taniman** [comment]
Using Break Even Price in 2.4.3
