### ISSUE TITLE
[Feature Request] - set the initial_cost of each coin based on DEFAULT_min_buy_volume = TOPXX.

### ISSUE THREAD

**Issue by DrFREEST** [taniman/profit-trailer-enhancements#622]
Hello.
I have a suggestion.
Currently only the following options are available.
BTC_initial_cost = a%
ETH_initial_cost = b%
XRP_initial_cost = c%
...
DEFAULT_initial_cost = x%

In addition to the above
Can you apply the following methods?
(Related option: DEFAULT_min_buy_volume = TOPXX)

TOP1_initial_cost = a%
TOP2_initial_cost = b%
TOP3_initial_cost = c%
...
DEFAULT_initial_cost = x%

**Comment by taniman** [comment]
I beleive with the ability to use different type of dynamic logic to set your initial_cost this is no longer needed.
