### ISSUE TITLE
Add and remove pairs

### ISSUE THREAD

**Issue by LOVEAFLUTTER** [taniman/profit-trailer-enhancements#623]
Hi would it be possible to have back the add and remove pairs like we had on the old GUI?

**Comment by taniman** [comment]
Have a screenshot of what it is you mean. Or more description. We have had many different GUIs

**Comment by LOVEAFLUTTER** [comment]
Hi I haven’t got a a picture, but on the last one and before if I want to
trade pair you had a blacklist box where I could choose the pairs I wanted
to trade rather than true and false.

Saved so much time.

Thanks for your reply

**Comment by LiamAird** [comment]
The Basic GUI, which made this possible, have been removed from the bot, as it were bugged. 
You can still add and remove pairs. You can read about it here: http://wiki.profittrailer.com/doku.php?id=pairs_config#default_trading_enabled

Exchange default with the coin you want to enable/disable
