### ISSUE TITLE
[Feature request] Divergence trading

### ISSUE THREAD

**Issue by des1re10** [taniman/profit-trailer-enhancements#631]
Indicators such as MFI or RSI should be traded on divergences. Single values are quite meaningless.

The strength of the divergence should be adjusted dynamically by the different derivatives of the ascents of the triangles.

**Comment by obsidain001** [comment]
I agree! Please add MFI so we can trade on divergences!

**Comment by taniman** [comment]
Note to self : ConvergenceDivergenceIndicator

**Comment by taniman** [comment]
First implementation in 2.5 will need testing and feedback
