### ISSUE TITLE
Add % amount to the "Total Profits" in Stats/Show as Tables

### ISSUE THREAD

**Issue by sharquz** [taniman/profit-trailer-enhancements#632]
Please add % of daily profit in the view as tables page in stats. It gives the user a better at a glance "how much have I made today / month"
Similar to PT tracker. It's the only reason I fire up Tracker.

<img width="850" alt="Screenshot 2019-11-11 at 00 30 21" src="https://user-images.githubusercontent.com/2532476/68553707-70201400-041b-11ea-8a17-2768e1715158.png">
<img width="1092" alt="Screenshot 2019-11-11 at 00 24 03" src="https://user-images.githubusercontent.com/2532476/68553709-70201400-041b-11ea-961b-8568e1719481.png">

**Comment by LiamAird** [comment]
Coming - same as #775
