### ISSUE TITLE
Add amount of candles to look back on pdhigh and pdlow

### ISSUE THREAD

**Issue by iller75** [taniman/profit-trailer-enhancements#633]
If the amount of candles to look back one could find the latest low or high of a pair. 

This could, for example, be used in a breakout strategy if one looks back at say 50 candles and the price goes above this one could confirm a breakout or breakdown depending one ones strategy one is using. Or it could just be used to look back at the latest high or low candle and save that info.

**Comment by taniman** [comment]
this is possible with pdhigh and pdlow range
