### ISSUE TITLE
DYNAMIC GAIN value using a % of ATRPERCENTAGE

### ISSUE THREAD

**Issue by hoffer49** [taniman/profit-trailer-enhancements#635]
It might be useful to have the ability to set the GAIN value to a % of ATRPERCENTAGE using a formula similar to what can be used for trailing buy, profit, and stoploss:
EXAMPLE:
DEFAULT_DCA_A_Sell_Strategy = GAIN
DEFAULT_DCA_A_Sell_Value = 0.5 * V

This would allow the gain value to be dynamic based on the ATR of each coin.

**Comment by en3z** [comment]
I really want this feature.

**Comment by taniman** [comment]
In 2.4.29 you will be able to use the SA, SB values etc inside a sell_formula and that way you could possibly make the GAIN dynamic. 


Having a dynamic logic in sell_value and buy_value is not possible itself because indicator values have not been calculated yet at that point.
