### ISSUE TITLE
Buy entry using single moving average

### ISSUE THREAD

**Issue by kunalsen83** [taniman/profit-trailer-enhancements#636]
To improve strategies based on EMA cross-overs (for example),  can we have a buy strategy added that works only on (percentage difference from) a single Moving Average ?
The faster moving average often acts as support in a uptrend and best values are often achieved when entering using the faster moving average.  At the moment this cannot be achieved directly using the EMACROSS/ SPREAD or GAIN, which are in use. 
Figure below to illustrate:
![image](https://user-images.githubusercontent.com/30568429/70320292-41c80580-181c-11ea-9d70-8c105ba82334.png)

**Comment by alexanderadnanj** [comment]
TRY THE FOLLOWING

EMAGAIN_candle_period = 300
EMAGAIN_fast_length = 20
EMAGAIN_slow_length = 20

DEFAULT_A_Buy_Strategy = EMAGAIN
DEFAULT_A_Buy_Value = 0.01
DEFAULT_A_Buy_Value_Limit = 0.02
