### ISSUE TITLE
Make it possible to prioritize a certain buy strat

### ISSUE THREAD

**Issue by iller75** [taniman/profit-trailer-enhancements#637]
Say for example that you have two different buy strats, one buys into an uptrend and the other one is a pullback strat. 

I would like to be able to prioritize them with a weight say for example that i'd rather buy into an uptrend i set that to a higher priority and PT would buy coins that has that strat to true over the pullback one.

**Comment by taniman** [comment]
I think addons like feeder and magic are more appropriate for this type of logic.
