### ISSUE TITLE
Crowdsourced SHATlist

### ISSUE THREAD

**Issue by bkafe** [taniman/profit-trailer-enhancements#64]
Ability to leverage a crowdsourced shatcoin list with weighting on up/down vote.
This could be reviewed, filtered (volume, price, etc) and added to SOM list via GUI or rules within PAIRS file.

This would be similar in nature to a SPAM list, or Malware list...but for coin ratings.

**Comment by clownfish44** [comment]
This would not be a part of profit trailer but a standalone resource
