### ISSUE TITLE
[Feature Request] MACROSS | MASPREAD to be able to use different MA types

### ISSUE THREAD

**Issue by VendrediPT** [taniman/profit-trailer-enhancements#640]
I'd like to request for a Buy/Sell Strategy that will allow users to select which type of Moving Averages to use for CROSS and SPREAD (ex: Use SMA for fast and HMA for slow).  Part of my personal algorithm for long entry is when the price is above a specific SMA and a specific HMA.  However, I also require the SMA to be above the HMA to further eliminate false signals.  

I hope this is a realistic request that can be done.
Maybe something like below:
MA_cross_candles = 6
MA_candle_period = 14400
SMA_fast_length = 5
HMA_slow_length = 20

**Comment by taniman** [comment]
Has been implemented in 2.4.9
