### ISSUE TITLE
A few requests for vwap additions

### ISSUE THREAD

**Issue by iller75** [taniman/profit-trailer-enhancements#643]
Vwap is an awesome indicator but i think it could become even better with some additions. 

1. Use vwap as a stoploss, ie if pair price goes below vwap with x % cut your losses.

2. vwap cross as a buy/sell indicator, ie if pair price crosses vwap buy or the other way around for a short bot.

**Comment by Daniel-Rafique** [comment]
This is needed.

**Comment by taniman** [comment]
Point number 2 is already what the current VWAPPERCENTAGE does.  as it's the percentage above/below the VWAP value

Point number 1 needs a bit of thinking about.

**Comment by taniman** [comment]
already possible
