### ISSUE TITLE
Scale Out Take Profit Reset

### ISSUE THREAD

**Issue by locohammerhead** [taniman/profit-trailer-enhancements#645]
Currently the SOTP only takes profit once per level, regardless of if it completes a dollar cost average.  I'd like to see a simple boolean that resets SOTP if the bot completes a dollar cost average.
Example
DEFAULT_DCA_take_profit_reset = true
SOTP set to 5%, 10%, 15%
Position hits 5%, level 1 SOTP completes
Position drops into negative and DCA level 1 completes
SOTP resets 
position rises to 5% again
SOTP takes action on level 1 again

Currently SOTP ignores when a DCA happens and looks for it to hit level 2 before taking action.

**Comment by taniman** [comment]
Already impleented a few versions ago. If DCA happens the level resets automatically no property needed
