### ISSUE TITLE
[FEATURE REQUEST] Set the Amount and Leverage values in TV Signals.

### ISSUE THREAD

**Issue by voltaxvoltax** [taniman/profit-trailer-enhancements#647]
Hello Guys, would be possible to implement in PT TV Signals the amount and the leverage we set in the alert? This way we don't have always the same amount invested, as some signals could be less profitable than others. 
Thanks.

**Comment by taniman** [comment]
This should be ready in 2.4.28  and can be tested and see how well it works.
