### ISSUE TITLE
Crossing up or down function

### ISSUE THREAD

**Issue by runein** [taniman/profit-trailer-enhancements#649]
A crossing up or down function like you have on tradingview is desperately needed. Especially for RSI and STOCH.

For example, how do you solve RSI crossing up 30 in the last candle --> initiate buy ?

OR

Buy when STOCH RSI crosses up 10 and sell when it crosses up 30?

You can add multiple indicators to this and try and solve it but it gets very messy.

runein

**Comment by alexanderadnanj** [comment]
https://wiki.profittrailer.com/doku.php?id=pairs_config#default_a_buy_strategy_direction

**Comment by runein** [comment]
Sure, but this does not cover a up or down cross in the last candle. 

How would you solve RSI crossing up 30 in the last candle -->Buy. And RSI crossing up 70 in the last candle --> Sell ?

**Comment by alexanderadnanj** [comment]
sure this doesn't work?

DEFAULT_A_buy_strategy = RSI
DEFAULT_A_buy_value = 30
DEFAULT_A_buy_value_limit = 0
DEFAULT_A_buy_strategy_direction = UP

DEFAULT_A_sell_strategy = RSI
DEFAULT_A_sell_value = 70
DEFAULT_A_sell_value_limit = 100
DEFAULT_A_sell_strategy_direction = UP

if you want to applied to closed candle 
RSI_candle_period = 300
RSI_length = 14
RSI_only_closed_candles = true

**Comment by runein** [comment]
Unfortunately, it won't work. 

After you have sold RSI 70-100 it will buy as soon as it crosses below 30 RSI, which is in the wrong direction. It will buy as price (RSI) is heading down.

**Comment by locohammerhead** [comment]
@alexanderadnanj I can confirm that strategy direction doesn't work.

**Comment by taniman** [comment]
CROSSOVER/CROSSUNDER strategies have been added for a few months now
