### ISSUE TITLE
Feature Request: [More Info In Logs]

### ISSUE THREAD

**Issue by RichardLuo0506** [taniman/profit-trailer-enhancements#65]
Problem:
   A big problem for those of us who spend 6+ hours a day charting our strategies is that fast EMA lines will swing wildly on the current candle before it settles down. This results in much confusion when charting our buy triggers on TradingView, as well as potentially missing key parts of the trigger such as ALL_max_buy_spread. As far as I know, nobody is testing the effects of ALL_max_buy_spread, for all we know, it could be one of the most important triggers in PT.

Solution:
   It would be nice to have a more detailed log of why PT performed an action. Something like this would allow us to eyeball or write our own scripts to backtest, so you don't have to spend months building a backtest feature. (maybe in telegram messages)

PT bought ADABTC because:
Price was -1.8 below EMA_1 (ALL_buy_value = -1.5)
Spread was 0.2 (ALL_max_spread = 1)
Etc...

**Comment by iAmVaeVictus** [comment]
I like this, and seems low impact on the bot performance and on developer time to implement.

**Comment by ianMihura** [comment]
Yes,, at least to be able to choose the level of verbose we want

**Comment by ukespaz** [comment]
Agreed. I often spend considerable time trying to understand why PT bought at a certain point. This idea would be very helpful.

**Comment by clownfish44** [comment]
You already can turn on debug please read about in the wiki.
