### ISSUE TITLE
[FEATURE REQUEST] trailing_profit_rebound_count deep candle facility

### ISSUE THREAD

**Issue by EccentricDyslexic** [taniman/profit-trailer-enhancements#650]
I can see a use for the rebound count to have two or three setting possibilities, for short candles one rebound and longer candles more rebounds. 
I find that on sudden drops long candles have more rebounds. Having just one setting means the trailing stops higher up in the drop if set to a low figure for long candles, and lower down or not at all for shorter candles. if set to a higher number.
Candle length could be determined by comparing current candle with the length of the previous 2 or 3 candles (this could also be an option).

**Comment by EccentricDyslexic** [comment]
[https://youtu.be/ZOHBY-1wv_I](url)

**Comment by taniman** [comment]
trailing rebound is one of those settings that I am not planning on updating. They seemed like good ideas at the time but have proven to be less than ideal
