### ISSUE TITLE
[FEATURE REQUEST] SL bails out to Test Mode instead of SOM

### ISSUE THREAD

**Issue by EccentricDyslexic** [taniman/profit-trailer-enhancements#651]
An ultimate feature surely, if a trade resulted in a stop loss being hit, then bail out to test mode.
Still making trades based on config but not actually making trades (with real money) until the test mode trades dont result in stop loss being hit.
One could have an option as to how many good trades are made before being allowed to go swimming again.

**Comment by taniman** [comment]
Too much work, with too liitle demand
