### ISSUE TITLE
[FEATURE REQUEST] Add strategy switching based on moving average

### ISSUE THREAD

**Issue by FO320** [taniman/profit-trailer-enhancements#652]
I would love for my bot to be able to switch strategies between longing and shorting based on a moving average: 

Price above MA = long strategy
Price below MA = short strategy

**Comment by taniman** [comment]
Are you talking about the PT AUTO Config?
As you can switch configs but currently the bot does not support long and short in same bot.

**Comment by FO320** [comment]
Yes, exactly. Right now, AUTO CONFIG allows for VWAP- or ADX-based switching, I would love the same kind of config switching using a 200 MA. But it only makes sense once the bot is able to long and short.

**Comment by taniman** [comment]
You mean long and short in same bot. Cause the bot can long and short.

And you could put the long bot in ano buying state once trend chsnges. But it is clear I guess.

Is this 200MA per coin or jist looking at BTC for example to switch the complete  set?

**Comment by FO320** [comment]
The way I would intend to use it would be just for BTC. But it doesn't make a lot of sense as long as the bot does not close (or stoploss) open positions on long/short switch.

**Comment by taniman** [comment]
I see. We do have that feature actually. Just needs a bit more testing. But it is implemented already

**Comment by FO320** [comment]
Nice, looking forward to that!

**Comment by taniman** [comment]
It should be possible to switch strategies based on moving average in 2.4.28
