### ISSUE TITLE
KDJ indicator

### ISSUE THREAD

**Issue by hoffer49** [taniman/profit-trailer-enhancements#653]
This would be a VERY useful addition to the indicators that are already present and I think it would be an easy one to add since it's a derived form of the Slow Stochastic and just adds another line to represent the divergence of D from K.

Here are a few references that explain the calculations:
https://github.com/kaelzhang/kdj
https://news.cqg.com/blogs/indicators/2016/08/kdj-indicator
https://ichihedge.wordpress.com/2017/03/22/indicator-calculating-kdj/

Keeping my fingers crossed for this one ;)

**Comment by hoffer49** [comment]
Here's a reference that explains the calculations:
https://ichihedge.wordpress.com/2017/03/22/indicator-calculating-kdj/

**Comment by taniman** [comment]
Implemented for 2.5.0
