### ISSUE TITLE
Euros/dollar value in PT stats

### ISSUE THREAD

**Issue by bluetyphoon77** [taniman/profit-trailer-enhancements#656]
Would be great to have those euro/dollar values in stats for daily profits, monthly profits,.... like we had in Tracker.
Thanks a lot ;)
Cheeeers

**Comment by LiamAird** [comment]
Can you share a screenshot of the wanted implementation? 
Where do you want fiat values, etc.

**Comment by bluetyphoon77** [comment]
Hi,
Same as what tracker does.

Yvan


________________________________

**Comment by bluetyphoon77** [comment]
Just to mention: I'm not sure if Tracker was using the fiat value at the time of each sell. But this would be better in my opinion.

Cheeers

Yvan


________________________________

**Comment by LiamAird** [comment]
Should already be there - if not, please explain with screenshots as previously requested
