### ISSUE TITLE
Feature Request take profit portion based on strategies & signals

### ISSUE THREAD

**Issue by locohammerhead** [taniman/profit-trailer-enhancements#657]
It's been great being able to scale out and take portion of profit based on gain %.
I would like to extend this option to close a portion of of the position based on strategies or signals
DEFAULT_DCA_A_sell_strategy = SIGNAL
DEFAULT_DCA_A_sell_strategy_label = EXAMPLESIGNAL
DEFAULT_DCA_A_take_profit_portion = 5%
DEFAULT_DCA_A_take_profit_portion_1 = 10%
DEFAULT_DCA_A_take_profit_portion_2 = 15%
...
DEFAULT_DCA_A_sell_strategy = HIGHBB
DEFAULT_DCA_A_sell_value = 5
DEFAULT_DCA_A_take_profit_portion = 5%
DEFAULT_DCA_A_take_profit_portion_1 = 10%
DEFAULT_DCA_A_take_profit_portion_2 = 15%

**Comment by taniman** [comment]
being tested for next release
