### ISSUE TITLE
Feature Request: DCA Trigger % values per coin

### ISSUE THREAD

**Issue by sethiano** [taniman/profit-trailer-enhancements#66]
Please add DCA Trigger % per coin functionality. This will be a great feature on it's own, but with the help of feeder, it will allow us to automatically on the fly raise\lower DCA trigger % levels based on coins activity in the x ammount of time.

This would be HUGEEEEE!

Ideally it would allow us to keep buying down in bear markets and not get buried in DCA.

Example:

PT Functionality: make xcoin dca at -1% -2% -3% because it isn't very volatile. Make Ycoin dca at -5% -10% -15% because it's volatile.

Once this is implemented then the Feeder guys can add it into their product so now Feeder can detect xcoin dropped 15% in 60 minutes so it will allow feeder to change xcoin dca triggers to -10% -15% -20%

PT functionality needs to allow the base code first though.

Thank you to all who have helped! Amazing Product!!!

Seth

**Comment by clownfish44** [comment]
This is already part of feeder and the pull request is here https://github.com/taniman/profit-trailer-enhancements/issues/19
