### ISSUE TITLE
Auto add new pairs once a pair is in "safe" profit

### ISSUE THREAD

**Issue by iller75** [taniman/profit-trailer-enhancements#665]
It kind of sucks that you have to wait until a pair has sold to be able to make a new trade. So what i'm suggesting is a setting that says if pair profit = x then allow a new pair to be bought which could take your pairs above your max pairs. 

If you would pair this with take profit safety for example you should be pretty safe and be able to do more trades instead of waiting until a pair has sold.

**Comment by drbrauwn** [comment]
Another way to accomplish this, is to set MAX pairs, as a ratio of TCV for BALANCE that is in PAIRS log. 
Or add a line to ignore MAX pairs, when Balance in PAIRS is below % of TCV.

This way if you have scaled out in PAIRS, your %BALANCE in PAIRS in regards to TCV drops and it would allow for new buys.

However you then should also need to include the initial cost of a PAIR that has been bought and is in DCA somehow.

**Comment by drbrauwn** [comment]
I still like this a lot. What about this. 

**armed_pair_count_ignore = TRUE**

So if a pair is ARMED and TPS is activated. The PAIR does not count towards max pairs anymore.

For DCA

**DCA_armed_pair_count_ignore = TRUE**

**Comment by taniman** [comment]
I like the solution proposed in #770 . Will continue thinking on that one
