### ISSUE TITLE
GUI display SELL TRAILING TRIGGER  (P%) - based on HP (highest point) minus TV (trailing value)

### ISSUE THREAD

**Issue by drbrauwn** [taniman/profit-trailer-enhancements#666]
Display the latest obtained SELL TRAILING TRIGGER set in P% in green in pairs and DCA log, according to TRAILING values. (see image)

Sell trailing trigger is easily obtained by  HP (highest point) minus TV (trailing value).

It will help in  seeing in a glance how trailing values like GROW for example effects the sale.
Observing these triggers will help adjust them and tweaking them according market conditions

![image](https://user-images.githubusercontent.com/37036023/80171262-2bafbb80-85ea-11ea-9647-f011fd10a3cf.png)

**Comment by taniman** [comment]
Can you remind me why you do not like them at where they are currently? It's the same glance to see them or not?

**Comment by LiamAird** [comment]
@drbrauwn

**Comment by drbrauwn** [comment]
In retrospect I believe the current display meets the right standards already.
