### ISSUE TITLE
[Feature Request] PDHIGH (etc) with value from ATR% 

### ISSUE THREAD

**Issue by EccentricDyslexic** [taniman/profit-trailer-enhancements#667]
Ie, instead of-
Default buy strategy = PDHigh 
Default buy value = 0.1
(I take this as ‘if current price is 0.1% above previous candle’ = true)

I’d like ‘if current price is above ATR/2’ = true.

**Comment by taniman** [comment]
You can use dynamic values inside a formula to accomplish this logic. 

Define PDHIGH -> A
Define ATR  -> B

strategy_formula = SA > SB/2

Possible in  2.4.29
I think with a little creativity this will do what you request here
