### ISSUE TITLE
Feature Request: [Programmatically Combine Strategies]

### ISSUE THREAD

**Issue by RichardLuo0506** [taniman/profit-trailer-enhancements#67]
Preface:
   This is not exactly asking for a fully customizable way of combining indicators, because that would be a ton of work. This is a compromise.

Problem:
   PT is not being used remotely to its full potential. The great thing about profit trailer is that it works very well for a specific market condition. Fast EMAs capture profits well on an uptrend. Super slow EMAs avoid getting caught on a downtrend decently. Most people's strategies combine the two and it's a mess because the more we spread our strategies thin to account for all conditions, the less profit we take in a good market, and we rely on wild swings to make a profit. On the other hand, people like me overextend by a massive amount to take advantage of a good market, but get caught and lose valuable trading time when the market condition changes.

Theory:
   If we can be more selective with our buying opportunities, we can offset the loss of opportunities by taking a larger position, which would allow our strategies to work more efficiently to fit the needs of the specific market conditions we target. If we all target different market conditions, we'll also be less prone to market manipulation.

Example:

Pairs:
```
ALL_buy_strategy = EMAGAIN && LOWBB
ALL_buy_value = -1.5 && 20
```

Indicators
```
BB_period = 3600
BB_sma = 24

EMA_period = 300
EMA_1 = 24
EMA_2 = 3
```

The above example would roughly translate to "I want to buy when price meets my EMAGAIN strategy triggers, but only if it's oversold in a 24 hour period according to LOWBB". A strategy like this would lose out on many buying opportunities on an uptrend, but also limit the risk of DCAing all the way down from the top of a huge rally and being stuck for days/weeks. This is essentially adding an element of Risk Management.

Essentially, we're maximizing our efficiency for a specific type of market by making our entry points more consistent.

[Imgur](https://i.imgur.com/LqNInxf.png)

In this image, we're saying we only want the first buying opportunity. The second buy opportunity we'll forgo, because it could just as easily look like the third buy opportunity.

**Comment by FatedOne** [comment]
I think this would be brilliant!

**Comment by clownfish44** [comment]
Already in the next milestone update here https://github.com/taniman/profit-trailer/issues?q=is%3Aopen+is%3Aissue+milestone%3Av2.0

**Comment by RichardLuo0506** [comment]
Which one?

**Comment by clownfish44** [comment]
https://github.com/taniman/profit-trailer/issues/82

**Comment by RichardLuo0506** [comment]
Oh I see. That would be great. I figured if it takes too much work, this would be a lite version of it.
