### ISSUE TITLE
Implement the Schaff Trend Cycle indicator

### ISSUE THREAD

**Issue by iller75** [taniman/profit-trailer-enhancements#671]
The schaff trend cycle indicator is a trend indicator but that is better than the MACD as it also has a timing component. 

A bit more info can be found here

https://www.youtube.com/watch?v=8pu_G3Eujh4
https://www.investopedia.com/articles/forex/10/schaff-trend-cycle-indicator.asp
https://www.tradingpedia.com/forex-trading-indicators/schaff-trend-cycle

**Comment by missilelaunchr** [comment]
Great suggestion, I was just searching to see if Profit Trailer supported this while considering my purchase.

**Comment by iller75** [comment]
@LiamAird woops, had totally forgotten about that :D

**Comment by LiamAird** [comment]
Right, will close this one

**Comment by TheDeumel** [comment]
So is this going to be implemented?
