### ISSUE TITLE
Separate Running Strategies

### ISSUE THREAD

**Issue by iflesler** [taniman/profit-trailer-enhancements#672]
It would be great to be able to have 2 or more running separate strategies, and ensure that they run completely separate.
We would be able to profit on separate strategies on the same bot, without the need install new bots and thus loading the VPS.
For instance I could run a short term strat along with a long term strat on the same account and bot.

**Comment by taniman** [comment]
the way to do this is using separate bots, Running separate strategies in same bot is a complexity we do not want to add to the bot especially since using multiple bots will accomplish this
