### ISSUE TITLE
[Pair Buying Future] max_change_percentage = %BTC

### ISSUE THREAD

**Issue by perdubaro** [taniman/profit-trailer-enhancements#673]
When BTC is mooning alts in most cases follows the trend but many of those not instantly and they are catching up delayed. So my idea is - when BTC price is up 15 % in a day set up DEFAULT_buy_max_change_percentage = %ofBTC price like 30 % to catch those alts who haven't followed trend yet.

**Comment by leszek9** [comment]
it could be usefull to set DEFAULT_buy_min_change_percentage to %ofBTC pirce drop and use it in short strategy to catch those alt which are late with BTC downtrend

**Comment by taniman** [comment]
This property has not changed. but in 2.5.0 you have the ability to add any indicator to look at another PAIR
so you can add CHANGEPERCENTAGE strategy that looks at BTCUSDT and based on that you create your buy/sell logic
