### ISSUE TITLE
MA strategy suggestions that are really needed (x)MA, wick,touch,above,below

### ISSUE THREAD

**Issue by iller75** [taniman/profit-trailer-enhancements#674]
So one thing i have been missing for a long time is for the bot to tell if the price went above, below, touched (wick or full candle) the different MA's 

So my suggestions is to have a new indicator for the different MA's
Basically define if the price has touched/wicked below/above the ema you have defined, is above it, below it and in (below or above i guess would have to be defined in a percentage) x amount of candles also if one would like that. 

This would make it possible to make strats where you buy for example if a specific ema has been tested and price bounced of that level etc.

**Comment by EccentricDyslexic** [comment]
Upvoted

**Comment by taniman** [comment]
This can be accomplished with a combination of SMALINE and PDHIGH/LOW/ values
