### ISSUE TITLE
Add ATR to trading_pairs_buy_priority

### ISSUE THREAD

**Issue by iller75** [taniman/profit-trailer-enhancements#676]
Would be awesome to be able to buy the most volatile coin etc first using this so please add :)

**Comment by Kurohitsugi9** [comment]
+1

**Comment by MrtnMns** [comment]
+1

**Comment by taniman** [comment]
Added STRATASC/STRATDESC for buy priority so we can sort based on a of our buy strategies. So if you add ATR as a buy strategy you could sort to get most volatile coins first

Added to 2.5.0
