### ISSUE TITLE
[Feature Request] Skip levels straight to buy

### ISSUE THREAD

**Issue by EccentricDyslexic** [taniman/profit-trailer-enhancements#677]
As above, if A certain level1 condition becomes true, go straight to buy. (Spécial shortcut symbol maybe ¥§~ or something?

**Comment by LiamAird** [comment]
Please describe the feature request in detail and provide a possible use case for such a feature.

**Comment by EccentricDyslexic** [comment]
At the moment, one must repeat the code at each level to enable a strategy to pass straight to buy stage. If we could have a short cut symbol this would keep things clearer and simpler. 
Ie instead of -
Level1_strategy = (A && B && (C || D)) || (D || E) || (G && H)
Level2_strategy = K || (D || E) || (G && H)
Level3_strategy = (H && I) || (D || E) || (G && H)
We could have
Level1_strategy = (A && B && (C || D)) || (D || E §) || (G && H §)
Level2_strategy = K 
Level3_strategy = H && I

The § symbol means = skip all other levels.

**Comment by taniman** [comment]
I see not issue with repeating if you want to skip to the end. It makes things easy to understand
