### ISSUE TITLE
[Feature Request] Trailing_buy_no_reset = true

### ISSUE THREAD

**Issue by EccentricDyslexic** [taniman/profit-trailer-enhancements#678]
Don’t reset if price recovers above starting price. Ie bot buys no matter what after starting trailing.

**Comment by LiamAird** [comment]
Please describe the feature request in detail and provide a possible use case for such a feature.

**Comment by EccentricDyslexic** [comment]
The problem at the moment is the bot will cancel the buy if the price rises above the start trail price. This results in no buy at all. If we could have a setting to prevent PT from resetting itself if the price doesn't drop and then rise by the set amount, this will ensure it buys straight away if the prices doesn't drop first. Sometimes a signal comes in and price is still dropping, great, PT will trail, but if price rises and doesn't drop, then no buy will take place, missing the opertunitiy  To buy.
Hope that helps.

**Comment by taniman** [comment]
This logic runs the risk of always buying as soon as trailing starts because price moves a lot up and down. And in that case the question will be why trail at all. 
So I am gonna skip this for now
