### ISSUE TITLE
[Feature Request] Default_await_candle_close = TRUE

### ISSUE THREAD

**Issue by EccentricDyslexic** [taniman/profit-trailer-enhancements#679]
As above. await full formation of candle before progressing/assesing situation.

**Comment by taniman** [comment]
Just want to make clear that this is not how requests should be made. It is not clear what the purpose is of this request and why it is being requested. 

No one would be able to upvote it as they do not have a background knowlegde.

with that being said, I had already indicated in the ticket that this would be worked on. So no need to create a request
