### ISSUE TITLE
Ability to Change Initial Buy, Percentage Buy, and Leverage based on TV Alerts.

### ISSUE THREAD

**Issue by majhealth** [taniman/profit-trailer-enhancements#680]
Many indicators offer the ability to have multiple configurable alert conditions. Levels of long or shorting. Take VWAP Bands, Pivot Points, or Support and Resistance as examples. It would benefit the users to be able to configure different risk and or buying power based on specific alert conditions. I could see this being added to either the alert from TV itself to inform the bot, or in the pairs config itself for the alert. I have provided an example of each below.

-------------------------------------------------------------------------
Using Tradingview Alert to configure:
-------------------------------------------------------------------------
Initial Buy Percentage Config: without Leverage Change
IBP = Initial Buy Percentage

token="License"
position=OPEN
pair=BTCUSDT
valid=60s
IBP=1
label=Longopen
mode=STRATEGY
-------------------------------------------------------------------------
Initial Buy Value Config: without Leverage Change
IBV = Initial Buy Value

token="License"
position=OPEN
pair=BTCUSDT
valid=60s
IBV=0.001
label=Longopen
mode=STRATEGY
-------------------------------------------------------------------------
Leverage Config: Using IBP with as example.
LEV = Leverage

token="License"
position=OPEN
pair=BTCUSDT
valid=60s
IBP=1
LEV=10
label=Longopen
mode=STRATEGY
-------------------------------------------------------------------------
Alternatively using PAIR config as the configuration location
-------------------------------------------------------------------------
Initial Buy Value Config: without Leverage Change
DEFAULT_A_buy_strategy_IBV = Initial Buy Value

DEFAULT_A_buy_strategy = SIGNAL
DEFAULT_A_buy_strategy_label = MyTradingViewLabel (optional, any alphanumeric label you want)
DEFAULT_A_buy_strategy_IBV = 0.001
-------------------------------------------------------------------------
Initial Buy Percentage Config: without Leverage Change
DEFAULT_A_buy_strategy_IBP = Initial Buy Percentage

DEFAULT_A_buy_strategy = SIGNAL
DEFAULT_A_buy_strategy_label = MyTradingViewLabel (optional, any alphanumeric label you want)
DEFAULT_A_buy_strategy_IBP = 1
-------------------------------------------------------------------------
Leverage Config: Using IBP with as example.
DEFAULT_A_buy_strategy_lev = Leverage

DEFAULT_A_buy_strategy = SIGNAL
DEFAULT_A_buy_strategy_label = MyTradingViewLabel (optional, any alphanumeric label you want)
DEFAULT_A_buy_strategy_IBP = 1
DEFAULT_A_buy_strategy_lev = 10
-------------------------------------------------------------------------

**Comment by taniman** [comment]
Implemented in 2.4.28 needs testing to see how/if it works correctly. Create a ticket and I can give you the info
