### ISSUE TITLE
[Feature Request] Liquidation Stop-Loss For Crossed

### ISSUE THREAD

**Issue by AudiInvestor** [taniman/profit-trailer-enhancements#682]
Hi Guys,
I know there is already a stop loss feature in profit trailer which is amazing for normal and isolated pairs. I believe I'm not the only one to work out a good stop loss for crossed as the liquidation can changed based on how much balance you have. My idea is being able to create a stop loss based on a percentage amount away from the liquidation number. For example if your liquidation price is 1,825.00 for ETH, The bot would do a stop loss 10% (if typed in 10% in the config) before it hit the liquidation price.

**Comment by taniman** [comment]
We are beta testing this feature for next release

**Comment by taniman** [comment]
or at least a feature you can use together to buy/sell/stoploss based on liqprice
