### ISSUE TITLE
Apply Heikin Ashi to a specific indicator

### ISSUE THREAD

**Issue by iller75** [taniman/profit-trailer-enhancements#683]
The reason is quite simple, Heikin Ashi is not a good entry indicator. 
It can however be used to spot a trend and also good for making exits. 

So i would for example want to have a specific new setting to each indicator, a true false setting would do similar to the up and down you can use on rsi. This way you could use regular candles on certain indicators but for example use heikin ashi on the trend and exit indicators.

**Comment by taniman** [comment]
This options has been added to 2.5.0 each indicator support candle_type
