### ISSUE TITLE
[Feature Request] link specific buy strategies to specific sell strategies 

### ISSUE THREAD

**Issue by EccentricDyslexic** [taniman/profit-trailer-enhancements#685]
For example-
Default_Buy_Strategy1_formula =( A&&B ) || C 
Default_Buy_Strategy2_formula = D || (E && F)

Default_A_Buy_strategy= EMAGAIN 
Default_A_Buy_value = -0.1

Default_B_Buy_strategy= RSI
Default_B_Buy_value = 30

Default_C_Buy_strategy= EMACROSS
Default_C_Buy_value = 15

Default_D_Buy_strategy= EMACROSS
Default_D_Buy_value = 30

Default_E_Buy_strategy= SMAGAIN 
Default_E_Buy_value = 1

Default_F_Buy_strategy= SMAGAIN 
Default_F_Buy_value = 3

Etc

Default_sell_Strategy1_formula =A&&B && C 
Default_sell_Strategy2_formula = D || A

Default_A_sell_strategy= EMAGAIN 
Default_A_sell_value = 4

Default_B_sell_strategy= RSI
Default_B_sell_value = 80

Default_C_sell_strategy= EMACROSS
Default_C_sell_value = 3

Default_D_sell_strategy= SMAGAIN 
Default_D_sell_value = 4

So linking a particular buy strategy, say a high probability, low profit goal strategy with a matching low profit goal. And a high certainty buy strategy with a higher profit goal.
Hope that makes sense.

**Comment by taniman** [comment]
You could also create a new bot with the low probability strategy settings in a different account

**Comment by EccentricDyslexic** [comment]
Yes, but that would need another bot and another vps (for me) and another account. I agree that is an option, but not ideal.

**Comment by taniman** [comment]
That's true, but some features just are not worth the user confusion it will bring after
