### ISSUE TITLE
[Feature Request] EMAGAIN ect be combined with ATR%

### ISSUE THREAD

**Issue by EccentricDyslexic** [taniman/profit-trailer-enhancements#686]
My suggestion this time is for EMAGAIN be combined with ATR%
ie
default b buy strategy = emagain
default b buy strategy pairing = ATR%
default b buy value = V * 2
so value of buy or sell strategy changes dynamically with volatility

**Comment by taniman** [comment]
You already created a similar request some time ago.  So this is a duplicate
