### ISSUE TITLE
Add dca levels ahead of time, ie limit orders

### ISSUE THREAD

**Issue by iller75** [taniman/profit-trailer-enhancements#687]
Especially when doing leverage trading sometimes the bot is not quick enough to react to a buy that is needed. So pt should post dca limit orders in advance so if a drop happens the orders are already set and the bot can dca without problems. Not sure how often it should update the orders but i think this is a pretty important feature to have. 

Say you have a max of 10 dca levels, all of these should then be set on the exchange ahead of a buy is needed and updated every x seconds price moves up.

**Comment by taniman** [comment]
I am sure some other bot can do this. But PT does not do limit buy orders. The way the bot works does not support this logic
