### ISSUE TITLE
Allow -> DCA_max_trading_pairs to be LEVEL specific

### ISSUE THREAD

**Issue by drbrauwn** [taniman/profit-trailer-enhancements#688]
What I think would help on FUTURES trading, especially with agressive DCA is this:

to have

**DCA_max_trading_pairs  (level specific)**

I would like all pairs to be allowed to DCA 1, but only 3 of them to DCA 2 and 1 at DCA 3

DCA_max_trading_pairs _1 = 6
DCA_max_trading_pairs _2 = 3
DCA_max_trading_pairs _2 = 1

This allows more positions to be DCA'd at level 1, and to be more selective down the road. This prevent being into heavily DCA's positions on the event market agressively turns against you.

A more dynamic approach that enables a smooth flow of the coins through DCA, when funds are available is this:

**DCA_levelx_max_allowed_pairs =x**

**DCA_level2_max_allowed_pairs = 3
DCA_level3_max_allowed_pairs = 1**

Now you can have as many coins as you want at level 1
Only 3 pairs with level 2
Only 1 pair with level 3

Make sure to set max_buy_times. Max buy times cannot be exceeded. The above allowed pairs only adds to that in a sense that it allows for a certain amount of your DCA coins to go to this specific level **(*which always is below max_buy_times*)**  When a coin goes to level 4 for example, then a new pair is allowed  to go to level 3. The above keeps your risk in check and manages your balance dynamically!

**Comment by taniman** [comment]
note to self. Could be something like DCA_level(X)_max_trading_pairs

**Comment by taniman** [comment]
Added to 2.5
