### ISSUE TITLE
Integrated charts for all pairs with ability too input strategies within charts.

### ISSUE THREAD

**Issue by acpstunts** [taniman/profit-trailer-enhancements#69]
Would be really nice too have integrated charts in the GUI especially if multiple buy strategies are being added. Would be amazing too have everything integrated in to the GUI so its your "one stop shop" for all the info needed to determine strategies/pairs/settings to run.

**Comment by clownfish44** [comment]
Charts per coin and tracking has already been requested here https://github.com/taniman/profit-trailer-enhancements/issues/5
