### ISSUE TITLE
[FEATURE REQUEST] stop_loss_strategy FIXEDPRICE

### ISSUE THREAD

**Issue by SkyHighStacks** [taniman/profit-trailer-enhancements#691]
I'd like to be able to use FIXEDPRICE as a stop_loss strategy. That way I can put the SL exactly where I'd like it, e.g. under a support level. 

Right now I have to use a percentage. When I add to a position at the exchange or an extra buy order gets (partially) filled I have to manually change that percentage to keep the SL at the same price. 

Using FIXEDPRICE would also remove the hassle from switching from stop_loss to take_profit_safety when I move the SL above the buy price. With FIXEDPRICE all I'd have to do is put in the new higher SL price.

With a FIXEDPRICE stop_loss_strategy I could add to a position with a stop-limit buy order at the exchange right above a strong support, and let PT sell everything if it breaks down through that support. I wouldn't know how to do that right now.

Ciao!

**Comment by alexanderadnanj** [comment]
am not sure, but I think you can use it under your sell strategy, like this

DEFAULT_sell_strategy_formula = (A || B)

DEFAULT_A_sell_strategy_label = 
DEFAULT_A_Sell_Strategy = FIXEDPRICE 
DEFAULT_A_Sell_Value = 10000

DEFAULT_B_Sell_Strategy = GAIN
DEFAULT_B_Sell_Value = 20

**Comment by taniman** [comment]
Either the above comment or a dynamic logic could work to achieve this
