### ISSUE TITLE
[Feature Request] Store configs local again

### ISSUE THREAD

**Issue by Flosen86** [taniman/profit-trailer-enhancements#693]
Storing configs local again, not on the PT Server. Like it was in the older Versions

**Comment by Flosen86** [comment]
Having often Timeouts, while trying to get the config files from the server.

**Comment by taniman** [comment]
It is not as easy as that. As some features won't work correctly if using offline configs. Like our autoconfig.
But this will be looked at soon again

**Comment by taniman** [comment]
A good start for this has been added  for 2.5.0. It is not fully offline, But the active config will be offline certainly
