### ISSUE TITLE
[Feature Request] Different % Buys based on leverage.

### ISSUE THREAD

**Issue by ConorBradley-DigitalAgency** [taniman/profit-trailer-enhancements#695]
Due to binances hedging flaw (Long & Short Leverage changes on the last buy leverage for both pairs). My Idea is to be able to have a different percentage buys based on leverage. Which would help towards making it less of an hinderance. My initial buy is x50 then it DCA's at x10 leverage However if LONG was to buy the same pair, It would change my DCA's all to x50 Lev which has brung me very close to liquidation. By having different percentages based on leverage it would stop my normal x10 Lev DCA buys (-150% Buy) DCAing even faster when the same pair is bought initially.

An Example could be:

DEFAULT_DCA_X_Buy_Leverage = 10
DEFAULT_DCA_X_buy_value_1 = -150
----
DEFAULT_DCA_X_Buy_Leverage = 50
DEFAULT_DCA_X_buy_value_1 = -650

**Comment by taniman** [comment]
Not sure I follow this request.  But I do not see us making buy_leverage a per strategy  option. 

DEFAUKT_DCA_buy_leverage is current syntax and it will remain like so.

**Comment by taniman** [comment]
This could possibly be achieved using dynamic logic in 2.5.0 with a new LEV dynamic property
