### ISSUE TITLE
[FEATURE REQUEST] Adding max listed days

### ISSUE THREAD

**Issue by ConorBradley-DigitalAgency** [taniman/profit-trailer-enhancements#697]
Hi Guys,
Im wanting to develop a shorting strategy that works on min listed days and max listed days.
Newly listed coins on futures usually goes down in a certain timeframe, Which is why I would like max listed pairs implementing so I can get rid of coins that have been on the exchange for over x amount of days.
Many Thanks & Keep up the good work.

**Comment by taniman** [comment]
Added to 2.5.0
