### ISSUE TITLE
[Feature Request] Post sale price watching

### ISSUE THREAD

**Issue by ianbruton** [taniman/profit-trailer-enhancements#699]
Basically for the ablilty to specify a time period to keep watching the price of a coin

possible benefits:
- determine how effecient the sale was based on how much the pair price gained after we sold
- can report the low, high and close price of the watch period, with timestamps
- track the reported values over time for each pair to help with coin specific settings

**Comment by taniman** [comment]
This is already what STATS-AS does, It's the STATS After Sale, so you can see how that coin performed after it was sold
