### ISSUE TITLE
Manual Buy, Sell, DCA, SOM and SOMO Buttons

### ISSUE THREAD

**Issue by eFeRaven** [taniman/profit-trailer-enhancements#7]
Love the bot!  I've been learning some manual trading strategies and I also really enjoy how PT will sell coins I've bought with its trailing profit.

One feature that I think would be great, would be maybe another tab in the sidebar where you can manually buy a coin directly through PT.  Anything that limits the amount of tabs I have to have open is a winner.

**Comment by orangebutblue** [comment]
Just want to add to that:
PT should (optionally) trail the price of that coin - and not just buy it at a fixed price

**Comment by Slumberland** [comment]
Yes! 
Was hoping you could do this as well when I bought my licenses.

**Comment by jmccauli** [comment]
Would be amazing to have a manual "DCA NOW" button for individual coins!

**Comment by juato4** [comment]
this and #76 would be very useful!

**Comment by tactikill** [comment]
this is cool and a great feature, but I would like to see it implemented in a later version. i believe there are at least 3 other features that are more important to add at this time. i have the bot so i do not have to manually do things.

**Comment by CousinEddie** [comment]
+1

**Comment by PdubsRandom** [comment]
+1

**Comment by briersben** [comment]
+1
It would indeed be usefull to manually trigger DCA buys to override the default behaviour of PT (in case of low volume but you want to DCA anyway, ...) 
And a (panic) sell button could come in handy too.

**Comment by chostetler15** [comment]
I will say I have my settings to DCA 4 times, and if I hold a bag for a while, I like to DCA manually a 5th time. BUT it can be hard to watch the charts all day long, I mean that's what the bot is for, to do it for me. So I would say, it would be cool to specify which coin you would like a notification on an extra DCA and have that notification sent to your telegram chat. Then I can review the double down, and do it manually if I agree. So yes, a couple extra buttons would be nice...

**Comment by norova** [comment]
+1

**Comment by Wilddog69** [comment]
am i able to download these features ?, i dont seem to have an option to

**Comment by bluebibi** [comment]
+1

**Comment by Wilddog69** [comment]
????

**Comment by chostetler15** [comment]
@Wilddog69 this is for PT enhancements. These are not features, these are feature requests.

**Comment by clownfish44** [comment]
SOM, SOMO buttons already in 2.0. DCA Button in 2.1 milestone

**Comment by orangebutblue** [comment]
@clownfish44 don't forget the buy features

**Comment by Jthwaits** [comment]
Yup, this would be fantastic. At least the option to buy manually and track the sale stats and sell if it meets the sell criteria. Otherwise, the function to check the wallet for buys that've taken place outside of PT and sell based on the sale strat criteria, as above.
