### ISSUE TITLE
Add option for profits in a specific coin and not just BTC, ETH, USDT

### ISSUE THREAD

**Issue by klvnhng** [taniman/profit-trailer-enhancements#70]
Hi,

It would be amazing if we could have the ability to direct profits towards increasing holdings of a specific coin when trading against the main pairs (i.e. BTC, ETH, USDT, and BNB on Binance) rather than the other way around. 

Thanks for the active development towards the bot!

**Comment by clownfish44** [comment]
You can not sell for a coin if the market does not exist on the exchange. Why not just buy a coin when you want to?

**Comment by klvnhng** [comment]
This is not what I mean by my request. I mean using the same markets, but instead of the goal being to increase BTC (as an example; it could also be ETH or the other pairs), increase the overall holdings of a specific coin, like NEO. So instead of NEOBTC, we would essentially be doing BTCNEO if that makes sense.
