### ISSUE TITLE
[FEATURE REQUEST] stop_loss_strategy (X)MALINE 

### ISSUE THREAD

**Issue by alexanderadnanj** [taniman/profit-trailer-enhancements#701]
I'd like to be able to use *(X)MALINE as a stop_loss strategy.

*
SMALINE				
EMALINE				
HMALINE				
DEMALINE

**Comment by taniman** [comment]
That is already possible if you define the line as a buy or sell strategy and use dynamic value for the stoploss lie 
stop_loss_trigger = SX * -2
