### ISSUE TITLE
[Feature Request] - Import from exported zipfile

### ISSUE THREAD

**Issue by Simuman** [taniman/profit-trailer-enhancements#702]
Would be great to have the same functionality that's in the system for exporting for importing as well.  I know it's fairly easy to copy and paste setting.  But a simple import of the a zipfile process would be greatly appreciated, as I'm not sure about anybody else but I prefer to edit my settings externally in Notepad++ before adding them to PT.

**Comment by bvebve** [comment]
+1

**Comment by taniman** [comment]
There is no need to edit settings in notepad before saving them in PT and I won't encourage it by building such a feature for importing
