### ISSUE TITLE
Always show adv stats

### ISSUE THREAD

**Issue by jSevyn** [taniman/profit-trailer-enhancements#703]
Is there any way to have a feature to turn on or just set it so that it would always show ALL advanced stats and sell strategy values at all times? Currently I have it set to show advanced stats but when it sells for trailing stop loss it does show the stats but it would also be nice to see the sell strategy values like it does when it sells for gain in the sell logs. It would also be nice to see the adv. trailing stats some times even if they arent currently trailing just to see where the values are. I have found having all these values available come in handy when it comes to evaluating and analyzing data to help fine tune settings depending on how you use them.

**Comment by taniman** [comment]
all values are now displayed in the latest version of the bot. In the new GUI it will be made even clearer
