### ISSUE TITLE
DEFAULT_buy_timeout_after_negative_sell

### ISSUE THREAD

**Issue by alexanderadnanj** [taniman/profit-trailer-enhancements#705]
DEFAULT_sell_strategy_formula = A || B

DEFAULT_A_sell_strategy = GAIN
DEFAULT_A_sell_value = 0.2

DEFAULT_B_sell_strategy = CHANGEPERCENTAGE
DEFAULT_B_sell_value = -5

DEFAULT_buy_timeout_after_negative_sell = 240

Set the amount of minutes that the bot is not allowed to buy a coin after it was sold at lost . ex: We just sold at lost ETH so do NOT buy ETH again for x minutes after we sold it.

that way we can use the available strategies as SL

**Comment by taniman** [comment]
added for 2.5
