### ISSUE TITLE
DYNAMIC DCA_Enabled property

### ISSUE THREAD

**Issue by hoffer49** [taniman/profit-trailer-enhancements#706]
Allow the use of dynamic values to enable a coin to be DCA'd using Global Strategy.
For example: Send a coin to DCA when the profit drops 1 x the value of the daily ATR (see below)

Global_A_Strategy_Label= 1d_ATR
Global_A_Strategy = ATRPERCENTAGE
DEFAULT_DCA_Enabled = SGA * -1

**Comment by taniman** [comment]
implemented for 2.5.0
