### ISSUE TITLE
Stoploss below recent low

### ISSUE THREAD

**Issue by FO320** [taniman/profit-trailer-enhancements#707]
It would be awesome if one could set a stop below the last swing low. I imagine something like this:

Stoploss_strategy = RECENTLOW

RECENTLOW_lookback_period = x (timeframe)
RECENTLOW_lookback_candles = y (how many candles to check back at time of opening position)

Even greater would be if one could add ATRPERCENTAGE into that, in order to set a stoploss a certain ATR%-distance below the recent low, e.g. determine recent low and set a stop 1.5*ATR% below it.

**Comment by taniman** [comment]
This is already possible using PDLOW and dynamic logic. 
On top in 2.5.0 we have added ability to get the PDLOW value at entry of position. If you are looking for a more static approach.
