### ISSUE TITLE
[FEATURE REQUEST] total_profit_trailing based on TCV

### ISSUE THREAD

**Issue by bvebve** [taniman/profit-trailer-enhancements#708]
I suggest a **total_trailing_profit** based on TCV, when all condition match it triggers a panic_sell.   The start trailing point could be the TCV value of the last panic_sell (or the Start Balance if no previous panic_sell)

Example: when TCV has grown 5% over the start balance I would like to sell everything and restart normal operations (panic_sell + continue). If this is not the first time, then actual TCV should be 5% over the TCV value of last panic_sell. These way I'm sure It will never trigger a global sell in lost.

This is very proffitable when trading based on Non-StableCoins.

**Comment by taniman** [comment]
This requires us to keep a record of the last panic sell and makes this logic more complicated. 
I am not a fan especially since I do not believe it will be globally adopted
