### ISSUE TITLE
Please add an option to hide all $$ on the Pairs screen.

### ISSUE THREAD

**Issue by Tomokrypto** [taniman/profit-trailer-enhancements#709]
It would be great to have the option to turn off the $$ values, and even the TCV. Its very distracting seeing these while trading. I find I sell early If I see I am in profit in dollars. I also am scared to make good trades when my balance is down, so its lose lose.. I currently have masking tape covering these areas of the screen, but I'm sure there is a more elegant solution.

**Comment by LiamAird** [comment]
Already requested at #504
