### ISSUE TITLE
Set take_profit by # of days since purchase

### ISSUE THREAD

**Issue by lebo69** [taniman/profit-trailer-enhancements#710]
Similar to the SO1 setting which sells when a target % is met.

Is it possible to include a setting to lower take_profit % if X number of days have passed?

Example:

Default_take_profit is set at 5%.

If PAIR purchased more than 15 days ago, then take_profit is 3%
If PAIR purchased more than 20 days ago, then take_profit is 2%
If PAIR purchased more than 30 days ago, then take_profit is 1%
etc...

This will allow the bot to easier sell a pair that could not hit a higher take profit %.

Thanks.

**Comment by taniman** [comment]
This should be possible using dynamic logic already
