### ISSUE TITLE
Receive notifications in Discord and/or Telegram whenever the bot changes strategy automatically

### ISSUE THREAD

**Issue by Tatobest** [taniman/profit-trailer-enhancements#711]
It would be useful if the bot could send notifications whenever the AUTO_CONFIG settings trigger and the bot changes automatically to another configuration. It would help understand better bot results over a period of time by highlighting the specific points when market conditions changed. 
As a bonus, getting bot alerts about overall changes in market conditions when away from charts and computers can also be very helpful.

**Comment by taniman** [comment]
Will be added to 2.5.0.  The ability to send a discord message when the config auto switches
