### ISSUE TITLE
[FEATURE REQUEST] Clean interface. Hide some strategies

### ISSUE THREAD

**Issue by bvebve** [taniman/profit-trailer-enhancements#714]
Related to Feature Request #719

Using 5 o  more strategies when there are 30 pairs listed makes the page too long to monitor. Many times I only need to check colors on the formula and, maybe, just one or two SSV/SST.

Request for a setting option to hide a strategy from the interface.

Maybe:
	DEFAULT_A_buy_strategy_hide = true|false
	DEFAULT_buy_strategy_formula_hide = true|false
	DEFAULT_buy_strategy_levelx_formula_hide = true|false
	DEFAULT_A_sell_strategy_hide = true|false
	DEFAULT_sell_strategy_formula_hide = true|false
	DEFAULT_sell_strategy_levelx_formula_hide = true|false
	DEFAULT_DCA_A_buy_strategy_hide = true|false
	DEFAULT_DCA_buy_strategy_formula_hide = true|false
	DEFAULT_DCA_buy_strategy_levelx_formula_hide = true|false
	DEFAULT_DCA_A_sell_strategy_hide = true|false
	DEFAULT_DCA_sell_strategy_formula_hide = true|false
	DEFAULT_DCA_sell_strategy_levelx_formula_hide = true|false

**Comment by taniman** [comment]
The beta GUI has ways to hide columns you don't want to see on quick glance
