### ISSUE TITLE
[FEATURE REQUEST] Optimization and easier label management 2

### ISSUE THREAD

**Issue by bvebve** [taniman/profit-trailer-enhancements#716]
I have this indicator

BB15_std = 2
BB15_candle_period = 900
BB15_length = 20

I need this other indicator that use ALMOST the same values

BB30_std = 2
BB30_candle_period = 1800
BB30_length = 20
BB30_only_closed_candles = true

Maybe it would be better to use this syntax:

BB30 = BB15
BB30_candle_period = 1800
BB30_only_closed_candles = true

**Comment by taniman** [comment]
I am gonna have to decline this one. The code logic change for this is too much
