### ISSUE TITLE
[FEATURE REQUEST] Optimization and easier label management 1

### ISSUE THREAD

**Issue by bvebve** [taniman/profit-trailer-enhancements#717]
Related to Feature Request #719

I have this indicator

BB15_std = 2
BB15_candle_period = 900
BB15_length = 20
BB15_only_closed_candles = true

I need this two other indicators that use the same values but different label

HIGHBB15_std = 2
HIGHBB15_candle_period = 900
HIGHBB15_length = 20
HIGHBB15_only_closed_candles = true

LOWBB15_std = 2
LOWBB15_candle_period = 900
LOWBB15_length = 20
LOWBB15_only_closed_candles = true

Maybe it would be better to use this syntax:

HIGHBB15 = BB15
LOWBB15 = BB15

**Comment by taniman** [comment]
We are not trying to create a programming language though. 
Also doing explicit declaration is better to find errors than implicit

If you were to define the  label as the default we usage

BB_std = 2
BB_candle_period = 900
BB_length = 20
BB_only_closed_candles = true

Then in PAIRS/DCA you can define your strategies and both would use that property without a problem

A_buy_Strategy = LOWBB
B_buy_strategy = HIGHBB

both would make use of BB_ property
