### ISSUE TITLE
[FEATURE REQUEST] Different formula for different DCA Level

### ISSUE THREAD

**Issue by bvebve** [taniman/profit-trailer-enhancements#718]
I would be great if we can use different formulas for different DCA Levels (1,2 ... Z)

DEFAULT_DCA_buy_strategy_formula_1
DEFAULT_DCA_buy_strategy_formula_2
...
DEFAULT_DCA_buy_strategy_formula_Z

DEFAULT_DCA_buy_strategy_levelX_formula_1
DEFAULT_DCA_buy_strategy_levelX_formula_2
...
DEFAULT_DCA_buy_strategy_levelX_formula_Z

DEFAULT_DCA_sell_strategy_formula_1
DEFAULT_DCA_sell_strategy_formula_2
...
DEFAULT_DCA_sell_strategy_formula_Z

DEFAULT_DCA_sell_strategy_levelX_formula_1
DEFAULT_DCA_sell_strategy_levelX_formula_2
...
DEFAULT_DCA_sell_strategy_levelX_formula_Z

**Comment by taniman** [comment]
That's already possible, Please make sure you have read the bot documentation or ask in discord before creating requests
