### ISSUE TITLE
[FEATURE REQUEST] Use Labels on formulas instead of letters

### ISSUE THREAD

**Issue by bvebve** [taniman/profit-trailer-enhancements#719]
On ticket #714 I was asking about hidding some strategies from interface.
On ticket #717 I was asking about easiering label managment.

Now I continue the idea. This time I combine those previous requests with the use of labels in formulas instead of letters.

The result could be easy to read and a clean interface indicating just the formulas width colored labels

Ex.  LEVEL2 FORMULA (2m) BELOWBB15 && BOTTOMRSI7

**Comment by taniman** [comment]
this would take up to much space. Even if it helps readability
