### ISSUE TITLE
 Adding a coin Manualy traded coin Button either purchased or transferd in to the exchange.

### ISSUE THREAD

**Issue by frogwraps** [taniman/profit-trailer-enhancements#72]
I Using the hot config is a pain having to figure out the average is a royal pain. so it would be nice to have the ability to add coins alredy purchased to a Pair in PT and have it figure out what the average cost is without having to calculate and cut and paste each time I make a manual trade or transfer in.

**Comment by clownfish44** [comment]
It already re-averages the coin in PT if you buy more of it. It can take like 5-10 min but it will work.

**Comment by frogwraps** [comment]
but it dosnt do it for manual bought coins on the exhange when u are alredy in a posisition.
