### ISSUE TITLE
[FEATURE REQUEST] Use BSV in _sell_value and/or _sell_strategy_formula

### ISSUE THREAD

**Issue by bvebve** [taniman/profit-trailer-enhancements#720]
**(We've being talking about this on discord. We agreed to begin this ticket with "RETRIEVING THE BSV FROM BUY LOG" for better understanding.  Thank you)**

Update: On changelog 2.4.32 you included

> Add strategy buy_value (BST) to  dynamic formula logic
> Example: TA > 10 ? 0.01 : 0.03 (Where TA is the Trigger Value (BST) of strategy with letter A)

What I'm requesting now is **VA** instead of **TA**, I mean, using the **BSV**

Common traders has a full trading strategy. Entering the market is always followed by a related exit operation.

Simple example:
Buy when BBWIDTH is more than 2 and RSI is less than 30
My trading strategy is to exit (sell) when the price gets over BBWIDTH(buy)/2.
Sell when GAIN is more than BBWIDTH(buy)/2

Maybe it could be as easy as:
DEFAULT_A_buy_strategy = RSI
DEFAULT_A_buy_value = 30
DEFAULT_B_buy_strategy = BBWIDTH
DEFAULT_B_buy_strategy_value = 2
DEFAULT_buy_strategy_formula = A && B
...
DEFAULT_A_sell_strategy = GAIN
DEFAULT_A_sell_strategy_value = BSV_B/2
or DEFAULT_sell_strategy_formula = ( A > BSV_B/2 ) ? true : false

BSV_B is the BSV of B strategy got from Buy Log or DCA Log.

**Comment by taniman** [comment]
you are aware in most recent versions you can use the strategy values in your formula? So this is already possible like this

DEFAULT_sell_strategy_formula = SA > SB/2

Means that if the value of strategy A is greater than the value of strategy B / 2

Have a look at the release notes and the wiki for some of this dynamic logic. Also we discuss some of the options in discord

**Comment by taniman** [comment]
This has been implemented in 2.5.0
