### ISSUE TITLE
Adding Keltner Channel as one of strategies

### ISSUE THREAD

**Issue by freeebits** [taniman/profit-trailer-enhancements#721]
Hi,

As I know, Keltner channel is similar to SMA of ATR %  on BB Width and can be useful to check the trend and volatility of a coin.
If BB is inside the Keltner channel (low volatility) , soon the coin moves to a certain direction so we can buy in such a condition.

// Calculate Keltner Channel
ma      = sma(source, length)
range   = useTrueRange ? tr : high - low
rangema = sma(range, length)
upper = ma + rangema * mult
lower = ma - rangema * mult

Thanks.

**Comment by taniman** [comment]
Added for 2.5.0
