### ISSUE TITLE
[FEATURE REQUEST] Volatility strategies with "BBwidth Average"

### ISSUE THREAD

**Issue by bvebve** [taniman/profit-trailer-enhancements#723]
Bollinger Band WIDTH averange over time is a good indicator for volatility.

I use it in TradingView as SMA(BBwidth) and I compare actual BBwidth to speculate when the actual trend is going to reverse.

Indicator BBWSMA for SMA(Width of BB) is the medium average of BBWidth percentage, so it's always positive.
This buy/sell strategy is true when the BBWSMA is < the buy_value or >= the sell_value. 
BBWSMA returns the SMA of BBwidth  ->  SMA(BBwidth)
Parameters:
BBWSMA_std = 2
BBWSMA_candle_period = 300
BBWSMA_length = 20
BBWSMA_smalength = 100  <- the length of the SMA(BBWIDTH)

Going further ....

Indicator BBHSMA for SMA(HighLine of BB) is the max expected value of price
This buy/sell strategy is true when the BBHSMA is < the buy_value or >= the sell_value. 
The value of BBHSMA returns the % difference betwen actual price and the average (SMA) of BB's HighLine
Parameters:
BBHSMA_std = 2
BBHSMA_candle_period = 300
BBHSMA_length = 20
BBSMA_smalength = 100  <- the length of the SMA

Indicator BBLSMA for SMA(LowLine of BB) is the lowest expected value of price
This other buy/sell strategy is true when the BBWLMA is < the actual price or >= actual price. 
The value of BBHSMA returns the % difference betwen actual price and the average (SMA) of BB's LowLine
Parameters:
BBLSMA_std = 2
BBLSMA_candle_period = 300
BBLSMA_length = 20
BBLSMA_smalength = 100  <- the length of the SMA

**Comment by taniman** [comment]
#777 is a bit mroe general and will make this one possible. in the very least the first part
