### ISSUE TITLE
[FEATURES REQUEST] PDCLOSE_range and PDCLOSE_range_position for PDCLOSE indicator

### ISSUE THREAD

**Issue by bvebve** [taniman/profit-trailer-enhancements#724]
Request for PDCLOSE_range setting and a way to get the HIGHEST or LOWEST "closed" values within the range.
Maybe:

> PDCLOSE_range = number of candles back
> PDCLOSE_range_position = MAX|MIN
 

And the same for PDOPEN

**Comment by taniman** [comment]
Added to 2.5.0
