### ISSUE TITLE
[FEATURE REQUEST] Include ATRPERCENTAGE_indicator = RMA

### ISSUE THREAD

**Issue by bvebve** [taniman/profit-trailer-enhancements#725]
Requesto to include RMA in the moving average options when setting ATRPERCENTAGE indicator.

RMA is default in Trading View for ATR calculations, we can change it for plotting but there is no way to change it in [Crypto Screener](https://www.tradingview.com/crypto-screener/), so I would be better to use the same reference.

Thank you

**Comment by taniman** [comment]
RMA aka SMMA ha been added for 2.5.0
