### ISSUE TITLE
Storing Coin Price to a variable when buy/sell level becomes true

### ISSUE THREAD

**Issue by freeebits** [taniman/profit-trailer-enhancements#728]
Getting the price and storing it to compare to the price of each level.

At level 1, you find the coin's price fits your 1st buying condition (found price is very low) and the price is stored to a variable.
At level2, you find the 2nd strategy is met and the price at the moment is stored to another variable.
At level 3, you compare the price of level 1 to the one of level 2 and find the chart made a higher low so you buy it. You can check the trend as well.

**Comment by bvebve** [comment]
Similar feature requested at https://github.com/taniman/profit-trailer-enhancements/issues/720

**Comment by taniman** [comment]
Not sure if this one is really required as you could use PDCLOSE and such on a 1 minute level to get some info. But I have added this for 2.5 and we can test and see if it works or not
