### ISSUE TITLE
[FEATURE REQUEST] Add Buy/Sell Strategy for the Current Candle's HIGH

### ISSUE THREAD

**Issue by VendrediPT** [taniman/profit-trailer-enhancements#730]
Currently PDHIGH is an available buy/sell strategy that uses the previous candle's high data.  Elroy and the PT Team has been making this product more and more robust as we move forward and I'm hoping that a strategy can be provided that will account for the current candle's HIGH price.  This way, another layer of protection can be inserted (based on the user's strategy) that will prevent rebuying in unless the price has passed the current candle's high.  This will also allow a user to be less restrictive on the DEFAULT_buy_timeout_after_sell.

I hope that this makes sense.  I honestly believe that it will benefit those users that are trading on the higher timeframes.  This ideology can also be used for the current candle's LOW and may be of massive benefit to those who are shorting.

**Comment by taniman** [comment]
Was implemented some versions ago
