### ISSUE TITLE
Using initial buy strategy values in formulas

### ISSUE THREAD

**Issue by iFelo** [taniman/profit-trailer-enhancements#735]
**Description of issue:**
I have been testing a strategy to set stop losses with indicators such as PDLOW. Whenever trades take longer than expected, naturally the pdlow value changes. The stop loss will eventually change as the PDLOW from the initial buy is out of range after a while.

**Request:**
Make it possible to use the original buy value, or initial buy value as a fixed value in formulas.

**Proposed solution:**
For example: When PDLOW is strat A and ATRP strat B, you would normally write: _SA + (2 * SB)._
If you need a fixed value you would have to write _**I**SA + (2 * SB)_ to use the initial buy value of strat A. These values are stored in the buy log. The I comes from Initial, this could also be an O for original or any other character that makes sense for you :)

**Comment by bvebve** [comment]
Similar feature requested at https://github.com/taniman/profit-trailer-enhancements/issues/720

**Comment by taniman** [comment]
This has been implemented in 2.5.0. Though we get the LAST buy and last sell value.  So if you do DCA. it will get the last DCA buy values.
