### ISSUE TITLE
HLC3

### ISSUE THREAD

**Issue by TPostalService** [taniman/profit-trailer-enhancements#736]
For those who use SMA cross candles for trend trading(candles at least 4h), HLC3 ((high + low + close)/ 3 ) would be a big improvement.
When backtesting on TRADINGVIEW, HLC3 gives way better results than the default Close.
I've tested this strategy on 32 high cap coins and 24 coins gave a significantly better return.
See yourself using the pine script below.

hlc3 : 
//@version=4
strategy("hlc3MovingAvg2Line Cross", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=100)
fastLength = input(12)
slowLength = input(26)
price = hlc3
mafast = sma(price, fastLength)
maslow = sma(price, slowLength)
if (crossover(mafast, maslow))
	strategy.entry("MA2CrossLE", strategy.long, comment="MA2CrossLE")
if (crossunder(mafast, maslow))
	strategy.close("MA2CrossLE", strategy.long, comment="MA2CrossSE")
//plot(strategy.equity, title="equity", color=color.red, linewidth=2, style=plot.style_areabr)

close : 
//@version=4
strategy("closeMovingAvg2Line Cross", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=100)
fastLength = input(12)
slowLength = input(26)
price = close
mafast = sma(price, fastLength)
maslow = sma(price, slowLength)
if (crossover(mafast, maslow))
	strategy.entry("MA2CrossLE", strategy.long, comment="MA2CrossLE")
if (crossunder(mafast, maslow))
	strategy.close("MA2CrossLE", strategy.long, comment="MA2CrossSE")
//plot(strategy.equity, title="equity", color=color.red, linewidth=2, style=plot.style_areabr)

**Comment by taniman** [comment]
Added to 2.5.0
