### ISSUE TITLE
StochRSI + Analysis Charts

### ISSUE THREAD

**Issue by Balsius** [taniman/profit-trailer-enhancements#74]
Hi! From what I have tested StochRSI is the best indicator to make great buys and sells. I spent a few days tracking/researching and about 75% buys, even in Bear market as we were, provided good buy opportunities to make a positive result. This is the kind of indicator I would like to make the buy. I you like it or have a comment, please share. Thanks for your attention.
P.S.: You can check on this guys Chart analysis, something like this would be of great help and value: https://www.youtube.com/watch?v=oKumExuetwE&t=279s
Blessings and all the best 4 U ALL

**Comment by clownfish44** [comment]
StochRSI is already in the next milestone update here https://github.com/taniman/profit-trailer/issues/82 and charting has been requested here https://github.com/taniman/profit-trailer-enhancements/issues/5
