### ISSUE TITLE
Testbot buy level logic order of operations when using waitxcandles as level 1

### ISSUE THREAD

**Issue by locohammerhead** [taniman/profit-trailer-enhancements#740]
While testing out a scalping config I noticed the following.

Bot is set to buy upon price drop in somewhat rapid succession.  

bot should only buy 1 DCA level per 1 minute candle.
strat Z - waitxcandles 2x 1 minute candles (since 1 is the current candle)
DEFAULT_DCA_buy_strategy_level1_formula = Z
DEFAULT_DCA_buy_strategy_level2_formula = E && D && G && H && L && N
DEFAULT_DCA_buy_strategy_level2_timeout = 60

The logic should reset level 1 when level 2 is true, however during times of fast price changes it looks like the bot ignores the reset logic and will use level 2 in rapid succession allowing the testbot to execute 3+ DCA levels at a single time instead of executing 1 and waiting another 2 minutes.  
I currently have the 60 second timeout set to help better simulate the above but it far from a perfect solution to this.

**Comment by taniman** [comment]
I believe there is a misunderstanding of how this logic works. and this looks more like some kind of bug report
We can see in Discord if this can be clearup for your underwstanding
