### ISSUE TITLE
Banking profits 

### ISSUE THREAD

**Issue by LOVEAFLUTTER** [taniman/profit-trailer-enhancements#741]
Hi it would be lovely if we could withdraw automatic into a separate pot so it dont get used by the bot.
To use for compounding daily interest with locking some away as a percentage of daily gain if any.
Maybe it could store in another stable coin like busd?
Thanks in advance.
Loveaflutter

**Comment by carlpwilliams** [comment]
Hmm, this might be useful. You could also set a limit (say, 1%) and anything after that is moved to a pot or stable coin that isn't traded or something?
Would be good if someone is not interested in compounding too much and wants to draw profits.

**Comment by taniman** [comment]
We will see about a transfer from futures to spot for safe keeping. It will be manual for now. 
auto converting to a stable coin that is not the base coin is not possible and won't be done as of now
