### ISSUE TITLE
Backtesting

### ISSUE THREAD

**Issue by lebo69** [taniman/profit-trailer-enhancements#743]
It would be extremely helpful if you could add a back-testing module to test strategies in previous market conditions.

**Comment by des1re10** [comment]
Such a tool exists already: https://embedded-solutions.org/Crypto_Backtesting_Tool.html

**Comment by spenderniere** [comment]
How it works? Any Vids or something out there?

**Comment by des1re10** [comment]
By now we got a describtion in the wiki. A video is planned. If you got certain questions regarding usage or anything else, feel free to send an email to support.

**Comment by iller75** [comment]
Well that would require one to code ones entire pt strat into your tool, if it would just take the file or even a pt feeder file then i could potentially consider it, but not for that price though.

**Comment by taniman** [comment]
As explained here https://github.com/taniman/profit-trailer-enhancements no backtesting feature requests allowed
