### ISSUE TITLE
Stoploss below recent low

### ISSUE THREAD

**Issue by FO320** [taniman/profit-trailer-enhancements#744]
I would love if the bot was able to set stoplosses below a recent low.
E.g.
DEFAULT_stop_loss_strategy = SWINGLOW
DEFAULT_stop_loss_strategy_range = xxx (low of the last xxx candles)

or, even better:
DEFAULT_stop_loss_strategy = SWINGLOW
DEFAULT_stop_loss_strategy_trigger = -1 (1% below the swing low), or SX (Strategy X, for example ATR, so one could set a stop 1 ATR below a recent swing low)

**Comment by taniman** [comment]
I have explained just yesterday om Discord to a user how that could be accomplished using PDLOW for example. 
so in theory this is already possible.
