### ISSUE TITLE
long up and down

### ISSUE THREAD

**Issue by bloodbit** [taniman/profit-trailer-enhancements#745]
Hi.

Because the setups are totally different it would be great to have the possibility to manage at least 2 bots for the same account. One for pullbacks and the other for breakouts. The tricky part may be to sync the pending and reserve coins without losing the buy values. So, maybe you can “redirect” reserve, pending and stats to one of them to make it work like “master-slave”. The baseline should be similar to your long/short management.

thanks

**Comment by taniman** [comment]
This is not a realistic request. we can't build a network of bots
