### ISSUE TITLE
[Feature request] dynamic DCA rebuy percentage

### ISSUE THREAD

**Issue by des1re10** [taniman/profit-trailer-enhancements#746]
You need to make DCA rebuy percentage as strategy instead of just dependend on the DCA levels! This would allow the bot to be far more efficient. Trading is about probability. When there is a small dip, rebuy just a small portion. When there is a large dip, rebuy a lot. That would allow the bot to get out of its current position much faster and should have much more profits over time.

![dynamic dca rebuy percentage](https://user-images.githubusercontent.com/11975743/99092415-66526300-25d1-11eb-9546-bdd6bdfb63e1.png)

Example DCA file:

DEFAULT_DCA_buy_strategy_formula = ((A && D) || (B && E) || (C && F)) && G

DEFAULT_DCA_A_buy_strategy = RSI
DEFAULT_DCA_A_buy_strategy_label = RSI5M
DEFAULT_DCA_A_buy_value = 30
DEFAULT_DCA_A_buy_value_limit = 0
DEFAULT_DCA_A_buy_strategy_direction = DOWN

DEFAULT_DCA_B_buy_strategy = RSI
DEFAULT_DCA_B_buy_strategy_label = RSI15M
DEFAULT_DCA_B_buy_value = 30
DEFAULT_DCA_B_buy_value_limit = 0
DEFAULT_DCA_B_buy_strategy_direction = DOWN

DEFAULT_DCA_C_buy_strategy = RSI
DEFAULT_DCA_C_buy_strategy_label = RSI15M
DEFAULT_DCA_C_buy_value = 10
DEFAULT_DCA_C_buy_value_limit = 0
DEFAULT_DCA_C_buy_strategy_direction = DOWN

DEFAULT_DCA_D_buy_strategy = REBUYPERCENTAGE
DEFAULT_DCA_D_buy_value = 5

DEFAULT_DCA_E_buy_strategy = REBUYPERCENTAGE
DEFAULT_DCA_E_buy_value = 10

DEFAULT_DCA_F_buy_strategy = REBUYPERCENTAGE
DEFAULT_DCA_F_buy_value = 100

DEFAULT_DCA_G_buy_strategy = PROFITPERCENTAGE
DEFAULT_DCA_G_buy_value = -10

**Comment by taniman** [comment]
buy_percentage can use dynamic logic and you can accomplish this.
