### ISSUE TITLE
Method for 3rd parties to integrate features directly into the UI

### ISSUE THREAD

**Issue by elitriona** [taniman/profit-trailer-enhancements#75]
For example, if 3rd parties like PT Feeder or PT Tracker develop features for ProfitTrailer, they could integrate UI elements directly, instead of running things separately. This might help foster an ecosystem of "plugins" or "add-ons" with a clearer way for people to enhance PT features from 3rd parties.

**Comment by clownfish44** [comment]
This already exists using js https://github.com/CryptoGnome/Community-Tools/tree/master/ProfitTrailer-Tools/Web-GUI-Addons There is many other ways to hook into pt as well
