### ISSUE TITLE
Mathematical Formula as Signal

### ISSUE THREAD

**Issue by ARDAKARABEL** [taniman/profit-trailer-enhancements#750]
Dear Team,

For example I wanted to write a formula, which takes the last 3 closed values of 1m cycle, and would like buy, if the if statement is true.

last2 = close[1]
last1 = close[0]
last = close

Example
if((((last1/last2)-1)+(current/last1)-1)>0.1)
 buy

Can't we get such funtionality?

Elroy helped me, but did not fit my needs :(

![image](https://user-images.githubusercontent.com/6768399/99198678-3eb6f280-27ab-11eb-8b21-0f095c2dea1c.png)

Thank You!

**Comment by taniman** [comment]
this is possible in the bot already with _offset logic
