### ISSUE TITLE
[FEATURE REQUEST] take profit safety arm stop

### ISSUE THREAD

**Issue by MikeBOFH** [taniman/profit-trailer-enhancements#751]
Hello,

I have a feature request.

I would really prefer if there is a way to stop selling the BOT when it falls into the negative percentage range.

So to the existing variable:
DEFAULT_take_profit_safety_arm

Example:
DEFAULT_take_profit_safety_arm_stop = 0%

That he should not sell below 0% (profit / loss)

Background:
My problem today was, I had a large position open, the price went positive (+%), the sale was then triggered, the bot then started to sell piece by piece, but the price is again negative in that time (- %) fell and he sold on.
When my position was completely sold, the price began to rise again.
I haven't had any problems with small positions so far, but he can't sell the big ones fast enough, so a break in sales would be very helpful if it falls below the percentage

Best regards
Mike

**Comment by taniman** [comment]
This can be accomplished using a simple dynamic logic line an extra property is not needed

Assuming you have GAIN as Strategy with Letter A.
Assuming you had your arm at 5 and fire at 3

DEFAULT_take_profit_safety_arm =  SA < 0 ? 0 : 5 
DEFAULT_take_profit_safety_fire =  SA < 0 ? 0 : 3

This would disable TPS if the GAIN % is below 0. You can adjust this accordingly. 
TPS will completely reset after being disabled for more than 5 minute. After that it would need to completely arm again
