### ISSUE TITLE
[FEATURE REQUEST] Set Bought Price on Dust

### ISSUE THREAD

**Issue by droolingtaz** [taniman/profit-trailer-enhancements#753]
I have a few coins I just moved over to my Binance US account and they are under the dust folder.  Since PT did not buy them, they have no bought price and currently bought price can only be set when they are under the positions folder.

**Comment by LiamAird** [comment]
Currently its not possible to set bought price for dust pairs via routes. 
@taniman we need to add it, or close issue

**Comment by taniman** [comment]
Its 1 api endpoint already exists. Same api to set bought price for normal pairs in api/v2

**Comment by LiamAird** [comment]
Coming
