### ISSUE TITLE
Adding the option to close a deal not by interest, but by strategy, a strategy to choose from.

### ISSUE THREAD

**Issue by Choza444** [taniman/profit-trailer-enhancements#758]
DEFAULT_take_profit_safety_arm _strategy = HMASPREAD
DEFAULT_take_profit_safety_arm _value = 5
DEFAULT_take_profit_safety_fire_value_limit = 4

DEFAULT_trailing_stop_loss_arm_strategy = HMASPREAD
DEFAULT_trailing_stop_loss_trigger_arm_value = 6
DEFAULT_trailing_stop_loss_trigger_arm_value_limit = -1

**Comment by taniman** [comment]
this type of logic is already  possible using dynamic formula logic
