### ISSUE TITLE
‼️****{ Feature Request Ω Reversal Trading.}****‼️ 

### ISSUE THREAD

**Issue by juato4** [taniman/profit-trailer-enhancements#76]
INFO: This is not my idea,"Reversal trading" is a method for dealing with confirmed bags.

**Reversal trading**

Reversal trading is a GunB technique to keep on trading while prices are moving downwards, and when you already own a bag.

The principle is to use the already invested amount of base currency to accumulate more units of the quote currency while prices are moving downwards. When prices eventually rise again, the bag can be sold for profit in base currency at a lower price point then without reversal trading.

When a bag is confirmed by RT_METHOD, it's sold for base currency and the invested amount is reserved for buying more units back when prices drop further to the level defined by RT_BUYDOWN. This process will repeat when prices keep dropping, enabling you to keep accumulation quote currency without investing additional assets.

![36511037-885d60da-1765-11e8-8b64-5f6bf89a1048](https://user-images.githubusercontent.com/35824627/36999757-e8564478-209f-11e8-989e-13e48ba199fb.PNG)

Notice how the final sell order happens at a lower price than the initial buy, yet makes a profit

![36511226-306f940a-1766-11e8-8b2b-f054ffb3d46d](https://user-images.githubusercontent.com/35824627/36999765-f11617dc-209f-11e8-9d06-86e5edfe1e1c.png)

Flowchart

![36509213-3af928c0-175f-11e8-8edf-b16eb6333b55](https://user-images.githubusercontent.com/35824627/36999785-fbb3626c-209f-11e8-9e02-b792667ae7a2.PNG)

Parameter | Default value | Description
-- | -- | --
RT_ENABLED | false | Values: true or false. When set to true, Reversal trading will try to use the assets invested in your bag to accumulate a bigger bag, which can eventually be sold for profit earlier than the original bag.
RT_METHOD | HIGHBB | Values: HIGHBB, RSI or numerical value that represents a percentage. This sets the trigger for initiating reversal trading. When set to HIGHBB the reversal trading process will start when the actual upper Bollinger Band drops below bought price (not the distance from it as set in HIGH_BB). When set to RSI it starts when RT_RSI_BUY is reached. When using a numerical value, you set the exact percentage below bought price to start reversal trading. Beware that while setting HIGHBB or RSI confirms the existence of a bag, using a numerical value does not.
RT_BUYDOWN | 2 | Values: numerical - represents a percentage. This defines the percentage the price has to drop after each reversal trading order before the next one is placed.
RT_RSI_BUY | Strategy dependent | Values: numerical - represents a number. Sets the RSI level to trigger reversal trading when RT_METHOD is set to RSI.

-------

Say you have 1000 ALT worth 1 btc (which is 0.001 per ALT) and the price drops 10% down to 0.0009

Now you have 1000 ALT worth 0.9 BTC right?

So it sells your 1000 ALT at 0.0009 and gets 0.9 BTC

Then, the price drops 5% more, which is now 0.000855

It buys back your ALT at the new price using 0.9 BTC, giving you 1052 ALT

So you have MORE in your ALT bag than you did when the price first dropped.

Which means that you have less of a hill to climb back up for the price to recover to get back to breakeven.

In this case, you can sell your 1052 ALT at 0.000952 to get 1 BTC. But regardless, once you get back to breakeven plus the fees incurred during reversal trading it will resume selling with your original strategy.

You'll be able to control this using % price drops, HIGHBB or RSI depending on how you want it to be triggered. Great stuff

it's different that a trailing stop because it rebuys automatically and incorporates fees, etc.

price falls 5%, you sell into a reversal trade

price falls more, you buy a larger bag using whatever base currency you got from the first reversal trade sell

price doesn't fall more or recovers slightly, the bot buys your exact bag back for the exact same price. you recover that fee when you make a gain on the trade later

"if you set the % too low, your bot will get spooked by normal price fluctuation"

Reversal trading is a method for dealing with confirmed bags. it's not a replacement for not doing your research and setting your stops within normal trading range

he way that I'm looking at this is... you will have 3 ways of dealing with downtown in prices depending on your risk level:

1) STOP_LIMIT <--- get me out with a small loss, reserve my trading capital

2) REVERSAL_TRADE <--- start reversing on the way down without using additional trading capital with the knowledge that I will still have to wait out the prices rising again but not as high as if I had held

3) DOUBLE_UP <--- start averaging on the way down using additional trading capital with the knowledge that I will still have to wait out the prices rising again but not as high as if I had reversal traded

**Comment by syl201971** [comment]
Would want this for suee

**Comment by tactikill** [comment]
I am not following. It would help if your chart specified which price was rising and falling. also, why did you use PAY in your example and not DOGE like your chart? I'm dumb, and this is not clearly explained. Thank you.

**Comment by LeaderOfChampions** [comment]
What? This makes zero sense.

**Comment by RunPlz** [comment]
As far as I understand this strategy is also known as "scalping" but someone who was enlightened by the crypto gods was told this for "ALTS" instead of BTC and it is now being called "Reverse Trading". Ta-daaa!

**Comment by cryptt** [comment]
So basically you will short PAY. Nice!

**Comment by octobrium** [comment]
this is the same thing as setting a stop-loss, and hoping the coin dips more so you can buy back.
DCA + trailing is already a great, safe solution for dips. "reverse trading" sells at a loss and relies on the coin dipping more after you sell. aka it requires predicting the future for it to work

**Comment by juato4** [comment]
he way that I'm looking at this is... you will have 3 ways of dealing with downtown in prices depending on your risk level:

1) STOP_LIMIT <--- get me out with a small loss, reserve my trading capital

2) REVERSAL_TRADE <--- start reversing on the way down without using additional trading capital with the knowledge that I will still have to wait out the prices rising again but not as high as if I had held

3) DOUBLE_UP <--- start averaging on the way down using additional trading capital with the knowledge that I will still have to wait out the prices rising again but not as high as if I had reversal traded

**Comment by juato4** [comment]
Say you have 1000 ALT worth 1 btc (which is 0.001 per ALT) and the price drops 10% down to 0.0009

Now you have 1000 ALT worth 0.9 BTC right?

So Gunbot sells your 1000 ALT at 0.0009 and gets 0.9 BTC

Then, the price drops 5% more, which is now 0.000855

Gunbot buys back your ALT at the new price using 0.9 BTC, giving you 1052 ALT

So you have MORE in your ALT bag than you did when the price first dropped.

Which means that you have less of a hill to climb back up for the price to recover to get back to breakeven.

In this case, you can sell your 1052 ALT at 0.000952 to get 1 BTC. But regardless, once you get back to breakeven plus the fees incurred during reversal trading Gunbot will resume selling with your original strategy.

You'll be able to control this using % price drops, HIGHBB or RSI depending on how you want it to be triggered. Great stuff

**Comment by juato4** [comment]
it's different that a trailing stop because it rebuys automatically and incorporates fees, etc.

**Comment by octobrium** [comment]
again, this requires predicting the future.
in your example, if the coin drops anywhere from 1-4%, but not 5%, and then start mooning, you will not buy back. this means you effectively panic sold a whole stack of alts and then missed a sell opportunity

"but you could just set the increments to 3% then!"
if you set the % too low, your bot will get spooked by normal price fluctuation, and will keep selling things at a loss whenever some whale dumps a big load. 

depending on whether it sees the absolute minimum price the coin gets to as a *buy* or a *sell* trigger, you have a 50/50 chance of making the right call. a 50/50 chance combined with paying trading fees every time you buy/sell = overall loss

**Comment by juato4** [comment]
]
price falls 5%, you sell into a reversal trade

price falls more, you buy a larger bag using whatever base currency you got from the first reversal trade sell

price doesn't fall more or recovers slightly, the bot buys your exact bag back for the exact same price. you recover that fee when you make a gain on the trade later

"if you set the % too low, your bot will get spooked by normal price fluctuation"

Reversal trading is a method for dealing with confirmed bags. it's not a replacement for not doing your research and setting your stops within normal trading range

**Comment by clownfish44** [comment]
In 2.0 u can use multiple indicates which would eliminate the need for this as it will be more accurate.

**Comment by juato4** [comment]
@clownfish44 , when 2.0 come out?

**Comment by juato4** [comment]
Taniman Didnt know what are you talking about...

This feature didnt come with 2.0

Enviado desde mi iPhone
