### ISSUE TITLE
BREAKOUTS ~ RSI / BB

### ISSUE THREAD

**Issue by ricardodacosta** [taniman/profit-trailer-enhancements#762]
As it is right now, strategies available are mostly based on Buy low Sell high, which is not bad except during a bullish market.

Waiting for RSI to reach below level 20-30 is a waste of time during bullish run as RSI will mostly stay above 40
Waiting for Price to reach a level below the mean or close to LOW BB Band is also a waste of time as Price will be trending above the mean during a bull market environment

A BREAKOUT strategy is a must have during Bullish Market Environments and Profit Trailer currently has none.

I would like to suggest adding the following momentum type BREAKOUT STRATEGIES

- LOWBB_BREAKOUT where as the bot buys when LOWBB crosses  ABOVE buy_value
- LOWBB_TRENDING where as the bot buys only if LOWBB is ABOVE buy_value along with some other strategy
- RSI_BREAKOUT where as the bot buys when RSI crosses ABOVE buy_value
- RSI_TRENDING where as the bot buys only if RSI is ABOVE buy_value along with some other strategy
- ATR_BREAKOUT where as the bot buys when price crosses above an X multiplier of ATR value

For those who can Short the Market the strategies will be opposite for entering SHORTS.

**Comment by en3z** [comment]
In my opinion, these are possible by combining formulas. If BB breakout is not possible with crossover you can try offset and formula. I am using atr breakout very well. Try it in test mode.

**Comment by ricardodacosta** [comment]
> In my opinion, these are possible by combining formulas. If BB breakout is not possible with crossover you can try offset and formula. I am using atr breakout very well. Try it in test mode.

Thank you. Didn't think of that. offset and formula does achieve the result I was looking
