### ISSUE TITLE
Auto-Load PT Feeder (or any other add-on) at PT startup

### ISSUE THREAD

**Issue by TheBigShort111** [taniman/profit-trailer-enhancements#764]
Provide a method of automatically loading PTFeeder (or other add-ons) during PT startup. This would be a nice feature for those using external add-ons that have to load them separately after PT loads.

Since PTFeeder logs and config is already integrated in PT, having the ability to load Feeder under the same startup routine as PT would be a welcome addition.

**Comment by TheBigShort111** [comment]
My sentiments exactly! - If I only knew how to code!

**Comment by taniman** [comment]
This is not something for the bot and will not be included in the bot. AS suggested above you can create a feature request on PTManager page
