### ISSUE TITLE
Looking at the MACD of BTC to trade other coins

### ISSUE THREAD

**Issue by swanfield1979** [taniman/profit-trailer-enhancements#765]
What I would like is to let other coins trade when the BTC MACDline is positive or negative. So when the MACD lines have crossed I would like to be able to signal other pairs to trade. For example

A: EMA
B: MACDLINECROSS
C: PDHIGH
Z: BTCMACDBULLISH

The Z could be a signal perhapse or something else. If we could do this perhapse:
position=OPEN
pair=DEFAULT

The reason for this is that when BTC MACD is positive all other coins move with BTC. Atleast the most of them. Also I would like to be trading up in a positive market and a MACD cross is faster. Also this could be handig when trading ETH f.e.

**Comment by taniman** [comment]
There is only 1 limitation to this logic, when a signal buys it is closed. But you can figure that part out I guess.
I have added `buy_strategy_pair` for 2.5.0 and so you could indicate what PAIR the indicator should be looking at. like `BTCUSDT`
