### ISSUE TITLE
allow for more **MAX TRADING PAIRS** when coins are in PROFIT

### ISSUE THREAD

**Issue by drbrauwn** [taniman/profit-trailer-enhancements#770]
**MAX TRADING PAIRS**

max_trading_pairs = 3

Set the maximum number of pairs that the bot is allowed to own at one time to 3.

**NEW FEATURE**
Coins that have X_PROFITPERCENTAGE or where TAKE_PROFIT_SAFETY is actived (ARMED) do not count towards MAX PAIRS (because they are in profit and no more at risk).

max_trading-pairs_exclude = ARMED
max_trading-pairs_exclude = PROFITPERCENTAGE
max_trading-pairs_exclude_profitpercentage_value = 5

**Comment by drbrauwn** [comment]
Because of **RISK management**, I believe it is neccesary to keep a HARD CAP as MAX PAIRS currently is, and introduce a new soft cap to allow for ''some'' more pairs, but not infinitely with no end.

If ProfitTrailer keeps buying when coins are in PROFIT, and for some reason there are server or API issues, even an armed coin or coin in profit with Trailing Stop Loss, can still go negative be liquidated and wreck the account, in a very unfortunate turn of events. To prevent this I believe MAX_PAIRS could stay as it is.

For example 10 pairs is our hard cap with 

**max_trading_pairs = 10**

3 trading PAIRS that are not in Profit yet, is the soft CAP. 
**This leaves 7 spots left to be filled when the first three go in profit as specified below.**

max_trading_pairs_not_in_profit = 3
max_trading_pairs_in_profit = 10

allow_new_pair = PROFITPERCENTAGE
allow_new_pair_value = 5

**Comment by symvar** [comment]
Good idea! I was about to make the same suggestion.

**Comment by taniman** [comment]
I think I have an implementation for this ready for 2.5 that comes close to this request. 
I would need feedback on the implementation and if changes need to be made possibly
