### ISSUE TITLE
Add estimated % gain / loss on the 'Daily Stats' table on the dashboard

### ISSUE THREAD

**Issue by ianbruton** [taniman/profit-trailer-enhancements#775]
![image](https://user-images.githubusercontent.com/4050482/104660075-276e8580-56c6-11eb-95fc-f8be5d0f0ba4.png)

You'll have to excuse my image editing skills, but it would be nice to be able to see the percentage growth for each day

You could also list the average daily percentage growth on this page, perhaps in the 'All Time Profit" Tile

**Comment by LiamAird** [comment]
Coming

**Comment by ianbruton** [comment]
That's awesome! thanks guys!
