### ISSUE TITLE
Ability to add an SMA to any indicator

### ISSUE THREAD

**Issue by ricardodacosta** [taniman/profit-trailer-enhancements#777]
There are many strategies that can benefit from adding a Simple Moving Average (SMA) to another indicator.

For example On Balance Value will be way more effective if we could add a rule such as 
"Buy when OBV is above a value which is above an X period average of OBV" 
With the ability to add an SMA to OBV indicator, this can be implemented by Buy if OBV >= SMA20(OBV) for example

Also RSI

Many people use RSI to enter trade when RSI is oversold, below 20. However a lot of times, price can continue moving further down while keeping the RSI within 20-30. Adding a SMA to RSI would allow to specify entries when the RSI is above a SMA of RSI giving you a confirmation that the RSI has began to climb above the average of previous X period. Buy when RSI > SMA20(RSI)

BBWIDTH would another and I am sure it can be applied to others.

**Comment by paulcarouge** [comment]
would be awsome!

**Comment by hoffer49** [comment]
This is very interesting indeed...perhaps even being able to apply any type of MA (EMA, HMA, etc) to the indicators would be of even greater use ;)

**Comment by TheDeumel** [comment]
Would be a great feature indeed. Maybe even being able to switch between an MA and a RANGE like already possible with PDLOW and such.

**Comment by taniman** [comment]
Implemented  in 2.5.0 will need a lot of testing
