### ISSUE TITLE
RSI (or another strat) INCREASE/DECREASE + timeframe

### ISSUE THREAD

**Issue by d0m1n0o** [taniman/profit-trailer-enhancements#778]
The goal is to define a value of a strat (E.g. RSI value = 30) which the bot will take as a (minimum in this case) reference in a given time, defined by the user (Ideally in seconds). If in that (dynamic) time the indicator has increased or decreased by the amount the user has specified, the strat will be true.

**For example, a positive change of 1 point of RSI, in the timeframe of 60 seconds, above RSI 30 and below 65.**
Same with Stoch, for example, you get the point.

I think this buy strat logic would make many things way simpler as it could help the bot to know about the current trend pretty well. Depending on candle size and combination of strats, of course.

The bot would have to be remembering a lot of/some past values constantly tho, depending on the timeframe. Not so sure about the ease of programming that. Similar to trailing I guess.

Cheers!

**Comment by d0m1n0o** [comment]
Something else that crossed my mind is having 3 or more confirmation points in a given timeframe, and (now getting carried away) maybe an average calculation, for the case some middle points are lower.  Adjusting RSI length also comes into play here I guess.
Anyways, the point is to track the trend on RSI or Stoch so that it buys on an uptrend.

**Comment by taniman** [comment]
I believe tracking the trend is already possibly using offset logic. 
You can check RSI offset 0, 1, 2
If you put it on a 1 minute candle you would be tracking what RSI did in the past  3 minutes.

adding a tracker that tracks the value of each cycle of the bot  would be gathering too much data  that might not even be useful.
