### ISSUE TITLE
Feature Request: restrict buys on 24 hour change

### ISSUE THREAD

**Issue by Hurgnation** [taniman/profit-trailer-enhancements#78]
Hi,

I have my buys set up how I like them with the exception of when they buy a coin that has a high 24 hour profit. I find the times I get into bags is when the bot buys something that was riding high the day previously and is now coming down from that high. What I have been doing is manually checking each day which coins are showing high 24 hours changes and disabling them from trading until the price returns to the norm.

Ideally, it would be nice if there was a function that checks a coin's 24 hour change in 'possible buys' and excludes it if it falls outside of that range.

An example may look like:

restrict_buy_24H%_greater_than = 10
restrict_buy_24H%_less_than = 20

^ This would exclude any coins from the buy log if their 24hour change is outside of 10% profit or 20% loss.

**Comment by jbraydc** [comment]
You can do this with PT Magic easily - even set them in sell only mode so you can't buy them.

**Comment by clownfish44** [comment]
Already exists in magic and feeder which has been requested here https://github.com/taniman/profit-trailer-enhancements/issues/19
