### ISSUE TITLE
Ability to rename strategies without deleting & making a new one

### ISSUE THREAD

**Issue by willemrosenthal** [taniman/profit-trailer-enhancements#781]
I'd like to be able to rename strategies without having to delete, copy and remake them.

**Comment by LiamAird** [comment]
Please elaborate on this request. 
Do you make strategies, as in DEFAULT_A_buy_label or do you actually mean configs, that you choose from?

**Comment by taniman** [comment]
I am fairly sure this is about config. It will be added to 2.5.0
