### ISSUE TITLE
name to each bot

### ISSUE THREAD

**Issue by padmaCoin** [taniman/profit-trailer-enhancements#783]
The possibility to give a name to each bot visible on all pages

**Comment by taniman** [comment]
We already have site name setting. That will give the bot a name that is displayed in the TAB of your browser.
If you use context path setting it can also be used as a naming logic so to speak. you access your bot than.
http://localhost:8081/binancebot

Those are 2 options.  I think the sitename with the name in browser tab already is enough enough to know what bot you have selected
