### ISSUE TITLE
Range Parameter for Indicators

### ISSUE THREAD

**Issue by TheDeumel** [taniman/profit-trailer-enhancements#785]
Hey everyone,

I thought about having a range parameter for more if not all indicators. Like you can already check for PDLOW in a certain range, why not if, for example, a previous candle closed below the LOWBB line within the last X candles? This would make things a lot easier in setting up all the configs due to less inputs with several offset values.

Hope you give it a thought,
Regards Deumel

**Comment by taniman** [comment]
this request look like the request we already have to allow an SMA on all indicators. I would say SMA could be replaced with a RANGE indicator if it's possible to implement  see #777
