### ISSUE TITLE
Auto max leverage

### ISSUE THREAD

**Issue by d0m1n0o** [taniman/profit-trailer-enhancements#788]
Staying updated on the changes in the leverage of the coins is not practical.

It would be easier to set a max leverage for all, and have the bot purchase at the highest leverage for each coin, under that value.
E.g.

max = 50x - buys 'all' at 50x and the rest at it's max
max = 125x - buys btc at 125x and the rest at it's max
max = 25x - etc.

**Comment by taniman** [comment]
I have already declined 1 of these. Users should be the one to keep informed on what the exchange is changing and trade accordingly. 
This part of risk management will not be changed by me at this point
