### ISSUE TITLE
Auto Setting Update - Like RSS Feed

### ISSUE THREAD

**Issue by SpinFX007** [taniman/profit-trailer-enhancements#79]
Would be good to have a feed from an external repository that will update your settings, something like an RSS, pick a setting and subscribe.  Allow it to auto update or a button to agree to update.  So that you don't have to manually download peoples settings.  

Because at the moment the way to get settings is quite daunting for a new user and for people that are not as tech-savvy.   Also, give you a  way to rank settings to help optimise the bot.  Would also take a lot of hounding out of the Discord for setting, and hopefully allow more talk about settings and tweaking.

**Comment by ACETyr** [comment]
Good until the first jokers put up some panic sell strategy getting thousands of PT instances to loose ppl money...

**Comment by clownfish44** [comment]
Very very very bad idea just like @ACETyr stated. If you need settings I recommend cryptognome's they are free and updated often.

**Comment by SpinFX007** [comment]
Yeah it would have its ups and downs, maybe they have to be verified first.
