### ISSUE TITLE
I'd like to be able to skip the formula levels to buy with a specific alternative strategy. "BUY STRATEGY LEVEL(X) SKIP FORMULA"

### ISSUE THREAD

**Issue by DoctorEam** [taniman/profit-trailer-enhancements#796]
![image](https://user-images.githubusercontent.com/38581667/107931298-57869e00-6f7c-11eb-8c88-d86af7ba43d9.png)
This is the idea, and it would need something like this to be able to do it: 
"BUY STRATEGY LEVEL(X) SKIP FORMULA"

It would give the option of skipping the next formula levels, and buying with the given formula in that line. 
It could be active at any level you choose, and create a shortcut to another buy strategy, while being ignored at the rest of the levels, so that the sequence stays as the alternative route.

Example:

DEFAULT_buy_strategy_level1_skip_formula = (H && I && J && K && L && M) && (SM > (SN + 1)) && (SN > (SO +1)) && P

DEFAULT_buy_strategy_level1_formula = A
DEFAULT_buy_strategy_level2_formula = B
DEFAULT_buy_strategy_level3_formula = (SF > SG)
DEFAULT_buy_strategy_level4_formula = (SC > (SD +2)) && E

DEFAULT_buy_strategy_level2_formula_timeout = 45
DEFAULT_buy_strategy_level3_formula_timeout = 50
DEFAULT_buy_strategy_level4_formula_timeout = 80

As long as A is not true, it will attempt to skip the sequence and buy with that formula. If A becomes true, it will enter the sequence until it sells or times out any or all levels and gets back to level 1.

Edit:
Update. I think it's solved now, more or less (still a different course of action than with the other idea).
![image](https://user-images.githubusercontent.com/38581667/107936170-9c153800-6f82-11eb-8deb-03c789b22cd6.png)

**Comment by taniman** [comment]
The way you have defined this. it would skip only level 1 and go to level 2 in my view. It can't skip all levels. 
but I see the point you are making

I could as well just make it so default_buy_strategy_formula could be used together with levels logic. Instead of either or.

**Comment by d0m1n0o** [comment]
"I could as well just make it so default_buy_strategy_formula could be used together with levels logic. Instead of either or."

This seems like a good & practical solution, considering that the levels are usually used as a unit that makes one strategy.

What I meant is that if it was DEFAULT_buy_strategy_level(x)_skip_formula, it would look for that formula at the specified level only, to skip all following levels (and use that formula) if it's true. Skipping 1 level can be accomplished with an "or" + strat, and is already the nature of the level formulas. :)

**Comment by taniman** [comment]
I understand what you mean now. but if my suggestion also accomplish your goal I will go that way. 
It would be easier to implement for me. less logic I think

**Comment by taniman** [comment]
Implemented my style in 2.5.0

**Comment by DoctorEam** [comment]
epic!
