### ISSUE TITLE
Improved Telegram Settings

### ISSUE THREAD

**Issue by SpinFX007** [taniman/profit-trailer-enhancements#80]
The Ability for the user to set that is sent in the telegram message updates.

Maybe some simple switch boxes in the GUI that  allows the choice of a few things like:
 - Profit percentage with a fiat amount
 - Number of pairs 
 - Number of DCA pairs
 - Buys - with a fiat amount
 - To be able to turn on and off what you want to see
and whatever else - so really a way to customise the messages

**Comment by frydrce** [comment]
Notification after dca 2nd level!

**Comment by clownfish44** [comment]
Already in 2.0 milestone update

**Comment by sas7085** [comment]
Need for Telegram alert for DCA buys
