### ISSUE TITLE
Dynamic Gain

### ISSUE THREAD

**Issue by FaithlessVoid** [taniman/profit-trailer-enhancements#801]
Hello Devs,

I just realized it is currently not possible to use dynamic values with the GAIN sell strategy.

I would like to set the targets for both Stop Loss and Gain dynamically - depending on the ATR-value of the coin.
It is possible for Stop Loss, Trailing Stop Loss and Trailing Profit, but not for the Gain target.
I believe it should be.

Or is there a workaround that I just cannot think of right now?

Thank you in advance and thanks for your effort,
FaithlessVoid

**Comment by en3z** [comment]
You can use sell formula with atr for dynamic gain. 
sell strategy a is gain
sell strategy b is ATRPERCENTAGE 
if you wanna sell at 2 atr, use sell formula like this
SA/SB > 2

**Comment by FaithlessVoid** [comment]
Thank you very much -
this thread can be closed
