### ISSUE TITLE
Profit Percentage use on another bot on the same server

### ISSUE THREAD

**Issue by ispo77** [taniman/profit-trailer-enhancements#808]
Server where i run 2 bots. One for long and one for short. I would like to insert one new strategy into the short bot for buy if in the long bot have open positions what is in negative 2% profit for example.  When it’s happened will send buy signal for short bot for buy. Is it possible to develop somehow?

In strategy’s have this profit percentage. I would like to use this but what data take from long bot. And will use in short bot. I hope i was understandable. And thanks ur answer

**Comment by taniman** [comment]
sorry, but this sounds more like an addon than something for the bot. Bots do not communicate with each other.
