### ISSUE TITLE
Ladder and Accumulate?

### ISSUE THREAD

**Issue by Tjosy** [taniman/profit-trailer-enhancements#81]
Laddering is a common way of accumulating a given cryptocurrency. It seems to me that a modified DCA process... maybe call it "buy_only_mode" (with a matching max_to_accumulate value) could be a useful tool for would-be long-term HODLers.

For more background, see:
https://steemit.com/bitcoin/@haejin/an-effective-buying-and-selling-strategy-laddering-a-tutorial-on-to-cast-a-ladder

**Comment by clownfish44** [comment]
keeping coins has been requested here https://github.com/taniman/profit-trailer-enhancements/issues/71
