### ISSUE TITLE
Placing limit orders on the exchange

### ISSUE THREAD

**Issue by mag106** [taniman/profit-trailer-enhancements#811]
Hello, please make it possible to place a limit sell order on the exchange.

1. This is necessary in order to guarantee to close the deal when the price bounces at least 0.01%
2.when trading with tradingview signals, in order to be guaranteed to close the deal

At the moment, without placing a limit order, I see such a picture that the bot does not always have time to sell the position due to a long api response, and sometimes the position makes 5 circles of reaching the sell price - and only then is it sold!
I beg you to consider the possibility and make such an implementation, for sure it is not difficult, because the api of any exchange supports this function

**Comment by yashablack** [comment]
this is a good idea

**Comment by PV111** [comment]
Great idea.

**Comment by weedgreeder** [comment]
Really need this in my bot. If its real pls make limit order real!

**Comment by konduktor1076** [comment]
very good idea.sometimes it's really not enough.thank you and a great product!

**Comment by VladNord** [comment]
nice feature, I want it!

**Comment by EdjOne** [comment]
really need it, hope it will be implemented very soon, since PT staff are really cool

**Comment by taniman** [comment]
@mag106 You can't really know what is diifficult to implement in the current bot logic and framework. 

On spot this is certainly not possible as once you create a limit order the coin is not available anymore for the bot to manage.

So I can only assume you are talking about futures in this case. And in that case the logic required needs to change how current bot logic works because most logic in the bot is enhanced for spot trading

Also this request look a lot like 
#763

**Comment by mag106** [comment]
@taniman you just need the ability to place a limit order without trailing without everything on the futures !
at least the performance of the teams 
#DEFAULT_DCA_pending_order_wait_time = 0 
#DEFAULT_DCA_pending_gain_percentage = 5
 #DEFAULT_DCA_cancel_pending_trigger = -5
 to place a limit order for example at +5% and cancel the limit order at PNL -5%, after setting a limit take profit - no trailing is needed !You only need the opportunity to set a take profit on the limit on futures
 P.S sorry for my English

**Comment by taniman** [comment]
We will see what is possible to do in 2.5.0, but I got some other things that I find more important at the moment.  Also I have many many other things to do.

**Comment by mag106** [comment]
thank You for your time, I really hope for your help with the limit take profit

**Comment by cavasotti** [comment]
great idea, much needed.

**Comment by mirror-ru** [comment]
Good idea

**Comment by LIVE-PT** [comment]
very good idea.sometimes it's really not enough.thank you and a great product!!!

**Comment by nukodim** [comment]
Really good idea! Thanks

**Comment by wolfman77** [comment]
Absolutely!

**Comment by taniman** [comment]
Added in 2.5.0
