### ISSUE TITLE
Feature request: Multiple prince_drop_trigger formula & multiple SOM_trigger_lengths

### ISSUE THREAD

**Issue by willemrosenthal** [taniman/profit-trailer-enhancements#817]
Having multiple SOM_trigger_lengths is a MUST have.

Being able to trigger SOM when BTC tanks over the course of an hour, then KEEP it triggered, in case of another worse dip is essential. Right now I have to choose between my bot halting buys momentarily when a dip occurs, only to buy a ton right before a 2nd dip, or have it be enter SOM several hours too late on a huge pump and dump.

**Comment by chmccc** [comment]
great idea!

**Comment by taniman** [comment]
There is already a feature implemented in 2.5 that can be used instead of adding this feature see #765
