### ISSUE TITLE
Fee tracking

### ISSUE THREAD

**Issue by jbraydc** [taniman/profit-trailer-enhancements#82]
A fee tracking window on the monitoring page would be handy.

**Comment by Tosko4** [comment]
+1

**Comment by taniman** [comment]
Please elaborate what this means

**Comment by Tosko4** [comment]
How much Fee’s has been paid. Maybe a chart of top 10 fee’s spent on coins.

**Comment by clownfish44** [comment]
https://github.com/taniman/profit-trailer-enhancements/issues/5 is all for more tracking
