### ISSUE TITLE
Feature Request:  highlight rows in PT UI

### ISSUE THREAD

**Issue by ITJusus** [taniman/profit-trailer-enhancements#820]
I feel like I spend way too much time straining my eyes, counting from top down, counting from bottom up, and running my mouse very carefully from left to right...all in an attempt to line up (for example in the Buy log) each Buy strategy on the left with their corresponding BSV, BST, and BSL values on the right.  This same concept applies to PBL, Sales Log, Pair Log, DCA Log and so forth.

I think It would make a night and day difference for our experience if we had the ability to click a row and that entire row highlights/shades so that it is very clear which strategy/header on the left corresponds with which values on the right.  One step further, if we could then utilize the CONTROL key to select multiple separate individual rows or the SHIFT key to select a block of rows for highlighting, that would make the PT UI so much more efficient and painless to view.

Here is an example (color of shading is less important, as long as contrast is clear)...

![image](https://user-images.githubusercontent.com/36611314/113145914-a454ca00-91f4-11eb-9abf-7703869f58c2.png)

**Comment by LiamAird** [comment]
You can switch on the beta gui for this.
The beta gui gives a better overview that could fix your 'issue' with this.

Go to settings, top right, enable beta gui and restart the bot.

**Comment by ITJusus** [comment]
Wow, thanks.  That really does help and pretty amazing actually.  The one drawback I see with BETA is the filters are no longer sticky (they reset the row count select from drop-down and search value each time I navigate back and forth between the Buys and Sales logs).  I also liked having the row option of "all" as well, but I get why it may not be a developer's favorite option to have available.  It is BETA after all.  Let me try this out for a while, but definitely at least addresses my request for this ticket.

**Comment by LiamAird** [comment]
Please create new issues, if you are facing issues. 
There will be no new work done on the old GUI.
