### ISSUE TITLE
[Feature Request] Buying only during certain days and/or hours

### ISSUE THREAD

**Issue by anhcalisj95** [taniman/profit-trailer-enhancements#827]
My bot settings seem to perform well at night (when there are no news coming from the US).
Hence, my feature request would be to allow buying only during certain hours or days.

e.g. 

DEFAULT_buying_days = 1,2,3,4,5,6,7
DEFAULT_buying_hours = 20,21,22,23,24,1,2,3,4,5,6

So only allow buying from Mon through Sun from 8pm to 6am (PST).

**Comment by taniman** [comment]
Please in the future search before adding requests as there is already a feature implemented for 2.5 that will allow to set a time period for buying and selling
