### ISSUE TITLE
manual sell

### ISSUE THREAD

**Issue by IslandFamily** [taniman/profit-trailer-enhancements#83]
Option for sell now button through the monitor..

IE: If I see it trailing a coin and I can tell where it will be starting to drop again, before the software kicks in and sells, a manual sell button there would be handy. I know I can sell it manually myself, but when I do that now, it does not get tracked in the software.

**Comment by clownfish44** [comment]
Already requested here https://github.com/taniman/profit-trailer-enhancements/issues/7
