### ISSUE TITLE
Feature request: MACD divergence

### ISSUE THREAD

**Issue by Mexxwelll** [taniman/profit-trailer-enhancements#834]
Hello,

I would like to have the possibility to use divergence on MACD. So that we can get higher highs on candles and lower highs on MACD.

As far as I know right now we are able to trade on crosses, but would like to trade with the divergence part in combination with the candles.
https://www.investopedia.com/terms/m/macd.asp#example-of-divergence

Thanks in advance.

Gr. Mexx

**Comment by wolfman77** [comment]
This would be for bigger timeframes, right? We are talking about several days or several hours at least.

**Comment by taniman** [comment]
Convergence divergence as already been requested and added for 2.5 in some way. Though it needs plenty of testing to see if it works as expected
