### ISSUE TITLE
ISSUE - TRAILING_PROFIT_ENABLED_FORMULA not getting Svalues

### ISSUE THREAD

**Issue by bvebve** [taniman/profit-trailer-enhancements#835]
It seems TRAILING_PROFIT_ENABLED_FORMULA is not getting **S**_values_

Taken from the wiki:

> DEFAULT_sell_strategy_formula = (A && B && C) || D
> DEFAULT_trailing_profit = 0.5
> DEFAULT_trailing_profit_enabled_formula = (A && B && C)

Now my example:

> DEFAULT_sell_strategy_formula = (A && (SB > 2 * SC)) || D
> DEFAULT_trailing_profit = 2 * SC/10
> DEFAULT_trailing_profit_enabled_formula = (A && (SB > 2 * SC))

ERROR:  Invalid formula (true && (Strue > 2 * Strue))

Can you check it, please?

**Comment by LiamAird** [comment]
Please come to our discord server and create a support ticket. 
This is meant for improvement requests. 

[https://discord.gg/eakB23b](https://discord.gg/eakB23b)
