### ISSUE TITLE
Enhancement; Feature Request - ability to SELECT and/or EDIT multiple entries simultaneously

### ISSUE THREAD

**Issue by wakhan92** [taniman/profit-trailer-enhancements#836]
Hello there,

Perhaps there is a workaround/ setting catered towards this already, in which case please do let me know :) I am fairly new

Within the PT logs, specifically "BUY" and "SALES" for this example, I could not find a way to select multiple entries at once. The entries have to be deleted one at a time; not sure if I have some setting toggled off? 

Within the GUI, I want to be able to select/ custom sort/ edit/ delete items SELECTIVELY. A "clear all" or "select all" feature would also make UI easier and less time consuming. Overall providing a better client experience :D

Thank you for your consideration!
Waleed
![Capture - PT Feature Enhancement](https://user-images.githubusercontent.com/83757117/117277137-90246e00-ae2d-11eb-8583-b0b9a79c8e0a.JPG)

**Comment by taniman** [comment]
I can't remember the last time I had to delete an entry from my logs.  So I do not see the added value of this feature. 
If you want to reset your bot and clear all data,, there is a button for that. Otherwise I fail to see the benefit
