### ISSUE TITLE
Greater ability to target and limit trading specific coins.

### ISSUE THREAD

**Issue by jbraydc** [taniman/profit-trailer-enhancements#85]
We can target coins by volume and by price but there are many other things that could be used to target coins. Like changing volume, changing market over 1hr, 12hr and 24 hr, external signals, AI logic, multiple indicators etc. I would like the ability to look at market data in the bot, filter data, select coins manually or automatically based off risk profiles. Links to places you can find out more information about specific coins. The ability to see what your strategy does on a specific coin. An easier intuitive way of creating your whitelists and blacklists with protection from pump and dumps and downhill trades. You say your want coins that have more than this volume that have not increased in volume by this % in x amount of time that havnt increased or decreased in value by x %, that are recommended by these signals and the following AI logic and market indicators, that have a good reputation and low/med/high etc risk profile - Information about the coin (has it been pumped and dumped recently, has it been trending up or down for the last week) etc The ability for users to share whitelists or black lists, encouragement for good and successful settings maybe like competitions. Optional protection from new coins that are added to the exchange. Some flexibility with trading settings like rather than DCA for100% you could DCA for 50% for example. The ability to add a sell target and sell off increments until you reach it.

**Comment by clownfish44** [comment]
This already exists in pt feeder / magic and has been requested here https://github.com/taniman/profit-trailer-enhancements/issues/19
