### ISSUE TITLE
I need the static value at the final growth not to exceed the maximum values.

### ISSUE THREAD

**Issue by babynchik** [taniman/profit-trailer-enhancements#852]
I need the static value at the final growth not to exceed the maximum values.

**Comment by babynchik** [comment]
Is it possible to enforce
DEFAULT_initial_cost=2%
DEFAULT_max_initial_cost=1?

**Comment by babynchik** [comment]
The bottom line is that with an increase in the deposit on futures and dynamic leverage, the leverage has its own volume limitations, and this is necessary at each stage the grid worked up to the maximum value for entering the market.

**Comment by babynchik** [comment]
this is relevant for those who overclock using the maximum values ​​and conditions of the exchange, on any leverage. if the entry price in% is higher than the maximum trade safety, it will be violated because the order grid is calculated in such a way that it is as safe as possible to get a stable profit up to a certain deposit on futures.

**Comment by taniman** [comment]
Added to latest version of 2.5
