### ISSUE TITLE
Feature Request: Multiple Take Profit Safety Levels

### ISSUE THREAD

**Issue by turcane** [taniman/profit-trailer-enhancements#853]
If someone is not using DCA/Trailing Profit multiple take profit safety levels could help.
This could look like:

DEFAULT_S01_take_profit_safety_arm = 5
DEFAULT_S01_take_profit_safety_fire = 1
DEFAULT_S02_take_profit_safety_arm = 10
DEFAULT_S02_take_profit_safety_fire = 5
DEFAULT_S03_take_profit_safety_arm = 20
DEFAULT_S03_take_profit_safety_fire = 15

This could safe profit when profit increases but falls again before sell strategies are fulfilled. Multiple levels could increase the profit.

**Comment by taniman** [comment]
this is what Trailing stop loss does.
