### ISSUE TITLE
[Indicator Request] ADX

### ISSUE THREAD

**Issue by bitlord69420** [taniman/profit-trailer-enhancements#857]
Hi PT-family.

I'd love to use ADX as a separate logic in ProfitTrailer. At the moment we can only use it to switch configs.

The indicator works fantastic by suggestings bullish, bearish or flat-trends. However, if we can only base it on BTC, it makes us miss out on some other pairs making huge moves.

For example: 
as I'm writing this (12/07/21), my ADX which takes care of switching configs mainly recognized sideways price action on BTC lately. 
> As a result - my bot was not exposed to the huge Axie Infinity (pair: AXS) run.

IF however we could use ADX as an individual indicator, we simply could point out the price action per coin, and thus keep the sideway alerts for BTC while maintaining an opportunity to grab other coins running up quickly (such as Axie Infinity "AXS" atm).

Please! Make this possible if you have the time. I'd be very grateful.

Kind regards.

**Comment by taniman** [comment]
Duplicate
