### ISSUE TITLE
SOM and SOMO Buttons

### ISSUE THREAD

**Issue by RF-Radio** [taniman/profit-trailer-enhancements#86]
One function that I have been missing since the beginning of my ProfitTrailer days is the ability to click a button to activate/deactivate Sell Only Mode or Sell Only Mode Override. This tool could be invaluable to quickly shifting your bot to SOM if you feel the market conditions are not favorable but your SOM triggers have not yet been met.  By the same token, you could override SOM when observing favorable trading conditions before the trigger resets occur.  I have had to do this many times, and I’m sure many of you have too.

If you’ve been missing the ability to activate SOM/SOMO with the click of a button, vote to have this issue sent to the top of the list.

**Comment by clownfish44** [comment]
Many button already requested here https://github.com/taniman/profit-trailer-enhancements/issues/7
