### ISSUE TITLE
ROC Indicator (Rate of Change)

### ISSUE THREAD

**Issue by hoffer49** [taniman/profit-trailer-enhancements#864]
This could be of benefit for PT users :) 

https://www.investopedia.com/terms/p/pricerateofchange.asp

The Price Rate of Change (ROC) is a momentum-based technical indicator that measures the percentage change in price between the current price and the price a certain number of periods ago. The ROC indicator is plotted against zero, with the indicator moving upwards into positive territory if price changes are to the upside, and moving into negative territory if price changes are to the downside.

The indicator can be used to spot divergences, overbought and oversold conditions, and centerline crossovers.

**How to Calculate the Price Rate of Change Indicator**
The main step in calculating the ROC, is picking the "n" value. Short-term traders may choose a small n value, such as nine. Longer-term investors may choose a value such as 200. The n value is how many periods ago the current price is being compared to. Smaller values will see the ROC react more quickly to price changes, but that can also mean more false signals. A larger value means the ROC will react slower, but the signals could be more meaningful when they occur.

1. Select an n value. It can be anything such as 12, 25, or 200. Short-term trader traders typically use a smaller number while longer-term investors use a larger number.
2. Find the most recent period's closing price.
3. Find the period's close price from n periods ago.
4. Plug the prices from steps two and three into the ROC formula.
5. As each period ends, calculate the new ROC value.

**Comment by en3z** [comment]
https://wiki.profittrailer.com/en/config/changepercentage
