### ISSUE TITLE
PivotPoint Level for DEMARKREVERSAL

### ISSUE THREAD

**Issue by hoffer49** [taniman/profit-trailer-enhancements#866]
The pivot point for the DEMARKREVERSAL indicator is calculated differently than the Standard and Fibonacci pivotpoints which uses (High+Low+Close)/3. The Demark Pivot Point is calculated as follows:

If Close > Open, then X = (2 x High) + Low + Close
If Close < Open, then X = High + (2 x Low) + Close
If Close = Open, then X = High + Low + (2 x Close)

Pivot Point = X / 4

In addition to the options (SUPPORT/RESISTANCE) for the DEMARKREVERSAL_pivot_level, it would be nice to have the PIVOTPOINT level also which often serves as resistance when price is below it and also serves as support when above it.

**Comment by taniman** [comment]
Done for latest 2.5 release
