### ISSUE TITLE
please bring back ORDERBOOK_PROFIT_CALCULATION

### ISSUE THREAD

**Issue by CryptoScottS** [taniman/profit-trailer-enhancements#899]
I'm getting quite a few sells where TPS is firing,  but because of low orderbook depth the final price is negative with market sells.

This feature worked great before and kept sells from happening too soon...increasing the percentages for all coins is a "shotgun" approach, which is not needed for coins that have sufficient orderbook depth.

Slippage has been suggested as a possible replacement, but it doesn't seem to help.

**Comment by taniman** [comment]
Sorry, this option is not coming back.
