### ISSUE TITLE
Test Buy Strategy Before Selling a Pair

### ISSUE THREAD

**Issue by kernelpanic19** [taniman/profit-trailer-enhancements#90]
Before selling a pair, test the buy strategy.  Do not sell if the pair is eligible to buy again.  This avoids a situation where the bot sells and then immediately rebuys a pair, which costs you the spread as well as the commission fee.

The pair status could go from 'trailing' to 'trailing PBL' or something more descriptive.

I'm not sure if this is why the rebuy_timeout parameter was provided, but I think it would be preferred to avoid the sell entirely vs just delaying the rebuy.

This happened to me quite a bit when i first got started with the default buy and sell strats.

**Comment by clownfish44** [comment]
Please use rebuy_timeout it will prevent this
