### ISSUE TITLE
STOCHRSICROSS blind spot

### ISSUE THREAD

**Issue by ITJusus** [taniman/profit-trailer-enhancements#902]
In the real world, StockRSI values for K and D are often both equal to 0 or equal to 100.  This is because 0 is the lowest (floor) both K and D can go down to and 100 is the highest (ceiling) K and D can go up to.  Often when the market is trending up sharply (for a prolonged period of time)...D and K eventually get stuck together at 100 for sometimes several candles.  Anytime the market trends lower sharply (for a prolonged period of time)...D and K get stuck together at 0 for sometimes several candles.  

These are opportune times to catch reversals with StochRSI, but it seems PT stops being able to detect the cross when the last D/K were = 0 or = 100.  This means the PT edition of STOCHRSICROSS is only useful when the market is not trending very high/low...which is a bummer because once the market trends too high or low (to where D and K are equal) then your STOCHRSICROSS gets missed entirely and you never enter or exit the trade when desired.

This makes this tool unreliable for real use.  To fix this, there would need to be code added to the "cross_candles" definition so that if both D and K become equal at 0 (with strategy_direction = UP) or become equal at 100 (with strategy_direction = DOWN), then it is still counted as a cross when K becomes no longer equal to D.  That's my thinking anyway.

Below is an example of this common occurrence (highlighted in yellow is several candles of 0, 100, and then 0 again).

![image](https://user-images.githubusercontent.com/36611314/145696246-d8e35dc3-787d-427d-8a55-700ce56696e4.png)

**Comment by magicsword80** [comment]
The Stoch (not RSI) barely stay at 0 or 100 for a long time. But PT doesn't support Stoch K and StochCross . If it does, we can use  both Stoch/StochRSI to compare and check for signal.

**Comment by taniman** [comment]
I have created a fix for this. That should make the cross become true in those rare cases.  Release 2.5.9
