### ISSUE TITLE
Add ADX to bot config as a strategy

### ISSUE THREAD

**Issue by magicsword80** [taniman/profit-trailer-enhancements#904]
It maybe duplicate.
We had ADXTREND for Auto Config Switch a long time but we don't have ADX as a strategy. 
ADX runs smoother than Stoch, MACD, PSAR... and seem not have Divergence problem. 
On cryptowat.ch I saw they have the whole formula for ADX and DMI +/-  (in picture below) and they can count ADX for each pair. I think  PT can make it too.
![3](https://user-images.githubusercontent.com/96141810/146649528-a9c2015e-4df6-4e5b-8747-da105b51b6ae.png)

**Comment by cmartin81** [comment]
I really want this also!! 👍

**Comment by magicsword80** [comment]
PT added ADX to bot. This topic can be closed.
