### ISSUE TITLE
Feature Request: Manual Watch and Sell

### ISSUE THREAD

**Issue by PwnAppleTea** [taniman/profit-trailer-enhancements#91]
I have heard many people that request this feature to exist. What this feature is suppose to do is maximize profit for the owner of PT by allowing him/her to manually pause a pair before it gets pumped or will definitely go up WITHOUT having to tell the bot to be put into watchmode which takes a while. The time it takes to change the lines in the pairs could be fatal if a pair was to be pumped within seconds.

Question: Why have this feature if the bot is to automate trading?
Answer: Sometimes a fellow person that watches with cautious seizes the moment, when it arrives. Should a pair go to moon, the fellow person shall act with quick hands... when given the right tools.

Question: What does this idea seek to resolve?
Answer: Maximize profit from a pair if a Pump And Dump is identified by the user.

Question: How can this idea exist?
Answer: Perhaps execute a quick script to override the desired pair into watchmode IMMEDIATELY. The Sell button can be the same command for "Panick Sell" or sold at market price with a limit order or equivalence.

Below is an example of what it might look like:
![ptidea](https://user-images.githubusercontent.com/28717823/36767788-9ddea75c-1c01-11e8-9f55-15ff2db50b1b.png)

**Comment by clownfish44** [comment]
Buttons have been requested here https://github.com/taniman/profit-trailer-enhancements/issues/7
