### ISSUE TITLE
MAX DCA PAIRS

### ISSUE THREAD

**Issue by HerbTrading** [taniman/profit-trailer-enhancements#927]
there are 2 things that drive me crazy on max dca pairs

First:

There is no Softpairs cap for dca pairs ! this is a feature that would make max dca pairs a lot smarter ( same with softpairs cap in pairs )

Second:

if i use:
DEFAULT_DCA_enabled = true
DCA_max_trading_pairs = 3

PT will "Pick" 3 coins to get dca buys 

the problem here is.
It choice which one get dca buys BEFOR it bought even once ( with the settings the pair can be up 500% in profit and still counts as a dca pair even its on dca 0

it would be a lot better when ALL pairs CAN get a dca buy BUT if iam on 3 dca pairs then show max dca pairs

https://cdn.discordapp.com/attachments/410809208666193921/972819834716975114/unknown.png

here is a good example picture  ( my config has positive and negative dca ) both pairs on dca 0

RSR shows MAX DCA PAIRS 
AR could get a buy 

but what if on RSR the indicators are true ? right it will never buy even i dont have 3 dca pairs

**Comment by taniman** [comment]
already done
