### ISSUE TITLE
Additional timeframes to confirm trend

### ISSUE THREAD

**Issue by pompousraccoon** [taniman/profit-trailer-enhancements#93]
Say you are trading on the 15 minute charts and you want additional confirmation on if it is a good buy and trending overall in the right direction on the 30 and the 1 hour charts. 

Possible settings for a confirmation triggers. 

Indicators file:
//Trigger Indicator//
EMA_period = 900
EMA_1 = 23
EMA_2 = 3

//Confirmation 1 Indicator//
EMA_confirm1_period = 1800
EMA_confirm1_1 = 24
EMA_confirm1_2 = 3

//Confirmation 2 Indicator//
EMA_confirm2_period = 3600
EMA_confirm2_1 = 24
EMA_confirm2_2 = 3

Pairs File:
//Pair buy strategy//
ALL_buy_strategy = EMAGAIN
ALL_buy_value = -1
ALL_trailing_buy = 0.5

//Confirmation 1 buy strategy//
ALL_confirm1_strategy = EMAGAIN
ALL_confirm1_value = -1.5

//Confirmation 2 buy strategy//
ALL_confirm2_strategy = EMAGAIN
ALL_confirm2_value = -1.75

**Comment by clownfish44** [comment]
This is not possible and will not happen but the 2.0 update will have multiple indicators used all at once so you can confirm with a different indicator.
