### ISSUE TITLE
Add percentage change from last bought price indicator 

### ISSUE THREAD

**Issue by 556isback** [taniman/profit-trailer-enhancements#933]
When I use DCA feature, the closest indicator to percentage change from last bought price is profit percentage, but that is not how I calculate price level where I want to add more fund and I am sure I am not the only one thinking this way.
I manage to solve it by using DCA buy formula, BHBPRICE and current price. However  the system require profit percentage as indicator so I have to add it in my config file. 

So I hope the profit trailer team could add percentage change from last bought price as indicator and remove the requirement of profit percentage in config file.

Thankx.

**Comment by taniman** [comment]
I think you are speaking of LASTDCABUY. Where you can define a buy to happen x% above or below the last DCA buy.
The requirement for PROFITPERCENTAGE strategy will be removed.
