### ISSUE TITLE
Need bug fix: Not re-calculate RGAIN after DCA 

### ISSUE THREAD

**Issue by magicsword80** [taniman/profit-trailer-enhancements#940]
Right now RGAIN doesn't change after DCA, no matter how many times DCA - because bot only re-calculates RGAIN after a sell and on the next buy. This causes a big hole in calculating to recovering the loss if DCAing.
I suggest PT bot should have ability to recalculate RGAIN after any DCA times (equal to new buy).
Base on the formula:  
**RGAIN = -1 * (RDIFF/COST) * 100 * leverage**
RGAIN can be calculated right at any time - needn't care how many times DCA or % RGAIN before DCA.

This is not a feature, it's bug fix to make Reversal logic run well.

**Comment by taniman** [comment]
I have a test version to try with this change in.
