### ISSUE TITLE
Add min buy volume period feature

### ISSUE THREAD

**Issue by 556isback** [taniman/profit-trailer-enhancements#944]
too many scam pump which leads to a massive volume. 24h volume filter is not enough in current market conditions.

**Comment by taniman** [comment]
You can use the Candle indicator source is volume and also smooth it using a SMA/EMA. And add this indicator as an extra option to your buy formula.

So why exactly would we need to add logic to min_buy_volume filter?

**Comment by 556isback** [comment]
Oh, I didn't know there are volume data in Candle source, thanks for informing me. And this makes it not necessary to add this logic to current bot, my bad.
Thanks again for letting me know about this.
