### ISSUE TITLE
buy and sell log - Auto plotting on chart

### ISSUE THREAD

**Issue by priddy23** [taniman/profit-trailer-enhancements#95]
If possible, I would like to see my buys and sell history for a pair auto plotted on a chart. 

I can already get to the pair chart by clicking on the coin name ( I prefer the profit trailer tool I got from CryptoGnomes GitHub). It would be nice if when I see the chart if my buys and sells where plotted on the graph. It could be as simple as pulling up an integrated chart in a small pop up window. Cryptohopper does this nicely, without the plotting script obviously. 

This would help tweak current strategies by creating a simple visualization of exactly when my bot is buying and selling. I have a pine script that does this but even with only 10 input fields in the settings, it takes a lot of time out of my day. An auto script that can pull directly from my PT saved data would be O' So helpful.

P.S, Thank you Helmi for the wonderful indicators already. They are great for seeing possible buys, my idea is for seeing solely my realtime data.

**Comment by clownfish44** [comment]
Charts have been requested in #5
