### ISSUE TITLE
would it be possible to use formula in MTPSC at some stage?

### ISSUE THREAD

**Issue by dreadddy** [taniman/profit-trailer-enhancements#957]
DEFAULT_A_Formula = (SGI > SGJ) && (SGI > SGK) && (SGH > SGK)
DEFAULT_A_Formula_Label = FULLBULL 
Max_Trading_Pairs_Soft_Cap = FULLBULL ? 6 : (SGI > SGK) && (SGJ < SGK) && (SGI < SGK) && (SGH > SGK) ? 5 : (SGI < SGK) && (SGJ > SGK) && (SGJ > SGI) && (SGH < SGK) ? 4 : (SGI < SGJ) && (SGI < SGK) ? 3 : 2
instead of Max_Trading_Pairs_Soft_Cap = (SGI > SGJ) && (SGI > SGK) && (SGH > SGK) ? 6 : (SGI > SGK) && (SGJ < SGK) && (SGI < SGK) && (SGH > SGK) ? 5 : (SGI < SGK) && (SGJ > SGK) && (SGJ > SGI) && (SGH < SGK) ? 4 : (SGI < SGJ) && (SGI < SGK) ? 3 : 2
maybe creating a global formula like Default_A_Global_Formula =
cause this is so messy

![image](https://user-images.githubusercontent.com/33052901/187802092-c18f0aaf-2f2e-4b2d-a342-6592598efb5d.png)

**Comment by taniman** [comment]
done
