### ISSUE TITLE
Let me trade with BNB but save min balance to pay for fees

### ISSUE THREAD

**Issue by jalvarezca** [taniman/profit-trailer-enhancements#96]
In Binance we have 50% discount if we pay with BNB so it's good to keep a min balance.
But at the same time I want to trade with BNB, without risking to sell all coins.

**Comment by orangebutblue** [comment]
why can't you just use "ALL_min_buy_balance"

**Comment by securitygeneration** [comment]
@orangebutblue min_buy_balance won't work to do what @jalvarezca is asking about. That setting forces PT to keep a certain balance in your base market, and won't allow you to say "trade BNB, but always keep at least X BNB". 

I like this idea, as it would indeed allow day-to-day trading of good coins (for small profits), whilst also being able to hold these coins if one feels they have potential for actual growth.

**Comment by orangebutblue** [comment]
I see, it's not really about BNB, it's about any coin.

Maybe you should rename the issue to something like "hold coins". Being able tell PT to ignore certain amount of certain coins (aka holding him). 

Example:
Hold 1 BCH - but still buy and sell BCH like any other coin, while ignoring the 1 BCH you already have

**Comment by jalvarezca** [comment]
Yes, I was referring to my specific need, which is trading BNB in USDT market. If I do that I loose all my BNB coins when they are sell and start using BTC for fees, loosing my 50% discount.
But I guess it can have other uses. :-)

**Comment by clownfish44** [comment]
Use ALL_min_buy_balance so that it always keeps some BNB for you

**Comment by jalvarezca** [comment]
Hi. I need PT to not sell all BNB, not when buying, I'm trading on USDT market.
