### ISSUE TITLE
NO FUNCIONA BIEN EL EQ EN LA VERSION 46 Y 47 

### ISSUE THREAD

**Issue by rikigoda** [taniman/profit-trailer-enhancements#970]
ME HIZO UNAS PERDIDAS CONSIDERABLE AL ACTUALIZAR EL BOT DE LA VERSION 30 A LA 47 ,ME COMPRO CUALQUIER IMPORTE NO EL FIJO QUE TENGO ,,HE VUELTO  ALA VERSIÓN 38 EN ADELANTE NO ME ANIMO A ACTUALIZAR ,,,
OTRO PROBLEMA ES QUE EL PRECIO QUE TENGO EN KUCOIN EN EL BOT TARDA MUCHO EN ACTUALIZARLO Y COMO SABEMOS QUE ES MUY VOLÁTIL LA VENTA NO ME LA HA REALIZADO PORQUE YA EL PRECIO BAJO ,PORQUE TARDA TANTO  EN ACTUALIZAR PRECIO

**Comment by LiamAird** [comment]
Please post support request in our discord: https://discord.gg/2ecEYUBa

This is for ideas and feature requests. 
We will be able to help better and more easily on our discord.

**Comment by rikigoda** [comment]
LLEVO USANDO PROFITTRAILER VARIOS AÑOS HE CREADO MI BOT Y FUNCIONA PERFECTO ,PERO ESTOY ARTO DE PERDER TIEMPO TRATANDO DE ENTRAR EN LA BASURA DE DISCORD ,NO PUEDO ENTRAR POR ESO ESTOY TRATANDO DE COMUNICARME POR AQUÍ , TELEGRAM ES MUCHO MEJOR ..SEGUIRÉ CON MI BOT SOLO ES PARA INFORMAR QUE NO SIRVE LA 47  ,, MI BOT ESTA FUNCIONANDO DE MARAVILLA AHORA CON EL 32--
