### ISSUE TITLE
Combine Buying Signals - If EMAgain, EMAspread, EMAcross are true, then buy

### ISSUE THREAD

**Issue by ootimiok** [taniman/profit-trailer-enhancements#99]
Combine Buying Signals - If EMAgain, EMAspread, EMAcross are true, then buy - select one, two or all three. 

Same values and trailing options to be available

**Comment by clownfish44** [comment]
This is already in the next 2.0 milestone https://github.com/taniman/profit-trailer/issues?q=is%3Aopen+is%3Aissue+milestone%3Av2.0

**Comment by sas7085** [comment]
Single strategy is not working properly . Competitors are providing multiple  strategy to buy . Multiple strategy gives more concreate signal for buy.
